### ISSUE TITLE
[Bug] Pressing <down> after search using <up> does not clear line

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/clink#103]
Using the <kbd>Up</kbd> key, I can do a substring search, starting from the characters that are already typed. But, for instance, if I do not find something that was looking for in the search, I press <kbd>Down</kbd>. But this does not clear the appended search items. 

See the GIF below. Other shells (PowerShell in middle tab and Zsh in rightmost tab) clear the items after pressing <kbd>Down</kbd>.

![hmm](https://user-images.githubusercontent.com/46838874/115510891-e4f8ae00-a29d-11eb-89cf-b457ecca8472.gif)

Is there a setting that controls this?

My `.inputrc` is this:

```
"\e[A": history-search-backward
"\e[B": history-search-forward
$if clink [
        set history-point-at-end-of-anchored-search on
] $endif
```

**Comment by chrisant996** [comment]
The Readline manual should help with learning about how the Readline commands work.

I expect that bash will behave the same, since the Readline library is what bash uses for input.

**Comment by rashil2000** [comment]
Indeed, bash behaves the same in this regard. I tried my best to search, but I couldn't find anything to enable this in the Readline manual.

Clink however does add niceties that Readline does not include, like `history-point-at-end-of-anchored-search`, so I thought this might be the best place to ask.

**Comment by rashil2000** [comment]
No no, I was not saying that that history command should remove what I typed. I was just giving an example as to how Clink adds some functionality that Readline doesn't provide itself.

Also, pressing Esc would clear the entire line, which is a deviation from what other modern shells do (in the GIF above), and it would mean retyping the whole substring with which we began the search.

**Comment by chrisant996** [comment]
It looks as if this behavior might actually be an accidental and unintentional side effect, based on reviewing the Readline code for `history-search-forward` vs `next-history` and comparing how they "save" the current line.

Have you considered reporting it as an issue in bash?

**Comment by rashil2000** [comment]
I haven't. To be honest, I don't really use bash that much, and their bug filing procedure is slightly more involved (it requires sending reports to their mailing list). I'm not sure if I'm adept enough for that.

So the bug is specific to Readline, or is it specific to bash itself?

**Comment by chrisant996** [comment]
> I haven't. To be fair, I don't really use bash that much, and their bug filing procedure is somewhat more involved (it requires sending reports to their mailing list). I'm not sure if I'm adept enough for that.

I'll rephrase:  I don't feel a need to invest in making a change in Readline for this issue.  I'm content with the behavior.  And I don't want to become a proxy for reporting suggestions and issues in Readline simply because I don't expect as much effort invested into reports.  (That would lead me to require a similar level of effort ;-).

> So the bug is specific to Readline, or is it specific to bash itself?

Readline.  Which is part of bash, but is available as a library for other things to use if they want.

You don't have to use bash or Readline to report an issue in it.  My point is that reporting it there and showing that it occurs in that code base starts a conversation with the author, and enables the author to weigh in as to whether (and why) it's intentional, or if it's a bug.  If the author agrees with you and addresses the issue, then Clink will benefit as soon as it can incorporate the next release of Readline.

**Comment by rashil2000** [comment]
I have filed a bug report in the Bash mailing list. You can follow it here if interested:
https://lists.gnu.org/archive/html/bug-bash/2021-07/msg00014.html
