### ISSUE TITLE
Install into a stable location

### ISSUE THREAD

**Issue by ethanhs** [chrisant996/clink#108]
I just updated clink and I noticed that it is now being installed into `C:\Program Files (x86)\clink\1.1.40.31e5f7`. This install location seems to be unstable. I realize this is a weird ask, but could this location be stable at least across minor versions? 

I want to be able to add clink's inject into my Autorun registry setting, but I have to edit this each time clink updates, which would be very painful.

Edit: Sorry to be clear I want to set my own autorun setting so that clink will start quietly, which is why the default autorun installation does not work for me.

**Comment by chrisant996** [comment]
Thanks for reporting this! That seems very problematic, yes.

I wonder if there was a good reason the installer is doing that, but I'll look into fixing that soon.

**Comment by chrisant996** [comment]
And also, why not use clink's `autorun install` command? For example `clink autorun install -q` to suppress the logo.

**Comment by chrisant996** [comment]
> I just updated clink and I noticed that it is now being installed into `C:\Program Files (x86)\clink\1.1.40.31e5f7`. This install location seems to be unstable. I realize this is a weird ask, but could this location be stable at least across minor versions?

Can you clarify what "now" means in "it is now being installed"?
It looks like Clink has always behaved this way, it isn't new.

Can you clarify more specifically why it's a problem?
I can see some reasons it could be troublesome, but I need to know the specific reason for this specific situation.

Also, does using `clink autorun install -q` solve the issue about suppressing the logo?  If so, is that sufficient?

**Comment by ethanhs** [comment]
Hi,

> Or did you download an old version?
I think I installed an old version. I'm not sure how that happened to be honest, but I think the issues persists with the latest.

I set up my machine to install needed programs and such via Puppet https://github.com/ethanhs/personal-puppet and modifying the registry was the easiest thing to do, because I wasn't aware of `clink autorun install`. It seems the correct incantation is `clink autorun install -- -q`, and I think that will work fine.

Thank you for the help!

**Comment by chrisant996** [comment]
Whups, yes I forgot the `--`, sorry!  Glad it's working ok for now.

I hadn't noticed that the installer uses a versioned install directory, and I think that's generally an undesirable approach.

However, I want to be cautious about whether/when to change that, because the installer code says `; Install to a versioned folder to reduce interference between versions.` which appears to indicate this is an intentional choice to solve some problems.  Changing it seems likely to bring back those problems, and then additional research and testing will be needed to find another viable solution.

I've added it to the todo list, but I don't anticipate taking any action in the near future.

Thanks!

**Comment by ethanhs** [comment]
I think versioning the install dir is useful (in case someone tries to install 2 different versions for some reason), I think my concern was with the git hash being part of the version. Perhaps keeping the major and minor (or maybe just major) version(s) in the install path would work.

**Comment by chrisant996** [comment]
_(This got fixed later; so I'm changing the label.)_
