### ISSUE TITLE
Regression for .. completion

### ISSUE THREAD

**Issue by EdVanDance** [chrisant996/clink#111]
I recently updated clink after a very long time (> 4y) and noticed that an issue I reported previously mridgers#277 appeared again.

A lot has changed since then, I couldn't figure out anything that might help to fix this issue.

Very happy, that you took over maintenance for clink @chrisant996. Kudos to you 👍

**Comment by chrisant996** [comment]
Are you saying the exact same issue occurs?
mridgers 277 says that `..`<kbd>Tab</kbd> inserts a space.
When I use any of the completion commands in Clink v1.2.5, it does not insert a space.
It also does not insert a `\`, which I think is the main point, but I want to make sure that I'm understanding correctly -- because if it's also inserting a space then I need additional information to understand what's happening.

**Comment by chrisant996** [comment]
Also, it looks like how bash works is that `.` and `..` are _only_ considered possible completions if the current word is `.` or `..`.

That's a significant nuance, since otherwise `menu-complete` would always start out with `.\` and then `..\`, and that would be very annoying for anyone who uses `menu-complete` (like myself).

And this is another case where completion results are unstable based on the word that's typed.  Clink v1.0.0 introduced a performance improvement that caches the completions for a word's position.  It builds the completion list assuming the current word is empty ("") and then _filters_ the completions based on the actual typed word.  Clink's current design and implementation are incompatible with the requested behavior.

I'll see what I can do about it, though.  I had to make changes 5e46b9a22b12ff059c4f28fc89e72dd332f305c0 and 3146af22687aee91967bdb83cafcc5ae83dc3c91 to support `~` completion, which has a similar characteristic of "completion results are unstable based on the word that's typed".  Hopefully a similar technique can be used to accommodate `.` and `..`.

**Comment by EdVanDance** [comment]
> Are you saying the exact same issue occurs?

You are right, it's not exactly the same. Current clink does not insert a space, just nothing happens.

I'm not familiar with menu-complete, but I think I know what you mean.

>  that would be very annoying for anyone who uses `menu-complete`

Yeah, I can relate to that.

> Clink's current design and implementation are incompatible with the requested behavior.

That's unfortunate.

> I'll see what I can do about it, though.

Alright, thank you very much.

I'm wondering why nobody else has this "issue". As a workaround I'm going to try to get used to type `../` instead, at least on english keyboard layouts `/` is next to `.`.

**Comment by chrisant996** [comment]
For future reference:

I'm torn on this.

Yes, bash behaves this way.
But Readline does **_not_**.
And Clink is **_not_** trying to be bash nor is it trying to be a shell -- it is trying to be an enhancement for the CMD shell, using Readline for input.

This particular issue is in the gray area of bash vs Readline vs CMD, and so I'll mimic this bash behavior at least for now (pending complaints in the opposite direction).

There are many ways that Clink does not behave the same as bash, and that's both ok and intentional.  For example, when completing the first word, bash only considers directories as possible completions if there is no file match, but Clink uses the `exec.dirs` setting to control whether to consider directories.  Bash (or at least git-bash) is also very slow at collecting matches, but Clink is very fast -- part of the improved speed comes from little differences like the preceding.

**Comment by garoto** [comment]
How is having to type an extra `\` and the end of a `cd ..` a burden? `\` is also very close to the ENTER key on US-English layout keyboards. Looks like picking nits to me.

**Comment by chrisant996** [comment]
> How is having to type an extra `\` and the end of a `cd ..` a burden? `\` is also very close to the ENTER key on a US-English layout keyboard. Looks like picking nits to me.

I don't disagree.  At the same time, I recognize that a lot of Clink users are trying to get a bash-like experience with CMD, and muscle memory can be hard/annoying to retrain.  I'm willing to support this case, especially since Martin had added support for it on request.

Btw, Martin didn't support it the same as bash:  Martin's fix made `.`<kbd>Tab</kbd> list `.\` and `..\` as possible completions.  But in bash `.`<kbd>Tab</kbd> completes uniquely to `./`.  I've made Clink mimic bash in that respect as well.  I spent a bit of time analyzing the many edge cases with bash and `.` or `..` completions (as the first word in the input line, as a later word, at the beginning of a word, at the end of a word, `complete` command, `menu-complete` command, `old-menu-complete` command, and so on -- these all have slight differences, but they follow from specific principles so it made sense to support them).  Clink should behave very closely to bash now for `.` and `..` completions.

**Comment by EdVanDance** [comment]
@chrisant996 Thank you very much for bringing this behavior back.

@garoto Yeah I agree for US english layouts. I switched to US english a couple months ago, after using the German layout for 20+ years, where <kbd>/</kbd> is <kbd>Shift+7</kbd> and <kbd>\\</kbd> is <kbd>AltGr+-</kbd> (<kbd>AltGr</kbd>is the right <kbd>Alt</kbd> key) or <kbd>Ctrl+Alt+-</kbd> (<kbd>-</kbd> as in next to 0). Just pressing <kbd>Tab</kbd> after <kbd>..</kbd> is pretty handy in that case.

**Comment by garoto** [comment]
I go to great lenghts to try and always buy EN-US layout keyboards instead of a kb with my local layout even if that means expending more monies. Way less headaches for my specific computer-usage cases.

**Comment by chrisant996** [comment]
I noticed all 4 cases of this problem are present again.  I'll track down when/how it got reintroduced, and fix it again (and hopefully in a more future-proof way).

I noticed it while working on adding completion support for directory shortcuts (`...\`, `....\`, `.....\`, etc).

**Comment by chrisant996** [comment]
The regression was introduced in v1.3.1 in commit 9abce03b1d when converting the default file match generator from C++ to Lua, as part of introducing the `autosuggest.async` setting to stay responsive to input while generating suggestions.

I made two mistakes while converting the check for the input ending with one or two dots, which existed specifically (and only) to fix issue 111. The check isn't just a literal check for one or two dots -- it has to make sure the input is either `.` or `..` or ends with `/..` or `\..`, and it has to ignore all quotes in the input (for example, `\".""""".""` must be considered a match to `\..`). I didn't fully/accurately convert a couple of C++ idioms into their corresponding Lua idioms.
