### ISSUE TITLE
Clink install adds "--profile ~\clink" to autorun

### ISSUE THREAD

**Issue by rmccampbell** [chrisant996/clink#116]
On installation the clink autorun command includes `--profile ~\clink`. This is not really a problem, but it is not documented anywhere. Also, confusingly, it seems to interpret "~" as the AppData folder instead of the home folder, which makes this the same as the default directory. I confirmed this with other paths, i.e. `clink inject --profile ~\temp` will show `C:\Users\%USERNAME%\AppData\Local\temp` in `clink info`.

**Comment by chrisant996** [comment]
Thanks for calling this out.

> On installation the clink autorun command includes `--profile ~\clink`. This is not really a problem, but it is not documented anywhere.

It's documented here:  [File Locations](https://chrisant996.github.io/clink/clink.html#filelocations).

> Also, confusingly, it seems to interpret "~" as the AppData folder instead of the home folder, which makes this the same as the default directory. I confirmed this with other paths, i.e. `clink inject --profile ~\temp` will show `C:\Users\%USERNAME%\AppData\Local\temp` in `clink info`.

Yes.  Clink 0.4.9 interpreted `~` as the AppData folder.  I was able to change `~` in the input line expand to %HOME% instead of the AppData folder, but I can't "fix" how the `--profile` flag interprets `~` without actually breaking existing installations (if I were to change `~` in the `--profile` flag to expand to the home directory, then Clink would no longer find people's existing customizations).  So it's a quirk that I think has to stay, for backward compatibility.

**Comment by rmccampbell** [comment]
Ah ok. I read the documentation as just saying the behavior when no profile was specified. The tilde behavior should probably be documented somewhere anyway.

**Comment by chrisant996** [comment]
> Ah ok. I read the documentation as just saying the behavior when no profile was specified. The tilde behavior should probably be documented somewhere anyway.

I'm pretty happy for it to remain documented to the same degree it currently is.  One has to go hunting to find it.

Also, beware asking for undocumented internal things to be documented.  😉  Last time that happened, Martin removed support for `--scripts` since it was meant only as a testing aid for himself.  But Cmder had already begun to completely rely on that undocumented behavior to take over Clink and force it to behave differently than was intended.  So one of the first things I had to do to revive the Clink project was to deal with that.

I would argue such things are already "too documented".  I certainly don't want to document them even more!  😄

**Comment by rmccampbell** [comment]
I still think people looking at the default inject script will be confused and think that their profile should be in their home folder. Perhaps the profile parameter should be set to a full path on install, or just removed entirely and just rely on the default profile.

**Comment by chrisant996** [comment]
Thanks.  While I don't disagree about the observations in an abstract sense, this isn't something I'm going to invest in.  There is no functional benefit, but it would cost me time and add risk of regression.  It's been this way for at least 5 years (maybe 8?) and doesn't seem to have been noted before.

I would be happy to review a PR if someone else wants to invest time on it.
