### ISSUE TITLE
inputrc is not read from `state` directory

### ISSUE THREAD

**Issue by EdVanDance** [chrisant996/clink#118]
I'm struggling for quite some time to fix this issue, but I can't figure it out by my self.

I'm trying to benefit from vladimir-kotikov/clink-completions#135 ...

So I created an inputrc and added:
```
set colored-stats on
```

Here is the relevant `clink info` output:
```
version  : 1.2.7.3b2d3f
binaries : C:\Users\edvan\scoop\apps\clink\1.2.7
state    : C:\Users\edvan\AppData\Local\clink
scripts  : C:\Users\edvan\scoop\apps\clink\1.2.7 ; C:\Users\edvan\AppData\Local\clink ; D:\tools\msys\home\edvan\.dotfiles\clink
inputrc  : %clink_inputrc%
             (unset)
         : state directory (see above)
             C:\Users\edvan\AppData\Local\clink\.inputrc   (exists)
```

It had no effect, so I tried to figure out what is going on ... it boils down to `rl.isvariabletrue('colored-stats')` returning false.
I added a simple script `C:\Users\edvan\AppData\Local\clink\test.lua`:
```
if rl.isvariabletrue('colored-stats') then
  print "yes"
else
  print "no"
end
```

It always prints `no`. Am I doing something wrong or is there an actual issue?

**Comment by chrisant996** [comment]
`print(rl.isvariabletrue('colored-stats'))` and `print(rl.getvariable('colored-stats'))` both work fine for me.
And I tried with a var that's on, and with a var that's off -- both work fine.

Sharing the `.inputrc` file might help, if that's possible.  Maybe the inputrc file has some other content that affects the outcome?  For example maybe a line later in the file sets colored-stats to off, or maybe there are conditional lines, or etc.

Do any other lines in the inputrc file take effect?  E.g. key bindings or other config variables?

Also, I might be confused:  what is the expected connection between `colored-stats` and https://github.com/vladimir-kotikov/clink-completions/pull/135?

**Comment by EdVanDance** [comment]
Sorry for not being clear enough, that is my entire inputrc, only this single line:
```
set colored-stats on
```
And there is no other inputrc:
```
inputrc  : %clink_inputrc%
             (unset)
         : state directory (see above)
             C:\Users\edvan\AppData\Local\clink\.inputrc   (exists)
             C:\Users\edvan\AppData\Local\clink\_inputrc
         : %userprofile%
             C:\Users\edvan\.inputrc
             C:\Users\edvan\_inputrc
         : %localappdata%
             C:\Users\edvan\AppData\Local\.inputrc
             C:\Users\edvan\AppData\Local\_inputrc
         : %appdata%
             C:\Users\edvan\AppData\Roaming\.inputrc
             C:\Users\edvan\AppData\Roaming\_inputrc
         : %home%
             C:\Users\edvan\.inputrc
             C:\Users\edvan\_inputrc
```

I just tried adding `set editing-mode vi` but `print(rl.getvariable('editing-mode'))` prints `emacs`.

[git.lua#L166](https://github.com/vladimir-kotikov/clink-completions/blob/dc590e83e1123cfd222757cc269ebf703e1ef80a/git.lua#L166) Coloring the star for predicted branches happens only if `colored-stats` is on.

I'm using Fluent Terminal, but I also tried in plain cmd. Same behavior.

I have only one non-default setting:
```
terminal.emulation = native
```
Removing that did not help either.

I moved the inputrc to `%LOCALAPPDATA%` and `%USERPROFILE%`, same story.

Is there anything else I can do?

**Comment by EdVanDance** [comment]
I just set up a minimal build environment and started some printf debugging ...

What I got to know so far:
- Although clink info says it's looking at state (localappdata\clink), it actually does not read an inputrc if it exists there (verified by looking into clink.log).
- Seems like lua scripts are loaded/executed before reading the inputrc, therefore my script always prints the default values.
- It also seems like the inputrc is read again after every command, not sure if this is expected, I assume it's not because by default readline has a specifc function mapped to C-x,C-r to re-read the inputrc (clink overwrites that mapping with clink-reload)
- I tried clink-reload, here inputrc is read before loading/executing and then my test script gives the result I expected (although my expectation might be wrong)

Now I don't even know why the colored star is not working, because the settings are only off during the start. I will try to dig deeper.

The test scipt:
```
print(rl.getvariable('editing-mode'))
print(rl.getvariable('colored-stats'))

function myfunc()
  print(rl.getvariable('editing-mode'))
  print(rl.getvariable('colored-stats'))
end
```

inputrc:
```
set editing-mode vi
set colored-stats on
C-p: "luafunc: myfunc"

```

**Comment by EdVanDance** [comment]
If my understanding is correct, `host::edit_line()` creates a fresh `line_editor` for each prompt, therefore it also creates a fresh `rl_module` instance, which calls `load_user_inputrc()` from the constructor.

**Comment by EdVanDance** [comment]
So actually the star thing works now, because I moved my inputrc to `%LOCALAPPDATA%`.

**Comment by chrisant996** [comment]
> * Although clink info says it's looking at state (localappdata\clink), it actually does not read an inputrc if it exists there (verified by looking into clink.log).

Doh!  Commit a6d8d14627cb01f3a757a3a9231c7e9ddba3bce5 made `clink info` look for an inputrc in the state directory.  But I completely missed making the corresponding change in `load_user_inputrc()` which is responsible for actually loading the inputrc file.  Thank you for tracking that down.

> * Seems like lua scripts are loaded/executed before reading the inputrc on startup, therefore my script always prints the default values.

Oh, yes, that's true, the first time an inputrc is loaded is after the first time scripts are loaded.  The first time Lua scripts are executed after inject (or after changing the scripts directory/ies) the scripts will not see the final inputrc state.  This is a side effect of how the `editor_module` stuff is set up.

> * It also seems like the inputrc is read again after every command, not sure if this is expected, I assume it's not because by default readline has a specifc function mapped to C-x,C-r to re-read the inputrc (clink overwrites that mapping with clink-reload).

It's expected, at least in the sense that Martin intentionally made it work this way, and the object oriented programming principles behind it seem reasonable, so I haven't messed with that.  I can see an argument both ways (load each time or load only once).  With that said, the same principles caused Lua to be torn down and reloaded for each `edit_line()` call, and that was causing functional problems e.g. with the Z.lua script, so I did mess with that part.

It makes sense for `rl_module` to be responsible for setting up the Readline commands.  The question is when/where -- can it be a `static` method that happens independently of any `rl_module` instance, or should the scope and lifetime of editor modules change, or etc.

> If my understanding is correct, `host::edit_line()` creates a fresh `line_editor` for each prompt, therefore it also creates a fresh `rl_module` instance, which calls `load_user_inputrc()` from the constructor.

Yes.  There are definitely pros and cons to that.  And I had to move the Lua initialization back to the host level so that e.g. Z.lua could maintain state across multiple prompts.  I think it may make sense at some point to refactor the modules a bit.  Martin clearly was going in one direction with the `editor_module` stuff, but I felt it was better to use Readline and make any needed changes in Readline, rather than circumventing Readline and trying to still integrate with Readline -- that was making some Readline features just not work properly (especially key bindings).  So anyway, yes, there are definitely pros and cons about the current approach.  I think I've gotten it to a point where it functions well, but there are some details that are questionable and suggest that the object design isn't optimally suited for the functional needs.

**Comment by chrisant996** [comment]
Mercy.  The concept of the profile directory is only in the "app" layer, and `rl_module` and `editor_module` are in the "lib" layer which shouldn't (and doesn't) know anything about any "app" layer concepts.  That's why the regression happened -- Clink 1.0.0 refactored the design, but the new organization creates subtle layering inversions in a few places.

It's easy to hack a solution, but I want to maintain the logical separation so it might get a little ugly.  Especially since it has to be compatible with unit tests, and naturally "lib" unit tests don't even have the "app" layer present.

**Comment by EdVanDance** [comment]
Awesone, thank you very much, especially for sharing all the insights. Very Interesting 👍 

Btw. is there a place to ask questions?

**Comment by chrisant996** [comment]
> Btw. is there a place to ask questions?

I guess open an issue. 🤷‍♂️ I haven't figured out if there's a better way. 😄
