### ISSUE TITLE
How to reuse registered parsers for doskey macros?

### ISSUE THREAD

**Issue by EdVanDance** [chrisant996/clink#119]
I'm using [git.lua](https://github.com/vladimir-kotikov/clink-completions/blob/master/git.lua) as an example.

Here is my macro:
```
gco=git checkout $*
```

How to get `gco` to complete like `git checkout`? Ideally without modifying the original `git.lua`.

**Comment by chrisant996** [comment]
> I'm using [git.lua](https://github.com/vladimir-kotikov/clink-completions/blob/master/git.lua) as an example.
> 
> Here is my macro:
> ```
> gco=git checkout $*
> ```
> 
> How to get `gco` to complete like `git checkout`? Ideally without modifying the original `git.lua`.

What an interesting question!

I think ideally Clink could/should handle that automagically, enabling both completions and coloring to work.  Coloring is tricky to handle automagically for that, but I have an idea that seems promising.  Completions should be mostly easy, except the hardest part would be blocking completions if there's no `$*` or etc.

I don't think there's currently a way to reuse a parser unless it's specifically designed for sections to be reusable.

The cited one is designed to be reusable ... but only from inside the git.lua file.

**Comment by chrisant996** [comment]
Since argmatchers, generators, and classifiers have direct access to some Readline APIs, those APIs will need to be modified to be able to redirect to an expanded version of the input line.  That's more effort and more complicated, but still doable.

In the meantime, if you want to get something working quickly you could remove the `local` keyword from the `config_parser` definition, and then you could use it in your own argmatcher, e.g. like `clink.argmatcher("gco"):addarg(config_parser)`.

**Comment by chrisant996** [comment]
Oh, or did you want to contribute and hook this up yourself in Clink?  You mentioned building it and debugging a bit, and you made accurate observations, so I assume you're comfortable in C++.  So if you're looking for a fun little project then let me know and I can share some pointers where/how to start.  Otherwise I'll hook it up myself sometime in the near future.

**Comment by EdVanDance** [comment]
> Oh, or did you want to contribute and hook this up yourself in Clink? You mentioned building it and debugging a bit, and you made accurate observations, so I assume you're comfortable in C++. So if you're looking for a fun little project then let me know and I can share some pointers where/how to start. Otherwise I'll hook it up myself sometime in the near future.

Well that actually sounds like a fun side project, I'm not as comfortable as I would like to be I guess, but somehow this makes it even more interesting to me. If you don't expect a solution in a couple of days, I would like to give it a shot. I'm not familiar with the codebase yet, so it will probably take a while to get started.

Some pointers regarding where and how to start would be really appreciated.

**Comment by chrisant996** [comment]
Sure, and this is a good opportunity for me to write up an overview of the code base. I'll add a markdown file to the repo in the next day or two.

If you want to explore in the meantime, the `get_linestate()` calls are the key spots of interest.  The `line_state` class represents the input line.

At a high level, my basic idea is if there's no argmatcher, but there is a doskey alias, then expand it in memory and proceed with a `line_state` based on the expanded string.

For input line coloring it can do the same thing, but it will have to map the colored cells back to the original actual input line.  Which can be done by keeping track of which characters in the expanded line came from the original line, and only keep those colored cells.

There's a spot in the "regen matches" code which get word break info, and that will need to be moved first, I think. I'll take a look Monday or Tuesday evening for how to relocate that.

I'll write more detail soon-ish.

**Comment by chrisant996** [comment]
@EdVanDance I added some `TODO("ISSUE119 -- blah blah blah");` annotations in `clink\lib\src\line_editor_impl.cpp` with high level notes on what is needed where.  They don't yet cover _how_ to do certain pieces -- e.g. how to check whether an argmatcher exists (which crosses the Lua/C++ boundary and so it involves a little boilerplate code; there are examples around the code base).

**Comment by EdVanDance** [comment]
@chrisant996 Thank you very much. I already had a look at some of these sections 😃

I'm still trying to understand all the relations going on, so please bear with me.

My initial thought was creating a custom generator:
- check if we are handling an alias (no? -> stop)
- expand alias, run lua generators on expansion

But probably I'm too naive 😄

Do you think that is computationally too expensive?

**Comment by chrisant996** [comment]
> My initial thought was creating a custom generator:
> 
> * check if we are handling an alias (no? -> stop)
> * expand alias, run lua (or more?) generators on expansion

It's necessary to build an expanded `line_state` and send that through the normal generator and classifier flows:

I like the idea of using a custom generator and custom classifier -- i.e. implementing it in Lua.  But it will run into difficulty further down the path:
1. It will need to produce an expanded `line_state`, and that needs to be done in the C++ code.
2. It will need to use the alias expansion code, and that needs to be done in the C++ code.

So I think it makes sense for the C++ code to decide whether to use the "normal" `line_state` construction, or to build an "expanded" `line_state`.  Either way, it can then just send the `line_state` through the normal generator and classifier flows.

The `_find_argmatcher` function in `arguments.lua` will need to be made public (remove `local` and add `clink.` to name), and the C++ code will need to call it.  That involves a little interfacing with Lua, but it can be done by mostly copying from similar calls into Lua code.

The classifier flow needs to also translate the expanded coloring choices back into the original input line.  For that I would extend the alias expansion code so that it can also produce an array of bool values indicating which characters in the expanded string came from the original string vs due to the alias expansion.  Then when it's time to translate the colors back to the original "coordinate system", the array of bool values controls that:
- Use a pair of slow/fast iterator pointers:
  - Let `orig_faces` point to the `m_faces` in the `word_classifications`.
  - Let `expanded_faces` point to the `m_faces` in the `word_classifications`.
  - They will advance at different rates, enabling in-place translation of the results.
- Loop over the array of bools.
  - If an element is true, `*(orig_faces++) = *expanded_faces;`
  - Regardless whether an element is true, `expanded_faces++;`

Makes sense?  Questions are welcome.

> Do you think that is computationally too expensive?

I'm not worried about computation cost, provided that it has optimizations to short circuit out as soon as it detects there isn't a doskey alias or there isn't an argmatcher for the expanded string.

**Comment by EdVanDance** [comment]
Oh I'm sorry, I wasn't clear enough again.

I wasn't talking about implementing it in lua, but in c++ like the `file_match_generator`.

I hacked a quick prototype:
- Duplicated `file_match_generator` as a starting point
- Hooked it up [here](https://github.com/chrisant996/clink/blob/b2a8c257c96907a34796a715f703210736748a6b/clink/app/src/host/host.cpp#L618), between the lua genarator and the file_match_generator 
- Gave it access to the lua generator
- faked an expanded line_state
- passed it to the lua generator

So we are just generating approriate canditates, without faking the actual line editor state.

Surprisingly it seems to just work:
![image](https://user-images.githubusercontent.com/3735563/119476904-c9763c80-bd4e-11eb-999a-60467eaa3dbd.png)

I made an assumption, could you please verify?
- Because the new generator runs after the original lua generator, we know there was no matching argmatcher

I ran into an issue with the tests. Even if I break the new generator on purpose, by returning true unconditionally, therefore preventing execution of the `file_match_generator`, all tests are still green. Any ideas why?

I would like to add tests early, I still need to figure out how the test infrastructure works. Could you please provide some exotic scenarios which come to your mind?

And one more thing, `doskey` belongs to the `app` layer atm, would it be ok to move it to `lib` to use it for alias expansion? In it's current form it probably can't handle the "alias withoug argumets" case.

Please share your thoughts 😃

**Comment by EdVanDance** [comment]
I guess I naturally assumend the lua generator only provides completion candiates, does it have any other side effects?

Maybe that's why I don't understand the classifier flow implications.

**Comment by chrisant996** [comment]
> Surprisingly it seems to just work:

Nice proof of concept! 😃

> I wasn't talking about implementing it in lua, but in c++ like the `file_match_generator`.

I want to hook this up thoroughly; I'm not content to make it only work for one of Clink's features (i.e. argmatchers).
- Using a custom generator can't affect other custom generators or classifiers, so it would _only_ make argmatcher completions work (not argmatcher input coloring, and not custom completions or custom input coloring).
- Sending an expanded `line_state` in from outside the generators/classifiers (per the `TODO` notes in `line_editor_impl.cpp`) will affect all generators and classifiers (including `argmatcher_generator` and `argmatcher_classifier` in arguments.lua).

> `doskey` belongs to the `app` layer atm, would it be ok to move it to `lib` to use it for alias expansion?

Yes:

It looks like it's in the `app` layer because it's considered part of the "host", i.e. cmd.exe.  Doskey aliases don't work in Powershell, for example.  Clink 0.4.9 could apparently be injected into Powershell as well, but Clink 1.0.0 lost that ability.  The way the code is structured, I get the impression Martin was intending to eventually hook that up again.

Even if Clink does eventually support injecting into Powershell again, I think it's reasonable for the app/host layer to "configure" the lib layer indicating which capabilities to enable.

So yes, moving `doskey` to `lib` seems reasonable to me.

> In it's current form it probably can't handle the "alias withoug argumets" case.

I think you're referring to blocking completions if an alias doesn't include `$*`, yes?  I figured it's reasonable to tackle that in a follow-up change.

> I ran into an issue with the tests. Even if I break the new generator on purpose, by returning true unconditionally, therefore preventing execution of the `file_match_generator`, all tests are still green. Any ideas why?
>
> I would like to add tests early, I still need to figure out how the test infrastructure works. Could you please provide some exotic scenarios which come to your mind?

The test infrastructure is used to run unit tests, and the prototype change is in `clink/app/src/host/host.cpp` which is very high level code outside any of the testable units.

If the enhancement is implemented by sending an expanded `line_state` into the existing generate and classifier flows in `line_editor_impl.cpp`, then it will be exercised by the unit tests.

I think it will be sufficient to just update a few tests that fail (or fix bugs, if the tests are revealing regressions) and to add a few cases each for argmatcher completions, argmatcher classifications, custom generator completions, and custom classifier results (both word classifications and also use of `applycolor()`).  Probably 2-5 positive cases each, and 1-2 negative cases each (if applicable).

**Comment by chrisant996** [comment]
_Update on a design point:_

Oh, I was wrong about the `TODO` note in `line_editor_impl::update_internal()` -- the `set_word_break_info()` is fine there.

The issue is actually the `get_word_break_info()` call in `line_editor_impl::collect_words()`.  It builds a temporary `line_state`, but it will need to instead take `const line_state&` as a parameter.  That will have a ripple effect on callers, and possibly on where buliding an expanded `line_state` needs to be happen.

**Comment by EdVanDance** [comment]
> I want to hook this up thoroughly; I'm not content to make it only work for one of Clink's features (i.e. argmatchers).

Ok, got it. I wasn't really aware of all the other features.

> I think you're referring to blocking completions if an alias doesn't include $*, yes? I figured it's reasonable to tackle that in a follow-up change.

Yes, that's what I meant. Alright 👍 

So I was tinkering around and now I'm confused 😄

Not quite sure how to do the expansion. Initially I thought to create a new line_state by transforming the current, I thought this would have the least side effects to not break anything else. I can't put my finger on it, but it feels wrong somehow.

Currenty I'm thinking about doing the expansion within an undo group in the the rl_buffer and then just undo ... Do you think that might be an option? Or would it mess up `vi-redo`?

**Comment by chrisant996** [comment]
> Not quite sure how to do the expansion. Initially I thought to create a new line_state by transforming the current, I thought this would have the least side effects to not break anything else. I can't put my finger on it, but it feels wrong somehow.

Yeah...  You reached the part about `rl_buffer::collect_words()`, right?  😕

`collect_words()` is built into `rl_buffer`, but it doesn't actually functionally depend on Readline at all, so it shouldn't have a structural dependency on Readline (`rl_buffer::get_buffer()` directly returns Readline state).

Refactoring needs to happen.  It could be done through:
1. Inheritance.  E.g. insert a derived class between `line_buffer` and `rl_buffer` which implements `collect_words()` and `find_command_bounds()` etc.
2. Helper function.  E.g. move the body of `rl_buffer::collect_words()` into a helper function that just needs `const char* buffer` and `int len` arguments.

Either way seems reasonable, and also pretty straightforward.  Also, neither way precludes the other; in fact both could be done if desired (but why do both until more than one is actually required).

Once the `rl_buffer` dependency is lifted, then it becomes possible to expand into a string (I think you've already got that working) and then run the refactored variant of `collect_words()` directly on the string buffer.  Thus a separate `line_state` can be produced without using the Readline buffer.

Does that clarify?  That's the issue you ran into, yes?

> Currenty I'm thinking about doing the expansion within an undo group in the rl_buffer and then just undo ... Do you think that might be an option? Or would it mess up `vi-redo`?

I would avoid that mainly because:
- Undo groups seem to be able to have user-visible side effects while a history search is active (e.g. <kbd>Up</kbd> arrow a few times then edit).
- Some operations may trigger redisplay at inopportune moments and actually display the expanded input line temporarily (causing flicker or other disorienting effects).
- Addressing it at a lower level via refactoring has broader code benefits.

**Comment by EdVanDance** [comment]
> Yeah... You reached the part about rl_buffer::collect_words(), right?

Actually I didn't reach so far to be honest. In the end I wasn't sure, should I create a new `line_state` or should I modify the inputs of `get_linestate()`. 

> Does that clarify?

It was definitely very valueable feedback. I think I can figure out how to create  a new `line_state`  now.

> I would avoid that mainly because ...

Got it 👍 

I hope you don't mind that it takes so long, I can't spend as much time as I would like to, but I really enjoy the journey. Thank you very much for the support.

**Comment by chrisant996** [comment]
> I hope you don't mind that it takes so long, I can't spend as much time as I would like to, but I really enjoy the journey. Thank you very much for the support.

There's no hurry. 🙂

Thank you for the idea, and for generously contributing your time and energy!  And very glad the journey is fun -- that's certainly a big part of why I do this. 😁

**Comment by chrisant996** [comment]
@EdVanDance -- just checking in:  Is this something you want to finish?  There's no rush, but if you'd like I'm happy to implement it.  I just don't want to steal a project if it's something you'd like to finish.  😊

**Comment by EdVanDance** [comment]
Sorry for not letting you know earlier, I broke my arm about 10 days ago. Typing isn't fun atm and I assume this won't change in the upcoming 2 to 3 weeks. Sure, go ahead. I hope I can pick up something else in the future.

**Comment by chrisant996** [comment]
Oh snap!  (Too soon?)  Sorry to hear it, and hope the arm heals well and quickly!

**Comment by EdVanDance** [comment]
> Oh snap! (Too soon?) Sorry to hear it, and hope the arm heals well and quickly!

Nah, it's all good, it was actually quite funny. 😄 Hope so too. 👍

**Comment by chrisant996** [comment]
This has turned out to be very complicated.

In the following examples, let `_` represents the cursor position.

### _Look at how crazy it gets..._

#### Doskey macros can omit a command entirely
`doskey aaa=$1`
- So using the `menu-complete` command (cycle through completions) would end up changing which argmatcher to use, thus also changing what completions "should" be generated for the next `menu-complete` keypress.  It's such a niche case that Clink will ignore it, and might behave confusingly, but Clink will consider it to be user error.

#### Doskey macros can reorder arguments
`doskey aaa=foo $3 $2 $1`
- Typing `aaa x_` then<kbd>Tab</kbd> treats `x` as the first arg to the argmatcher for `foo`.
- Typing `aaa x y_` then<kbd>Tab</kbd> treats `x` as the _second_ arg to the argmatcher for `foo`.
- Typing `aaa x y z_` then<kbd>Tab</kbd> treats `x` as the **_third_** arg to the argmatcher for `foo`.
- So using arg completion can't use the "right" match generator because the other arguments haven't been entered yet, so there's no way to "shift" the match generators to correspond to the reordering done by the doskey macro.
- It might look like with a bit of extra work Clink could notice when a doskey macro reorders args and then Clink could internally reorder how argmatchers interpret typed arguments.  But even if that were done, the Lua script match generators themselves still won't understand and will still misbehave.  So it's not worth trying to compensate for reordering.
- Clink must simply behave naïvely, and consider it to be user error.

#### Doskey macros can concatenate arguments with other text, and/or with each other
`doskey aaa=foo xx$1 y$2y $3zz`
- Typing `aaa a_` <kbd>Tab</kbd> has to generate completion for `xxa` and then strip off the leading `xx` before inserting the completion.
- And if `aaa a_` <kbd>Tab</kbd> has to display matches, then should it show the `xx` prefix or not?
- Again it's not worth trying to compensate for concatenations:
    - Match display will show `xxa`.
    - Match completion will insert `xxa`, which will then turn into `xxxxa` when the doskey macro is eventually expanded to run it.
- Clink will consider it to be user error.
`doskey bbb=foo $2$1`
- Typing `bbb \fil_    ~` and <kbd>Tab</kbd> gets interpreted as `foo ~\fil_`, which completes to `foo c:\users\yourname\filename`.  And then should it split the completion?  `bbb \filename_    c:\users\yourname`?
- Again not worth compensating:
    - Match completion will insert `c:\users\yourname\filename`, and the input line will become `bbb c:\users\yourname\filename    ~`.
- Clink will consider it to be user error.

#### Doskey macros can repeat arguments
`doskey ddd=foo $1 $1`
- Typing `ddd a b_` will use arg 2's match generator for `b`; it won't reuse the arg 1 match generator.
- Again, even if Clink noticed the repeated arg expansion in the macro, Lua scripts would not understand and would misbehave.  So again it's not worth trying to compensate for repeated arguments.
- Clink will let them complete "wrongly" and consider it to be user error.

#### Doskey macros can omit arguments
`doskey eee=foo $1 $1 x$9$9x $8mmm$2`
- Again, there's no reasonable way to behave other than to malfunction and call it user error.
