### ISSUE TITLE
Adding doskey aliases through/with clink

### ISSUE THREAD

**Issue by bw1faeh0** [chrisant996/clink#125]
I know there are some ways by creating a doskey macro file and do some registry hacks to load my personal doskey settings with every new command line. 

I just wonder if there could be a solution for this with the help of clink (maybe some lua scripts or using the already existing .inputrc file).
Of course I could edit the clink.bat within the install dir, but my changes would be lost with an update of clink...

**Comment by chrisant996** [comment]
Does `os.execute()` not work to run `doskey` commands?

**Comment by EdVanDance** [comment]
`doskey` also allows to create macros/aliases on the fly, like: `doskey myalias=very long command`.

Here is a pretty bare-bones example how I would hook this up in lua for clink:
```
local function alias(short, long)
    os.execute('doskey ' .. short .. '=' .. long)
end

alias('gs', 'git status -sb')
alias('gco', 'git checkout $*')
```

clink itself has means to interact with doskey macros, but AFAIK there is no public API for that.

**Comment by bw1faeh0** [comment]
> Does `os.execute()` not work to run `doskey` commands?

To be honest, I'm not familiar with the lua interface of clink and even with the help file I was not able to answer my question. Maybe I didn't read carefully enough...

At the end I don't know how to write a lua extension and how to plug it into the start of clink ("autoload"/"autostart"/you name it...).

@EdVanDance s reply looks promising, but again, I don't know where to put the code into, where to put the lua file and how to tell clink to use this lua file...

**Comment by chrisant996** [comment]
> > Does `os.execute()` not work to run `doskey` commands?
> 
> To be honest, I'm not familiar with the lua interface of clink and even with the help file I was not able to answer my question. Maybe I didn't read carefully enough...

[Extending Clink](https://chrisant996.github.io/clink/clink.html#extending-clink) says the locations Clink loads Lua files from.  So, that's where to put Lua files.

> At the end I don't know how to write a lua extension and how to plug it into the start of clink ("autoload"/"autostart"/you name it...).

It loads all Lua files from those locations. It's that simple.

Read up on Lua to understand more about Lua. But "load a Lua file" means executing the code it in.

> @EdVanDance s reply looks promising, but again, I don't know where to put the code into, where to put the lua file and how to tell clink to use this lua file...

The first section under "Extending Clink" is "Location of Lua Files".
That says where Lua files are loaded from.
Make a mything.lua file in one of those locations, and put Lua code in it.
It will run when Clink starts.

Can you share some specific feedback about what's not clear?

**Comment by bw1faeh0** [comment]
> The first section under "Extending Clink" is "Location of Lua Files".

🤦‍♂️

> Can you share some specific feedback about what's not clear?

No, thats too simple... I wasn't expacting that. Sorry for this unnecessary issue.

**Comment by chrisant996** [comment]
> > The first section under "Extending Clink" is "Location of Lua Files".
> 
> 🤦‍♂️
> 
> > Can you share some specific feedback about what's not clear?
> 
> No, thats too simple... I wasn't expacting that. Sorry for this unnecessary issue.

Ok, but that's useful feedback!  I've made several documentation changes for the upcoming v1.2.10, such as the table of contents now includes sub-headings under Extending Clink and some other sections.  So now "The Location of Lua Scripts" is visible in the table of contents.  At least for myself, that kind of thing makes it a lot easier to mentally process the documentation.

Maybe it would be helpful for the docs to show a specific simple example of making a Lua script.

And maybe this is the key unexpected point:  Lua can have code outside of functions.  Thinking of it from a C/C++ perspective, the whole .lua file is a big implicit `main() { ... }` function.  And functions declared inside are actually lambdas (except that globally declared functions go into a big function table, making sure they don't get garbage-collected away).

I'd like to have maybe 2 or 3 "orientation" sentences and/or a simple example near the beginning of the "Extending Clink" section.  I feel it's a little light in describing _how_ Lua is integrated in Clink.  I worked it out by working on the Clink code base itself, by reading Lua docs, and by examining various samples.  Now I want to distill out a couple key points to help the "ah-ha!" moment happen more quickly and easily.

So if you can, please feel free to share any specific feedback about what's missing/etc in the docs that made it difficult to catch this part.

Thanks!
Chris

**Comment by bw1faeh0** [comment]
> Maybe it would be helpful for the docs to show a specific simple example of making a Lua script.

Would be perfect!

> And maybe this is the key unexpected point: Lua can have code outside of functions. Thinking of it from a C/C++ perspective, the whole .lua file is a big implicit main() { ... } function. And functions declared inside are actually lambdas (except that globally declared functions go into a big function table, making sure they don't get garbage-collected away).

This is some hard stuff for me, who expectes one file with a void main (void)... If all lua file are executed that clinks finds in the path given by %CLINK_PATH% (and so on) how dows it handles the order of execution? What about race conditions when function in differenet files 'act' on the same issue (e.g. prompt)?

And one big issue I just stubled over right now:

Your headings are missing chapter numbers. Let's say I just found a intresting topic "Completion Colors" by scrolling through the new docu of 1.20. I never read about the colors stuff before. Looked into it. Says something about set `colored-completion-prefix` to `on`. My first thought was: "Where to put it in?". There is no file mentioned. There is no clink command mentioned, that enables that feature persistent. Ok, scrolling up a little bit... Mhh.. does this chapter belongs to "Configure readline"? Maybe I could put this setting into my `inputrc`.
And in this case chapter number are very helpful :D 

And the next question that arises from this (after I put `set colored-completion-prefix on` into my inputrc):

Where do I set `LS_COLORS=so=90:fi=97:di=93:ex=92`? Ok, I know I could put it directly into my command line, but this is not persistent across different sessions. So where to set it? inputrc? This would be my guess based on the structure of the docu, but I'm not sure. And until now, I don't know. The only way I know to set env variables in windows persistent is a pain in the ass. Maybe I could modify the `clink.bat` in the install dir. But this is not recommended, becaus I don't know what happens with the next update to this file.

Maybe one addtional note:

Personally I read documentation not from top to bottom. I'm jumping to a specific (sub-) chapter and trying to find all the information starting from this chapter. This procedure works If the author put all needed information into this chapter. This procedure does not work, if the author expects, that the chapters before are already read...

**Comment by chrisant996** [comment]
Thank you for explaining!  I'm not sure there's anything I can do to help, unfortunately.

> > And maybe this is the key unexpected point: Lua can have code outside of functions. Thinking of it from a C/C++ perspective, the whole .lua file is a big implicit main() { ... } function. And functions declared inside are actually lambdas (except that globally declared functions go into a big function table, making sure they don't get garbage-collected away).
> 
> This is some hard stuff for me, who expectes one file with a void main (void)... 

Lua is not C.  Some reading up on Lua may be useful for understanding Lua.

Clink docs are for using Lua in the context of Clink.  The Clink docs link to Lua docs, but will not attempt to replace the Lua docs.

> If all lua file are executed that clinks finds in the path given by %CLINK_PATH% (and so on) how dows it handles the order of execution? 

`clink info` shows the order the directories are searched.
`dir *.lua` in a directory shows the order files are loaded from that directory.

This is the most natural approach.  A program would have to go out of its way to behave differently than that, and at that point it really would need to explain in detail how it works.

> What about race conditions when function in differenet files 'act' on the same issue (e.g. prompt)?

The Clink docs explicitly explain that in the section on customizing the prompt, and in the Lua API Reference entry for the relevant API.  The priority parameter when creating a prompt filter object controls the order.

Prompt filters are event handlers.  They are not procedural code that runs on loading Lua scripts.  It doesn't matter the order the procedural code runs that creates the prompt filters, because the priority order specified by script code controls execution order.

> And one big issue I just stubled over right now:
> 
> Your headings are missing chapter numbers.

There are benefits and drawbacks both ways, but I'm not going to use numbers.

> Let's say I just found a intresting topic "Completion Colors" by scrolling through the new docu of 1.20. I never read about the colors stuff before. Looked into it. Says something about set `colored-completion-prefix` to `on`. My first thought was: "Where to put it in?". There is no file mentioned. There is no clink command mentioned, that enables that feature persistent. Ok, scrolling up a little bit... Mhh.. does this chapter belongs to "Configure readline"? Maybe I could put this setting into my `inputrc`.
> And in this case chapter number are very helpful :D 

How would section numbers help further?  Is the intent to find the beginning of a chapter?  All chapter headings are underlined, and are listed in the table of contents.  I added indented sub-headings in the table of contents using a smaller font.  That's pretty universal for indicating a section within a chapter.

Skipping around in a document will inherently skip past preceding explanations, and that may make it difficult to understand later text.  This is typical in written material.  I don't think it's appropriate for every section to explain all the things from previous sections.  I don't think I've ever encountered a document which does that -- is there a specific example document that does a good job of explaining things in every section, so I could learn from it?

> And the next question that arises from this (after I put `set colored-completion-prefix on` into my inputrc):
> 
> Where do I set `LS_COLORS=so=90:fi=97:di=93:ex=92`? Ok, I know I could put it directly into my command line, but this is not persistent across different sessions. So where to set it? inputrc? This would be my guess based on the structure of the docu, but I'm not sure. And until now, I don't know. The only way I know to set env variables in windows persistent is a pain in the ass. Maybe I could modify the `clink.bat` in the install dir. But this is not recommended, becaus I don't know what happens with the next update to this file.

LS_COLORS is an environment variable, as indicated in the docs by the % signs surrounding it.

The inputrc file is not a batch script, and OS environment variables cannot be set in it.  The Clink docs explicitly cover inputrc file syntax, and the Readline docs cover it in more detail.

There isn't a "best" approach for how/where/when to set environment variables.  There are so many possible approaches, and that's a bit outside of Clink.  Unfortunately Clink docs aren't going to be a primer for how to use CMD or batch scripts or etc.  I have to draw a line somewhere.

(Could set env var in registry, or in a batch script, or in a Lua script.  Could call script via CMD's AutoRun regkey, or via another script.  Could make a script that does various preparation actions and then starts Clink -- the actions could include setting env vars, setting doskey macros, and many other things.  It's up to a user how they want to configure things.)

> And after setting up this color stuff I'm not sure, where I can see this colors. Completion when navigating through my dirs with `cd` ? Output of `dir`? I don't know how to test this settings (di=93).

Clink links to the Readline docs.  Some things probably won't be clear without reading the Readline docs.

The Clink docs say the colors affect "displaying possible completions".  That's a feature of Readline and is described in those docs.  There are several Readline commands that can display possible completions.  By default <kbd>Tab</kbd> inserts an unambiguous partial completion or lists ambiguous options, or <kbd>Alt</kbd>+<kbd>=</kbd> lists possible completions.

> Maybe one addtional note:
> 
> Personally I read documentation not from top to bottom. I'm jumping to a specific (sub-) chapter and trying to find all the information starting from this chapter. This procedure works If the author put all needed information into this chapter. This procedure does not work, if the author expects, that the chapters before are already read... 

The approach will run into problems when one topic requires knowledge about several other topics.  That's what's happening here.

This author (and Martin before me) went to some trouble to arrange the documentation in an order that introduces topics that build upon preceding topics.  Skipping ahead may require backtracking to fill in gaps, depending on which topics a reader is already familiar with.

**Comment by hagaigold** [comment]
> `doskey` also allows to create macros/aliases on the fly, like: `doskey myalias=very long command`.

[Another option will be to use a macro file thru clink setting](https://gist.github.com/hagaigold/02d5f6e1d11ad15b76a29cdbd803157c):  


```
settings.add('my.alias.filepath',
    '',
    'File name to load aliases from',
    'This file is actually a DOSKEY MACROS file.')

local filepath = settings.get('my.alias.filepath')

if filepath and filepath ~= '' then
    os.execute('doskey /listsize=500 /macrofile="' .. filepath .. '"')
end
```
