### ISSUE TITLE
Make Esc-. do what A-. does

### ISSUE THREAD

**Issue by uknomadgames** [chrisant996/clink#126]
Hi 

Not strictly an issue, and thanks for taking over maintenance of clink - it keeps me almost sane whem I'm working on Windows.

I've just upgraded to your version from <insert old version here from 2019 or so> and I can't seem to work out how to make Esc-. map to yank-last-arg like it used to 

It's now mapped to clink-reset-line.

Thanks
Rob

**Comment by chrisant996** [comment]
Had you set up a custom key binding for that?  <kbd>Esc</kbd>-<kbd>.</kbd> in Clink v0.4.9 (the old version) is not mapped to `yank-last-arg` by default.

I wrote a [Key Bindings](https://chrisant996.github.io/clink/clink.html#keybindings) section in the documentation trying to explain how to set up key bindings.  Have you read the section, especially the "Discovering Clink key sequences" sub-section?

What have you tried so far?
Can you share what is unclear in the documentation, so I can improve it?

**Comment by uknomadgames** [comment]
Hi 

I haven't set a binding for that, and didn't have to for the 0.49 version - I've just grabbed that verson and built it to verify that, by
running cmd.exe and then running clink_x64 inject. This is with no inputrc

I have read the docs, but not managed  to get it work

The behaviour seems to be standard - at least on unix systems that I've used. 

On the latest version, mapping Esc in either of these ways

"\e[27;27~-." : yank-last-arg
"Esc-." : yank-last-arg

doesn't result in the old behaviour

It seems to me that on the v0.49, the escape key == Alt (or Meta)

The docs are great btw - I don't really think anything is missing.

cheers
Rob

**Comment by chrisant996** [comment]
Oh, at some point `clink set esc_clears_line 0` must have been used.
That's the missing step to reproduce the behavior in Clink v0.4.9.

Anyway, yes, on *nix systems indeed terminal input is messy, because <kbd>Esc</kbd> is both a key that can be input directly, and is also embedded into many other input keys.  If you bind a function to <kbd>Esc</kbd>, then it breaks _**all**_ special input keys (arrow keys, function keys, etc) -- and that gets especially complicated with key chords (you can even fall into a situation where all further input is broken until you figure out what ANSI escape code you accidentally started that's consuming all input, and figure out how to end it to restore keyboard input working).  If you press a key that isn't bound (e.g. <kbd>F11</kbd>) then some stray characters get inserted into the input -- the leftover portion of the special key sequence that didn't match anything.  And if you manually type the ANSI escape code sequence for some other character then the terminal behaves as though that _other_ character was pressed.

You're taking advantage of that last quirk and manually typing the ANSI escape code for <kbd>Alt</kbd>+<kbd>.</kbd>.  I get it.  It's reasonable, especially coming from a *nix background as yourself.

Since Clink is on Windows, I wanted to provide Windows-like key binding support:  unbound keys don't insert anything and can beep or flash to indicate they are unbound, <kbd>Esc</kbd> can be bound to whatever you like without breaking the rest of the input experience, and you cannot manually input the ANSI escape codes for other keys.  I realize that's "not how *nix terminals work"; this is a conscious intentional departure.

With that said, I can add a setting to allow *nix-like input, along with all of its quirks and issues.

**Comment by chrisant996** [comment]
> "\e[27;27~-." : yank-last-arg

The key sequence above binds <kbd>Esc</kbd>,<kbd>-</kbd>,<kbd>.</kbd> to `yank-last-arg`.

Where did the `-` come from?  I.e. what in the docs made it seem like making `-` part of the raw input sequence was needed?  I want to clarify the docs.

The following would bind <kbd>Esc</kbd>,<kbd>.</kbd>:
```
"\e[27;27~.": yank-last-arg
```

**Comment by uknomadgames** [comment]
Thanks for the comprehensive reply. 
Your last post which shows the correct binding for Esc-. (using the escape sequence without the -) actually seems to make Esc-. do what I want - I must have just typed that in wrong - mixing the "\M-." style with the raw codes for Esc. I don't think the docs are unclear - that was just my mistake.

I don't know if I need the full *nix style Esc - since Esc-. doing yank-last-arg is mostly all I ever do.

Thanks for all the help

Rob

**Comment by chrisant996** [comment]
> ... binding for Esc-. ... I must have just typed that in wrong ... I don't think the docs are unclear - that was just my mistake.

Ok thanks for the feedback!

> I don't know if I need the full *nix style Esc - since Esc-. doing yank-last-arg is mostly all I ever do.

Ok sure, that makes sense. I've still added a setting, since I can see how a *nix user could potentially actually like how *nix terminal input works (though I can't personally relate with that 🙃).
