### ISSUE TITLE
Bug completing files with - or _ characters

### ISSUE THREAD

**Issue by uknomadgames** [chrisant996/clink#129]
Make a directory, and then create 2 files in the directory
$ echo > test-1
$ echo > test_2

now try to tab-complete test-

The trailing - is deleted. Same for completing test_

Not a show-stopper, but I _do_ have some tools that fit this pattern so I hit this a few times a day

Cheers
Rob

**Comment by chrisant996** [comment]
It sounds like the `match.ignore_case` setting is set to `relaxed`.
You can confirm by running `clink set match.ignore_case`.
When that's set to `relaxed`, then `-` and `_` are treated as equal -- so then the longest common sequence is `test`, and thus the text gets shortened.

Sounds like running `clink set match.ignore_case 1` (or `clink set match.ignore_case 0`) may produce what you want.

I'm not sure why Clink has this "relaxed" mode or why it's the default.  I'm hesitant to change something just because I don't understand it; sometimes that causes bigger problems than it solves.  ;)

**Comment by uknomadgames** [comment]
Ok  - it looks like it sets it to relaxed by default. I like ignore case on anyway (but of course on window that's moot), but setting it to ignore case _also_ fixes the issue.

I will close it.
Thanks
Rob

**Comment by chrisant996** [comment]
I realized this was a regression, and it will be fixed in the next update.
