### ISSUE TITLE
[Feature Request] Support for UNIX completion files

### ISSUE THREAD

**Issue by pukkandan** [chrisant996/clink#135]
I know that clink supports argument completions using lua. However, creating completion for each program is quite tedious. The only collection of completion files for clink that I found is https://github.com/vladimir-kotikov/clink-completions. But that only covers a very few apps. 

On the other hand, since UNIX systems have supported completions natively for a long time, many cross-platform packages already comes with completion files (or there are thrid party scripts readily available). It would be amazing if clink could load these directly without the user having to translate each file manually into lua.

It is not necessary to support all the variations offered by the various UNIX shells. Just supporting any one of these formats would enable clink to access a vast library of auto completions with minimal effort from the user.

I understand that this is definitely not a trivial feature to implement, but thought I might as well ask

**Examples**:
git: https://github.com/git/git/blob/master/contrib/completion
npm: (unofficial) https://github.com/Jephuff/npm-completion/blob/master/completions/npm.sh
youtube-dl: The `youtube-dl-2021.06.06.tar.gz` in [releases](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.06.06) contain fish, zsh and bash completion files

**Documentation**:
bash: https://www.gnu.org/software/bash/manual/bash.html#Programmable-Completion
fish: https://fishshell.com/docs/current/completions.html

**Comment by chrisant996** [comment]
First, I definitely understand the motivation and concept.  It would be great.

Those are not "completion files".  Those are shell scripts for specific shells.  Clink would have to become one of those shells in order to run their shell scripts.  (In fact it would be much easier for a shell to support Clink's Lua scripts than for Clink to become any of the shells.)

This isn't something Clink can do, sorry.

Perhaps someone with an interest could try to write a program that can translate some shell scripts into Lua, but that's probably an enormous task that would even then only partially work.

**Comment by chrisant996** [comment]
Also, completion scripts for bash, fish, and zsh expect that they're running on *nix.  Even if Clink embedded the code for one of those shells and ported their code to Windows, that still wouldn't be sufficient because the scripts themselves expect to be running on *nix and to have other *nix programs available to be called by the script.

I wish there were some way to automagically get completions for programs, but it's a chicken-and-egg problem.  To get a broad collection of completion scripts, Clink needs to be widely used.  Without a broad collection of completion scripts, Clink can't become widely used.

If Windows had man pages, then Clink could parse them to auto-generate completions (similar to what the fish shell does).  But Windows doesn't have man pages.  This is where Powershell's scripting language is very clever; all Powershell scripts give the shell the info it needs to automatically generate basic completion support for the script (though it still can't auto-generate more sophisticated completions for custom argument types).  But even then, Powershell can't auto-generate completion support for things that aren't Powershell scripts or built-in Powershell commands.
