### ISSUE TITLE
[Feature Request]: Allow setting Readline bindings from the commandline

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/clink#140]
Bash allows setting Readline options and keybindings on the fly, from the shell itself, like this:

```bash
bind '"\e[B": history-search-forward'
bind "set colored-stats on"
```

Would it be possible for Clink to do the same? I'm imagining something like this:

```batch
clink bind 'C-r: "luafunc:fzf_history"'
clink bind 'set history-point-at-end-of-anchored-search on'
```

One use case for this:
Many people version control their config files. With bash it's simple, the .bashrc can handle everything, so no need for .inputrc if we put the lines (as shown above) in the .bashrc. In clink's case, there are already two files, the clink_settings and clink_start.cmd. Maintaining another .inputrc file is slightly cumbersome.
Another use case:
This allows experimenting with different suitable keybindings/options without having to edit the .inputrc file and restarting the shell again and again. 

I understand it might not possible or desired by everyone, let me know I'll close in that case.

**Comment by chrisant996** [comment]
I understand some of the motivation.  I think the proposal raises new issues, and I would recommend looking for a different approach.

> One use case for this:
> Many people version control their config files. With bash it's simple, the .bashrc can handle everything, so no need for .inputrc if we put the lines (as shown above) in the .bashrc. In clink's case, there are already two files, the clink_settings and clink_start.cmd. Maintaining another .inputrc file is slightly cumbersome.

Can you clarify how having 3 files under version control is more cumbersome than 2?

Also, why wouldn't all the Lua scripts be under version control as well?  For me it's currently over 80 files under version control for my Clink installation (clink binaries, other binaries, inputrc file, lua scripts, icon files for shortcut links, and many others).

> Another use case:
> This allows experimenting with different suitable keybindings/options without having to edit the .inputrc file and restarting the shell again and again.

Why not use <kbd>Ctrl</kbd>+<kbd>X</kbd>,<kbd>Ctrl</kbd>+<kbd>R</kbd> to reload the inputrc file?  That seems a lot easier, and doesn't require building/documenting/supporting new things.

> Bash allows setting Readline options and keybindings on the fly, from the shell itself, like this:
> 
> ```shell
> bind '"\e[B": history-search-forward'
> bind "set colored-stats on"
> ```
> 
> Would it be possible for Clink to do the same? I'm imagining something like this:
> 
> ```batchfile
> clink bind 'C-r: "luafunc:fzf_history"'
> clink bind 'set history-point-at-end-of-anchored-search on'
> ```

The `clink bind set` part is already possible with some Lua code, using [rl.setvariable()](https://chrisant996.github.io/clink/clink.html#rl.setvariable) to set a Readline variable and [clink.onfilterinput()](https://chrisant996.github.io/clink/clink.html#clink.onfilterinput) to intercept the command line and parse it to implement a custom command.

It's already confusing enough that there are Readline variables and Clink settings.  It seems like a `clink bind set` command would exacerbate confusion versus `clink set`.

`clink set` persistently sets settings -- call it once and it's set in future sessions until you change it.  That's a fundamentally different approach than the proposed `clink bind` or `clink bind set` where they must be run every session.  That will cause further confusion.  Confusion = issues being added to ask questions, and my time being spent to answer them.  I try to avoid decisions that knowingly increase support costs.

The binding part isn't possible currently from Lua code.  I would be more willing to add Lua support for setting key bindings than to make specialized new command line commands.  Especially since the proposed command doesn't cover listing key bindings or variables.

It also defeats portability:  a single inputrc file can be shared between bash and Clink (see [Configuring Readline](https://chrisant996.github.io/clink/clink.html#configuring-readline) and also the Readline manual itself).

**Comment by rashil2000** [comment]
> Why not use Ctrl+X,Ctrl+R to reload the inputrc file? That seems a lot easier, and doesn't require building/documenting/supporting new things (which are already possible in other ways).

Thanks for this! I assumed this keybinding was only for the Lua scripts and not for .inputrc.

> The clink bind set part is already possible with some Lua code, using clink.onfilterinput() to intercept the command line and parse it to implement a custom command which uses rl.setvariable() to set a Readline variable.

I understand this is only for setting variables and not for keybindings? Please correct me if I'm wrong.

> It seems like a `clink bind set` command would exacerbate confusion versus `clink set`.

The suggestion was actually just `clink bind` and not `clink bind set`. What follows `clink bind` would be the line in the .inputrc file, verbatim (in quotes, like in the bash example above). 

> `clink set` persistently sets settings -- call it once and it's set in future sessions until you change it. That's a fundamentally different approach than the proposed `clink bind` or `clink bind set` where they must be run every session. 

Yes, the behavior of `clink bind` would just apply to the current session (like `clink echo`, it's effect wouldn't be persistent). This is in line with how bash does it.

> The binding part isn't possible currently from Lua code. I would be more willing to add Lua support for setting key bindings than to make specialized new command line commands. Especially since the proposed command doesn't cover listing key bindings or variables.

This would be a valuable addition regardless of the current feature request.

Let me know if I have left any information out.

**Comment by chrisant996** [comment]
> > Why not use Ctrl+X,Ctrl+R to reload the inputrc file? That seems a lot easier, and doesn't require building/documenting/supporting new things (which are already possible in other ways).
> 
> Thanks for this! I assumed this keybinding was only for the Lua scripts and not for .inputrc.

The inputrc file is reloaded at every new prompt.  E.g. even just hitting <kbd>Enter</kbd> reloads the inputrc file.

> > It seems like a `clink bind set` command would exacerbate confusion versus `clink set`.
> 
> The suggestion was actually just `clink bind` and not `clink bind set`. What follows `clink bind` would be the line in the .inputrc file, verbatim (in quotes, like in the bash example above).

The suggestion means `clink bind set` exists.

> > `clink set` persistently sets settings -- call it once and it's set in future sessions until you change it. That's a fundamentally different approach than the proposed `clink bind` or `clink bind set` where they must be run every session.
> 
> Yes, the behavior of `clink bind` would just apply to the current session (like `clink echo`, it's effect wouldn't be persistent). This is in line with how bash does it.

It is not in line with how other Clink things work.

**Comment by chrisant996** [comment]
> > The binding part isn't possible currently from Lua code. I would be more willing to add Lua support for setting key bindings than to make specialized new command line commands. Especially since the proposed command doesn't cover listing key bindings or variables.
> 
> This would be a valuable addition regardless of the current feature request.

I have not yet implemented such support, because it makes it way too easy for well-meaning scripts to embed hard-coded key bindings and wreck users' customizations.

**Comment by rashil2000** [comment]
I understand, thank you for your time

**Comment by chrisant996** [comment]
> > > The binding part isn't possible currently from Lua code. I would be more willing to add Lua support for setting key bindings than to make specialized new command line commands. Especially since the proposed command doesn't cover listing key bindings or variables.
> > 
> > 
> > This would be a valuable addition regardless of the current feature request.
> 
> I have not yet implemented such support, because it makes it way too easy for well-meaning scripts to embed hard-coded key bindings and wreck users' customizations.

But in v1.2.46 I added `rl.getbinding()` and `rl.setbinding()` which a Lua script can use to query or override key bindings.  These functions only affect the current session; they do not update any config files.

For example, oh-my-posh uses these to override how <kbd>Space</kbd> works and do contextual right-side prompt updates.

It's of course something that's easy to abuse, and scripts could potentially use it in ways that ruin users' key binding configurations.  Hopefully script authors will avoid doing that in scripts that they share with others.
