### ISSUE TITLE
doc: sample of :generate() function throws error

### ISSUE THREAD

**Issue by bw1faeh0** [chrisant996/clink#144]
The `git checkout` lua sample declares a function `string.start()` which does not work.\
Changing to `string_start()` fixed it for me.

**Comment by chrisant996** [comment]
I had added the `local` part when I copied it from another example.  But it isn't possible to declare `local function string.some_name()` because the function is part of `string.` and `local` can only be applied to a name that would otherwise be global (`local function bar()` works, but `local function foo.bar()` is nonsensical since the `local` and the `foo.` disagree with each other).

`function starts_with()` or `function string.starts()` would declare a function that other scripts can use.
`local function starts_with()` would declare a function that only the current script can use.
