### ISSUE TITLE
Can't compile with mingw?

### ISSUE THREAD

**Issue by highend** [chrisant996/clink#146]
Hi,

MinGW (8.1.0 x86_64 posix seh) resides in `E:\MinGW_x64` and its `.\bin` folder is in `%PATH%`
premake (5.0.0 alpha 16) resides in `E:\premake` and it's also in `%PATH%`

I've done the following:
- Downloaded the current source code (https://github.com/chrisant996/clink/archive/refs/heads/master.zip)
- Extracted it to `E:\clink-master`
- Opened a command prompt in that folder
- Executed `premake5.exe gmake2`
- CD into `.\build\gmake2`
- Executed `mingw32-make.exe config=release_x64`

The output that I get is this:
```
E:\clink-master\.build\gmake2>mingw32-make.exe config=release_x64
"==== Building readline (release_x64) ===="
bind.c
process_begin: CreateProcess(NULL, cc -MMD -MP -DHAVE_CONFIG_H -DHANDLE_MULTIBYTE -DCLINK_RELEASE -DNDEBUG -DCLINK_BUILD_ROOT=\"E:/clink-master/.build/gmake2\" -DBUILD_READLINE -I.. -I../../readline -I../../readline/compat -m64 -O3 -g -o obj/x64/release/readline/bind.o -MF obj/x64/release/readline/bind.d -c ../../readline/readline/bind.c, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make.exe[1]: *** [readline.make:252: obj/x64/release/readline/bind.o] Error 2
mingw32-make.exe: *** [Makefile:120: readline] Error 2
```

Line 252 of `readline.make` is
`$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/callback.o: ../../readline/readline/callback.c`

Any idea why this fails?

**Comment by chrisant996** [comment]
I've never used mingw.

But if line 252 is what you pasted, then that's the problem.
That is line 252 + line 253, with the newline removed.

Did something alter the `readline.make` file?
Newlines matter, so if the newline between line 252 and line 253 got lost somehow, then naturally there will be build failures.

When I run `premake5 gmake2`, here are lines 250-255.
```makefile
$(OBJDIR)/bind.o: ../../readline/readline/bind.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/callback.o: ../../readline/readline/callback.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
```

**Comment by highend** [comment]
> Did something alter the readline.make file?
No

After checking the `readline.make` file again, I have the exact same lines that you've posted (from 250-255).

The source file `bind.c` exist in `..\..readline\readline` as a relative path going upwards from `E:\clink-master\.build\gmake2`...

**Comment by chrisant996** [comment]
Maybe something may have changed the current directory, causing the relative path to not find the bind.c file anymore.  It might be interesting to change that command line in the makefile to print the current working directory, and see.

Or maybe look for a way to get more specific error details from mingw.

**Comment by chrisant996** [comment]
Or is it an error from gmake, saying it can't find the `cc` file and therefore can't execute the command...?

**Comment by chrisant996** [comment]
By the way, where are you finding "MinGW (8.1.0 x86_64 posix seh)", and are you running it on Windows?  Or running it from a Linux subsystem on Windows?  Or cross-compiling from Mac or Linux?

I can't find mingw 8.1.0.  Could upgrading to a more recent mingw help?

**Comment by chrisant996** [comment]
Unfortunately, the Detours library only supports MSVC.  That may be a problem for compiling with mingw.

**Comment by chrisant996** [comment]
I resolved a bunch of mingw pedantic warnings.

However, Detours only supports being compiled with MSVC.
So that's a bigger problem.
I wanted to make no modifications to Detours, but if it's possible to make very small ones then I might.

**Comment by highend** [comment]
Thanks for the analysis, Chris!

Indeed, after using `set CC=gcc` the build process now fails on `hooks.c` (after spitting out a few warnings on previous files).
I do not really want to install the MSVC C++ build tools with ~6 GB space requirements so I this won't compile with MinGW without investing a huge amount of time: Don't waste yours!

**Comment by chrisant996** [comment]
I got it building with MinGW, because I wanted to restore that if possible, and because I was curious.

However, when built with MinGW, Clink does not actually run.  It crashes, and the assembly code doesn't make much sense, so it may be that MinGW is producing invalid code.  (At the point of crashing, it's writing to memory that it should only read from, and it's writing a hard-coded 0x8000 that makes no sense given that the only local variables are `const char*`.)

But it crashes after seeming to successfully inject, so maybe there is hope.

Also, Clink has always disabled certain things when compiled with MinGW.  Basically I don't think MinGW has ever been fully supported; only maybe 98%.  I had to provide alternative implementations for a couple things, so there might be behavioral differences in some cases.

I'm curious to understand why it's crashing.  But after fighting against linker bugs for a few hours, and rearranging code to work around MinGW, it probably will not receive much support from me moving forward.

(MinGW is extremely slow compared to MSVC, threw a bunch of bogus analysis warnings, produces _much_ larger binaries, has some kind of quite bad linker bug, and several other issues.  Bottom line is, it has left a rather sour first impression.)

**Comment by chrisant996** [comment]
- The `gmake2` action in Premake is buggy.  E.g. it builds resources but neglects to link them.  But FWIW `gmake2` is apparently not the preferred action for mingw; apparently Blizzard added `gmake2` but probably most users should use the `gmake` action instead.  Nevertheless, I added hackery in Clink's premake config script to compensate.
- MinGW resolves calls using different template signatures than MSVC; it took a couple hours to track that down.  I'm inclined to call it a MinGW bug, but I don't technically know what's "right" there from ISO perspective.  I worked around it.
- MinGW isn't C99 conformant for vsnprintf.  I see posts blaming an underlying Microsoft implementation, but I'm not convinced because MSVC works fine.  I added a `_POSIX=1` define to work around it.
- And various other MinGW problems.

With those out of the way, Clink compiles cleanly with MinGW, except for warnings in the Detours library.

But it still crashes.  I can't tell yet if it's crashing _during_ injection (which could be MinGW interfering with the Detours library) or if it's crashing later and might be something more fixable.

**Comment by chrisant996** [comment]
The latest Detours compiles cleanly for MinGW, after fixing another set of failures that crept in from a change that happened after the MinGW warnings were addressed.

I tracked down and fixed the crash.  MinGW and MSVC manage the stack differently, so MinGW flushed out an issue that wasn't affecting MSVC.

It's mostly working, but some things still don't work -- e.g. something is failing with async prompt filtering (whose implementation might be dependent on MS extensions in the C runtime, I'm not sure yet).

P.S.  Why am I wasting my time on this?  Because it's not wasting time -- Clink is becoming healthier.  While MinGW has some problems, it also provided a good excuse to finally clean up some messy dependencies between components in Clink.  And it highlighted 2 bugs in Clink that existed but didn't have observable symptoms with MSVC.

**Comment by chrisant996** [comment]
I added a workaround for MinGW not conforming with C2011's `"x"` flag in `fopen()` calls.  It _seems_ to be working now, based on some sanity tests.

Seems to compile cleanly, and function correctly.  MinGW is not the "officially supported" compiler toolset for Clink, but for playing around it may be reasonable.

**Comment by highend** [comment]
Thank you Chris!

Atm, it won't compile at all for me (latest source from 5 minutes ago)
`premake5` with `gmake`, not `gmake2`

```
E:\clink-master\.build\gmake>mingw32-make.exe config=release_x64
"==== Building readline (release_x64) ===="
Creating obj/x64/release/readline
The syntax of the command is incorrect.
mingw32-make.exe[1]: *** [readline.make:247: obj/x64/release/readline] Error 1
mingw32-make.exe: *** [Makefile:117: readline] Error 2
```

`readline.make`:

245-251
```
$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif
```

113-118
```
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
```

**Comment by chrisant996** [comment]
Looks like something about expanding `(posix,$(SHELLTYPE))` on your machine is causing a failure.
That doesn't happen on my machine, so I think this is likely a configuration issue on your machine.
Good luck!


P.S.  Line 117 isn't from readline.make; the error says `Makefile:117`.
Here are lines 114-118 from `Makefile`, which invoke the `readline.make` file:
```makefile
readline:
ifneq (,$(readline_config))
	@echo "==== Building readline ($(readline_config)) ===="
	@${MAKE} --no-print-directory -C . -f readline.make config=$(readline_config)
endif
```

**Comment by highend** [comment]
Damn, you're right, wrong file *sigh*

Don't know where this comes from, I'll try it with a fresh Windows 10 in a VM...

**Comment by chrisant996** [comment]
> Damn, you're right, wrong file _sigh_
> Don't know where this comes from, I'll try it with a fresh Windows 10 in a VM...

No, line 247 in readline.make was accurate.  I was only noting that the 117 quotation cited the wrong file.

**Comment by chrisant996** [comment]
Adding again to ensure it's seen (it was an edit and the conversation has moved past it):

For me `$(SHELLTYPE)` is msdos.  Maybe it's something else for you, and maybe it contains characters that interfere with the makefile operation?  You could add a line `@echo SHELLTYPE is $(SHELLTYPE)` after line 246 to find out what `$(SHELLTYPE)` is on your machine.

**Comment by highend** [comment]
For whatever reason, it's `posix` on my main machine, not `msdos`. The only thing that changed in the last few days was the installation of the `MS C++ build tools`.

It compiles fine in the virtual machine (where the shell type is `msdos` as expected)...

**Comment by chrisant996** [comment]
In readline.make here is how premake set up the makefile to set SHELLTYPE:
```makefile
SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif
```

Maybe `%SHELLTYPE%` is already set, or maybe `%COMSPEC%` is set to something unusual.  There are just a couple observations that would help you choose what to troubleshoot next (this isn't related to Clink at this point, so you should be all set to troubleshoot on your own).

**Comment by highend** [comment]
You're absolutely right, this isn't a `Clink` problem (anymore).

`%SHELLTYPE%` isn't set and `%COMSPEC%` is pointing to the correct `cmd.exe`. Thanks for making this work (with MinGW), I'll use the VM for compiling over the next days^^
