### ISSUE TITLE
LUA debugger does not work

### ISSUE THREAD

**Issue by Ircama** [chrisant996/clink#152]
## LUA debugger does not work

Code to test the issue:

- Add *test.lua*:

  ```lua
  local test_filter = clink.promptfilter(10)
  
  function test_filter:filter(prompt)
      pause()
  end
  ```

- Run CMD with `clink set lua.debug true`

Result:

```
Microsoft Windows [Version 10.0.22000.168]
(c) Microsoft Corporation. All rights reserved.

Clink v1.2.28.f398a1
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2021 Christopher Antos
https://github.com/chrisant996/clink


Lua Debugger

Stacktrace:
[1]***  Lua in ?:0
[2]     xpcall in [C]:-1
[3]     Lua in ?:0

Paused at file =? line 0 (0)
Cannot find =?.lua

Message: pause

Type 'help' for commands
[DEBUG]> dump prompt
'dump prompt'
prompt = nil;
[DEBUG]> dump test_filter
'dump test_filter'
test_filter = nil;
[DEBUG]> print("hello world")
'print("hello world")'
Compile error: attempt to call a nil value
[DEBUG]> exit
'exit'
```

## Temporary workaround

This debugger appears to work: https://github.com/slembcke/debugger.lua

To install, set `clink set lua.debug false`, then save the *debugger.lua* file to the user directory, put `local dbg = require("debugger")` to the top of the LUA file to debug (e.g., *test.lua*) and use `dbg()` (instead of `pause()`) to start the debuger. E.g.,

```lua
local dbg = require("debugger")

local test_filter = clink.promptfilter(10)

function test_filter:filter(prompt)
    dbg()
end
```

Output:

```
C:\Users\user>
debugger.lua: Loaded for Lua 5.2
break via dbg() => C:\Users\user\AppData\Local\clink\test.lua:7 in method 'filter'
debugger.lua> p prompt
prompt => "C:\\Users\\user>"
debugger.lua>
debugger.lua> e print("hello world")
hello world
```

**Comment by chrisant996** [comment]
> ## LUA debugger does not work

There are two specific bugs, and thank you for bringing them to my attention.
"Does not work" might overstate the situation. 😉 

1. The `pause()` call breaks at the expected point when using a debug build of Clink, but I had not yet noticed that it breaks 1 line after the expected point when using a released build of Clink (which is outside the function scope from the example, which is why the local variables are not present; they are literally no longer in scope).  This is happening because released builds use embedded precompiled scripts, and that interferes with Lua's sense of how many lines exist to be stepped over.  I've fixed the step counts.

2. The expression evaluation in the debugger calls `loadstring()`, which is not defined in standard Lua 5.2, hence the compile error.  I've fixed it to call `load()`.

Feel free to use the alternative debugger if it's preferred.  However, it is missing a lot of debugger functionality, and crucially it is missing the ability to set breakpoints.
