### ISSUE TITLE
Keys inoperable -- ESC key and shortcut keys for new console feature

### ISSUE THREAD

**Issue by David-Maisonave** [chrisant996/clink#153]
1. Nothing happens when **[ESC]** key is press
    * Expected behavior:   It supposed to clear the current command listed after the prompt.
2.  15 of the shortcut keys introduced in 2014 for windows console features fail to work.  Nothing happens when these keys are used.
    * Expected behavior:  See below file for specific keys, expected functionality, and shortcut keys source information.
[CLinkShortcutKeysIssuesWithNewWin10ConsoleFeatures.pdf](https://github.com/chrisant996/clink/files/7108870/CLinkShortcutKeysIssuesWithNewWin10ConsoleFeatures.pdf)

**Comment by chrisant996** [comment]
What version of Clink is being used?

The exact same text is in an issue in the old Clink repo, which is v0.4.9 and is 5+ years old.

Please clarify.

**Comment by chrisant996** [comment]
I read the PDF.

You are correct that many of those keys don't do the same in Clink as in a plain console window.

They're not meant to.

But your list is clearly using a 5+ year old version of Clink.  The current version supports many of the keys by default, and most can be bound to similar or identical behaviors.

For information about Clink capabilities and key bindings, refer to the Clink documentation.

(A few of the keys cannot be made to work the same, even by customizing key bindings, because they are only available when using the OS input editor.  This is expected.)

**Comment by David-Maisonave** [comment]
Sorry that I forgot to post the version. I tested version **v1.2.28**, which is listed as 9 days old.

I originally posted these issues on  **mridgers-clink**, but then I found out you have a much more updated and improved version.  I was going to post the exact same list, but then I thought I better make sure your version had the exact same issues.

I was happy to see that more than half of the console feature shortcut keys work with your version.  But there were still 15 keys that didn't work, so I updated the PDF file, and posted the updated version here.

-IMHO, the most important keys that fail to work is the ESC and CTRL+F (Find text on screen).
1. The ESC key is important because this is a function that users have been using for years with DOS console, and IMHO, that's the first thing they'll see wrong with Clink.  That was the first thing I notice. The ESC key works when using Ctrl-R and it works for clink-popup-complete. It would be more consistent behavior if it works in general. 
    - Readline uses the ESC key as an alternative to the ALT key. 
      - Solution 1: Modify the code so when the user press the ESC key twice then issue a **kill-whole-line**. 
      - Solution 2: A better fix would be to have the option to disable ESC key as the meta-key.  Everyone has ALT keys on there windows computer, so the ESC as the meta-key is an obsolete requirement.  
      - Either of these solutions would most likely have to be done in the C\C++ code.
    - I tried playing around with the inputrc file, but the best workaround I got working was the below lines:
      ````
      # Best workarounds for DOS ESC key
      "\e[Z": kill-whole-line    # Shift+Tab to clear current line.
      "`":  kill-whole-line        # ` (tic key) to clear current line. 
      "\M-z": kill-whole-line   # Alt-z to clear current line.
      ````
    - In any case Clink should have a shortcut key to clear the current line, and it would be best if it was a single key stroke, or a combination that's easy to use and remember.

2. The CTRL-F is a more recent feature, which I think most users are not aware of, but if you let this key pass through, you can post this as a feature Clink supports.  I think more users would find Clink appealing seeing this feature listed on the intro page.
    - I can access this feature by right clicking the title-bar, and selecting [Edit]->Find.  If you can let this key combination go to windows, it should be able to handle it.


### **Can you please reopen this issue?**
I think it can benefit from more discussion.

**Comment by chrisant996** [comment]
I think I understand the viewpoint you're coming from:  you expect that Clink will add input capabilities to CMD, without changing any existing input capabilities.

It's a reasonable viewpoint.

However, Clink is based on the bash input capabilities.  Ctrl+F and many other keys already have other behaviors in bash.

You can reconfigure the default Clink key bindings, and come very close to the default Windows console keys.  The Clink documentation can help with that.  If I find some time, maybe I will post a sample inputrc file with key bindings that are most similar to the default Windows console keys.

**Comment by chrisant996** [comment]
Also, the default binding for <kbd>Esc</kbd> in Clink is `clink-reset-line`, which clears the input line.
If you're seeing other behavior, then probably there is a configuration problem.

1. Please post your `.inputrc` file, and your `clink_settings` file (use `clink info` if necessary to find them).
2. What terminal are you using?  Plain default console window?  Or ConEmu, or Windows Terminal, or something else?

Also, <kbd>Alt</kbd>+<kbd>F</kbd> is by default bound to `clink-find-conhost` which invokes the Find behavior you're looking for.  If you want a different key to invoke the Find behavior, feel free to bind another key.

If you're having trouble finding information in the Clink documentation, please share specific feedback about the documentation, and it may be possible to improve the documentation.

**Comment by chrisant996** [comment]
> **Can you please reopen this issue?**
> I think it can benefit from more discussion.

Closing an issue does not stop the conversation.  I've reopened the issue for now, since closing it seemed to create confusion.

**Comment by chrisant996** [comment]
What if instead of Clink being broken, it is just designed to behave differently?  I would encourage reading more about how to configure Clink in the Clink documentation.  If parts are unclear, please share feedback about what isn't clear.

Try using Alt+H to view the key bindings for Clink.

Regarding the list from the PDF file:
- Ctrl+F -- it's normally bound to `forward-char`, which is like Right Arrow.  It sounds like you want to bind it to `clink-find-conhost` instead.
- Ctrl+A -- it's normally bound to `beginning-of-line`, which is like Home.  It sounds like you want to bind it to `cua-select-all`.
    - However, it is **impossible** for Clink to make it select the entire buffer, because the Windows operating system does not have any API to allow a program to do so.  That part of the selection behavior you're looking for is a hard-coded part of the default terminal in Windows, and console programs must make a difficult choice:  do not enhance the input capabilities at all, or lose the ability for certain keys to work.  This is an artifact of how Windows works.
- Ctrl+M -- Clink does not by default differentiate between Ctrl+M and Enter.  You can get the behavior you're looking for by using `clink set terminal.differentiate_keys true` and then use `clink echo` to find the key binding sequence for the specialized Ctrl+M sequence, and then bind that to `clink-mark-conhost`.
- Shift+Ins -- this pastes in Clink.  Maybe you were using an old version of Clink.
- Shift+Up and Shift+Down -- It is **impossible** for Clink to make that work how you want (see notes on Ctrl+A above).
- Ctrl+Shift+Home and Ctrl+Shift+End -- No, these do not normally extend the selection one word to the left.  Ctrl+Shift+Left and Ctrl+Shift+Right are what normally extend the selection one word to the left or right, and in Clink they do that.
- Ctrl+Home and Ctrl+End -- In CMD these normally erases to the beginning or end of the line.  And they do the same in Clink.
- Ctrl+Up and Ctrl+Down -- In CMD these normally scroll the screen by one line.  In Clink Alt+Up and Alt+Down are what do that.  I can add default key bindings for Ctrl+Up and Ctrl+Down as well, since they aren't bound to anything else yet.
- Ctrl+Shift+Plus and Ctrl+Shift+Minus -- I can consider maybe adding commands for changing the transparency.  But they may not work properly, depending on what terminal program is being used (ConEmu, ConsoleZ, Windows Terminal, and many others).

There is a small number of keys that you want to bind differently.  The rest either already work how you want, or a couple are impossible to work how you want.  In particular, <kbd>Esc</kbd> does normally work how you've requested.  So maybe there are problems in your .inputrc file?  I don't know, there is very little information shared, so it's very difficult for me to attempt to help.  Please share more information.

If you are still finding most of the keys don't work in Clink v1.2.28, then there is likely a configuration problem -- if so, send your .inputrc file and clink_settings file; find them via `clink info`.

Here are bindings for the handful of keys that don't by default work how you wanted:

**.inputrc**
```
"\C-a": cua-select-all    # ctrl+a
"\C-f": clink-find-conhost    # ctrl+f
"\e[1;5A": clink-scroll-line-up    # ctrl+up
"\e[1;5B": clink-scroll-line-down    # ctrl+down

# For this key binding to work, first run "clink set terminal.differentiate_keys true".
"\e[27;5;77~": clink-mark-conhost    # ctrl+m
```

**Comment by David-Maisonave** [comment]
I tried the above script, and the ctrl-f works now.  That's great!
The ctrl-a selected the current line.  The DOS console selects the entire screen with ctrl-a.  But selecting the line is better than not selecting anything at all.
Keys (C-Up, C-Dwn) didn't work for me, but IMHO, they're not that important.

After reading your post where you said ESC key should work to clear the input line, I suspected that some files left over from Clink 0.49 might be causing the issue.  So I uninstalled Clink v1.2.28, and deleted folder AppData\Local\clink, which was not deleted as part of the uninstall.
I then reinstalled Clink v1.2.28, and the ESC key started working.

I'm really happy the way the new Clink is working now.

I notice that after reinstalling it, there's no settings and no clink_settings file, so I think these two files were left there from the Clink 0.49 install.  I think it would be a good idea for the install process to check for the existence of these two files, and prompt the user to disable the files by renaming them.
I've attached the files to this post in case you wanted to see what triggered the issue.
Thank you very much for your help in this.

[clink0.49_settings_and_clink_settings_files.zip](https://github.com/chrisant996/clink/files/7111025/clink0.49_settings_and_clink_settings_files.zip)

**Comment by chrisant996** [comment]
Aha!  Thanks for sending the settings files.  It revealed an issue in migrating settings from v0.4.9:  the `esc_clears_line` setting was migrated backwards.

When v1.2.29 is released soon, it will include that fix.

**Comment by chrisant996** [comment]
> I notice that after reinstalling it, there's no settings and no clink_settings file, so I think these two files were left there from the Clink 0.49 install. I think it would be a good idea for the install process to check for the existence of these two files, and prompt the user to disable the files by renaming them.

I'll clarify:

1. Clink reads the old `settings` file to migrate the settings, so the install process should not tell users to remove or rename the file.
2. There was a bug in how the `esc_clears_line` setting was migrated; it was migrated exactly backwards.
3. The `clink_settings` file is empty (or doesn't get created) if the settings match the defaults; that's why the file wasn't present after a fresh install.  The install process should not tell users to remove or rename that file, as doing so would lose all Clink settings.

**Comment by chrisant996** [comment]
v1.2.33 added a setting:  `clink set clink.default_bindings windows` sets up the default key bindings to mimic Windows defaults, rather than bash defaults.  (E.g. Ctrl+A, Ctrl+F, Ctrl+M, Tab, and more).

Also the F1 through F9 keys are now supported.  Except that F7 will take longer to implement, so it's not included yet.

When I write a beginners' section in the docs, this is one of the first things it will mention.
