### ISSUE TITLE
LUA settings.set() crashes with boolean types

### ISSUE THREAD

**Issue by Ircama** [chrisant996/clink#154]
While `settings.add()` accepts a boolean type, like in

```lua
settings.add("myscript.myabc", true, "Boolean setting")
```

and while `settings.get()` might return booleans, `settings.set()` needs a boolean string (e.g., `"true"`, `"false"` and not a boolean type like `true`, `false`) and crashes if a boolean type is used.

Example:

```lua
local test_bug = clink.promptfilter(10)

settings.add("myscript.myabc", true, "Boolean setting")

function test_bug:filter(prompt)
    print(tostring(settings.get("myscript.myabc")))
    settings.set("myscript.myabc", false)  -- this crashes...
    settings.set("myscript.myabc", "false")  -- ...and this does not (but has another issue)
    print(tostring(settings.get("myscript.myabc")))  -- due to the crash, this line and the previous one will not run
end
```

**Comment by chrisant996** [comment]
Indeed!  Thanks for catching and reporting this.  It looks like this may be one of the things Martin hadn't finishing implementing.

It definitely should not crash.  However, the documentation states that the `value` must be `string` type.

It looks like a lot of work to implement valid conversions for native Lua types, since the valid conversions depend on the specific setting type.  Since `settings.set()` isn't persisted, it might not be worth doing all that work.  And the documentation says to pass a string.

So probably I will fix the crash and make it return an error instead.
