### ISSUE TITLE
LUA settings.set() does not appear to be persistent

### ISSUE THREAD

**Issue by Ircama** [chrisant996/clink#155]
It seems that `settings.set()` locally changes the setting value within the same LUA execution context, but does not update the configuration so that the next execution resets the previous value. Is there a way to make `settings.set()` persistent?

Example using a boolean type:

```lua
local test_bug = clink.promptfilter(10)

settings.add("myscript.myabc", true, "Boolean setting")

function test_bug:filter(prompt)
    print("Before changing the value to 'false':",
        tostring(settings.get("myscript.myabc")))
    settings.set("myscript.myabc", "false")
    print("After changing the value to 'false':",
        tostring(settings.get("myscript.myabc")))
end
```

Related output (pressing the <kbd>ENTER</kbd> key more times):

```cmd
C:\Users\user>
Before changing the value to false      true
After changing the value to false       false
C:\Users\user>
Before changing the value to 'false':   true
After changing the value to 'false':    false
C:\Users\user>
Before changing the value to 'false':   true
After changing the value to 'false':    false
C:\Users\user>
Before changing the value to 'false':   true
After changing the value to 'false':    false
C:\Users\user>
Before changing the value to 'false':   true
After changing the value to 'false':    false
C:\Users\user>
Before changing the value to 'false':   true
After changing the value to 'false':    false
C:\Users\user>
```

**Comment by chrisant996** [comment]
The `clink set` command always freshly reads the settings file, changes a setting, and writes the settings file.  This ensures that only the one setting gets changed.

If `settings.set()` writes the settings file, then it could accidentally revert other changes as well.

For example, consider this scenario:
- Clink instance 1 is started, and reads the settings.
- Clink instance 2 is started, and reads the settings.
- From instance 1, `clink set` commands is invoked to change settings A, B, C, D.
- From instance 2, a `settings.set()` call is invoked to change setting Z.

If the `settings.set()` call persists the setting, it will also revert settings A, B, C, D that were just changed.
The best way to make persistent setting changes is to use the `clink set` command.

E.g.
```lua
os.execute(os.getalias("clink") .. " set files.system false")
```
(By getting the "clink" alias, it doesn't matter whether clink is on the system PATH.)

**Comment by Ircama** [comment]
Thanks a lot for this swift feedback and for precisely clarifying the process behind these commands. I understand that a persistent write would be atomic on the whole configuration file and not on a single setting. It looks like `settings.set()` is of little use, considering that the changed value is lost at the end of the instance.

**Comment by chrisant996** [comment]
> It looks like `settings.set()` is of little use, considering that the changed value is lost at the end of the instance.

It looks that way, yes.  The changed value gets lost at the next prompt (long before the end of the instance), because settings are always reloaded (otherwise `clink set` wouldn't work at all).

I don't know how Martin might have intended to eventually finish this API, but its current implementation doesn't seem useful.

Thank you for being willing to close the issue -- I'm going to reopen it, and try making these changes:

Probably what needs to happen is this:
1. Lock the settings file.
2. Read the settings file into temporary data structures (not the main data structures, so that `set()` doesn't have a side effect of also applying other settings changed by other instances).
3. Change the one setting in the temporary data structures.
4. Resave the settings.
5. Unlock the settings file.
6. Apply the `settings.set()` change to the primary data structures.

It feels inefficient, but it's essentially the same as invoking `clink set`. Except that the latter doesn't do step 4 until the beginning of the next prompt.
