### ISSUE TITLE
Where to put new LUA scripts

### ISSUE THREAD

**Issue by Ircama** [chrisant996/clink#157]
I implemented [git_status.lua]( https://github.com/Ircama/clink/blob/ircama_git_status/examples/git_status.lua) which adds some changes to the [ex_async_prompt.lua]( https://github.com/chrisant996/clink/blob/master/examples/ex_async_prompt.lua) LUA example in order to better manage `git status` with colored tracking information. What would be the best way to publish this?
- PR to https://github.com/chrisant996/clink replacing *ex_async_prompt.lua* with the new developments,
- PR to https://github.com/chrisant996/clink adding an new file *git_status.lua* to the *examples* folder,
- PR to https://github.com/chrisant996/clink adding *git_status.lua* to a new *plugin* folder (or another folder name, which might host future additional developments and where some full working examples can be linked; e.g., I also implemented a basic colored prompt and a simple ERRORLEVEL exit code plugin),
- use another repository,
- other mode.

Thanks

**Comment by chrisant996** [comment]
Great question!

First, I'll respond to the specific options, and then I'll offer another option.

- Another repository is probably the best option right now.
- I'm considering enabling Discussions in the repo, which could potentially be a place where scripts could be shared, without needing separate repos for them.
- Not the examples scripts or folder:  The examples scripts are compiled into the documentation.  The reason they've been moved into separate .lua files is to make it easy for me to test the examples from the documentation without needing to manually copy/paste the examples into files.  I can simply `set clink_path=c:\repos\clink\examples` and they're all loaded automatically.
- Not a new plugin folder, because I don't want to include optional scripts as part of Clink itself.

Also, here are two more options:

1. There is a [cmder-powerline-prompt](https://github.com/chrisant996/cmder-powerline-prompt) repo with a sample prompt system.  It's an updated fork of another repo.  It can be used independently from Cmder, despite "cmder" in its name.  It includes more sophisticated git prompt support.
2. I'm working on a new [clink-flex-prompt](https://github.com/chrisant996/clink-flex-prompt) which is very similar to the powerlevel10k zsh prompt theme.  It requires Clink v1.2.29 which has not yet been released, but a prerelease copy is available here:  [clink.1.2.29.5a8085.zip](https://github.com/chrisant996/clink/files/7111212/clink.1.2.29.5a8085.zip).  This new prompt system has many configuration options and makes it very easy to customize the prompt, generally without needing any Lua programming.  There is not documentation yet (coming soon) but in the meantime hopefully the source code is readable.  It has built in prompt modules for battery, cwd, duration, errorlevel, git, and user.  It's easy to add new modules.
    - The clink-flex-prompt repo is a place where I could accept PRs for prompt script enhancements, and new modules.

**Comment by bw1faeh0** [comment]
Maybe you can rename your clink-flex-prompt repo to something like clink-extensions and provide sub dirs for plugins, prompts, etc.?

**Comment by chrisant996** [comment]
> Maybe you can rename your clink-flex-prompt repo to something like clink-extensions and provide sub dirs for plugins, prompts, etc.?

clink-flex-prompt is a specific thing.  Turning it into a collection of competing/incompatible scripts seems confusing.  Also, I definitely do not want to be in the business of spending my time managing PRs for all kinds of unrelated things.

**Comment by chrisant996** [comment]
[clink-flex-prompt](https://github.com/chrisant996/clink-flex-prompt) now works on v1.2.10 and higher.
Clink v1.2.29 has been released with transient prompt support and some other goodies needed by clink-flex-prompt.

As for where to put Lua scripts, I don't want to manage a library of scripts.  There's a lot of hidden cost in trying to do that.  I may enable Discussions at some point, and that might sort of be a place where scripts can be shared.  But probably it's better to share scripts by putting them in their own repos -- by the time there have been a couple updates to a script, a separate repo has a lot of benefits.

**Comment by chrisant996** [comment]
Yup. I'm thinking about options, but it's complicated.

Ones available via Scoop are the most discoverable (if one uses Scoop, which I don't, really), and get auto-updated.

There is a section in the Clink docs with links to the "best" scripts I know of.  Clink-completions and clink-flex-prompt are both listed there.

**Comment by Destroy666x** [comment]
I see, so not many recommendations as of now. GH tag is a quite good idea too.

**Comment by chrisant996** [comment]
I've made a [clink-gizmos](https://github.com/chrisant996/clink-gizmos) repo with the best Clink scripts that I use.

It does not include [clink-completions](https://github.com/vladimir-kotikov/clink-completions] or [clink-flex-prompt](https://github.com/chrisant996/clink-flex-prompt) at this time.  I will likely see about including the former, but the latter probably does not belong there (imagine if other prompt scripts were to be added -- they would be unlikely to coexist well).

This is not quite the same as a universal library of third party scripts, but it is at least a step in a useful direction.
