### ISSUE TITLE
Clink crashed when using shortcut key in my inputrc file

### ISSUE THREAD

**Issue by David-Maisonave** [chrisant996/clink#158]
Hi,
Crash occurred using Clink v1.2.28.f398a1 with DOS cmd.exe under system32 folder.
I've attached a zip file which contains 3 crash dump files, _inputrc, snapshot of the window when it crashed, clink.log, and a text file containing the screen text when it crashed.
[Clink Crash when using jump to target folder of last command shortcut key in my inputrc file.zip](https://github.com/chrisant996/clink/files/7131080/Clink.Crash.when.using.jump.to.target.folder.of.last.command.shortcut.key.in.my.inputrc.file.zip)

### The crash is easy to reproduce with the following steps.
1. Just add the below line to the _inputrc file
    ````
    "\ex": 'cd !$ \015ls\015'  # Jump to the target folder of the last command and run ls with Option-x
    ````
2. Start up cmd.exe under system32
3. Use the shortcut key alt-x

I'm not sure if there's something wrong with that line,but I got it from the following link:
[Shell Tricks: .inputrc binding fun - BrettTerpstra.com](https://brettterpstra.com/2015/07/09/shell-tricks-inputrc-binding-fun/)
I ran one last test with only that shortcut key in the file, and it still crashed.

Please let me know if you need anything else, and/or if there's something wrong I'm doing.

Thanks

**Comment by David-Maisonave** [comment]
Hi Chris,
Off Topic -- I really which your version of Clink could replace all the 0.49 version.  
When I google "clink download" your version doesn't even show up in the results which displayed 4 pages of links.
The only thing that comes close is Cmder which I think has your Clink version in it, and it's displayed as the 6th link.

I only found your link originally on a posted question.

Have you tried contacting Martin Ridgers, to see if he would let you post a link to your version on his main [Clink page ](https://mridgers.github.io/clink/) or better yet, let you take over or merge the project?

Have you thought about posting it on [Softpedia](https://www.softpedia.com/get/System/OS-Enhancements/clink.shtml), [cnet](https://download.cnet.com/Clink/3000-2094_4-75956859.html), [downloadcrew](https://www.downloadcrew.com/article/30645/clink), or [chocolatey.org](https://community.chocolatey.org/packages/clink)?

Would you mind if I tried posting it or updating Clinks on these sites?

**Comment by chrisant996** [comment]
> Have you tried contacting Martin Ridgers, to see if he would let you post a link to your version on his main [Clink page ](https://mridgers.github.io/clink/) or better yet, let you take over or merge the project?

Naturally, that was the first thing I ever tried, and I tried repeatedly for almost a year.  He disappeared from the internet and hasn't responded to any attempts to contact him.  Github is unable to allow taking over a project with the owner's approval.  I sincerely hope he is well, and I wish I could thank him for starting the project and sharing it.

> Have you thought about posting it on [Softpedia](https://www.softpedia.com/get/System/OS-Enhancements/clink.shtml), [cnet](https://download.cnet.com/Clink/3000-2094_4-75956859.html), [downloadcrew](https://www.downloadcrew.com/article/30645/clink), or [chocolatey.org](https://community.chocolatey.org/packages/clink)?

It's on scoop.

I'm interested in chocolatey, but it seems to involve both initial investment and ongoing investment to be able to be listed in chocolatey.

I'm comfortable with people finding martin's clink.  If they ever look at the Issues page, it should be pretty clear the repo is abandoned, and where to find the new one.  That's the best that github has been able to allow.

> Would you mind if I tried posting it or updating Clinks on these sites?

Seems reasonable.

**Comment by chrisant996** [comment]
> ### The crash is easy to reproduce with the following steps.
> 1. Just add the below line to the _inputrc file
>    ```
>    "\ex": 'cd !$ \015ls\015'  # Jump to the target folder of the last command and run ls with Option-x
>    ```
> 2. Start up cmd.exe under system32
> 3. Use the shortcut key alt-x

Yikes!  I don't know if this is a bug in Readline's callback mode (a way for programs to use it for input, while still being able to add their own additional functionality), or if it's a bug in how Clink integrates with Readline.

> I'm not sure if there's something wrong with that line,but I got it from the following link:
> [Shell Tricks: .inputrc binding fun - BrettTerpstra.com](https://brettterpstra.com/2015/07/09/shell-tricks-inputrc-binding-fun/)

It's not "wrong", but it is certainly unusual.  I'll investigate it, but I'll treat it as low priority because of how unusual it is.

**Comment by chrisant996** [comment]
This is a bug in how Clink uses Readline.  Martin's v1.0.0 rewrite changed how Clink uses Readline, and it is incorrect now (and does not follow the documentation for how to use Readline).

Fixing this will be complicated and require redesigning several data structures and classes and the flowchart of how Clink uses Readline.  I'll rewrite it, but it isn't possible to make a quick fix for this.

Thank you for finding and reporting this!  (I think.  Haha just kidding, I really do appreciate it, even if it revealed that some extra work is required.)

**Comment by chrisant996** [comment]
There is a bug in Readline after all:
- On [callback.c line 289](https://github.com/chrisant996/clink/blob/7942a62b57f7dd6538f9e724d2250580a371487d/readline/readline/callback.c#L289) it specifically checks whether the caller uninstalled the callback handler.
- But on [callback.c line 293](https://github.com/chrisant996/clink/blob/7942a62b57f7dd6538f9e724d2250580a371487d/readline/readline/callback.c#L293) it accidentally continues the loop even if the callback handler was uninstalled.
- Then when it loops around to [callback.c line 281](https://github.com/chrisant996/clink/blob/7942a62b57f7dd6538f9e724d2250580a371487d/readline/readline/callback.c#L281) again, it crashes.

So:
- If Clink uninstalls the handler, Readline crashes.
- If Clink doesn't uninstall the handler, Readline prints extra prompts and races ahead without actually running the `cd` command that was accepted by the `\015` in the macro string.

Once the Readline bug is fixed, it reveals there is also a bug in Clink:
- If Readline already has queued input waiting (e.g. the macro text) then Clink should proceed and use that.  Instead of waiting for new input from the physical keyboard.
