### ISSUE TITLE
The 'clink installscripts' command might corrupt its registry value

### ISSUE THREAD

**Issue by Ircama** [chrisant996/clink#161]
When more than two `clink installscripts` are issued, the clink installscripts registry value might get corrupted.

To reproduce the bug:

- clear the *InstalledScripts* registry value under `Computer\HKEY_CURRENT_USER\Software\Clink`
- run `clink installscripts C:\Users\user\AppData\Local\clink\clink-completions\`
- run `clink installscripts C:\Users\user\AppData\Local\clink\clink-flex-prompt\`
- check the registry key which wrongly includes
  ```
  completions\;C:\Users\user\AppData\Local\clink\clink-flex-prompt\
  ```
  instead of
  ```
  C:\Users\user\AppData\Local\clink\clink-completions;C:\Users\user\AppData\Local\clink\clink-flex-prompt
  ```

Notice also that the `Computer\HKEY_CURRENT_USER\Software\Clink` registry key is not included in the documentation and not shown in `clink info`.

Also, it does not seem that a mode to reset the *InstalledScripts* values is available via `clink` command line.

**Comment by chrisant996** [comment]
> When more than two `clink installscripts` are issued, the clink installscripts registry value might get corrupted.

Drat.

> Notice also that the `Computer\HKEY_CURRENT_USER\Software\Clink` registry key is not included in the documentation and not shown in `clink info`.

The installed script paths are shown in `clink info`: they are the last group of paths in the "scripts" entry.

The regkey location is intentionally undocumented.  What is the reasoning for why it should be documented?  I reserve the right to rename or move the regkey, or to stop using a regkey.  I think that documenting the location encourages others taking unsafe dependencies on internal implementation details.  Similar to how the format of the history file is not documented.

> Also, it does not seem that a mode to reset the _InstalledScripts_ values is available via `clink` command line.

That was intentional, to avoid buggy scripts removing all of your installed script paths with a single misguided command invocation.

Clink provides an argmatcher and completions for `clink uninstallscripts`, so you can easily remove them one at a time using completions.

But I've gone ahead and added a `clink uninstallscripts --all` flag.
