### ISSUE TITLE
Feature request: Autocomplete options on a single tab press

### ISSUE THREAD

**Issue by LuukHenk** [chrisant996/clink#175]
In bash there is the option to show [autocomplete options on a single tab press](https://stackoverflow.com/questions/3163902/how-do-i-set-bash-to-show-autocomplete-options-on-a-single-tab-press).

It would be really nice to have this feature as well in my windows environment. Might it be possible to add this feature to  click?

**Comment by chrisant996** [comment]
It's already there.

**Comment by LuukHenk** [comment]
What is the command for this? I can't find it

**Comment by chrisant996** [comment]
> What is the command for this? I can't find it

The instructions are in the article you linked.

**Comment by chrisant996** [comment]
Add this line to your `.inputrc` file.

```inputrc
set show-all-if-ambiguous on
```

Refer to Clink's docs on "Configuring Readline" for more info on the .inputrc file if you're not familiar.

But this works in Clink exactly the same as in bash.  The only difference is that Windows does not use `~` as a synonym for %userprofile%, so you can't follow the article you linked literally, since it's written for Linux.  You have to translate it for Windows.
