### ISSUE TITLE
Tab completion with leading dots unexpected

### ISSUE THREAD

**Issue by sbellon** [chrisant996/clink#183]
Assume you have folders `.foobar` and `foobar` in the same folder and want to do

`cd foo<tab>`

then this does not complete but shows both, `.foobar` and `foobar` as possible completions.

If you do however

`cd .foo<tab>`

then it immediately completes to `.foobar`.

Likewise, I think, `cd foo<tab>` should immediately complete to `foobar` and not treat `.foobar` as a possible alternative completion.

**Comment by sbellon** [comment]
Thanks for the quick reply!

I buy your third point "intentionally behave like Windows". But then again, this "leading dot Windows behaviour" has nothing to do with "wildcard matching". So I think it would be nice to have the option `match.leading_dot` where this behaviour can be toggled, rather than include it into the `match.wild` option.

But at least I now can do `clink set match.wild false` and then type `cd foo<tab>` and end up where I expect to end. :-)

**Comment by chrisant996** [comment]
> I buy your third point "intentionally behave like Windows". But then again, this "leading dot Windows behaviour" has nothing to do with "wildcard matching". So

Can you explain why it doesn't?  Maybe you mean you don't understand the relationship, or that you dislike the relationship.  The wildcard matching code is what does this.  It's a fact in the source code.  🤷‍♂️  The leading dot behavior is explicitly part of the definition of wildcard matching, and Raymond explained it in his blog post.  Consider reading it, if that hasn't happened already.

> I think it would be nice to have the option `match.leading_dot` where this behaviour can be toggled, rather than include it into the `match.wild` option.

You're looking at the effect in the `complete` command.
I'm looking at the effects in the `complete`, `menu-complete`, `clink-select-complete`, `glob-expand-words`, and `glob-complete-word` command, as well as several other commands (and Lua APIs, too).

The suggestion would do what you want in `complete`, but would break other behaviors.
Clink 0.4.9 had a bug in `menu-complete`:  typing `cd b`<kbd>menu-complete</kbd> would match `build\` but not `.build\` -- that's a definite bug from a Windows perspective:  `menu-complete` in CMD should cycle through the same matches as <kbd>Tab</kbd> normally would in CMD -- but it did not.
The match generation system generates matches -- it doesn't (and shouldn't) know or care what command ends up using them.  And Lua match generators should not have to deal with behaving differently for different commands.

Also, it would require special code to be written to actively second guess the OS APIs and apply special case filtering rules.

I have to draw a line somewhere, and this is where I draw it.  I won't do all of that, plus reintroduce old bugs and add `match.leading_dot_in_complete` and `match.leading_dot_in_menu_complete` plus other stuff, just to avoid turning off `match.wild`.

Let me know if there's more to the scenario that I haven't understood yet.

> But at least I now can do `clink set match.wild false` and then type `cd foo<tab>` and end up where I expect to end. :-)

I think that's easy and reasonable.
And I think it's reasonable for Clink to bring bash and Lua goodness to Windows, rather than trying to turn CMD and Windows into bash and *nix (which are impossible to do, so I don't want to get caught up in an impossible attempt).

It's also reasonable to use bash or zsh or fish or whatnot, if CMD and Windows are disliked.

**Comment by 3N4N** [comment]
@chrisant996, would you consider linking this discussion in [the manual](https://chrisant996.github.io/clink/clink.html#)? I saw `match.wild` option but didn't think it has any relation to tab-completion. Your detailed discussion makes it a lot easier to understand. If only it were easier to find. :)

**Comment by chrisant996** [comment]
> @chrisant996, would you consider linking this discussion in [the manual](https://chrisant996.github.io/clink/clink.html#)? I saw `match.wild` option but didn't think it has any relation to tab-completion. Your detailed discussion makes it a lot easier to understand. If only it were easier to find. :)

Link it where?

Also, can you describe why `match.wild` didn't seem related to completion? All of the `match.*` settings are about completion, so if there's something confusing in their descriptions, it would be useful to improve them.
