### ISSUE TITLE
Broken doskey macro functionality.

### ISSUE THREAD

**Issue by smru** [chrisant996/clink#187]
**In Command Prompt with no Clink installed:**
**In Command Prompt with Clink 0.4.9 installed:**

```
doskey.exe get-data=powershell.exe -Command "New-Object -TypeName PSObject -Property @{a=1; b=2; c=3; d=4; e=5} $*"
get-data
get-data | Format-Table
```

```
c : 3
e : 5
d : 4
b : 2
a : 1
```

```
c e d b a
- - - - -
3 5 4 2 1
```

**In Command Prompt with Clink 1.2.39 installed:**

```
c : 3
e : 5
d : 4
b : 2
a : 1
```

'Format-Table' is not recognized as an internal or external command,
operable program or batch file.

**For easy testing:**

```
doskey.exe get-host=powershell.exe -Command "Get-Host $*"
get-host | Format-Table
```

PS: Clink is excellent. Many thanks to Martin and you Chris.

**Comment by chrisant996** [comment]
> `What I can do is make an in-between mode that is enabled by default, where IF a doskey macro ends in $* then Clink can do the doskey.enhanced behavior`
> 
> I'm afraid this will lead to really crazy behaviour, when doskey macro acts differently depending on it's content. 

The `doskey.enhanced` feature already caused macros to behave differently than they're written, depending on how they're written.  But it's pretty uncommon.


> And besides, there are a lot of different cases:
> 
> ```
> doskey cmd1=busybox.exe cmd $*
> doskey cmd2=busybox.exe cmd -qr $0
> doskey cmd3=busybox.exe cmd $* -qr
> ```

@depler, all of the macros in the uploaded sample end with `$*`.  And so `safe` mode would work the same way you're used to for all of them.  And it would also let @smru's macros work.

Any doskey macro that contains `$1`...`$9` tags or contains `$*` earlier than the end of the macro is inherently trying to do very specialized fancy things.  `safe` mode lets such macros operate the way they're written to operation.  Clink can't know whether the user intends to use the macro both inside Clink and outside Clink, but it seems very reasonable to behave in a compatible manner.

With that said, @smru, Clink has some other bash-like features (such as `!` history expansion) that already behave differently than plain CMD.  So many Clink doesn't need (or intend) to be exactly compatible with CMD in every respect.  As long as there's a way to revert back to a compatible mode, maybe that's appropriate.

I have a pending change that makes `doskey.enhanced` have three modes:  `off` (like false today), `always` (like true today), and `safe`.  Safe mode stops doing additional expansions after it expands a macro that uses `$1`...`$9` tags or `$*` earlier than the end of the macro.

I will use the `safe` mode for a while before I choose which of the 3 modes will be the default moving forward.

**Comment by chrisant996** [comment]
It turns out it's even simpler; `doskey.enhanced` can still be true/false and true by default.

Any doskey macro that has `$*` or `$1`..`$9` inside quotes should stop expanding aliases after command separators.  The quotes explicitly mean the macro author wants to pass the args (including `|` and `&` command separator characters) as a string argument to another program (such as Powershell).  It's therefore up to that program how to handle the `|` and `&` characters.

So Clink can go back to enhanced doskey features enabled by default, and still work as expected for both @smru and @depler.

Along the way I also found and fixed some details that weren't working properly (e.g. when `doskey.enhanced` is false, then `alias|whatever` should not expand, because normally aliases are not expanded unless followed by a space).
