### ISSUE TITLE
After I set the alias of the "cd", "cd -" won't work

### ISSUE THREAD

**Issue by 836454543** [chrisant996/clink#191]
The command `cd` can't change driver in Windows. So I do that `doskey cd=cd /d $*`
But `cd -` won't work if I set the alias of `cd`
How should I do? 
I'm sorry for my pool english.

**Comment by garoto** [comment]
I use this:

`cd=IF /I "$*" NEQ "" (cd /d "$*") ELSE (if "$*" EQU "-" (cd -) ELSE (cd /d %HOME% ))`

**Comment by 836454543** [comment]
> I use this:
> 
> `cd=IF /I "$*" NEQ "" (cd /d "$*") ELSE (if "$*" EQU "-" (cd -) ELSE (cd /d %HOME% ))`

The first `else` means `$*` is empty. Why need the second `if` ?

**Comment by chrisant996** [comment]
> The command `cd` can't change driver in Windows. So I do that `doskey cd=cd /d $*` But `cd -` won't work if I set the alias of `cd` How should I do? I'm sorry for my pool english.

That's my mistake.  Clink looks only for literally "-" or "cd -" or "chdir -" in the input.

I'll make it parse spaces and tabs properly, and accept the "/d" flag.

> I use this:
> 
> `cd=IF /I "$*" NEQ "" (cd /d "$*") ELSE (if "$*" EQU "-" (cd -) ELSE (cd /d %HOME% ))`

That won't work, because "cd -" is not a CMD command, it's something that Clink handles specially.  It only works at the input command line, and only when it's the only input.  It doesn't work inside compound statements like "if" or when command separators are present.

I won't make it try to parse compound "if" statements or command separators (`|` or `&`), as that gets very complicated and could introduce incompatibilities, and is not something that one typically types as input.  It's meant as a typing convenience, not an extension to CMD's programming language.

**Comment by 836454543** [comment]
> > The command `cd` can't change driver in Windows. So I do that `doskey cd=cd /d $*` But `cd -` won't work if I set the alias of `cd` How should I do? I'm sorry for my pool english.
> 
> That's my mistake. Clink looks only for literally "-" or "cd -" or "chdir -" in the input.
> 
> I'll make it parse spaces and tabs properly, and accept the "/d" flag.
> 
> > I use this:
> > `cd=IF /I "$*" NEQ "" (cd /d "$*") ELSE (if "$*" EQU "-" (cd -) ELSE (cd /d %HOME% ))`
> 
> That won't work, because "cd -" is not a CMD command, it's something that Clink handles specially. It only works at the input command line, and only when it's the only input. It doesn't work inside compound statements like "if" or when command separators are present.
> 
> I won't make it try to parse compound "if" statements or command separators (`|` or `&`), as that gets very complicated and could introduce incompatibilities, and is not something that one typically types as input. It's meant as a typing convenience, not an extension to CMD's programming language.

Oh, thank you very much. It will help me a lot.
By the way, I want to know how to use `cd ~` like bash shell.

**Comment by chrisant996** [comment]
> By the way, I want to know how to use `cd ~` like bash shell.

`~\` by itself works to change to %USERPROFILE%.

Sometime between Clink v1.1.6 and the present, the ability to <kbd>Tab</kbd>-expand `cd ~` got broken again.  I see what's wrong, and will make a fix.  A quick fix isn't possible, but a fix should be available by this weekend.

I'll look at making a special exception to make `cd ~` work, since it already handles `-` specially.  But it isn't feasible to try to expand `~` everywhere for other commands or program invocations.  Tab expansion is the best that Clink can offer, for general usage.

**Comment by 836454543** [comment]
>Tab expansion is the best that Clink can offer, for general usage.

Thanks, that is what I need. Typing %USERPROFILE% is tedious.

**Comment by garoto** [comment]
> That won't work [...]

Welp, it works on the version I am/was using.

**Comment by chrisant996** [comment]
> > That won't work [...]
> 
> Welp, it works on the version I am/was using, but indeed it stopped working on current release.

How strange. What version was it working in? It should be impossible for the `cd -` part in it to work. I'm pretty sure that part of your command has never worked.

**Comment by garoto** [comment]
> How strange. What version was it working in?

`Clink v1.1.2.0e8168`

**Comment by chrisant996** [comment]
> > How strange. What version was it working in?
> 
> `Clink v1.1.2.0e8168`

Are you sure?  The code is identical to now.  It looks for an input line that exactly matches "cd -".  Your input line is much longer than that.  There's no way that "cd -" was working successfully in that long command line in v1.1.2.

**Comment by garoto** [comment]
Pretty sure. I have that doskey macro setup for quite quite some time now. I'll try and replicate the behavior on a barebones setup.

**Comment by chrisant996** [comment]
OS version won't matter.

**Comment by garoto** [comment]
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

 [ C:\Users\garoto ]

 > C:\Apps\Diversos\Clink\clink_x64.exe inject
Clink v1.1.2.0e8168
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020 Christopher Antos
http://github.com/chrisant996/clink


 [ C:\Users\garoto ]

 > doskey /macros
history="C:\Apps\Diversos\Clink\clink_x64.exe" history $*
clink="C:\Apps\Diversos\Clink\clink_x64.exe" $*

 [ C:\Users\garoto ]

 > doskey.exe /macrofile="C:\BIN\doskey.mac"

 [ C:\Users\garoto ]

 > doskey /macros|rg --color=never "^cd="
cd=IF /I "$*" NEQ "" (cd /d "$*") ELSE (cd /d %HOME%)

 > R:

 [ R:\ ]

 > cd -

 [ C:\Users\garoto ]
```

Ugh, hope the above is readable at the least.

**Comment by chrisant996** [comment]
OHH, I forgot. Right. Back then it was checking for `cd -` _before_ expanding doskey aliases. Which caused other problems. So now it checks after expanding doskey aliases.

So it wasn't even expanding the doskey alias at all, when using `cd -`. You could have left that part out of the macro.

Sounds like it would be appreciated if it checked _both_ before and after expanding doskey aliases.

**Comment by chrisant996** [comment]
There's no way to do let a doskey macro apply `/d` to `cd -`.

Which is better, given that `/d` can't be inserted via a doskey macro?
1. Check for `cd -` before expanding doskey alias (in addition to checking after expanding).
    - Benefit: `cd -` works even if there's a `cd=` doskey macro.
    - Drawback: the `cd=` doskey macro is bypassed when `-` is the arg to `cd`.
2. Only check for `cd -` after expanding doskey alias.
    - Benefit: a `cd=` doskey macro is expanded and gets to do its thing.
    - Drawback: the `-` arg will produce a syntax error.

If you want to insert `/d` even in `cd -` then you'll need to use `clink.onfilterinput()` in a Lua script, and convert `cd -` into `<space>cd /d -`.  The leading space character is important, to disable doskey expansion.  Otherwise the `cd /d -` would get expanded as a doskey macro, and then the `-` wouldn't get interpreted as meaning the previous directory.

**Comment by chrisant996** [comment]
[Clink v1.2.42](https://github.com/chrisant996/clink/releases/) is available now and should resolve the reported problems here.
