### ISSUE TITLE
Consider removing the hardcoded 50K `clink_history` line limit

### ISSUE THREAD

**Issue by garoto** [chrisant996/clink#193]
Packrat style, I like to have my history file to be a verbatim copy of whatever I typed into my cmd.exe prompt, so when I `grep` my history I can see the approximate set of circumstances that led me to make the wrong incantantion of a certain program. 

`ctrl+d` is a godsend for performing basic but efficient maintenance of the history file btw (wish Bash would emulate your ctrl+d solution, holy shit).

Making it a configurable option with a 50K line limit set by default doable?

**Comment by chrisant996** [comment]
> Packrat style, I like to have my history file to be a verbatim copy of whatever I typed into my cmd.exe prompt, so when I `grep` my history I can see the approximate set of circumstances that led me to make the wrong incantantion of a certain program.

The scenario makes sense.  

> `ctrl+d` is a godsend for performing basic but efficient maintenance of the history file btw (wish Bash would emulate your ctrl+d solution, holy shit).

I've shared the `remove-history` and `add-history` commands back to the official Readline repo, but I don't think Chet has incorporated them yet, and I don't know whether he'll hook up the necessary support in bash.

You can definitely bring it up in the official bash and/or Readline forums.  If you reference me and Clink then Chet should know what you're referring to.

> Making it a configurable option with a 50K line limit set by default doable?

I can relax the limit.  I'm not sure 50K will end up performing reasonably, but I can at least let people make that choice for themselves.

Regarding making 50K be the default, I don't think it's likely to be an appropriate default:

A fast CPU + fast SSD storage device might be able to yield a decent experience, but older/slower CPUs or rotational magnetic hard drives would produce performance problems.

The history file is read from the file every time the prompt is shown, so 50K entries will fluctuate between 50K and 100K entries due to the delete/compaction system.
- My history file is currently 145596 bytes, with 3639 lines (including deleted entries).
- That averages to 40 characters per line.
- 40 bytes times 50K line is 2 MB, and 40 bytes times 100K lines is 4 MB.
- Every time the prompt is shown, it would load up to 4 MB.

Even with fast CPU and SSD, there will be extra battery consumption when running on battery power.

**Comment by chrisant996** [comment]
> Making it a configurable option with a 50K line limit set by default doable?

Btw, it _is_ a configurable option: `history.max_lines`.

The max allowed is currently 50K, and I can increase that, but there is a fundamental scale problem (responsiveness and battery consumption, mainly).

**Comment by garoto** [comment]
Please, make it a 50K option by default but limitless otherwise when `-1`.

**Comment by chrisant996** [comment]
50K default is too high.

Limitless is a problem when the file is large:
- On x86 it will cause crashes due to memory exhaustion when the file has around 15 million entries.
- On x64 loading a 15 million entries will happen every single prompt, and is **not** fast.
- Even if GNU History and GNU Readline were rewritten to not store the history list in memory, they would still need to parse the entire history file to find line endings.  (Or use an actual database, but then grep or edit the history file become more complicated.)

I can make the limit 999,999 items but I think you'll run into performance problems long before you hit that limit.

What I'll do is:
1. Raise the max_lines limit to 999,999.
2. Leave the default max_lines at 2,500.
3. Add an optional number to `clink history compact` so you can override max_lines to force smaller compaction.

Then you could `clink set history.max_lines 999999` and whenever performance gets too slow then use `clink history compact [some_limit]` to speed things up again.

**Comment by garoto** [comment]
You obviously approach this "feature request" from a C programmer point-of-view :).

 999,999 is "fine" with me. My oldest `.bash_history` from around 2007 is nowhere near that line count, so that seems reasonable enough to me. It addresses my use-case at least.

**Comment by chrisant996** [comment]
> My oldest `.bash_history` from around 2007 is nowhere near that line count, so that seems reasonable enough to me. It addresses my specific use-case in a reasonable fashion.

How many lines is your file, exactly?

Clink will start corrupting the history file if it exceeds ~512 MB in size.
Currently that's not possible with a 50K limit in place, but it becomes technically possible with a 60K limit (even if unlikely).

> You obviously approach this "feature request" from a C programmer point-of-view :).

Also from a "trustworthy computing" point of view: I want software to be well formed and trustworthy; if it says it supports X then it should actually support X, not corrupt data long before X is actually reached.

Anyway, I expect "normal" usage will never run into a problem, other than performance degrading as the file grows.

But "limitless" leaves the door wide open for crashes and corruption.  It's a cop-out on the developer's part:  "I won't bother to account for this collection of problems, because maybe no one will hit them, and I don't want to do the work unless I'm forced to."  The user thinks "yay, limitless is supported", but in reality the programmer was thinking  "if you get more than X items or the file exceeds Y bytes then it'll all go horribly wrong without any warning -- but 640KB is more than anyone will ever need, so I don't need to handle big numbers".  😉

What I can do, I suppose, is bring back something called "limitless", but which actually limits to 999,999.
It's all about marketing, right? 😄

**Comment by garoto** [comment]
> How many lines is your file, exactly?

Not that much really, around 110K lines and 2.4MB in size. For comparison, my `clink_history` is ~2.97MB at the 50K line limit.

> What I can do, I suppose, is bring back something called "limitless", but which actually limits to 999,999.
It's all about marketing, right? smile

999,999 is plenty I agree.

**Comment by chrisant996** [comment]
Cool, thanks.

I've brought back unlimited (with an actual 999999 limit), I've cauterized the deletion mechanism so that it won't try to delete any lines past roughly 500 MB, and I've added a way to force compacting and pruning the history file even when unlimited.

After it's tested then I'll push it. So probably this weekend.

**Comment by chrisant996** [comment]
[Clink v1.2.42](https://github.com/chrisant996/clink/releases/) is available now, with support for 0 = unlimited again.

(In practical terms, it's unlimited.  Technically, it limits to 999999 items, and it can't delete history items past roughly the 511MB point in the history file.)

**Comment by garoto** [comment]
Thanks man! Merged my pre-50k-line-limit saved `clink_history` (which was only 50922 lines long now that I checked it again) file into my current one and did a `clink history compact --unique`:

```
Clink v1.2.42.d4506e
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2021 Christopher Antos
https://github.com/chrisant996/clink

[ R:\ ]
> clink history | wc -l
100764

[ R:\ ]
> clink history compact --unique
History compacted.

[ R:\ ]
> clink history | wc -l
71110

[ R:\ ]
> dir C:\Users\garoto\AppData\Local\clink\clink_history

08-Nov-21  18:01         4,189,905 clink_history
```

Really appreciate all the time and effort you put into clink.

**Comment by garoto** [comment]
Updating this issue to report that after this many months running with a limitless clink_history file:

	> clink history | wc -l
	75373

	> dir C:\Users\garoto\AppData\Local\clink\clink_history

	03-Jul-22  14:22         4,638,403 clink_history

Not bad. I try and do tons of realtime maintenance via a _remove-history_ keybind, but I still have a lot of recent cruft in need of a manual purge.

While I'm at it, just wanted to say that your work on this niche piece of software on your free time is of great value to everything that computing was meant to be. I highly appreciate everything you do regarding this project, from the C++ code to the highly detailed, and up-to-date, documentation.
