### ISSUE TITLE
Unsigned installer

### ISSUE THREAD

**Issue by nathaniel-holder** [chrisant996/clink#198]
The installer exe (clink.1.2.45.472728_setup.exe) is unsigned and shows "Publisher Unknown":
![image](https://user-images.githubusercontent.com/3880337/141681878-6b060764-457d-43eb-a34f-8c3fc0f61620.png)

**Comment by nathaniel-holder** [comment]
Sorry, duplicate of https://github.com/chrisant996/clink/issues/138

**Comment by chrisant996** [comment]
"Signing" is not enough.

There are three kinds of signing:
1. "Self signed". I could make my own certificate, and sign using that. But that has almost no benefits, and doesn't make SmartScreen happy. Also, every user would have to manually download my certificate and manually install it into their Trusted Root certificate collection. Also, when an employer locks down a computer, that is blocked.
2. "Code Signed". I could pay a couple thousand dollars every couple of years to get a basic code signature. But that doesn't get past SmartScreen, either. And you may point out sites that advertise signatures for around a hundred dollars per year -- but you have to also pay a lawyer to draw up documents to prove that you are a real person and that you are not malicious.
3. "EV Code Signed". This gets past SmartScreen's reputation filter, but NOT past anti virus detection. In order to get EV Code Signed, you must pay more money, and you must also prove that you are a public company with multiple employees.

None of the signature mechanisms prevent false positive detections from anti virus suites.

**Comment by chrisant996** [comment]
> Sorry, duplicate of https://github.com/chrisant996/clink/issues/138

No, this is not a duplicate of #138.

What's reported here is not an anti virus false positive.  This is simply SmartScreen saying "this software hasn't been seen enough by our proprietary algorithms for SmartScreen to know whether this is likely to be safe".  The only solution to this is EV Code Signing, which only multi-employee companies are allowed to get.
