### ISSUE TITLE
[Feature Request] clink installscripts only for certain clinks

### ISSUE THREAD

**Issue by Roze061** [chrisant996/clink#200]
Hello,
it would be nice if clink installscripts wrote in the clink profile running it

```
clink --version
1.2.45.472728

ver

Microsoft Windows [Version 10.0.19043.1348]
```

**Comment by chrisant996** [comment]
The purpose of `clink installscripts` is so that installers of script libraries can install them for all clink profiles.

When specifying a `--profile` to use, try also setting the `%CLINK_PATH%` environment variable to specify paths from which to load scripts for that profile.

I don't want to turn `clink installscripts` into a super complicated thing that's hard to specify, hard to report on the current settings, and hard to manage.

**Comment by Roze061** [comment]
can you add an optional parameter to only install on certain clinks.
I want clink not to write to the registry but to the clink profile.

hi chris can you update [examples/ex_fzf.lua](https://github.com/chrisant996/clink/blob/69fc922b90d17d2fe46557f4d8f668606165c572/examples/ex_fzf.lua) from #89 .
there are version restrictions for io.popenrw and there are more lua functions

**Comment by chrisant996** [comment]
> can you add an optional parameter to only install on certain clinks. 

`clink installscripts` is for use by installer scripts, and installer scripts don't know about different profiles.

> I want clink not to write to the registry but to the clink profile.

The whole point of `clink installscripts` is to write to the registry.
So you need to use something else.

`%CLINK_PATH%` can do what you want.
`clink set clink.path dir1;dir2;dir3;etc` ccan do what you want.

> hi chris can you update [examples/ex_fzf.lua](https://github.com/chrisant996/clink/blob/69fc922b90d17d2fe46557f4d8f668606165c572/examples/ex_fzf.lua) from [issues 89](https://github.com/chrisant996/clink/issues/89) . there are version restrictions for io.popenrw and there are more lua functions

Update it in what way?
What version restrictions are you running into?
What do you mean by "there are more lua functions"?

The file at `examples/ex_fzf.lua` is meant to illustrate how to write Lua code that filters matches.  It is not meant to be a script that you actually use.  I would rather make it more generic and not even mention fzf at all, rather than turn it into some kind of full featured script that gets updated regularly.

Maybe instead you would be interested in the fzf script that @rashil2000 wrote, which is mentioned [here](https://github.com/chrisant996/clink/issues/150#issuecomment-906594664).

**Comment by Roze061** [comment]
> The file at examples/ex_fzf.lua is meant to illustrate how to write Lua code that filters matches. It is not meant to be a script that you actually use. I would rather make it more generic and not even mention fzf at all, rather than turn it into some kind of full featured script that gets updated regularly.

I apologize for asking for an update for the sample script

>  What version restrictions are you running into?
>  What do you mean by "there are more lua functions"?

I mean this

> ```
> if not io.popenrw then
>     print("fzf.lua requires a newer version of Clink; please upgrade.")
>     return
> end
> ```

> This version of fzf.lua works with Clink v1.1.42 and has three commands:
> 
> - luafunc:fzf_file
> - luafunc:fzf_history
> - luafunc:fzf_complete

I'm sorry, don't think about it

yes i also use `clink set`, but i also use scoop to update and install clink lua scripts
now i know the equation might be like scoop adding a powershell module
Btw I don't want there to be more in the software registry keys, so I'm not going to use it

**Comment by chrisant996** [comment]
> I mean this
> 
> ```
> if not io.popenrw then
>     print("fzf.lua requires a newer version of Clink; please upgrade.")
>     return
> end
> ```

No versions of the script work on Clink v1.1.40 or lower.  All versions require at least v1.1.41.

Is the request to add a version check into the example script?
If so, why?

- With or without the version check, the script will refuse to run on an older version of Clink -- the version check simply substitutes a user-friendly message instead of a script execution failure message.
- If I were to add a version check in that example, then should I also add version checks everywhere else in the documentation where things won't work on older versions?  Should every example include instructions for how to do alternatives for all preceding versions of Clink?  That's not something that reference documentation or examples normally do (there are several reasons why not).

What I _will_ do is work on finishing the version info annotations in the Lua Reference section of the Clink documentation.  Some weeks ago I annotated every function with the version number where it became available.  However, I haven't yet chosen how to format that information in the Clink documentation, so it's not listed yet.

> * luafunc:fzf_file
> * luafunc:fzf_history
> * luafunc:fzf_complete

I think the request is less about updating the example, and more about finding a good way to share a fully functional fzf script, right?

That gets into the topic of how to make a library of scripts that people can choose to download.  I don't want to take on responsibility for curating or managing a repository of other peoples' scripts.  The best recommendation I can give at the moment is for script authors to make their own repos for their scripts, like how I made [clink-flex-prompt](https://github.com/chrisant996/clink-flex-prompt) for that set of scripts.

I guess no one is stepping up to do so for an fzf script, so I guess I can go ahead and make a repo for that one, and I can add a link to it in the [Sample Scripts](https://chrisant996.github.io/clink/clink.html#sample-scripts) section of the Clink documentation.  And also choose a better name for that section than "Sample Scripts".  🙃

**Comment by chrisant996** [comment]
Enhanced FZF script is available here:  https://github.com/chrisant996/clink-fzf

**Comment by chrisant996** [comment]
I've made a [clink-gizmos](https://github.com/chrisant996/clink-gizmos) repo with the best Clink scripts that I use.

It does not include [clink-completions](https://github.com/vladimir-kotikov/clink-completions] or [clink-flex-prompt](https://github.com/chrisant996/clink-flex-prompt) at this time.  I will likely see about including the former, but the latter probably does not belong there (imagine if other prompt scripts were to be added -- they would be unlikely to coexist well).

This is not quite the same as a universal library of third party scripts, but it is at least a step in a useful direction.
