### ISSUE TITLE
[Request] Script to apply file/dir/exe color to first word in input line

### ISSUE THREAD

**Issue by pukkandan** [chrisant996/clink#207]
Clink already allows for distinguishing files, folders, executables etc in `possible-completions` (and similar) using the `LS_COLORS` environment variable. But in the input line, only aliases and commands can be colored (using `color.doskey` and `color.cmd`).

It would be nice if the `LS_COLOR`s are also applied to the input line. Alternatively, there could be new options to separately customize these instead

**Comment by chrisant996** [comment]
The request makes sense.

Here are the problems:

> Clink already allows for distinguishing files, folders, executables etc in `possible-completions` (and similar) using the `LS_COLORS` environment variable.

For _completions_, yes.

> But in the input line, only aliases and commands can be colored (using color.doskey and color.cmd).

The input line currently colors words based on whether they are arguments, flags, commands, doskey macros, are beyond the end of recognized arguments, and more.

Suppose you type `clink set color.doskey` and there is a file named `set` in the current directory.

Then what color should `set` be?  I don't believe it should use a file color.  But there is no way for Clink to know whether the `set` argument is a file or not.  That's why it doesn't apply completion colors to the input line -- they are quite simply different kinds of things.

While it could be possible to blindly test every word for "is there a file with this name?" I believe that produces many cases where the coloring is both incorrect and misleading, and will result in a lot of "bug reports".

**Comment by pukkandan** [comment]
Sorry if it wasn't clear, but I only meant to add coloring for the first word (similar to color.doskey/color.cmd).

I understand that further words cannot be colored without the help of completion-scripts that understands the syntax of the program being invoked. Perhaps it could eventually be made possible for the argmatchers to mark something as filename/directory (rather than just flags/args) - but that is not the scope of my request

**Comment by chrisant996** [comment]
> Sorry if it wasn't clear, but I only meant to add coloring for the first word (similar to color.doskey/color.cmd).

I'd rather not build that into Clink, as it is inconsistent with the rest of how the input line coloring works.

I recommend for you to [write a classifier in Lua](https://chrisant996.github.io/clink/clink.html#setting-a-classifier-function-for-the-whole-input-line) to apply those colors to the first word.

> I understand that further words cannot be colored without the help of completion-scripts that understands the syntax of the program being invoked. Perhaps it could eventually be made possible for the argmatchers to mark something as filename/directory (rather than just flags/args) - but that is not the scope of my request

There are two ways to do that.  One consumes a lot of extra CPU time repeatedly and introduces annoyingly noticeable lag while typing, and the other is very convoluted and expensive to implement and _only_ works for actual completions and as soon as the word is edited (or typed rather than completed) then it must remove the color since it no longer knows what it actually is.

So, neither of those is really viable.

**Comment by pukkandan** [comment]
Thanks. I was not aware classifiers can be used for the whole input line. My lua knowledge is very minimal, but I will give a try implementing this. Anyway, since the functionality does exist, feel free to close the issue.

**Comment by chrisant996** [comment]
@pukkandan What is the motivation behind this?
- Are you wanting to customize colors for different file types?
- Are you just wanting to see a "not found" color like the fish shell does, when the command word isn't recognized? (i.e. not a file, dir, command, alias, or argmatcher.)

**Comment by pukkandan** [comment]
I didn't realize this issue was still open! I pretty much dropped trying to do this myself since I got busy with other things

The primary motivation was to be able to get a color when typing a valid executable, (and preferably also for directories). I am personally not interested in giving colors to other file types

**Comment by chrisant996** [comment]
> I didn't realize this issue was still open! I pretty much dropped trying to do this (for the time being) since I got busy with other things
> 
> The primary motivation was to be able to get a color when typing a valid executable (similar to color.cmd), and preferably also for directories. I am personally not interested in giving colors to other file types

Cool, thanks. I'll do something about that soon.

**Comment by chrisant996** [comment]
This turned out very cool.  Also pretty complicated!  Because I went all-out and used a background thread so that input stays fully responsive even if lookup takes a while to scan the file system.

**Comment by pukkandan** [comment]
This is perfect. Thanks!
