### ISSUE TITLE
RPROMPT bug

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/clink#210]
This is the minimal lua script to reproduce this issue:

```lua
local custom_prompt = clink.promptfilter(5)

function custom_prompt:filter(prompt)
  return os.clock().." "..os.getcwd().."\n".."> "
end

function custom_prompt:rightfilter(prompt)
  return os.geterrorlevel().." "..rl.getvariable('keymap')
end
```

Also this statement in .inputrc (and a blank clink_settings file)

```
"\t": clink-select-complete
```

Notice what happens to the right prompt when I press Tab - the last character disappears:

![cmd2](https://user-images.githubusercontent.com/46838874/143883363-e7300247-6147-4e10-8ee6-76f352c6c064.gif)

This happens on pressing Tab - even when there are no completion candidates.

**Comment by chrisant996** [comment]
Nice find.  It turns out isn't related to rprompt at all.  It's a mistake in where `clink-select-complete` positions the cursor before issuing "clear to end of screen" as part of drawing the list of matches.

(There's also a bug in how Clink's terminal emulation mode handles `ESC[J`, but you're not running into that; if you were using emulation mode then the whole rprompt would disappear -- for the same cursor positioning reason as above.)
