### ISSUE TITLE
Q: Can I make clink autorun only when "interactive" mode, i.e. in a window?

### ISSUE THREAD

**Issue by tvogel** [chrisant996/clink#212]
I just realized that when I have clink autorun enabled, some scripts (run from CMake) that seem to frequently invoke cmd.exe, are running a lot slower. Probably because the injection takes quite some time additionally to cmd.exe starting up. Is there a way, I could stop that from happening while still enjoying autorun in interactive cmd.exe windows?

**Comment by chrisant996** [comment]
I think you want Cmd.exe to only run its AutoRun regkey entries for interactive prompts.

Cmd.exe does not have such a feature.

I do not install Clink for autorun.  I have not removed the feature, because it already existed and people use it.  I would not recommend it, myself -- it seems simple enough to create one or more shortcuts that launch cmd.exe and inject Clink (and possibly use different profiles or different history files e.g. by setting CLINK_HISTORY_LABEL).
