### ISSUE TITLE
Tab completion is triggering when not pressing tab on 1.2.49

### ISSUE THREAD

**Issue by ben-may** [chrisant996/clink#213]
Hi,
We recently updated to 1.2.49 from 1.2.39 and now we have situations where tab-completion results are getting generated when the user is not pressing tab.  Is this a new feature that has a flag we can disable it with? or is it a bug?

Thanks,

-Ben

**Comment by chrisant996** [comment]
That's not much to go on.

What are the repro steps?
What does the user type that is triggering completion?
What does the screen look like?

Maybe the user turn on the new suggestions feature (which is off by default)?

What does `clink set autosuggest.enable` report?
See [Auto-suggest](https://chrisant996.github.io/clink/clink.html#gettingstarted_autosuggest) for more info on how suggestions work.

**Comment by ben-may** [comment]
Hey sorry for the lack of detail:
```
>clink set autosuggest.enable
        Name: autosuggest.enable
 Description: Enable automatic suggestions
       Value: False
```
In our repro cases we see the user type for example
p <arg>
then the space key to move to the next argument, and the next arguments completion matcher already starts running before the user has pressed tab.  I don't expect any completion lists to be generated etc. unless the user presses <tab>.  I'll see If I can cook up a quick and simple example to post here.

**Comment by ben-may** [comment]
Here is a sample that shows the bug:
```lua
test = {}

function test.test_arg_generator()
	print("ACTIVATED!")
	return { "subarg1", "subarg2", "subarg3"}
end

local testcommand = clink.argmatcher()
testcommand:nofiles()
testcommand:addarg("testarg1")
testcommand:addarg("testarg2")
testcommand:addarg({test.test_arg_generator})

local testcommand2 = clink.argmatcher()
testcommand2:nofiles()
testcommand2:addarg("test2arg1")
testcommand2:addarg("test2arg2")

local test_parser_table = {
	"testcommand" .. testcommand,
	"testcommand2" .. testcommand
}

local test_parser = clink.argmatcher("test")
test_parser:addarg(test_parser_table)
test_parser:addarg({}) -- add an empty arg so that after our commands completion is done we don't start trying to match files/directories
test_parser:loop(2)
```
with the above, if you type 
```test testcommand testarg1<space>```
you should see the "ACTIVATED!" print out, which I wouldn't expect unless I was to press ```<tab>``` after that ```<space>```

**Comment by chrisant996** [comment]
Thanks, I'll take a look!

**Comment by chrisant996** [comment]
Oh, I hadn't noticed the issue, but commit e52aa1d607d5c81ee8d539775cedeccb6044260a in v1.3 happens to have already fixed it as a side effect of significant internal improvements to the suggestions feature.

Can you use v1.3?  Or alternatively you could use v1.2.46 or lower.

**Comment by ben-may** [comment]
Can stick with v1.2.39 for now, I want to stick close to head of master though, so I will be interested in v1.3, is there any significant changes required to client code since it is a minor version bump?

**Comment by chrisant996** [comment]
> Can stick with v1.2.39 for now, I want to stick close to head of master though, so I will be interested in v1.3, is there any significant changes required to client code since it is a minor version bump?

Just incremental changes.  The bump to 1.3 just acknowledges the significance of the sum of incremental changes since 1.2.  The autosuggest feature is a relatively simple little bit of code, but with disproportionately big benefits, and was requested a long time ago.  This felt like the right inflection point to finally increment the minor version.

**Comment by chrisant996** [comment]
@ben-may can you clarify what user-observable problem occurred as a result of running the generators?

- Is it that the generators take a while to run, and that was making Clink less responsive to typing?

If so, then:

- Do the generators take a while purely due to reading the file system to collect matches?
- Or are the generators running programs which are taking a while to execute?  How do they run programs, is it via `io.popen()`?

Or other reasons/problems?  If so, can you share a little information about them?

I'm asking because I'm working on making the recent auto-suggestions feature use a coroutine to generate matches, so that the auto-suggestions feature does not impact responsiveness of typing.  The globber APIs are being updated to automatically support running in a coroutine, so that the match generators don't need modifications.  But if _other_ aspects of match generators are slow, then I want to know so that I can consider how to mitigate other slowness issues as well.

Thanks!

**Comment by ben-may** [comment]
hey @chrisant996 I hope you had a great holiday!  
The user-facing problem we had, was that we have a few generators that take a while to run (they spawned external processes that generated a list of things and returned them back to clink)

**Comment by chrisant996** [comment]
> The user-facing problem we had, was that we have a few generators that take a while to run (they spawned external processes that generated a list of things and returned them back to clink). So nothing to do with file-system access slowness or anything like that.

Ah, so yes they were indeed because of slowness.

1. Do the generators use `io.popen()` to run the external programs?
2. Is it ok to run the programs in the background?

In v1.3.1 when `autosuggest.enabled` is set to True, then generators run in the background by default (controlled by the `autosuggest.async` setting).  It might be possible now to turn on `autosuggest.enabled` and gain the benefits of the auto suggestions, without interfering with input or completion.

**Comment by ben-may** [comment]
I think ideally what would benefit us most is a user types:  ```test <verb>``` and then the generator starts running in the background as a non-blocking thing.  If the user then presses ```<tab>``` after that to get tab-completion results then you wait for it to finish populating the results.  That way if you don't press <tab> you don't have to wait, but if you do press <tab> then hopefully the results have been generated or half generated so you don't have to wait so long.  

we are using 
```lua
   os.execute()
```
To run our external programs to return the results.

**Comment by chrisant996** [comment]
> I think ideally what would benefit us most is a user types:  ```test <verb>``` and then the generator starts running in the background as a non-blocking thing.  If the user then presses ```<tab>``` after that to get tab-completion results then you wait for it to finish populating the results.  That way if you don't press <tab> you don't have to wait, but if you do press <tab> then hopefully the results have been generated or half generated so you don't have to wait so long.  

That is indeed the intended behavior.

(Caveat: when the old/deprecated API for match display filtering is used, then caching/reuse is not possible.)

> we are using 
> ```lua
>    os.execute()
> ```
> To run our external programs to return the results.

Ok, thanks, I will have to do some additional work to deal with that API.

I would expect using `io.popen()` would work just as well.  You'd need to `:close()` the returned file, for best results (vs waiting for gc to close it).

**Comment by chrisant996** [comment]
v1.3.2, or the current HEAD of the repo, should address the issue:
1. `os.execute()` now automatically yields when run in the background (for example, in the autosuggest background coroutine).
2. It is possible to make a function decline to run in the background by checking if it's running as a coroutine, and returning:

```lua
local function generate_matches()
    local _, ismain = coroutine.running()
    if not ismain then
        return
    end
    -- Do the normal work here...
end
```

**Comment by ben-may** [comment]
Thats great thank-you!
