### ISSUE TITLE
Add an option to run clink as Trustedinstaller by default

### ISSUE THREAD

**Issue by ibay770** [chrisant996/clink#217]
So whenever it is called in the system it has said privileges instead of right-clicking everyone on admin, why not just super boost it automatically?

**Comment by chrisant996** [comment]
It sounds like you are asking for the installer to automatically gain Administrator privilege without needing confirmation from the user.

That's not possible.  If it were, then all malware would automatically run as administrator.

**Comment by ibay770** [comment]
Correct, in the sense where you initially give permission for it to do so.
And I've seen malware and ransomware work even with all the security
protections on and everything (Wanncry for example) so we may as well be
the true owner of your machine. Appreciate the feedback though.



Nossy Drelich
706 -962-3222

BananaTechmaster <http://Bananatechmaster.strikingly.com/>

**Comment by chrisant996** [comment]
What you have asked for is not possible.

The only way to do so would be to maliciously hack computers. To be very clear, I do _not_ support malicious programming. Clink respects security and will continue to do so.

If you don't want to get prompted whether you trust software that's being installed, then you could turn off the UAC security, but I would never recommend that (and I would never turn off security like that on a computer I use, because of how dangerous it is).
