### ISSUE TITLE
dissable dll cache

### ISSUE THREAD

**Issue by NSP-0123456** [chrisant996/clink#232]
I have a security application (with compagny policies only). Recently  it prevent to load dll from temp folders. This is not possible  to inject as once the dll is copied, the application delete it...
I did not found any switch on clink -inject to prevent use of dll cache is it possible to add one ?

**Comment by chrisant996** [comment]
If attempting to copy to the dll_cache fails, then it should skip using it.

Try blocking access to it.

One simple way could be to delete the dll_cache folder, and create a file named dll_cache, instead.

**Comment by NSP-0123456** [comment]
This is a good trick and even of create folder fails, it try to launch from install folder...
Unfortunately even if the dll is not deleted the clink_xxx.exe is marked as exploit :
Category: Exploit, Event: Blocked, Details: Violation: OopThreadCreate; 
I will try to reach IT to signal false positive in CylanceProtect ......

**Comment by chrisant996** [comment]
> Details: Violation: OopThreadCreate

The anti-virus suite is responding to the fact that Clink is injecting itself into CMD (there is no other way that Clink could operate).  Injecting is an operation sometimes used by malware, so it is understandable that the anti-virus suite might flag it as suspicious.  In Clink's case it is a legitimate operation, and there are many other legitimate cases as well.

This is unfortunately something you will need to take up with Cylance and/or your IT department.  For example, it could be reasonable for the IT department to configure exceptions for `clink_x64.exe`, `clink_x86.exe`, `clink_dll_x64.dll`, and `clink_dll_x86.dll`.  Or it would be reasonable for Cylance to fix the detection so that it doesn't trigger a false positive on Clink.  However, if Cylance registers the hash of one specific version of Clink, then that won't help with future updates of Clink -- so configuring an exception is likely the most effective solution.
