### ISSUE TITLE
"the system cannot find the file specified" pops up after every command is launched

### ISSUE THREAD

**Issue by xFGhoul** [chrisant996/clink#243]
I'm not sure how or why this is happening, but every time I launch cmd, type a command or do anything really "the system cannot find the file specified" pops up and I don't know how to fix it

**Comment by chrisant996** [comment]
What are some things you did recently before that started happening?

There is very little information to go on.
But I infer that you installed Clink, and installed it with Autorun checked.
What did you do after installing it?
Was it working without an error for a while?
Have you looked at the output from `clink autorun show`?

There is so little information available that I can't really begin to guess what might be happening.
Unless you manually deleted the Clink directory under Program Files, instead of using the uninstaller.

**Comment by xFGhoul** [comment]
Alright I'll answer all your questions

1. Nothing really, except adding [oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh) using the `clink installscripts` command

2. no, second it was installed it started doing that

3. output of `clink autorun show`
![WindowsTerminal_TMZYsPW3Ws](https://user-images.githubusercontent.com/70284239/155013840-946f46f3-c2e8-4a2d-af4d-f6f57b0355d9.png)

**Comment by chrisant996** [comment]
That explains it.  🙂

> 1. Nothing really, except adding [oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh) using the `clink installscripts` command

When your script tries to launch oh-my-posh, the oh-my-posh program is not found.
Your script is causing the error because:
1. The script does not specify a path to the oh-my-posh program (or specifies an inaccurate path).
2. The oh-my-posh directory is not listed in the system `%PATH%`, so the OS can't find oh-my-posh when it tries to fill in the missing path.

You will need to review and fix the script that is launching oh-my-posh.
Probably the notes about filling in the path to oh-my-posh were skipped or misunderstood, or perhaps there was a typo.

**Comment by chrisant996** [comment]
(Also, it looks like you might be trying to use both clink-flex-prompt and oh-my-posh at the same time.  Each of those fully defines the prompt; when using both at the same time probably either one of them will end up getting skipped and do nothing, or they may interfere with each other and surprising things might occur in some cases.)

**Comment by xFGhoul** [comment]
> That explains it. 🙂
> 
> > 1. Nothing really, except adding [oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh) using the `clink installscripts` command
> 
> When your script tries to launch oh-my-posh, the oh-my-posh program is not found. Your script is causing the error because:
> 
> 1. The script does not specify a path to the oh-my-posh program (or specifies an inaccurate path).
> 2. The oh-my-posh directory is not listed in the system `%PATH%`, so the OS can't find oh-my-posh when it tries to fill in the missing path.
> 
> You will need to review and fix the script that is launching oh-my-posh. Probably the notes about filling in the path to oh-my-posh were skipped or misunderstood, or perhaps there was a typo.

The thing is, oh-my-posh is on my path, both account and system so I'm not sure what I'm doing wrong.

**Comment by xFGhoul** [comment]
> (Also, it looks like you might be trying to use both clink-flex-prompt and oh-my-posh at the same time. Each of those fully defines the prompt; when using both at the same time probably either (1) one of them will end up getting skipped and do nothing, or (2) they may interfere with each other and surprising things might occur in some cases.)

The two on is fine for me, but I do notice some freezing when typing sometimes, just for knowledge, how do I disable the two?

**Comment by chrisant996** [comment]
> The two on is fine for me, but I do notice some freezing when typing sometimes, just for knowledge, how do I disable the two?

The freezing happening when you press <kbd>Space</kbd> after the first word in the line, right?  That is because of an issue in oh-my-posh: it installs its own handler for <kbd>Space</kbd> and it launches oh-my-posh and does a lot of processing.

To resolve that, you will need to either report an issue in the oh-my-posh repo, or don't load an oh-my-posh script into Clink.  E.g. delete whatever Lua script you are using to load oh-my-posh in Clink.

**Comment by chrisant996** [comment]
> > That explains it. 🙂
> > > 1. Nothing really, except adding [oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh) using the `clink installscripts` command
> > 
> > 
> > When your script tries to launch oh-my-posh, the oh-my-posh program is not found. Your script is causing the error because:
> > 
> > 1. The script does not specify a path to the oh-my-posh program (or specifies an inaccurate path).
> > 2. The oh-my-posh directory is not listed in the system `%PATH%`, so the OS can't find oh-my-posh when it tries to fill in the missing path.
> > 
> > You will need to review and fix the script that is launching oh-my-posh. Probably the notes about filling in the path to oh-my-posh were skipped or misunderstood, or perhaps there was a typo.
> 
> The thing is, oh-my-posh is on my path, both account and system so I'm not sure what I'm doing wrong.

If you would like help figuring out what has been done wrong, you would need to share what you have done.
For example, it sounds like there is a bug in the script, and you wrote/configured/installed the script, so it would be informative to share the script, share how it was configured, and share how it was installed.
Etc.

**Comment by xFGhoul** [comment]
> > > That explains it. 🙂
> > > > 1. Nothing really, except adding [oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh) using the `clink installscripts` command
> > > 
> > > 
> > > When your script tries to launch oh-my-posh, the oh-my-posh program is not found. Your script is causing the error because:
> > > 
> > > 1. The script does not specify a path to the oh-my-posh program (or specifies an inaccurate path).
> > > 2. The oh-my-posh directory is not listed in the system `%PATH%`, so the OS can't find oh-my-posh when it tries to fill in the missing path.
> > > 
> > > You will need to review and fix the script that is launching oh-my-posh. Probably the notes about filling in the path to oh-my-posh were skipped or misunderstood, or perhaps there was a typo.
> > 
> > 
> > The thing is, oh-my-posh is on my path, both account and system so I'm not sure what I'm doing wrong.
> 
> If you would like help figuring out what has been done wrong, you would need to share what you have done. For example, it sounds like there is a bug in the script, and you wrote/configured/installed the script, so it would be informative to share the script, share how it was configured, and share how it was installed. Etc.

Ah ok, my setup process was

1. create a directory called scripts

2. use `clink installscripts` to install that module

3. create a .lua called oh-my-posh with the following content:
```lua
load(io.popen('oh-my-posh --config="C:/Users/Dante/powerlevel10k_modern.omp.json" --init --shell cmd'):read("*a"))()
```

**Comment by xFGhoul** [comment]
> > The two on is fine for me, but I do notice some freezing when typing sometimes, just for knowledge, how do I disable the two?
> 
> The freezing happening when you press Space after the first word in the line, right? That is because of an issue in oh-my-posh: it installs its own handler for Space and it launches oh-my-posh and does a lot of processing.
> 
> To resolve that, you will need to either report an issue in the oh-my-posh repo, or don't load an oh-my-posh script into Clink. E.g. delete whatever Lua script you are using to load oh-my-posh in Clink.

Ah alright

**Comment by chrisant996** [comment]
> my setup process was
> 
> 1. create a directory called scripts
> 2. use `clink installscripts` to install that module
> 3. create a .lua called oh-my-posh with the following content:
> 
> ```lua
> load(io.popen('oh-my-posh --config="C:/Users/Dante/powerlevel10k_modern.omp.json" --init --shell cmd'):read("*a"))()
> ```

What troubleshooting have you done so far?

Have you commented out the `load(...)` line in the Lua script you made?
If you comment it out and the problem stops, then you know that's the source of the problem.
And if commenting it out stops the problem, then it would suggest that you are mistaken about oh-my-posh being on the system PATH.

You've stated that the oh-my-posh directory is in the system PATH, but the runtime behaviors suggest it is not on the PATH.
How have you confirmed that the oh-my-posh directory is in the system PATH?

Have you tried printing the PATH (`set PATH`) to see whether the oh-my-posh directory is currently in the PATH env var?
Just because it was added in the Control Panel or by an installer program would not necessarily mean that it is set in any programs that were already running before then.

Have you tried using the Where command (`where oh-my-posh`) to check whether the oh-my-posh program is found?

I think you need to do some troubleshooting.

**Comment by UweKeim** [comment]
In my case this happened on a Windows Server:

1. User A installs Clink ("Run as Administrator").
2. User B logs in.
3. User B starts CMD.
4. Error for User B occurs.

My solution was to install it manually for user B, too.

But to be honest, in my opinion this is a bug if I cannot install Clink for all users.

Since it is installed in "C:\Program Files (x86)\clink" I really _do_ expect that one setup run is enough for all users.

**Comment by chrisant996** [comment]
> In my case this happened on a Windows Server:
> 
> 1. User A installs Clink ("Run as Administrator").
> 2. User B logs in.
> 3. User B starts CMD.
> 4. Error for User B occurs ("the system cannot find the file specified").
> 
> My solution was to install it manually for user B, too.
> 
> But to be honest, in my opinion this is a bug if I cannot install Clink for all users.
> 
> Since it is installed in "C:\Program Files (x86)\clink" I really _do_ expect that one setup run is enough for all users.

@UweKeim can you share some details about how Clink was installed?
Which boxes were checked in the installer program?
What Lua scripts are installed?
What is the context around the error message?  (I can't see the screen, so I can't tell which window is display the error message, or what is above or below it, or etc.)

The "the system cannot find the file specified" seems like it has to be coming from something _other_ than Clink.  It seems like a Lua script or etc may have a mistake in it.  Perhaps something is referring to something in the profile directory (which is naturally different for each user), or perhaps something is trying to invoke a program that is not on the system PATH for User B, or something like that?

**Comment by UweKeim** [comment]
Thanks, @chrisant996 

- We have a Windows Server 2022 (being upgraded recently from Windows Server 2019).
- I connect via RDP.
- Clink 0.4.9 was installed since years.
- No additional Lua scripts or anything was installed/configured
- Then I discovered your awesome continuation of that project and installed Clink 1.3.x with my user A.
- I rebooted and all that stuff.
- My co-worker connects via RDP as user B to the server and fires up a CMD.exe (as Administrator)
- Then right when it normally prints "Clink v1.3.8.c918a0" after CMD startup, it prints the error message.
- My co-worker user B then also runs the setup of Clink 1.3.x with his account.
- Everything works now both with my account as user A as well as his account as user B.

It is working now, but I'm not sure how this would behave on subsequent updates after 1.3.x. _Probably_ this is all fixed now, since the folder now stays the same (no 0.4.9 sub folder anymore), but I am not sure. Seems that the registration/"hook" of Clink into the CMD.exe (sorry for my words, I'm unsure about the internal correct mechanism) only registers for the user that installs Clink, not for all users.

**Comment by chrisant996** [comment]
Oh, thanks, I see what happened:

1. Both users had installed Clink separately in the past, and installed it with AutoRun checked.
2. AutoRun is installed only for the current user (naturally, out of respect for other users).
3. AutoRun writes a specific path into the registry, so each of the users had a registry key pointing to the old path.
4. When a new version of Clink gets installed, it naturally uninstalls the old version.
5. And then any other users whose AutoRun still points to the old version will experience a failure due to the old path in their AutoRun registry key no longer existing.

But, around v1.3.5 I rewrote that part of the installer program.  That problem won't happen anymore unless different users install Clink to different directories (users sharing a computer would need to coordinate about that; Clink can't really prevent users from actively taking manual steps that break each other's configuration).

Because now the installer puts all versions of Clink in the same directory (like all other apps do), unless a user overrides the install directory (just like happens with any other program in that situation).

Martin had tried to work around a bug in the Clink installer, by putting each version of Clink into a separate directory name.  That's what caused the problem.  And in v1.3.5 I fixed the installer bug and removed the hack that was causing the problem you've reported.

It should work as expected, moving forward from here.

**Comment by UweKeim** [comment]
Thank you very much. I do think regarding your 2. that an option „install for all users“ would be awesome.

**Comment by chrisant996** [comment]
> Thank you very much. I do think regarding your 2. that an option „install for all users“ would be awesome. 
> 
> If this option is checked, your 3. would write to HKLM instead of HKCU in the registry. 

The installer writes everything to HKLM, _except_ the AutoRun setting.

If you want to force all users on the machine to always Clink, use `clink autorun -a install` from an elevated command window.

See `clink autorun --help` and the Clink documentation for more info.

**Comment by xFGhoul** [comment]
Update...I removed `oh-my-posh.lua` and I'm still getting this error, now I'm beginning to assume it's something with my click install, It might be trying to find a script that doesn't exist...

**Comment by xFGhoul** [comment]
Also.... ` C:\Users\xxx\AppData\Local\clink` does not exist for me, could that be a cause? If so, how do I fix?

**Comment by chrisant996** [comment]
> Update...I removed `oh-my-posh.lua` and I'm still getting this error, now I'm beginning to assume it's something with my click install, It might be trying to find a script that doesn't exist...

Clink itself doesn't do anything that can report such an error.  Clink itself does not attempt to launch other programs.

However, Lua scripts may attempt to launch other programs, and Bat/Cmd scripts may attempt to launch other programs.

First, completely uninstall Clink and any configuration you have done regarding Clink.
Then do a fresh, clean install of _only_ Clink itself, without adding any configuration yet.
Make sure that works.

Then add configuration bit by bit, until you find which change introduces the error.

> Also.... ` C:\Users\xxx\AppData\Local\clink` does not exist for me, could that be a cause? If so, how do I fix?

How did you determine that it doesn't exist?
There are 5 directories listed there -- which ones exist and which ones don't?  (c:\users, c:\users\xxx, c:\users\xxx\appdata, etc)
AppData is a hidden directory, so if you opened C:\Users\xxx in File Explorer then you won't see AppData unless you've enabled "Hidden items" in File Explorer.

Sorry that you're having trouble setting up scripts and configuration.
You will need to do some troubleshooting and figure this out.

**Comment by xFGhoul** [comment]
yep, everything works perfectly now
