### ISSUE TITLE
Setup is not detecting previous installation dir

### ISSUE THREAD

**Issue by bw1faeh0** [chrisant996/clink#244]
Since version 1.3.7 the clink setup does not detect my clink installation directory anymore. It uses the default directory:

![image](https://user-images.githubusercontent.com/29235332/155083446-339d63ba-c733-4438-9652-0b7d2eb2b9ea.png)

**Comment by chrisant996** [comment]
Thanks for reporting this.

v1.3.5 is when that stopped working, when the "Modern UI" mode of the installer was adopted in order to show descriptions for each of the install checkboxes.

The "Modern UI" in the Nullsoft Installer System uses a different mechanism for filling in an initial value for the destination folder.
