### ISSUE TITLE
[Question] Pressing ESC twice to trigger lua script

### ISSUE THREAD

**Issue by bw1faeh0** [chrisant996/clink#248]
Hi,

I love the [sudo](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/sudo) plugin of oh-my-zsh, I'm using it frequently. Since I have [sudo](https://github.com/gerardog/gsudo) installed on my windows machine, I'm missing this plugin a lot.

Quotation from the plugins readme:\
"Easily prefix your current or previous commands with `sudo` by pressing <kbd>esc</kbd> twice."

Is clink able to detect pressing <kbd>esc</kbd> twice, so one can bind it to a lua function?

Maybe I'm able to use clinks features to implement a functionallity like the oh-my-zsh plugin.

**Comment by chrisant996** [comment]
Short version:  No.

Long version:

Welcome to the craziness of how <kbd>Esc</kbd> works in *nix.  *nix can't tell the difference between the <kbd>Esc</kbd> key pressed, versus the `0x1B` ESC byte that begins all enhanced keys, and <kbd>Alt</kbd>+ combinations, and so on.  There are a variety of hacks that programs use to help differentiate the inputs most of the time, but they're unreliable.  This is why on *nix systems, pressing <kbd>Esc</kbd> sometimes gets into a non-responsive state that you can't seem to get out of.

Anyway, Clink uses a keyboard driver that generates a unique key sequence when the actual <kbd>Esc</kbd> key is pressed.  That resolves all the crazy ESC-related input problems.

Except that chaining together multiple ESC gets weird.  And I tried some edge cases and discovered a bug in `what-is` (reports certain inputs incorrectly), and discovered that <kbd>Alt</kbd>+<kbd>[</kbd> generates an ambiguous sequence, and discovered some kind of infinite loop bug in a multi-key input sequence that invokes a text macro (I can't tell yet whether it's a bug in Clink, or a bug in Readline's callback mode -- Clink has uncovered multiple bugs in Readline's callback mode), and there is some kind of issue when `terminal.raw_esc` is disabled (not surprising, but I don't know yet what is the exact issue).

I'll look into fixing the weird bugs, but that's not going to help you with two ESC.  And you probably want a single ESC to do one thing, and a double ESC to do another?  And you probably want ESC[A to still be interpreted as UP, but you want ESC{timeout} to be interpreted ESC KEY, and ESCESC{timeout} to be interpreted as ESC KEY, ESC KEY.  And so one.  Except that using timeouts is unreliable -- if the computer is busy (e.g. using all CPUs at 100% while building a large project) then the timeouts are not going to work properly and suddenly keyboard input stops working properly; and timeouts only work for human input -- if you record the input and play it back then there are no delays in the replayed macro and so it gets interpreted differently than when you originally typed it.  These are some examples why Clink uses a more "Windows-like" input model instead of the old ambiguous raw terminal input model that *nix still uses.

Anyway, I'll fix the weird things are aren't working as intended.  But I really don't want to mess with timeouts.  Once the bugs are fixed, you should be able to bind ESC,ESC but then ESC by itself of course will not do anything.  And ESC,anything_else will eat the input.  And so on.  Much more predictable than *nix input, but it loses the ability to create ambiguous bindings like ESC,ESC.  (For example, ESC ESC O S is the sequence for Alt+F4... -- so in terminal.raw_esc mode ESC,ESC is ambiguous and suddenly you need multiple timeouts to differentiate between ESC, ESC ESC, ESC ESC O S, and various other inputs).

**Comment by bw1faeh0** [comment]
Ok, i think I can use an other combination of keys, maybe ctrl+ESC or just the string "fuck" + enter to repeat the last line with additional sudo prefix.

**Comment by chrisant996** [comment]
@bw1faeh0

It actually works fine.  I think maybe you didn't run `clink echo` to find the key sequence generated by the ESC key?

### Question: How do you use ESC normally?

It sounds like you have ESC ESC bound to something in zsh.
Is ESC by itself also bound to something in zsh?
Or do you press ESC only as a prefix key to other input sequences?
E.g. if you type ESC`[A` then do you expect that to get interpreted the same as if you had typed UP?

My guess is that *nix has conditioned you to mostly avoid pressing ESC unless you are intentionally typing a multi-key sequence.  But on Windows, ESC is how to clear the input line in CMD and in Powershell.  Which is why Clink has always defaulted to supporting ESC to clear the input line.

### Binding ESC ESC works fine (to the same degree it works in bash/etc

If you have the `terminal.raw_esc` setting `false` (the default value), then everything should have worked fine, provided you used `clink echo` to find that the sequence for the ESC key is `"\e[27;27~"`.

```inputrc
"\e[27;27~\e[27;27~":    "\e[Hsudo "
```

Tada.  Works for me.  Except that a single ESC press will no longer clear the input line, until _after_ you type another key that is not ESC.  Because of how shadowed keys work in Readline and bash and etc.

### Sidebar:  What is a shadowed key?

A "shadowed key" is when e.g. you bind `a` to something, and also bind `ab` to something.
Then `a` is a shadowed key, because it is a prefix of a longer key binding.

Suppose:
```inputrc
"a": "A"
"ab": "Bazinga"
```

If you type `a` then nothing happens yet:  `a` is shadowed and behaves differently depending on the next input.
If you next type `b` then you've typed the key binding `ab` and that is bound to a text macro which gets inserted.
So, when you type `ab`, what gets inserted instead is `Bazinga`.

But if you type `a` and then anything _other_ `b`, then the shadowed key binding `a` is invoked, followed by whatever _other_ thing you typed.  So, when you type `ax`, it is two separate key bindings for `a` and `x` and so what gets inserted is `Ax`.

### But `raw_esc` enabled won't work

If you have run `clink set terminal.raw_esc true` to use *nix-like terminal input handling for ESC, then you'll get the same quirks/problems/benefits as in bash and zsh and etc on *nix.

Assuming `raw_esc` is enabled per above, then you'd expect to be able to bind something like this:
```inputrc
"\e\e":    "\e[Hsudo "
```

But it doesn't work as expected -- typing ESC ESC does nothing until you type a third key:
Because `"\e\e"` is a "shadowed key".
Because `"\e\eOS"` is already bound to `clink-exit` so that ALT+F4 can exit in a plain Conhost console window.

Ok, fine so we should be able to unbind the ALT+F4 key and get it working:
```inputrc
"\e\eOS":    #unbind
"\e\e":    "\e[Hsudo "
```

### Nope, there is a Readline problem

It turns out, Readline has a problem when you unbind a longer key sequence, and then later bind something that _would have been_ shadowed before the unbind.  The unbind doesn't restore the keymaps fully to the state they would originally have been in.

So, `"\e\e"` gets freshly bound as though it is a shadowed key, even though there is no reason for it to be a shadowed key.

I'm reluctant to dive into making that invasive a change in Readline.

I suggest to have `raw_esc` in its default `false` state, and bind ESC ESC, taking into account that `"\e"` is not the key sequence emitted by pressing the ESC key by itself.

**Comment by chrisant996** [comment]
If you normally have `raw_esc` set to `true`, then let me know:

Maybe I can find a reasonable way to make a surgical change that mitigates the unbind problem, without investing in a full deep fix for the Readline keymap handling issue.

**Comment by bw1faeh0** [comment]
The ESC key isn't used by any function in my *nix env. I noticed, that is used to clear the input line in cmd/powershell/[you name it], but in clink I use CTRL + U to clear my input line, like I do in *nix env.

So, I modified my inputrc like you described:

> ### Binding ESC ESC works fine (to the same degree it works in bash/etc)
> If you have the `terminal.raw_esc` setting `false` (the default value), then everything should have worked fine, provided you used `clink echo` to find that the sequence for the ESC key is `"\e[27;27~"`.
> 
> ```inputrc
> "\e[27;27~\e[27;27~":    "\e[Hsudo "
> ```

As you guessed, `terminal.raw_esc` was set to `false`. 

> Tada.

This solution works perfectly fine for my needs! I was not aware, that `\e[H` is all I need. These escape sequences are still black magic for me (in terms like "I hadn't even known you could do something like that.").

Many thanks for showing me!
