### ISSUE TITLE
--quiet blank unwanted lines output 

### ISSUE THREAD

**Issue by xinxilas** [chrisant996/clink#250]
Look:

![image](https://user-images.githubusercontent.com/38674705/156380411-96317011-029c-42d7-9043-425f615b7d9e.png)

**Comment by xinxilas** [comment]
Sorry, this is from startship

**Comment by chrisant996** [comment]
I have to guess at what is at what is being reported, since it is not described specifically.

- I think you're implying that you launch `cmd /k clink inject --quiet`.
- I think you're implying that want the `C:\users\xinxilas\Desktop>` line to be at the very top of the new cmd window, and that there is 1 blank line at the top that you wish to remove.

If that's what you mean, then that is simply how CMD works.  CMD prints the blank line; it doesn't come from Clink:

It's the same blank line as in between the "Microsoft Windows ... All rights reserved." text and the prompt, when launching just `cmd`.  In other words, the third line here:

```
Microsoft Windows [Version 10.0.19043.1526]
(c) Microsoft Corporation. All rights reserved.

C:\Users\chrisant>
```

and the second line here:

```
Clink v1.3.9.4597fe (https://github.com/chrisant996/clink)

c:\Users\chrisant>
```

When you launch `cmd /k any_command`, then CMD skips the first two lines.  But it always prints the blank line.

You can see for yourself by launching something like `cmd /k rem`.  There is a blank line at the top.

The reason the Clink startup logo goes before the blank line is that `clink inject` occurs before CMD gets around to printing the blank line. 

If you don't want to accept the CMD behavior, then you could make a Lua script to use ANSI escape codes to force clearing the screen before the first prompt is displayed:

```lua
local cleared
clink.onbeginedit(function ()
    if not cleared then
        clink.print("\x1b[H\x1b[J", NONL)
        cleared = true
    end
end)
```

But that will _always_ clear the screen before the first prompt whenever Clink is injected, and also whenever Clink is reloaded by pressing CTRL+X,CTRL+R (for example).  That may or may not be acceptable, so you'll need to choose between the blank line or clearing the screen.
