### ISSUE TITLE
[question] how to move cursor to the start/end of the current line

### ISSUE THREAD

**Issue by mo-han** [chrisant996/clink#253]
on linux and the old version clink, ctrl-a and ctrl-e do the job.
but now it seems changed, forced to use the home/end key instead.

**Comment by chrisant996** [comment]
Did you install Clink by using the installer exe, and accepted the default choices?

The installer now has [Enhanced default settings](https://chrisant996.github.io/clink/clink.html#gettingstarted_enhanceddefaults) enabled by default.  You can uncheck the box, and future installs will remember that you unchecked the box (in other words, you only need to uncheck the box one time).

The "Enhanced default settings" include using Windows key bindings by default, so that CMD behaves like CMD by default.  See [Bash vs Windows](https://chrisant996.github.io/clink/clink.html#gettingstarted_defaultbindings) for a little more information.

**Comment by mo-han** [comment]
thank you so much

**Comment by chrisant996** [comment]
Also, the documentation needed more information about these, so I've made updates to the documentation.

Thank you for asking the question!
