### ISSUE TITLE
Support light themes using Windows builtin

### ISSUE THREAD

**Issue by alkuzad** [chrisant996/clink#256]
Currently if colorized_input is enabled then some commands will be invisible because they are very bright yellow. I could manually go through all colors and make them work but this would be so much easier if defaults would be automatic based on Windows setting. If windows is set to Light mode (via registry ` Get-ItemProperty -Path Registry::HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize -Name AppsUseLightTheme | Select-Object -ExpandProperty AppsUseLightTheme`) then I would like clink to be aware and use that, with override possible.

**Comment by chrisant996** [comment]
What terminal program are you using?

**Comment by chrisant996** [comment]
By the way, I use light theme.  In all terminal programs that I've used, light theme still uses black as the background for console windows.

So can you explain more?
- What version of Windows are you using?
- What terminal program are you using?
- How is the terminal program configured?
- Maybe include a screen shot?

There's not a good way to automatically support background colors other than black.

Try installing Clink with "Use enhanced default settings" unchecked, and then configure all the various colors how you want.

**Comment by alkuzad** [comment]
Windows10
WindowsTerminal 1.12.10393.0
Config: https://gist.github.com/alkuzad/37b7e2bd177e7cbe1d1c47466d2e2b69
![image](https://user-images.githubusercontent.com/3463594/157880254-8dc034e5-03cf-4a6c-b167-e11ebfe50750.png)

Windows definition of light theme seems different, this is article showing difference:
https://www.bleepingcomputer.com/news/microsoft/a-closer-look-at-the-new-windows-10-light-theme/

**Comment by chrisant996** [comment]
There is no way for a program to know what the configuration is for the current tab in Windows Terminal.

Regardless what theme the OS may apply to Windows Terminal, the user can configure many different kinds of background color/modes, and console mode programs can't tell what it is.  And if you use acrylic, then the background (and contrast) depends on what other window contents are behind the Windows Terminal window.

(There are many more technical problems involved here, as well.)

The only way that Clink could attempt to address the issue would be to abandon the use of rich colors entirely, and only use the 16 color palette.  I'm not going to abandon rich colors in "Use enhanced default settings" mode.

Why not either install Clink with "Use enhanced default settings" turned off, or configure the colors to your liking?

**Comment by alkuzad** [comment]
I installed this via Winget so I assume it accepted the default installer settings, I use my own profile however, does not know if this changes things. Windows Terminal has allows to configure colors but also obeys Windows settings by default giving user option to modify them. I am not asking to perfectly match the background, only to create two sets of defaults matching current windows settting that users still can modify. Clink uses my LS_COLORS to match quite a lot of colors but not all of them, you added some unique ones :)

This would also be a nice addon on top of the feature that Microsoft is planning to do, it was in discussion for a while but was drafted finally few days ago - [Theme-controlled color scheme switch](https://github.com/microsoft/terminal/pull/12613/files#diff-ff282bc5b3c91c5cb717f3f01dead7d95b62ac17671f8c2a3b2da8400bf47946R16). This would mean switching between two modes would be done automagically.

**Comment by chrisant996** [comment]
I understand the high level goal and motivation.

For now:
- See [Enhanced default settings](https://chrisant996.github.io/clink/clink.html#gettingstarted_enhanceddefaults) and [Colors](https://chrisant996.github.io/clink/clink.html#gettingstarted_colors).
- The simplest thing to do is delete the `default_settings` file in the Clink installation directory, which will then use the standard color defaults.  If you want more color beyond that, you can apply further color customizations as desired.

The specific proposed approach about detecting Windows Terminal theme isn't feasible, for reasons that become clear after researching the problem space a bit.  I won't (can't 🤷‍♂️) use the proposed approach.  But there are other options.

> This would also be a nice addon on top of the feature that Microsoft is planning to do, it was in discussion for a while but was drafted finally few days ago - [Theme-controlled color scheme switch](https://github.com/microsoft/terminal/pull/12613/files#diff-ff282bc5b3c91c5cb717f3f01dead7d95b62ac17671f8c2a3b2da8400bf47946R16). This would mean switching between two modes would be done automagically.

The "automagical" part is the problem.  The underlying issue is two things:
1. There is no way for a console mode program to know how its display is really being rendered by whatever terminal program is displaying its content.
2. The "Enhanced default settings" in Clink uses 24 bit color definitions to improve aesthetics, but that bypasses terminal theming.

Some more feasible options:
1. Don't even attempt to figure out how the terminal will render the display, and instead always only use ANSI 4 bit color escape sequences.  (That is extremely limiting, and not very aesthetically appealing.)
2. Make "Enhanced default settings" not be the default in the installer.  (That is not great, either.)
3. Make sure all the "enhanced default settings" colors have sufficient contrast against both black and white.
4. Attempt to use console APIs to analyze the current colors and make some automatic adjustments.  (The console APIs are deprecated and are being slowly decommissioned, so they're going to stop working eventually and are not a long term solution.  Also, different terminal programs provide different implementations of the console APIs, and so that wouldn't work reliably anyway.)

**Option 3** is the most universally viable, but it won't work very well with Acrylic in Windows Terminal (it pushes colors towards low contrast versus mid-gray colors, which are often the outcome of blur effects).

Zooming out a bit -- you want Clink to automatically fit with your own defaults.  That's what I want for myself, too.  Since we use opposite background colors (white vs black), the lowest common denominator ends up being very limiting.

I'll see what can be done.  But to be fair, you are already doing custom color configuration in LS_COLORS, for example.  It's easy to do custom color configuration in Clink, and it's even easier to just delete `default_settings` and start from no custom colors at all.

### Some Technical Background Info

You might have familiarity with ANSI 4 bit versus 24 bit colors, how the Windows console rendering architecture is designed, and console APIs.

If so, here are some things to keep in mind:

- It might be possible to use [`GetConsoleScreenBufferEx`](https://docs.microsoft.com/en-us/windows/console/getconsolescreenbufferinfoex) to get information about the current 16 color palette and current default color and try to detect when the default background color is a light color.  However, it is unreliable, different terminal programs implement it differently, it is a deprecated API, and some of its sibling APIs have already been altered/disabled so it's unclear how long before this one is disabled as well.
- Windows Terminal and CMD/Clink are separate processes, with separate "Windows Theme" settings.
- Windows Terminal has multiple tabs, and different tabs can use different themes.  Clink can't know which tab it's hosted in, nor what the current configuration is for that tab.

Windows Terminal is driving towards making Windows consoles work like Linux/Unix consoles.  Do Linux/Unix have support for Light/Dark themes, and does that apply to consoles in Linux/Unix?  Some food for thought.

**Comment by chrisant996** [comment]
Unfortunately, this is [tilting at windmills](https://en.wikipedia.org/wiki/Don_Quixote#Tilting_at_windmills).

The way light themes are defined in the current version of Windows Terminal, it's not possible for colorized console mode programs to support both light themes and dark themes without manual reconfiguration and/or adding a bunch of complicated logic (which I understand isn't even possible to do in Unix/Linux because they lack a way to query the color palette).

For example, in the light themes "bold default color" is white.  So the most common way to apply color -- bold -- makes text invisible.  That's a problem in the color theme definitions, not in console mode programs.

If Windows Terminal fixes the light theme definitions, then it will become possible to have a single set of color definitions in Clink that work well in both light and dark themes.  Until then, it doesn't make sense for Clink to make complicated attempts to overcome the broader external problems.  Even if Clink introduced a complicated solution, other console mode programs would still not work in light theme (e.g. try `findstr` in light theme...).  (And it is possible that the light themes may intentionally have these problems in order to be compatible with Unix/Linux terminals and console mode programs.)

I will consider slightly adjusting Clink's color values so that _with a properly authored light theme color palette_ everything displays reasonably.  But that's the most that a console mode program can realistically do.

**Comment by alkuzad** [comment]
Thank you for this long comment on this problem :) I knew some of these problems and I know where you are coming from. There is no option for getting consistent background data and with MS migrating from ConsoleAPI to escape sequences (to match VT100). There is also no guarantee that the current API will stay in place, however even WindowsTerminal is using them. Things like cmd.exe are not likely to change and actually messing with it's colors will change behaviour of clink in WT too. I will observe how things will evolve in WT and if needed do a helper program in AutoIT or fork Clink to support this on my own. Color related code is easy enough that even if I barely can code in C++ I could do that :)

**Comment by chrisant996** [comment]
You can make custom color schemes in Windows Terminal.
You can likely save yourself quite a lot of C++ coding by:

1. Create a light Color Scheme in Windows Terminal that inverts the white and black colors, so that the effect of color escape codes upon console programs in light theme is logically equivalent to the effect in dark theme.  You might also want to swap the Normal and Bright definitions for the other 12 colors.  Something like the following, though you may want to adjust the gray levels depending on your monitor and personal preferences.
    - Normal Black = `#ffffff`
    - Bright Black = `#cccccc`
    - Normal White = `#808080`
    - Bright White = `#000000`
    - Foreground = `#808080`
    - Background = `#ffffff`
2. Set your color settings in Clink to colors you prefer better.

I don't understand why you would need to fork Clink for this or write any C++ code.  Unless you want to hard-code Clink to make assumptions about what terminal program it's running in, and how the terminal program is configured.  That could be done, but it would be unreliable.  It seems much simpler to do the 2 steps listed above.  It could take as little as 15 minutes to get that all set up, and then some additional time for fine-tuning colors, if desired.  (It's just not something Clink can do on users' behalf, due to the manual nature of step 1, and inconsistencies between various terminal programs.)

**Comment by alkuzad** [comment]
@chrisant996 as you see in my attached config gist, I do have a white theme created (Espresso Soda, really recommend ❤), there is even one built-in (Tango Light). But it won't solve the issue of switching themes. If things get too shiny really bad I can easily switch theme on the fly but clink wouldn't react to it.

**Comment by chrisant996** [comment]
> @chrisant996 as you see in my attached config gist, I do have a white theme created (Espresso Soda, really recommend ❤), there is even one built-in (Tango Light). 

My [previous reply](https://github.com/chrisant996/clink/issues/256#issuecomment-1066205816) described a **_specific way_** to make a light theme that would solve the problem.
Espresso Soda does not do it.
Nor does Tango Light.

The existing "light themes" only update **two** colors to conform to a "light theme":  the Foreground and Background default colors.  That is not enough to allow escape codes to "work as expected" in programs.  And that is what you are (rightly) complaining about.  My suggestion describes how to change **six** colors to conform to a light theme.

Consider rereading the reply carefully, and trying what it suggests.

> But it won't solve the issue of switching themes. If things get too shiny really bad I can easily switch theme on the fly but clink wouldn't react to it.

There is no way for Clink to "react to switching themes".  If you believe my statement is in error, please describe specifically how you believe it is possible, and then we can discuss it.  (I already described why the original suggestion of checking the registry doesn't really work.)
