### ISSUE TITLE
Call custom lua function from promt

### ISSUE THREAD

**Issue by sphynx79** [chrisant996/clink#274]
There is one way to call lua function that i have in my lua folder.

For example i have in fzf.lua une function "fzf_directory" then i insert in my .inputrc to call this function

"\C-A-d":        "luafunc:fzf_directory"

but i whant call directly from promt without use shortcut
Thanks

**Comment by chrisant996** [comment]
I don't understand yet, can you explain more what you want to do?

Are you asking how to customize the prompt?

https://chrisant996.github.io/clink/clink.html#customizing-the-prompt

**Comment by sphynx79** [comment]
No I want to call my lua function from command line, without shortcut but directly

Example in command line:
:luafunc:fzf_directory
And this call lua function fzf_directory

**Comment by pukkandan** [comment]
So basically this? https://github.com/chrisant996/clink/issues/205#issuecomment-980508800

**Comment by chrisant996** [comment]
Running a Lua function at the prompt must be just a step in something larger.  What is the overall thing you are trying to accomplish?

Running a `fzf_directory` Lua function by typing it into the command line would show the fzf program, let you pick a directory...  And then do nothing with the result.  I don't understand what is the purpose of choosing a directory, and doing nothing with it.

But [#230 luaexec.lua](https://github.com/chrisant996/clink/discussions/230) has a script that lets you invoke Clink Lua functions (or expressions) by typing them at the command line.  I don't think it's going to accomplish what you're expecting, though.  Please explain the larger thing you're trying to accomplish, so that the best suggestions can be offered.

**Comment by sphynx79** [comment]
In this way I can create advanced commands and use lua instead of bash file or other scripting language like .bat file.

Also I can  debug my function  from the prompt without creating a shortcut just for test my script.

Per esempio adesso mi sono creato questo file .bat:

```
@echo off

if "%~1" == "" (
  set word=".*"
) else (
  set word=%~1
)

FOR /F "tokens=* usebackq" %%t IN (`tac %cmder_root%/config/clink_history ^
  ^| grep -iE %word% ^
  ^| fzf --no-sort`) DO %cmder_root%\vendor\git-for-windows\usr\bin\echo.exe -n '%%t' | clip

```
I could create a similar thing in lua, and create an alias that calls me this function to filter my history with fzf and print the result on the command line or run the command directly.

By the way I have another question how can I redirect the output of a script to my prompt

![image](https://user-images.githubusercontent.com/5004160/164749858-46124e5d-331c-48a5-ae41-6ec9fa6a38d8.png)


Whow can i put output here
![image](https://user-images.githubusercontent.com/5004160/164750157-a26aff5d-c074-464c-b0db-8866100712f4.png)

**Comment by chrisant996** [comment]
> In this way I can create advanced commands and use lua instead of bash file or other scripting language like .bat file.

Oh, I see.  You simply want to use Lua as a scripting language for writing and running programs.

Then you should use a standalone Lua interpreter.  See [LuaBinaries](http://luabinaries.sourceforge.net/) for where to download installations of Lua for Windows.

Here is why you don't actually want to run Lua scripts within Clink itself:  the Clink Lua interpreter stays running the entire time the console is open.  So, running other Lua programs inside the Clink Lua interpreter would allow the other Lua programs to interfere with Clink -- and vice versa, Clink's own Lua state and variables would interfere with the other Lua programs.

> Also I can debug my function from the prompt without creating a shortcut just for test my script.

I understand the intended convenience, but it doesn't really work out that way, because of the above.  You should instead use a standalone Lua interpreter, and you can load a debugger in it, etc.

> By the way I have another question how can I redirect the output of a script to my prompt

Are you asking how to customize the prompt?

https://chrisant996.github.io/clink/clink.html#customizing-the-prompt

**Comment by sphynx79** [comment]
Yes but with standalone Lua interpreter i can't interact with clink.
No i don't want customizze the prompt but print the output the bat result in command line.
For example make bat that use fzf for search in History, and print  my choise in the same position when i start the bat file.
In this way i can search in history chose the command and after press enter for lauch the command.

**Comment by chrisant996** [comment]
> No i don't want customizze the prompt but print the output the bat result in command line. 

I see.  What you mean is not "printing the output", but instead "inserting into the line editor".

> For example make bat that use fzf for search in History, and print my choise in the same position when i start the bat file. In this way i can search in history chose the command and after press enter for lauch the command.

I think you are saying the following:

1. You want to type out names of script files, and type out arguments to them, instead of pressing short key bindings.
2. You want to press Enter, and then:
  - Have the input line erased, _without_ starting a new prompt line.
  - Run the named Lua script.
  - Capture its output via redirection.
  - Insert the captured output into the line editor, _without_ starting a new prompt line.

You could make your own Lua function to replace the `accept-line` command and bind it to <kbd>Enter</kbd>.  Your function could parse the command line and decide whether to treat it as a request to run a Lua script:  if yes, load and run the script`*`; if no, use `rl.invokecommand("accept-line")` to invoke the normal <kbd>Enter</kbd> behavior.

But, why do you want to avoid using key bindings?  Can you please describe the motivation behind why you want to type out Lua function names as though they external programs, instead of just binding them to a key?


`*` there is a significant problem with this.  If you run a function that's already been loaded, then ok.  But if you load and execute a new script, then that script _stays loaded_.  And if you run it again, it will load _another copy_ of the script.  Because Clink is not a standalone Lua interpreter.  What you're describing is intentionally not how Clink works, and is not really compatible with Clink.  You can force it to happen, but there are side effects and earlier invocations can potentially interfere with later invocations, and memory consumption will grow without bound, and so on.  So it would be helpful to understand the motivation behind wanting this.

**Comment by chrisant996** [comment]
@sphynx79 if you can share more info then we can consider alternative options and reopen the issue.  In the meantime, I am closing the issue.
