### ISSUE TITLE
clink.1.3.16.023688 git status color disappear

### ISSUE THREAD

**Issue by zxyqq** [chrisant996/clink#279]
when I use clink.1.3.12.f70397, git status will color the add or changed files.
while update to clink.1.3.16.023688, git status color disappear.

**Comment by chrisant996** [comment]
Can you clarify the statement?
Can you show screenshots?

Are you saying that when you type `git status` and <kbd>Enter</kbd> to execute a git command, then the git program's output is somehow affected by Clink?  Git is a separate program.

Are you saying that you have a custom prompt script, and the prompt script internally runs `git status`, and the prompt script no longer applies color in the prompt?

Please help me understand what is being described.
Thanks for reporting this!

(I can't reproduce any changes in `git status`, nor in custom prompt behaviors.)

**Comment by chrisant996** [comment]
@zxyqq please clarify.

**Comment by chrisant996** [comment]
@zxyqq Hello?

**Comment by zxyqq** [comment]
I upgrade clink to the lastest version, now it is fixed .so close this issue

**Comment by chrisant996** [comment]
@zxyqq I'm glad you got it working again.  But I think you must be using a third party terminal program, and the terminal program must have some problem showing colors in some cases.  The only changes in Clink v1.3.17 are (1) to fix a problem where v1.3.16 thought the terminal screen was taller than it really was, and (2) fix which filenames are considered executable.

Since this issue contains no details, and the questions haven't been answered, I must mark this External as being unrelated to Clink.
