### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by KAXB** [chrisant996/clink#288]
Im using this program and there is something wrong with it. My computer default path turned into"?[?25l?[0 q?[?25hC:\Users\Administrator>?[m?[0 q?[?25h".May be I should try adjusting the font or encoding,but I dont know how to do it

**Comment by Akiira** [comment]
Just taking a guess here but those are clearly ansi escape sequences, so maybe your console doesnt support ansi? If you are just using the native windows console you could try `ConEmu` or the new windows terminal and see if that helps.

**Comment by chrisant996** [comment]
Those escape sequences are only used when Clink believes it is running inside Windows Terminal.  Windows Terminal supports those escape sequences.

So, why does Clink think it's running inside Windows Terminal when it actually isn't?

Maybe you started a program from Windows Terminal, and then a "normal" standalone console window got started by that other program, but the Windows Terminal environment variables have been inherited when launching the other programs, and thus downstream Clinks are tricked into thinking they're inside Windows Terminal.

Windows 10 understands those escape sequences even outside of Windows Terminal, but older versions of Windows might not.

You can disable that behavior via `set WT_PROFILE_ID=` and `set WT_SESSION=` in the affected cmd window (you could put then in a batch script, if needed).

### Here is the problem:

1. Windows Terminal does not support the Windows APIs for controlling the blinking cursor.  The only way to control the cursor is with escape sequences (without having undesirable side effects).
2. There is no reliable way to detect whether Clink is running inside Windows Terminal.  The recommended approach is to check for `%WT_SESSION`, but that is unreliable because the environment is inherited when launching new processes.

I will try to see if there's a way to examine the process tree (without requiring administrator elevation) to deduce whether Clink is running inside Windows Terminal.  E.g. trying to check whether conhost.exe or OpenConsole.exe are associated with the current cmd.exe process.

**Comment by chrisant996** [comment]
Also, see [Terminal Support](https://chrisant996.github.io/clink/clink.html#terminal-support) in the Clink documentation.

You could try something like this:

```cmd
set CLINK_TERMINAL_VE=\e[m
set CLINK_TERMINAL_VS=\e[m
```

to essentially make the cursor control sequences have no effect.

**Comment by chrisant996** [comment]
@KAXB can you confirm?

Does the problem only occur if you start Windows Terminal, then launch a program from Windows Terminal, and then from the launched program launch another command shell that doesn't use Windows Terminal?

Or can you share more details about the steps to reproduce the problem?
