### ISSUE TITLE
Feature request: Automatic tilde (~) replacing

### ISSUE THREAD

**Issue by NotSpaulding** [chrisant996/clink#289]
I would love if Clink could replace all tildes (`~`) with `%USERPROFILE%` automatically, not making you press <kbd>alt</kbd>+~ (if expand-tilde is enabled). Preferably this would be done after the command is written and "sent", so it's transparent to the user that `~` got replaced in the first place.

**Comment by chrisant996** [comment]
> I would love if Clink could replace all tildes (`~`) with `%USERPROFILE%` automatically, 

To clarify -- by "all", you mean "any `~/` or `~\` at the beginning of a word".

> not making you press alt+~ (if expand-tilde is enabled). 

Do you know about `expand-tilde` and completion commands automatically expanding tilde?

If `expand-tilde` is enabled, then completion commands automatically expand tilde.  Is it common to type out path names that start with tilde, without ever using completion?  I wonder if turning on `expand-tilde` in the inputrc file might be good enough.

I hesitate about automatically replacing tilde because if tildes are automatically converted then it becomes impossible to specify any non-filename argument that starts with tilde.  Also, since tilde is not a supported pathname component in Windows, it is perfectly valid to have directories and filenames that start with tilde in Windows.  If tildes are always automatically expanded, then it becomes impossible to refer to those directories or files -- while not a common thing, the fact it becomes impossible is a concern.

*nix shells do not expand tilde.  The OS itself recognizes tilde as a pathname component.  So if the tilde is not part of a filename, then because the shell doesn't actually know anything about tilde, the tilde is interpreted correctly no matter what.  Clink cannot duplicate that kind of behavior, because the Windows OS does not recognize tilde as a pathname component.  Clink doesn't know whether a word in a command line will be ultimately interpreted as a filename or as something else -- *nix shells don't know either, but they don't do any tilde processing at all, so it isn't a problem there.

> Preferably this would be done after the command is written and "sent", so it's transparent to the user that `~` got replaced in the first place.

If it were to be done, then yes, definitely.

**Comment by NotSpaulding** [comment]
> To clarify -- by "all", you mean "any `~/` or `~\` at the beginning of a word".
I was thinking it would be replaced when not in a string ie when not surrounded by single or double quotes (`'`/`"`); but there might be a better way to do this.

> Do you know about `expand-tilde` and completion commands automatically expanding tilde?
I tried doing that, yet it didn't seem to work; could you perhaps provide an example? I might be misunderstanding.

>  Is it common to type out path names that start with tilde, without ever using completion?
Not that common, but I still do it occasionally which would be nice to keep.

> I hesitate about automatically replacing tilde because if tildes are automatically converted then it becomes impossible to specify any non-filename argument that starts with tilde.
Yeah I thought about that, I forgot to specify in my original statement that tildes not surrounded by quotes would be replaced, which I think would solve the problem. If not, I think it would be easy enough to add an escape character, although not as convenient, it would have to be done. I also know that PowerShell can use tildes in commands with as far as I know, no issues, so maybe you can do what PowerShell does?

**Comment by chrisant996** [comment]
> > To clarify -- by "all", you mean "any `~/` or `~\` at the beginning of a word".
> 
> I was thinking it would be replaced when not in a string ie when not surrounded by single or double quotes (`'`/`"`); but there might be a better way to do this.

That would lead to complaints that tilde expansion doesn't happen for quoted file names.

> > Do you know about `expand-tilde` and completion commands automatically expanding tilde?
> 
> I tried doing that, yet it didn't seem to work; could you perhaps provide an example? I might be misunderstanding.

What did you try, specifically?

Have you referred to the [Init File](https://chrisant996.github.io/clink/clink.html#init-file) section of the documentation?  That's where I've provided examples for setting the various Readline config variables such as `expand-tilde`.

> I also know that PowerShell can use tildes in commands with as far as I know, no issues, so maybe you can do what PowerShell does?

Funny you should mention that.  In fact, Clink does exactly what Powershell does.  But you have to remember that Powershell is a _shell_ and Clink is not a shell -- for Clink the shell is `cmd.exe`, and cmd.exe does not expand tildes, and so unlike a shell, Clink doesn't know which words are filenames versus text arguments.

Powershell expands tildes when completion is used.  And the Powershell scripting language is a language -- when pathnames are given to Powershell commands or applets, then the Powershell API layer knows the string is a pathname and performs tilde expansion.  But if you run a command that is not a Powershell, then tildes are not expanded because Powershell is not involved.

You can see for yourself.
Start Powershell and create a file via `echo hello > ~\xyzzy` and then do the following:

- `ls ~` interprets the tilde as a the home dir, because `ls` is a Powershell applet.
- `more ~\xyzzy` prints the file you created, because `more` is a Powershell applet.
- `more.com ~\xyzzy` fails because `more.com` is the actual `more` program that is used outside of Powershell when invoking `more`, and since it is not part of Powershell, no tilde expansion happens.
- `git diff --no-index ~\xyzzy ~\xyzzy` reports an error, because git is not a Powershell applet, so no tilde expansion happens.

### Conclusion

- The request is understandable.
- Because Clink is not actually a shell, it is just a glorified input line editor, Clink can't do what's requested in any reliable way.
- Powershell is both an input line editor and also a shell -- so Clink's input line editor and Powershell's input line editor are both able to perform tilde expansion when completion is used.  But since Powershell is a shell, it can also do tilde expansion when shell scripting language APIs are invoked, but Clink cannot.

**Comment by NotSpaulding** [comment]
> That would lead to complaints that tilde expansion doesn't happen for quoted file names.

I rarely need to quote file names and such, especially when moving to my home directory, but I guess it could lead to inconsistencies which wouldn't be very nice.

> What did you try, specifically?
>
> Have you referred to the [Init File](https://chrisant996.github.io/clink/clink.html#init-file) section of the documentation? That's where I've provided examples for setting the various Readline config variables such as `expand-tilde`.

I have, I just set expand-tilde to on in `%USERPROFILE%\.inputrc`, I don't think I did anything wrong there, maybe I'm just misunderstanding how `expand-tilde` works exactly. I'll figure it out

> when pathnames are given to Powershell commands or applets, then the Powershell API layer knows the string is a pathname and performs tilde expansion. 

Oh, that's interesting, I was not aware of that, so I guess the PowerShell approach wouldn't work.

---

I was just wondering if you could make a lua script with the "specs" I mentioned (I would, but I don't know anything about lua programming), I want to see if my approach would somewhat work, if not see how unreliable it really is. Just to reiterate:

Tildes (`~`) not in quotes (`'`/`"`), would be replaced with `%USERPROFILE%` when the command is sent, so the user doesn't even see that the tilde even got replaced in the first place.
Another idea I had is tildes would always be replaced, even if they're surrounded by quotes; unless there's an escape character before them (such as \`), That might work better and more reliably than the string approach, so I think you should also take that into consideration.

**Comment by chrisant996** [comment]
I'm reluctant to build that into Clink because of the inconsistencies.

You can make a tiny Lua script to do it, though.

See the docs for `clink.onfilterinput()`.

**Comment by NotSpaulding** [comment]
Alright, I understand, thanks for your consideration and your help!

**Comment by chrisant996** [comment]
Just to be clear: you can write a short Lua script that does exactly what you're suggesting. `clink.onfilterinput()` lets you adjust the input line (after updating history, but before being executed by cmd.exe).

**Comment by chrisant996** [comment]
The [clink-gizmos](https://github.com/chrisant996/clink-gizmos) repo contains a `tilde_autoexpand.lua` script which performs automatic expansion of tildes.  It also highlights which tildes will be auto-expanded.  And you can use `~~` which gets translated into a plain tilde instead of auto-expanding, and it also highlights the `~~`.  The colors are configurable, and the `~~` string is configurable.
