### ISSUE TITLE
Colored completions are gone

### ISSUE THREAD

**Issue by thorstenkampe** [chrisant996/clink#29]
Colored completions (see below) were working in version 1.0.0.a1 (before the fork). Are they "gone" are work in progress?

![image](https://user-images.githubusercontent.com/475462/101986663-753f3a80-3c8f-11eb-8ca4-fa295b8f86ac.png)

**Comment by chrisant996** [comment]
They're much more sophisticated now, thanks to Readline v8.0.  They're off by default, though.  You can turn it on with the `colored-stats` and `colored-completion-prefix` config variables in the `.inputrc` file.

See these sections in the [Clink documentation](https://chrisant996.github.io/clink/clink.html) for more information:
- [Configuring Clink](https://chrisant996.github.io/clink/clink.html#configuring-clink)
- [Color Settings](https://chrisant996.github.io/clink/clink.html#color-settings)
- [Completion Colors](https://chrisant996.github.io/clink/clink.html#completion-colors)

I think it's appropriate for match coloring to be off by default so that one has the opportunity to configure the colors before getting hit with them.
