### ISSUE TITLE
Autocomplete with argument replacement

### ISSUE THREAD

**Issue by 0xCCh** [chrisant996/clink#293]
I did not find in the documentation how to make autocomplete with an argument replacement.
For example:
```
# test [ctrl+space]
--param_1 	Specify a
--param_2	Specify b
```

`# test param_1 123 `
and this command was automatically replaced by
`# test --a -some_param_1 123`

```
# test param_2 321
# test --b --c --some_param_2 --asd:321
```
Something like that. Is it possible to do this with lua?

**Comment by chrisant996** [comment]
I am having trouble understanding what is being requested.

I think you want to type `test param_1 123`, and then somehow "automatically" the input line will be replaced by `test --a -some_param_1 123`.

I don't understand what the "automatic" trigger is.  Is it pressing <kbd>3</kbd>?  Is it no further input for a few seconds?  Is it pressing <kbd>Enter</kbd>?

I don't understand what is being proposed for how `param_1` would be transformed into `--a -some_param_1`.

Can you clarify?

**Comment by chrisant996** [comment]
Ok, I understand now, thanks.

What if someone types `nmap -Q -g 100 blahblah f`<kbd>ctrl</kbd>-<kbd>space</kbd> and chooses `full`?
Which of these do you expect to happen:
1. Replace `f` with `-sS -T4 -PE ...` so that the input line becomes `nmap -Q -g 100 blahblah -sT -T4 -PE ...`?
2. Erase the whole command line and replace it with `nmap -sT -T4 -PE ...`, losing the `-Q -g 100 blahblah` part?

Neither of these are completion, and you won't be able to use completion to accomplish either of them.  Completion finishes typing something for you; it doesn't delete what you typed and replace it with something else.

If you use `menu-complete` as the completion command, then it becomes more clear why not:  `menu-complete` cycles through the available completions.  But none of `open_ports` or `full` or `fin` are completions -- you don't want those words to ever show up in the final command line.  If `menu-complete` expands `full` to `-sT -T4 -PE ...` then the second time you use `menu-complete` the whole command line has changed already, which resets `menu-complete` to start over at the first match.

But, there are other things you could do.
Here are a couple of examples:

- You could make a [`luafunc:`](https://chrisant996.github.io/clink/clink.html#luakeybindings) macro to invoke a function that uses [clink.popuplist()](https://chrisant996.github.io/clink/clink.html#clink.popuplist) to show a list of options.  You could make the function know about `nmap` and other commands.  You could make the function filter based on what has been typed.
- You could make a script that uses [clink.onfilterinput()](https://chrisant996.github.io/clink/clink.html#clink.onfilterinput) to parse the input line.  It could look for "nmap full" and replace it with `nmap -sS -T4 -PE ...`.  And then you could use completion to choose "open_ports" or "full" or "fin", and when you press <kbd>Enter</kbd> then the onfilterinput would modify the input line -- but you wouldn't see the `-sS -T4 -PE ...` part on the screen, ever (which might be fine, since you don't see them when you type `nmap_full`, either).

**Comment by chrisant996** [comment]
Here is a sample script that illustrates the two alternative options mentioned previously.


**example.lua**
```lua
--------------------------------------------------------------------------------
-- Completion and onfilterinput

clink.argmatcher("nmap")
:addarg("open_ports", "full", "fin")
:nofiles()
:adddescriptions(
    { "open_ports", description = "Scan all open ports" },
    { "full",       description = "Full scan" },
    { "fin",        description = "Fin scan" }
)

local function issue293_replace(line)
    if not line:find("^[ \t]*nmap ") then
        return
    end

    local ret
    if line:match("^[ \t]*nmap open_ports") then
        ret = "nmap fill this in"
    elseif line:match("^[ \t]*nmap full") then
        ret = "nmap -sS -T4 -PE ..."
    elseif line:match("^[ \t]*nmap fin") then
        ret = "nmap fill this in"
    else
        return
    end
    return ret, false
end

clink.onfilterinput(issue293_replace)

--------------------------------------------------------------------------------
-- Popup list

function issue293(rl_buffer, line_state)
    local sel
    local spaces, command = line_state:getline():match("^([ \t]*)([^ \t]+)")

    if command == "nmap" then
        sel = clink.popuplist("nmap", {
            { display="open_ports", value="nmap fill this in", description = "Scan all open ports" },
            { display="full      ", value="nmap -sS -T4 -PE ...", description = "Full scan" },
            { display="fin       ", value="nmap fill this in", description = "Fin scan" },
        })
    end

    if sel then
        local info = line_state:getwordinfo(1)
        rl_buffer:beginundogroup()
        rl_buffer:remove(1, -1)
        rl_buffer:insert(spaces)
        rl_buffer:insert(sel)
        rl_buffer:endundogroup()
    else
        rl_buffer:ding()
    end
end

rl.setbinding([["\eq"]], [["luafunc:issue293"]])
```
