### ISSUE TITLE
History in the prompt

### ISSUE THREAD

**Issue by jtsage** [chrisant996/clink#294]
Good day - I am tearing my hair out a bit trying to figure out how to (or if it's even possible) to add the history number to the prompt.

As an example, what I want is:

![2022-05-30 13_45_20-Issues · chrisant996_clink](https://user-images.githubusercontent.com/605986/171040689-681d4f29-6edc-4481-98eb-df19c2376046.png)

And what I have is:

![2022-05-30 13_45_34-Issues · chrisant996_clink](https://user-images.githubusercontent.com/605986/171040672-70d54a97-d5f0-4be2-91d8-fcd6b1b600e8.png)

The "::7" is the pty number, not really applicable to a windows system, but the "!513" is the _next_ history entry number (a.k.a. what this command will be entered as, if it is not ignored)

For the life of me, I can't seem to find this info anywhere - is it as simple as counting lines in the history file?

Thanks much!

**Comment by chrisant996** [comment]
I would not recommend manually counting lines:
1. Lines that start with `|` are marked for deletion and are not counted by Clink.
2. I may add timestamps into the history file, and that would further throw off a manual counting approach.
3. Depending on the `history.shared` and `history.save` settings, there may or may not be a `clink_history` file and there may or may not be a `clink_history_`**_pid_** file.
4. There may also be a `clink_history_`**_pid_**`.removals` file, which indicates removed entries that haven't yet been merged back into the master `cilnk_history` file.
5. The master history file might not even be `clink_history` if for example `%CLINK_HISTORY_LABEL%` is set.

You could use `clink history 1` to report the last history item.  But that spawns a separate process to read the entire history file(s), so it's not super efficient (though it will probably be very fast because disk caching will keep it in the hot cache).  You can use `os.getalias("clink")` to get the full path to the clink exe to invoke.

I'll consider adding some `rl.` functions to report the number of history items and perhaps gain access to history items, as well.

**Comment by jtsage** [comment]
Thanks so much for the info.  I did indeed grab the alias, then the output of `clink history 1`, chopped the leading number off, added 1, and got:

![2022-05-30 22_16_41-jts_prompt lua - fs2022_workspace (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/605986/171079696-6ae7925b-c231-4791-ba94-8a3288d623bf.png)

I have no idea how I had never heard of this project before - nice work - it really makes life nicer!

**Comment by chrisant996** [comment]
Added `rl.gethistorycount()` and `rl.gethistoryitems()` in commit e5114951900b5e7b626595c0341fcfd30469ac1f.

For e.g. writing history items to `fzf` it's probably easier and higher performance to invoke `clink history`, but for something like just getting the count or a few history items the new Lua APIs will be faster and much more convenient.
