### ISSUE TITLE
Alt-C does not capitalize words

### ISSUE THREAD

**Issue by boriskro** [chrisant996/clink#295]
Alt-C key stroke (capitalize-word) seem to have no effect. It was working in  0.4.9. Alt-U and Alt-L work fine however. Any idea what might be wrong?

**Comment by chrisant996** [comment]
Martin introduced <kbd>Alt</kbd>+<kbd>c</kbd> being bound by default to `clink-copy-cwd` in the v1.0.0 rewrite.  It's been that way for 6 years in the code, and has been released that way for 20 months in the new Clink fork.  No one else has commented about <kbd>Alt</kbd>-<kbd>c</kbd> no longer being bound to `capitalize-word`, so I think there is greater risk in changing it back at this late date.

Clink is designed to be configurable.  Would you consider adding a line to your `.inputrc` file to bind `"\ec": capitalize-word`?  For more information on how to configure Clink see [Configuring Clink](https://chrisant996.github.io/clink/clink.html#configuring-clink) and [Configuring Readline](https://chrisant996.github.io/clink/clink.html#configreadline) and [Customizing Key Bindings](https://chrisant996.github.io/clink/clink.html#customizing-key-bindings).

**Comment by boriskro** [comment]
Thank you for the quick response. I think clobbering an existing binding was a mistake. And I do not think remapping `clink-copy-cwd` to a different key is a significant risk.  `M-c` is a part of the popular Emacs binding scheme along with `M-u`, `M-l` etc. It is a default in many environments that make use of the getline library on various systems.  It is also widely used in text editors that have Emacs emulation, and of course by Emacs itself. I imagine many people have muscle memory for these things, but the issue is just too minor or not irritating enough to warrant opening a ticket.

I already fixed the issue locally by overriding it in my inputrc, so it is no longer a problem for me. Fixing the documentation is an okay course of action, but I hope you reconsider :)

**Comment by chrisant996** [comment]
Martin may or may not have made a mistake 6 years ago when he changed the key binding for Alt+C.

But, you're the only person to call this out. One complaint in 6 years (or even 2 years) is not a strong indicator of a mistake.

Can you explain why `capitalize-word` is a frequent part of editing a command line in Windows? I've never even wanted to do that in decades. So I'm interested to understand why capitalizing a word is considered to be a big mistake to not have the same key binding as in emacs (which isn't used that much overall on Windows, though it's used much more in *nix environments).

If you can help me understand the severity, it would help me to evaluate whether to revoke the change Martin made.

But, consider that if I did, then anyone who has found the Alt+C binding useful for copying cwd to the clipboard will then likely complain about how removing that is a mistake instead.

There is more than one perspective here, and this charge predates me by about 4 years. I would encourage to consider multiple perspectives.

**Comment by chrisant996** [comment]
> Sure, I use Mac/Linux/Windows on daily basis. And so far, the basic line editing experience has been incredibly consistent thanks to clink. I believe text navigation and manipulation is one of the clink's defining features. Other features are great, but text editing falls in the top three. I was on 0.4.9 up until very recently, and I have been a very happy user for the last 8 years or so. When I switched to 1.3 a few days ago, I immediately noticed the change. Why would one want word capitalization on Windows? Lots of things you type on the command line are still case sensitive. E.g. when you want to fix a search pattern `grep foo *` -> `grep Foo *`, it takes three keystrokes: `C-a`, `M-f`, `M-c`. It is just basic flow that works everywhere. And you do not think much about it until it stops working.

Thanks, that helps me understand.  The scenario is "people who use Emacs key bindings in all/most console programs, will automatically expect that if most other Emacs key bindings work then also Alt-C will, if they happen to be people who use Alt-C".  That makes a lot of sense, thanks.

> As far as emacs emulation not being very common on Windows, that's not quite true. A lot of shell-like prompts have it on by default: Python (ipython), Ruby (irb), Haskell (ghci). Many major text editors have Emacs emulation, although that's not the default, e.g. both VSCode and Visual Studio have it. But I do agree that among _Windows-only_ users 90% would not care. For multi-OS users this percentage might be reverse: 90% probably would care.

I wouldn't have replaced Alt-C, because it is related to Alt-U and Alt-L.  But Martin did, many years ago.  No one has noted the change until now.  One complaint isn't enough to convince me to change it **_for everyone_**, especially when it would replace the key binding for "copy cwd to clipboard" which is easy to imagine people may have become happy about in the meantime.

Yes, you're describing that Alt-C is available in various places.  That's very true.  People who use those places may or may not know about the Emacs key bindings and may or may not use them.  I'm wondering how much Alt-C is actively _used_ on Windows, and I'm wondering how great a percentage of _overall CMD.exe users_ overlap with the various places you mentioned where Alt-C is available by default.

If 90% of multi-OS users care about Alt-C, then why hasn't anyone complained about this in the past few years?  It suggests to me that either (1) many people don't care that much about Alt-C for capitalizing the current word or (2) some people who care about it almost never use it and didn't consider it worth reporting or (3) there aren't many multi-OS users of Clink or (4) that the 90% guess is skewed by subjective bias.

I have limited data to go on, but there is only 1 data point so far supporting Alt-C being important to change, and 1 data point is usually not sufficient to justify making a change that affects _all users_.
