### ISSUE TITLE
clink cannot exit normally since clink.1.3.14.626b2b

### ISSUE THREAD

**Issue by fcying** [chrisant996/clink#296]
In my one computer(A winver: win10 21H2 19044.1706), clink cannot exit normally since clink.1.3.14.626b2b

click `clink.bat`
click close button, get a error message. work fine with `clink.1.3.13.24b02e`.

![image](https://user-images.githubusercontent.com/106934/172138624-46f6c1fe-71b6-4b68-8cfe-ea8eede42cec.png)

new clink version work fine in another computer(B), B have the same winver with A, but not antivirus software installed(doubt this is the reason), but A's antivirus software is installed by company IT. I have no permission stop it, Is there another way to debug?

**Comment by chrisant996** [comment]
If it is a crash, can you look in the eventvwr and find the Application Error and the `.dmp` file containing the crash details, and upload it here in a `.zip` file?

**Comment by chrisant996** [comment]
I don't know why it would take too long to exit.  When I use the a debugger to examine what happens, Clink isn't involved in the exiting when the close button is clicked.  So I'll need some help to understand what is happening on your computer.

You can capture a debugging dump file by starting Task Manager, and right click on the appropriate `cmd.exe` process, and choose "Create dump file" (I don't know that will be in Chinese).  After saving a `.dmp` file, you can put it in a `.zip` file and upload it, and then I can examine the dump file to see what is happening.

**Comment by fcying** [comment]
I upload two dmp file(use clink 1.3.13 and 1.3.18)

1. click `clink.bat`
2. use Task Manager choose cmd.exe Create dump file
3. click close button.

[1.3.13.zip](https://github.com/chrisant996/clink/files/8849277/1.3.13.zip)
[1.3.18.zip](https://github.com/chrisant996/clink/files/8849286/1.3.18.zip)

**Comment by chrisant996** [comment]
Thanks - the dump needs to be created after pressing the close button, after the message box appears. So that the dump contains the failure situation, so that it can be analyzed.

**Comment by chrisant996** [comment]
@fcying Can you please save a dump file after clicking the close button? That should reveal what happened.

The dumps you uploaded were saved before the error, and so they don't reveal what happened.

**Comment by fcying** [comment]
Sorry I missed the message...

1. click clink.bat
2. click close button, jump error dialog
3. openTask Manager, choose cmd.exe, Create dump file

[cmd_1.3.18.zip](https://github.com/chrisant996/clink/files/8865906/cmd_1.3.18.zip)

**Comment by chrisant996** [comment]
@fcying The latest dump is captured perfectly, thank you.  The dump shows that the close button was clicked (doing that sets a global variable, and the global variable is indeed set).

But obviously Windows didn't actually terminate the CMD process.  That's supposed to be impossible; the OS forcibly closes console programs when the close button is clicked, within 5 seconds, no matter what.  And Clink isn't doing anything to try to interfere with that.

Clearly something is going wrong, but I can't see what.

Can you try capturing a Time Travel Debugging trace?
1. Install [WinDbg Preview](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/windbg-install-preview) and then,
2. Use [Time Travel Debugging](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-record#attach-to-a-process) to capture clicking the close button.
    - Launch Clink.
    - Follow the Time Travel Debugging directions for "Attach to a process" and attach it to the CMD.EXE process.
    - Click the close button.
    - Put the resulting `.run` file in a `.zip` file and upload the `.zip` file here.

That will capture much more detail about what's going on.  Normally a Time Travel Debugging trace file is able to reveal precisely what is happening and why.  However, in this case there is a possibility that it's going wrong inside the OS itself, or in an interaction with another process, and if that's the case then Time Travel Debugging won't be able to help much because it can't capture those.

P.S.  Also, I found a mistake in the ^C and ^Break support that was added in v1.3.14:  Clink forgot to restore normal ^C and ^Break behavior when a command is invoked.  So e.g. ^C during `dir /s` wasn't interrupting the dir command.  I've fixed that, now.  It should be unrelated to what you're experiencing, but there is a very small chance that [v1.3.19](https://github.com/chrisant996/clink/releases/tag/v1.3.19) might improve it.

**Comment by fcying** [comment]
test with v1.3.19
1. Launch Clink.
2. Attach to a process and record with Time Travel Debugging
3. click close btn.
4. stop record and stop debug
[cmd01_out.zip](https://github.com/chrisant996/clink/files/8867374/cmd01_out.zip)
[cmd01_idx.zip](https://github.com/chrisant996/clink/files/8867375/cmd01_idx.zip)
[cmd01_run.zip](https://github.com/chrisant996/clink/files/8867378/cmd01_run.zip)

**Comment by chrisant996** [comment]
@fcying, Perfect, thank you.

I captured a TTD trace for the same on my computer, where the CMD window closes successfully and immediately.
I compared the two traces.
They are identical. 😢
In both, Clink immediately responds.

This suggests that there may be some other software installed that is somehow participating/interfering with console termination.

### Speculative fix

I've made a speculative change that may or may not resolve the issue.
Please try this pre-release version:  [clink.1.3.20.74e091.zip](https://github.com/chrisant996/clink/files/8872297/clink.1.3.20.74e091.zip)

If that resolves the issue, then great, and there has to be either an OS bug (unlikely) or some other software that is interfering with console termination.

### If that doesn't fix it

If that doesn't resolve the issue, then my next troubleshooting idea would be:  Can you use [`pslist -t`](https://docs.microsoft.com/en-us/sysinternals/downloads/pslist) after pressing the close button, to get a list of processes, in tree form?  The tree allows us to infer which other processes may be attached to the same console.  If there are any other processes attached to the same console, then they _also_ receive the CTRL_CLOSE_EVENT, and if they are slow to respond then that can trigger the kind of message you're experiencing.

### Details from the TTD traces

Here is the analysis from the TTD traces, in case that's interesting:

Pressing Ctrl-C or Ctrl-Break or the close button causes the OS to inject a new thread into the process.
The new thread runs any "CtrlHandler" functions registered in the process.
In both traces, Clink's handlers are executed, do exactly the same thing -- which is basically nothing, since they don't care about the CTRL_CLOSE_EVENT, they only care about CTRL_C_EVENT and CTRL_BREAK_EVENT.
They return into OS user mode code for `kernelbase!CtrlRoutine` which is the OS function that the injected Ctrl event thread runs.
MSDN [documentation for CtrlHandler routines](https://docs.microsoft.com/en-us/windows/console/handlerroutine) says the OS terminates the app after the last CtrlHandler routine runs, regardless what it returns.
The CtrlRoutine code returns back to the BaseThreadInitThunk OS function that called it.
The BaseThreadInitThunk function reaches its end and calls RtlExitUserThread to end the thread.
The RtlExitUserThread function calls NtTerminateThread.
The NtTerminateThread function uses `syscall` to transition to kernel mode.
In both the failure trace and the successful trace, that is the last instruction recorded in the trace.
As I mentioned earlier, TTD is not able to capture kernel mode operations; whatever happens next is happening in kernel mode, and is not visible to us.

**Comment by fcying** [comment]
v1.3.20 work fine, When I click the close button, it's close immediately, thanks~~

**Comment by chrisant996** [comment]
Excellent! Soo strange... Either there is an OS bug, or there is interference from an external program -- probably the latter.

**Comment by chiwou** [comment]
> Excellent! Soo strange... Either there is an OS bug, or there is interference from an external program -- probably the latter.

the new version also "fixed" the virus detection in windows
