### ISSUE TITLE
Coroutine failure

### ISSUE THREAD

**Issue by u01jmg3** [chrisant996/clink#305]
Since updating to `v1.3.23` (I think), I've starting seeing the following:

<img width="220" alt="clink" src="https://user-images.githubusercontent.com/1266205/174404725-70627a09-a8dc-4b4c-9076-199ae6e29ab1.png">

Steps:
1. Open console
2. Start typing `git`
3. Arrow right to select suggested command from history

Note: clink has not crashed my console and the command executes. It is not limited to this suggestion alone. `v1.3.24` has the same issue.

**Comment by chrisant996** [comment]
You can make it go away by running `clink set lua.debug false`.

In v1.3.23 it started showing Lua errors inside coroutines when debug mode is enabled.

I'll try to find how to reproduce it.

**Comment by chrisant996** [comment]
@u01jmg3 I can't reproduce this.  

It looks like you have a custom prompt script, and maybe other scripts.  It could be that one of the scripts is revealing a bug in Clink (the fact that the error location is `?:0` indicates the error is happening in Clink's built-in Lua scripts).

Would it be possible to make a .zip file containing all your Lua scripts, plus the output from `clink set`, plus your `clink_history` file, and email it to my profile address?  (Or you can post it here if you feel comfortable with posting that info publicly -- your command history might potentially contain sensitive text, though.)

_(Alternatively, I can share a custom build that will show full debug info instead of `?:0`.  But even then, it's fairly likely that ultimately I would still need to see the other scripts/settings/history to be able to track down where it's going wrong.)_

**Comment by u01jmg3** [comment]
You have mail. 📨

I don't believe I have any custom Lua scripts.

Happy to test out a custom build.

**Comment by chrisant996** [comment]
Ah, I see why I thought there was an argmatcher; the custom color for a recognized executable looks similar to the default color for an argmatcher.

I still can't reproduce the problem, but I found some other coroutine issues and have fixes in the upcoming v1.3.26 -- maybe they are related.

If you continue to see coroutine errors in v1.3.26, then I'll share a custom build that includes the Lua debug info.

**Comment by chrisant996** [comment]
@u01jmg3 try v1.3.26 and please let me know if the problem still occurs.  I didn't make any specific change for an "attempt to concatenate a nil value" error, but some fixes I made might improve it for other reasons.

**Comment by u01jmg3** [comment]
Looks good. After installing v1.3.26 I ran `clink set lua.debug true` and so far I'm not seeing the same issue I was seeing. 🤞🏻

**Comment by chrisant996** [comment]
I haven't seen it occur in almost a month.  I'll close this, and it can be reopened if the issue resurfaces.
