### ISSUE TITLE
History entries first letter replaced with vertical line |

### ISSUE THREAD

**Issue by clinkist** [chrisant996/clink#316]
I have no idea what causes this, but some entries in my clink_history file have the first letter replaced with vertical line. It looks like this:
```
cd ..\whatever\
|pm run dev
|pm i
npm install --upgrade
```

v1.3.33.f2cac3, installed over 0.4.9 recently (and that's when the problem started).

**Comment by chrisant996** [comment]
See #90.  Those are deleted history entries.

Since you're inspecting the contents of the history files, I will guess that you are doing some kind of processing directly against the history files.

What kind of processing are you doing, and why?

There are `clink history` commands for compacting history and for removing duplicates.

The `clink history` command lists the command history for the current Clink session.  It splices together the master history, the current session history, and the current session deletions.  The file formats are designed for high performance and reliability; they are not suitable for parsing/manipulating by other programs.

Depending on the context where you're invoking `clink history`, you may or may not need to specify the profile directory (use the `--profile` flag) or the current session ID (use the `--session` flag).  When invoking `clink history` from within a Clink session, the correct profile directory and session ID are detected automatically.

**Comment by clinkist** [comment]
I wasn't doing any processing, just inspecting the file manually to extract some of the past commands that I used. I wasn't aware of the `clink history` command, thank you for that — I will certainly use it instead. And timestamps will come in handy as well.
