### ISSUE TITLE
if the screen is resized and the prompt no longer fits on one line the prompt is corrupted

### ISSUE THREAD

**Issue by jtnord** [chrisant996/clink#320]
if the amount of text that can fit on a line is changed that causes the current prompt to reflow across multiple lines then the existing prompt gets corrupted and multiple items are repeated.

could be a clink issue also?
`clink version  : 1.3.34.893e64`
`flexprompt 0.9`

Can be reproduced by any way that changes how much text can fit on a line, e.g. zooming (changing font size in terminal or changing terminal window width.

video shows zooming as it is easier to capture

https://user-images.githubusercontent.com/494726/177745015-eff15105-dcc5-4c19-8570-36eb0ed806d1.mp4

**Comment by jtnord** [comment]
@chrisant996 I am still seeing this with v1.3.40.1901c2 which contains ac3bd25e4cc2b93a2ef469af847a2720e5bb5236

**Comment by chrisant996** [comment]
> @chrisant996 I am still seeing this with v1.3.40.1901c2 which contains ac3bd25e4cc2b93a2ef469af847a2720e5bb5236

Are you seeing the exact same behavior as in the video above? Or is it different than before? If it's different, can you share a video of the new behavior?

**Comment by chrisant996** [comment]
Oh, haha.  The exact same problem happens in `bash` in Ubuntu in WSL in Windows Terminal.

Apparently the Readline library doesn't handle terminal resize very well.

Looks like I will have to write a custom resize handler, instead of relying on Readline's resize behavior.

But, on top of that, there is no way for a console mode application to fully reliably handle when the console is resized.  If you resize quickly, then the console continues to change size **_while_** the console mode application is redrawing its output.  And so the output naturally gets a little garbled while resizing.  But the degree of garbling that's happening here is because Readline isn't handling resize correctly.

**Comment by chrisant996** [comment]
While investigating the terminal resize problems, I found many additional bugs in Readline's display code.  The bugs are reproducible in `bash` in Ubuntu.

At this point, the costs associated with trying to fix Readline itself look significantly greater than writing fresh C++ code that takes advantage of Clink's native awareness of ANSI escape sequences and multibyte UTF8 characters.

It may take some time to complete that; it's tracked in issue 340 (linked above).
