### ISSUE TITLE
portable clink does not autocomplete

### ISSUE THREAD

**Issue by Daniel-Kenan** [chrisant996/clink#323]
Clink doesn't work if I am running the portable version.

How can I run it without using a setup wizard and using the power of portability?

**Comment by chrisant996** [comment]
In what ways doesn't it work?

What steps have been used?
What happens?

**Comment by Daniel-Kenan** [comment]
I downloaded the portable version of clink.
I opened the terminal typed `clink inject` in that current directory. Repo information presented itself on the screen. But the terminal was not suggestkmg anything as I was typing.

**Comment by chrisant996** [comment]
I think you are asking how to turn on the "Use enhanced defaults" option from the setup program, without using the setup program.

I recommend reading the [Getting Started](https://chrisant996.github.io/clink/clink.html#getting-started) section in the Clink documentation, and especially the [Common Configuration](https://chrisant996.github.io/clink/clink.html#common-configuration) sub-section.  It sounds like what you're looking for is the first thing covered there.

Is that what you're looking for?

**Comment by Daniel-Kenan** [comment]
Yes it is. 💯. But it is not working on my computer. I followed the instructions

**Comment by chrisant996** [comment]
I want to help. I order to help, I need more information than "it isn't working".

Would it be possible for you to show the full output from `clink info` and `clink set`?

And can you show the files that exist in your Clink directory?

**Comment by Daniel-Kenan** [comment]
![IMG_20220711_030321.jpg](https://user-images.githubusercontent.com/80764195/178170497-65fb0cb9-1fdb-4dfb-9528-c59d675d322a.jpg)

![IMG_20220711_030421.jpg](https://user-images.githubusercontent.com/80764195/178170529-9255dc1c-88de-4ca8-984c-46aa891e3319.jpg)

It doesn't show me suggestions of commands

Clink Info

![IMG_20220711_030759.jpg](https://user-images.githubusercontent.com/80764195/178170661-351a9a47-e972-488b-9000-63e6e68d69e5.jpg)

**Comment by chrisant996** [comment]
@Daniel-Kenan Thanks, the screenshot shows what the problem is.

The main step from the directions has not been applied yet.

Excerpt from [Enhanced default settings](https://chrisant996.github.io/clink/clink.html#gettingstarted_enhanceddefaults):

> If you install Clink from the .zip file then enhanced default settings are activated when the default_settings and default_inputrc files are present in the binaries directory or in the profile directory. The .zip file comes with the files, but their names have a _ prefix so that enhanced defaults won't automatically take effect. You can activate the enhanced default settings by renaming the files to remove the _ prefix.

The files have not been renamed per the directions yet.
Rename them to remove the leading `_` from their names.

That is why things aren't behaving as expected.

P.S.  I think you accidentally shared `clink inject` output instead of `clink set` output.  But luckily the screenshot showed that the files hadn't been renamed yet.
P.P.S.  Instead of attaching screenshots, consider copy/pasting the actual text from the terminal.  That way it is searchable, and it would also make it much easier to share things that are too long for one screenshot.

**Comment by Daniel-Kenan** [comment]
Thank you so much 💯. It works.

I have also noted what you said about copying actual text. I'll do so in future. Thanks a lot. I have learnt a lot from you💯.
