### ISSUE TITLE
1.1.8 and 1.1.11 detected as threats by Symantec

### ISSUE THREAD

**Issue by zrma** [chrisant996/clink#34]
Versions 1.1.8 and 1.1.11 are detected as threats by Symantec. 

![image](https://user-images.githubusercontent.com/4281810/102892169-d42c5d00-44a2-11eb-9c7d-89a7feccdf00.png)

![image](https://user-images.githubusercontent.com/4281810/102892196-da223e00-44a2-11eb-83cd-0256463edded.png)

thank you.

**Comment by chrisant996** [comment]
There's not really anything I can do about false positives in anti virus tools.

I can't read any of the text in the screen shots, so if there's important information in them maybe someone could translate.

**Comment by zrma** [comment]
ok, thank you for your answer.

**Comment by s-kocher** [comment]
Recently at work, I saw recent version of Clink be blocked by antivirus, Symantec again (Symantec Endpoint Protection aka SEP).
It was because of their reputation scanner : https://techdocs.broadcom.com/us/en/symantec-security-software/endpoint-security-and-management/endpoint-protection/all/Glossary/file-reputation-v32546090-d49e18645.html

We get this kind of alert : 
```
Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: WS.Reputation.1
```

This can be fixed by filling the false positive Symantec form : 
https://knowledge.broadcom.com/external/article/178170/submit-false-positives-detected-by-endpo.html

I already did that for proxy software, after few days, it was fine : https://github.com/genotrance/px/issues/62

Better wait there are less releases to submit to any antivirus company that reject clink the latest stable binary.

**Comment by garoto** [comment]
If this "flagging" starts to happen more often with Symantec and other snakeoil "AV suites", then it'll be a never ending struggle, new binaries after new binaries. It all sounds almost like a shakedown scheme.
