### ISSUE TITLE
Compilation errors with 3a5eabdf

### ISSUE THREAD

**Issue by jackL999** [chrisant996/clink#343]
``` Compiling...
  lopcodes.c
  macro.c
  loslib.c
V:\clink\clink\lib\src\display_readline.cpp(1270,9): error C2065: 's_display_manager': undeclared identifier [V:\clink\
.build\vs2019\clink_lib.vcxproj]
V:\clink\clink\lib\src\display_readline.cpp(1285,5): error C3861: 'clear_to_end_of_screen': identifier not found [V:\cl
ink\.build\vs2019\clink_lib.vcxproj]
V:\clink\clink\lib\src\display_readline.cpp(1287,9): error C2065: 's_display_manager': undeclared identifier [V:\clink\
.build\vs2019\clink_lib.vcxproj]
V:\clink\clink\lib\src\display_readline.cpp(1317,16): error C2065: 's_display_manager': undeclared identifier [V:\clink
\.build\vs2019\clink_lib.vcxproj]
  doskey.cpp

**Comment by chrisant996** [comment]
How are you compiling?

Debug? Release? Final?
X86? X64?

Master was compiling cleanly in x64 Debug for me.

I do not even try to keep master compiling cleanly for all flavors at all times.  I clean Release/Final and x86 build issues once features are complete.  The display rewrite is not complete right now.

**Comment by chrisant996** [comment]
Ah you're building for either Release or Final.

**Comment by chrisant996** [comment]
Np.  Thanks for reporting the issue!  I welcome reports about build errors in any flavor.

For full disclosure, since I'm essentially the only person working in this repo, I don't invest the time & effort of keeping master clean at all times for all flavors (only x64 Debug), though generally speaking it will stay clean.
