### ISSUE TITLE
CMD scrolling is broken on recent builds.

### ISSUE THREAD

**Issue by mcoret** [chrisant996/clink#345]
Scroll hotkeys (Alt-PgUp, Alt-Up, etc.) aren't working in CMD window on latest builds. I've checked the latest released build, and everything is working just fine.

**Comment by chrisant996** [comment]
Thanks. A leftover debugging change.

**Comment by nitincodery** [comment]
It is still broken.

**Comment by chrisant996** [comment]
> It is still broken.

Can you share more information about what you're experiencing?  Scrolling works for me in conhost windows.

Are you using Windows Terminal?  Windows Terminal removed the ability for console mode programs to scroll the console.  Instead, use Windows Terminal's own key bindings for scrolling the console.

**Comment by nitincodery** [comment]
I am using cmd.exe, sometimes it works, sometimes it doesn't work.

**Comment by chrisant996** [comment]
> I am using cmd.exe, sometimes it works, sometimes it doesn't work.

@nitincodery please share more details.

**Comment by nitincodery** [comment]
I've tried many times, scrolling is working fine now, I am sorry about "sometimes it doesn't work" statement, I'd log all the details next time when it will fail and let you know.

**Comment by chrisant996** [comment]
> I've tried many times, scrolling is working fine now, I am sorry about "sometimes it doesn't work" statement, I'd log all the details next time when it will fail and let you know.

Ok, thanks. I want to look into the issue, so I look forward to hearing more details. Since you're the only person to report this and I can't reproduce it, I'm stuck for now.

If you aren't using v1.5.1, then the first thing you should do is upgrade to see if that solves the problem. It always helps to know what version someone is using.

**Comment by chrisant996** [comment]
@nitincodery How are you scrolling? What version of Windows are you using?

The issue you replied in is about _keyboard_ scrolling not working.  That was fixed.

Are you instead experiencing problems scrolling _with the mouse wheel_?  (That would be an example of a detail that's important to share.)

If it's mouse wheel scrolling that you're having trouble with and you're using Windows 11, then you might be running into https://github.com/microsoft/terminal/issues/15711.

If that's the case, then try running `clink set terminal.mouse_input off` -- does that resolve the problem?

When reporting issues in any repo, please be include specific details.  And generally speaking, please open a new issue instead of replying to a closed issue.  Replying to a closed issue to report a new or similar problem breaks the ability to track issues accurately.
