### ISSUE TITLE
Pasting in clink 1.3.43 will duplicate the 2nd character

### ISSUE THREAD

**Issue by Uxorious** [chrisant996/clink#348]
I just upgraded from 1.3.42 to 1.3.43 and immediately downgraded.

There seems to be an issue with paste into the window.
For example, if I paste:
`set BLAH=`
It will actually paste:
`seet BLAH=`

Reverting back to 1.3.42 fixes it again.

**Comment by chrisant996** [comment]
Interesting!  I am only able to reproduce that inside ConEmu.  It works fine outside of ConEmu.

**Comment by chrisant996** [comment]
And only when using ConEmu's own paste command.  When using any of Clink's paste commands, it works fine.

So, something about how ConEmu emulates paste by injecting keystrokes is confusing Clink now.  It must be related to the changes for fixing #346.

**Comment by pukkandan** [comment]
I can reproduce in Windows Terminal

**Comment by chrisant996** [comment]
> I can reproduce in Windows Terminal

Ah, I forgot that I removed Window Terminal's default <kbd>Ctrl</kbd>-<kbd>V</kbd> key binding, so that Clink can do the paste.

When I invoke WT's own Paste command, then I am able to repro in WT as well.

There is something about how ConEmu and WT emulate paste by injecting keystrokes that is confusing Clink now.

**Comment by chrisant996** [comment]
The issue occurs only the _first_ paste.  Subsequent pastes work fine.

**Comment by chrisant996** [comment]
It is due to another bug in Readline's Callback Mode (`READLINE_CALLBACKS`).

In Readline 8.0 an optimization was added to the `self-insert` command, with the intent of speeding up pasted input.  But the optimization is incompatible with Callback Mode (it calls `rl_read_key()`, which bypasses Callback Mode).

The fix is to disable the `_rl_optimize_typeahead` mode.

----

_"Why does Clink use Callback Mode if there are so many problems with Callback Mode?"_

The Readline docs say it's the right way to use Readline, given the ways that Clink wants to extend Readline.  Clink's match completion optimizations, async prompt filtering, Lua coroutines, mouse input, and much more all rely on the `READLINE_CALLBACKS` mode.

**Comment by Uxorious** [comment]
Looks like it's working.
Thanks for the quick fix!
