### ISSUE TITLE
[FR] Option to disable writes to clink.log

### ISSUE THREAD

**Issue by God-damnit-all** [chrisant996/clink#349]
I run a lot of scripts, and I noticed just how many additional writes I was getting to my system disk. I'd really like an option to disable writing to clink.log altogether.

**Comment by chrisant996** [comment]
See `clink inject --help` and the `--nolog` flag.

But also, would you be willing to send me a sample showing the large number of additional writes caused by logging?
It should normally be doing very little logging.

If it's doing a lot of logging, then it may indicate a problem that needs an actual solution, rather than just turning off logging altogether.

**Comment by chrisant996** [comment]
@ImportTaste See `clink autorun --help` and the ability to specify additional flags.

**Comment by chrisant996** [comment]
But please -- pretty please -- consider sending me a sample log so that I can see the large number of additional writes.  If there is a large number of writes, then something is wrong.

Oh -- or your system is running a large number of cmd.exe processes in the background, such that autorun ends up producing a large volume of logging?

**Comment by chrisant996** [comment]
@ImportTaste I see.  Then you may need to turn off autorun to get the kind of performance improvement you're looking for.

The logging cost is very small compared to the cost of all those forced clink invocations and cross-process injections due to autorun.  It is not cheap launching clink.bat and clink_x64.exe and injecting into cmd.exe every single time a background (non-interactive) cmd.exe is launched.  It can definitely slow down the system, regardless of logging.

**Comment by chrisant996** [comment]
@ImportTaste That's an interesting question.  Currently, CLINK_NOAUTORUN is not about avoiding performance cost.  It can only prevent Clink from taking over the prompt display or the input line editor.

The only thing that knows about CLINK_NOAUTORUN is Clink.  So, Clink code has to be running, which means all the performance cost of injecting Clink has already been paid.

But the clink.bat file could be updated to detect CLINK_NOAUTORUN when it's being invoked in the context of autorun, and it could bail out very early.

But how would that help your scenario?  Is there a specific set of cmd.exe invocations that you control, during which you want to prevent Clink injection cost?

**Comment by chrisant996** [comment]
I looked closer, and setting the CLINK_NOAUTORUN envvar can't avoid launching clink_x64.exe, but it _does_ short circuit early enough to skip any of the cost of injecting into cmd.exe.

So, setting CLINK_NOAUTORUN would avoid roughly 2/3 of the performance cost.

But it doesn't seem useful as a way of improving performance, because something outside of Clink would have to figure out when to set/clear the CLINK_NOAUTORUN envvar.
