### ISSUE TITLE
expand directories in clink installscripts

### ISSUE THREAD

**Issue by jtnord** [chrisant996/clink#355]
I somewhat foolishly ran `clink installscripts .` in a directory (a clone from https://github.com/vladimir-kotikov/clink-completions) and the install failed with:

```
Script path '.' installed.

!init.lua:9: attempt to concatenate local 'parent_path' (a nil value)
.init.lua:9: attempt to concatenate local 'parent_path' (a nil value)
chocolatey.lua:1: module 'tables' not found:
        no field package.preload['tables']
        no file 'C:\Windows\System32\lua\tables.lua'
        no file 'C:\Windows\System32\lua\tables\init.lua'
        no file 'C:\Windows\System32\tables.lua'
        no file 'C:\Windows\System32\tables\init.lua'
        no file '.\tables.lua'
        no file 'C:\Windows\System32\tables.dll'
        no file 'C:\Windows\System32\loadall.dll'
        no file '.\tables.dll'
...
```

I think when installing scripts the path passed should be made absolute, because what is relative probably depends on where cmd.exe was started in (or it is relative to where clink is installed - which would be not the same as the current path in most cases)

workaround is a trivial `clink uninstallscrripts . && clink installscripts <the-full-path>`

**Comment by chrisant996** [comment]
I'm torn.

`set clink_path=.` will experience the same issue, and there's nothing Clink can do to expand that particular `.`.  I'm not sure that Clink should second guess what the user says to do.

What if someone has set up two shortcuts to launch Clink, and the shortcuts use two different working directories.  What if the user ran `clink installscripts .` because they really do want Clink to load scripts from whatever working directory it started in?  That's a reasonable -- albeit atypical -- usage style.

I could maybe see making `clink installscripts` report an error about relative paths, and require something like `-y` or `--yes` to force allowing relative paths (preemptively responding "yes" to the warning/error).

I'm not convinced it's universally correct to convert what the user specified into something else.

**Comment by chrisant996** [comment]
@jtnord Thank you for reporting this.  I can see how and why it was problematic and frustrating.

I want to make that better.  I also want to be careful not to over-optimize for blocking mistakes to the point that it also blocks potentially reasonable actions.

At this time, I don't want to add complexity to `clink installscripts` by detecting relative paths and reporting a warning, with a flag to disable the warning.

This is something to keep an eye on, for the future.
