### ISSUE TITLE
Clink will not setup the autorun option correctly when the autorun Registry Key contains certain "if exists"-statements

### ISSUE THREAD

**Issue by internationalTD** [chrisant996/clink#357]
I installed miniconda and downloaded clink afterwards.

Clink had the autorun registry value as:
`native : if exist "C:\Users\-SNIP-\AppData\Local\Temp\_MEI62242\condabin\conda_hook.bat" "C:\Users\-SNIP-\AppData\Local\Temp\_MEI62242\condabin\conda_hook.bat" & "C:\Program Files (x86)\clink\clink.bat" inject --autorun`

And the `if exists` stopped clink from injecting.
I had to swap the two statements around the & to get it working.

(sidenote, the set command didn't work for me, something about unknown option -u, so i set it using regedit.exe, at `HKEY_CURRENT_USER\Software\Microsoft\Command Processor`

**Comment by chrisant996** [comment]
If some programs add `if` commands in the AutoRun string, then they're going to cause problems with other things that also want to use AutoRun.

Whatever added the `if` should have put parentheses around it `( if exist file command )` to ensure it will be compatible with other commands in the AutoRun regkey.

Clink can't realistically prevent or compensate for problems caused by other programs using the AutoRun regkey incorrectly.

**Comment by garoto** [comment]
> Whatever added the if should have put parentheses around it [...] to ensure it will be compatible with other commands in the AutoRun regkey.

Can you elaborate on the "whys" that is the case? There are so many undocumented `cmd` behaviors and syntax idiosyncrasies that I would love if you could school us with the parenthesis thingy.

**Comment by chrisant996** [comment]
`if` treats everything after the condition as part of the command -- including `&`.

Parentheses group what's inside them.  So putting `if` inside parentheses causes the `if` command to end when the parenthesis group is closed.

This isn't secret or special, it's just how parentheses work.

**Comment by internationalTD** [comment]
The issue was not that hard to fix for me, even with hardly any experiences with the "idiosyncrasies".
However:
Would setting autorun to
`"C:\Program Files (x86)\clink\clink.bat" inject --autorun & (OLD_AUTORUN)`
not solve these issues in a lot of cases?

Or wouldn't a reference to `HKEY_CURRENT_USER\Software\Microsoft\Command Processor` when you run `clink autorun` be helpful?

I really love clink btw. I thought I'd file as a bug because it prevented me from using it out of the box, that's all!

**Comment by chrisant996** [comment]
It is not safe to blindly put parentheses around the `OLD_AUTORUN` -- adding parentheses could easily break some things.

The point is that Clink cannot have the Artificial Intelligence needed to analyze commands that other programs have put into AutoRun and detect when they are malformed and add compensating bug fix logic to make them still do whatever the original author intended, without interfering with Clink or other programs.

Given any one specific example, it's (relatively) easy for a human to look at the example and say how to fix the example.  But producing an automated fixer that works for all possible inputs ... that's an intractable problem.

Clink could instead always put its own stuff at the beginning.  But then that cases other problems with respect to order of precedence in some cases.

There's no one-size-fits-all solution.  And ultimately, the miniconda setup produced an AutoRun line that is inherently incompatible with other things wanting to also use AutoRun -- the root cause here lies in miniconda.

I recommend reporting this issue to the miniconda project.
