### ISSUE TITLE
Clink with history.save = False uses history file and persists typed in commands

### ISSUE THREAD

**Issue by KonopaKrzysztof** [chrisant996/clink#372]
Based on Cmder 1.3.20 with Clink 1.3.47 and 1.3.51.

According to documentation for history.save setting:

`Saves history between sessions. When disabled, history is neither read from nor written to a master history list; history for each session exists only in memory until the session ends.`

The wording borderline allows second interpretation but going by the principle of least surprise saving history between sessions implicitly refers to history.save = True and False disables persistence altogether and things never leave memory.

So let's see that in practice with a new profile, paths may vary:

```
"C:\Program Files\Cmder\1.3.20\Cmder.exe" /C "%USERPROFILE%\AppData\Roaming\Cmder\1.3.20" -- -run cmd /Q /C "C:\Program Files\Cmder\1.3.20\vendor\init.bat" -cur_console:n
echo history.save = False >> "%USERPROFILE%\AppData\Roaming\Cmder\1.3.20\config\clink_settings"
"C:\Program Files\Cmder\1.3.20\Cmder.exe" /C "%USERPROFILE%\AppData\Roaming\Cmder\1.3.20" -- -run cmd /Q /K "C:\Program Files\Cmder\1.3.20\vendor\init.bat"
```

Inspect "%USERPROFILE%\AppData\Roaming\Cmder\1.3.20\config": clink_history exists and it's empty

Type in: `echo hello`

Inspect "%USERPROFILE%\AppData\Roaming\Cmder\1.3.20\config": clink_history exists and has a new entry echo hello

Type in: `echo world`

Inspect "%USERPROFILE%\AppData\Roaming\Cmder\1.3.20\config": clink_history exists and has a new entry echo world

Close Cmder

Inspect "%USERPROFILE%\AppData\Roaming\Cmder\1.3.20\config": clink_history exists and contains echo hello and echo world lines

You can observe the same behavior with PID history files when history.shared = False:

```
sed -i '19s/history.shared = True/history.shared = False/' "%USERPROFILE%\AppData\Roaming\Cmder\1.3.20\config\clink_settings"
```

And obviously you cannot set history.max_lines = -1 like with Clink pre 1.0 history_file_lines = -1.

On a side note, current documentation:
- in https://chrisant996.github.io/clink/clink.html#the-master-history-file spells out history.save as history.saved
- in https://chrisant996.github.io/clink/clink.html#v1242 states that 0 on max_lines is supported but https://chrisant996.github.io/clink/clink.html#clinksettings still uses (1 to 50000) range

**Comment by chrisant996** [comment]
> `Saves history between sessions. When disabled, history is neither read from nor written to a master history list; history for each session exists only in memory until the session ends.`
> 
> The wording borderline allows second interpretation but going by the principle of least surprise saving history between sessions implicitly refers to history.save = True and False disables persistence altogether and things never leave memory.

1. First, the behavior shown below is not how `history.save` behaves when False.  More on that, below.
2. Second, always use `clink set` to change settings.  That way Clink automatically finds the current profile and can update the settings file correctly -- for example, migration from v0.4.9 setting names can happen, Clink can handle special side effects, and etc.  Directly changing the `clink_settings` file is not supported; you might be able to make that work right now, but I cannot guarantee that it will continue to work in the future.
3. Thanks for calling out places where documentation hasn't been updated yet.

> So let's see that in practice with a new profile, paths may vary:
> 
> ```
> "C:\Program Files\Cmder\1.3.20\Cmder.exe" /C "%USERPROFILE%\AppData\Roaming\Cmder\1.3.20" -- -run cmd /Q /C "C:\Program Files\Cmder\1.3.20\vendor\init.bat" -cur_console:n
> echo history.save = False >> "%USERPROFILE%\AppData\Roaming\Cmder\1.3.20\config\clink_settings"
> "C:\Program Files\Cmder\1.3.20\Cmder.exe" /C "%USERPROFILE%\AppData\Roaming\Cmder\1.3.20" -- -run cmd /Q /K "C:\Program Files\Cmder\1.3.20\vendor\init.bat"
> ```

Yes.  But now type `clink set history.save`.  It will report that `history.save` is True.  The manual attempt to change the setting did not work.

I'm able to reproduce the behavior.  But I can also see that the manual attempt to change the setting did not take effect.  I'm not sure yet why it didn't work, though.  I'll investigate and at least understand (and share) why it didn't work.  The investigation may or may not result in a change, depending on what is found.

Always use `clink set` to query of change settings.  Direct manual modification of the `clink_settings` file is not tested and is not supported.

> Inspect "%USERPROFILE%\AppData\Roaming\Cmder\1.3.20\config": clink_history exists and it's empty
> 
> Type in: `echo hello`
> 
> Inspect "%USERPROFILE%\AppData\Roaming\Cmder\1.3.20\config": clink_history exists and has a new entry echo hello

That's happening because the `history.save` setting is still True.  Offhand, I would have thought that the manual change would have worked -- but it isn't supported, and using `clink set history.save False` works correctly.

Once the `history.save` setting is changed correctly, then it would become clear that the history is written to disk in a temporary file which is later deleted, and does not get written into `clink_history`.  However, the way the documentation is phrased does make it sound like the command history will never leave memory, and that is incorrect.

**You didn't say:**  Is it important to you that command history never leaves memory, not even in a temporary file?  Even if Clink doesn't write to temporary files, the OS can still save the memory contents to `pagefile.sys`, so even if I write a new command history implementation that doesn't write to a temporary file, I still couldn't guarantee that command history would never written to disk at all.

So, from my perspective, the issue here is that in one place I missed updating the documentation, and I need to rephrase that place to make it clear that the history is written to a temporary file.

> * in https://chrisant996.github.io/clink/clink.html#the-master-history-file spells out history.save as history.saved
> * in https://chrisant996.github.io/clink/clink.html#v1242 states that 0 on max_lines is supported but https://chrisant996.github.io/clink/clink.html#clinksettings still uses (1 to 50000) range

Thanks, I'll update the docs.

**Comment by KonopaKrzysztof** [comment]
I had to sit and play with it for a while more but your explanations did help a lot, thanks.
I also completely forgot about default_settings, which init.bat does not copy, but would normally cover clink set part.

Just to clarify on the original intentions, I anticipated the same functionality that Clink v0.4.9 brings with history_file_lines = -1.
Between history.save and history.max_lines implementations it seems to be gone.
Windows forensics aside which I'm aware of and being another can of worms, that - from what I can tell - does not persist commands neither in any Clink history file nor in a Temp directory.
That would be my preference; generating a history file that would remain without entries during and after session would be fine as well. Even if from the logical point of view I could assume disabled features wouldn't cause similar IO side effects, knowing implementation trade-offs your mileage may vary.

This way it would be more of a feature request.

**Comment by chrisant996** [comment]
> Just to clarify on the original intentions, I anticipated the same functionality that Clink v0.4.9 brings with history_file_lines = -1. Between history.save and history.max_lines implementations it seems to be gone. 

Another reason to use `clink set` is so it can handle migration and backward compatibility.
```cmd
c:\chrisant > clink set history_file_lines -1
Setting 'history.save' set to 'False'
```

`history_file_lines -1` means `history.save false`.

Many problems in the old implementation have been fixed.  The feature of not retaining history between sessions is still present.

The reason Clink writes to a temp file even when `history.save false` is so that the `history` command (which runs a separate process) can still show the history.  While it could potentially be possible to build a second completely different implementation of history that uses Shared Memory in Windows so that the `history` command can still work, that's relatively expensive to do and it can be fragile to get `history` commands from a session to connect to the correct corresponding Shared Memory region to show the history from _this_ Clink session, versus a different Clink session that is running.  It's doable, certainly.  But I haven't been convinced yet that the cost is necessary.

> Windows forensics aside which I'm aware of and being another can of worms, that - from what I can tell - does not persist commands neither in any Clink history file nor in a Temp directory. That would be my preference; generating a history file that would remain without entries during and after session would be fine as well. 

Are you saying that you want `history.save false` to delete any existing history file, in addition to simply not using it?  So that if someone accidentally sets `history.save false` temporarily then it is a destructive mistake and they lose their history?  I'm concerned about that.

Isn't it enough to be able to run `clink history clear` to clear the history file?

> Even if from the logical point of view I could assume disabled features wouldn't cause similar IO side effects, knowing implementation trade-offs your mileage may vary.
> 
> This way it would be more of a feature request.

I hear a desire to hide activity from prying eyes.  I can understand that.  If you're interested in working on a Shared Memory implementation, we can discuss design details over email.  My email is in my github profile.  I don't plan to work on that in the near future, but I'm adding it to the TODO list.

**Comment by chrisant996** [comment]
> I'll make a change to ignore trailing whitespace specifically for Boolean and Integer settings.

Clink v1.4.0 ignores trailing whitespace on Boolean and Integer settings in the `clink_settings` file.
