### ISSUE TITLE
Would it be possible to use this READLINE implementation to recompile windows PSQL.EXE ?

### ISSUE THREAD

**Issue by kirkw** [chrisant996/clink#374]
I stumbled across this because of wanting to get Autocomplete in psql (PostgreSQL command line, running in windows).
They have disabled it, because there is no READLINE library that works for windows.
But notes have been made that if we get a port of READLINE that works, we could link it in.

I want to give this a try, but it is a STRETCH for my skillset right now.  And I don't want to waste my time if your implementation in READLINE was just so specific to this project.  (ie, you never envisioned someone embedding it into their own tool, like psql)...

Thanks in advance!

**Comment by chrisant996** [comment]
> They have disabled it, because there is no READLINE library that works for windows. 

"works for Windows" -- the implication is that a conclusion has been reached that "Readline doesn't work for Windows".

From a functional and compilation perspective that's not accurate, or the statement is paraphrased and became inaccurate during paraphrasing.  Readline compiles and works on Windows, you just need to set up the config file correctly for the platform and compiler.  Readline even comes with a tool that helps do that as automatically as possible, though some manual tweaks may be needed afterwards.  Clink's copy of Readline does have a very small number of adjustments for making certain things work better on Windows than in the stock Readline.  PowerShell also uses "PSReadline" which could be another candidate to explore.

> But notes have been made that if we get a port of READLINE that works, we could link it in.

There must be a list of issues that led the team to conclude Readline "doesn't work".  It would be important to review that list and assess each point.

Why was the phrase "link it in" used, instead of "compile it"?  Is the team looking for a pre-compiled binary library to avoid GPL?

> I want to give this a try, but it is a STRETCH for my skillset right now. And I don't want to waste my time if your implementation in READLINE was just so specific to this project. (ie, you never envisioned someone embedding it into their own tool, like psql)...

All Clink changes to Readline are bracketed by `/* begin_clink change` and `/* end_clink_change`.  You may want some of them, and you definitely would want to omit some of them.

**Comment by kirkw** [comment]
@chrisant996 Thank you for the response.  (And a cool tool, despite Windows Defender Blocking it, lol).

yes.  It appears that for NON English Western European Languages READLINE in windows has some issues.
One example given, is you cannot type the BACKSLASH.
My bad on wording (linking/compiling, this was my error).

And as it turns out, there is a FLAG that lets psql.exe use windows READLINE.  And since I am using EN, etc.
The bug does not apply to me.  I am working on compiling with that flag first.  Obviously.

Thank you for the details.  If I have to push in an alternate version of READLINE I will strongly consider what you have done first.
(the one feature I will miss, that I will seek to implement, if possible is F8... As in "CREA<F8>", and it goes back in history to bring up the prior command with that prefix (CREA: case sensitive)).

**Comment by chrisant996** [comment]
> It appears that for NON English Western European Languages READLINE in windows has some issues.
> One example given, is you cannot type the BACKSLASH.

That is too vague a summary. Can you share a link to the issue with more details?

Maybe the issue is that psql is using ACP (the Active Code Page), instead of UTF8, and hasn't redefined the default keymaps accordingly.

I suspect the problem is not in Readline, but rather in a misunderstanding about codepages and how to integrate Readline into a project.

> Thank you for the details.  If I have to push in an alternate version of READLINE I will strongly consider what you have done first.

I haven't made changes to Readline that would affect this. I think the issue is in how psql is integrating with Readline on Windows. Codepages can be hard to understand.

> (the one feature I will miss, that I will seek to implement, if possible is F8... As in `CREA<F8>`, and it goes back in history to bring up the prior command with that prefix (CREA: case sensitive)).

That command exists in Readline. It just isn't bound to F8 by default. Read the Readline docs for more info.

**Comment by kirkw** [comment]
Chris, thank, reading the documentation on how to get the F8 functionality to work in readline!  That alone makes you a rockstar for mentioning.

The rest is on me.  Thank you again for building what you have, making it open source, sharing it, and answering questions!
Truly Appreciated.
