### ISSUE TITLE
Auto complete with wrong behavior

### ISSUE THREAD

**Issue by ghlecl** [chrisant996/clink#375]
I have had to reinstall my work computer and thus I have reinstalled clink.

I have downloaded version 1.4.0.74a8d2.

I believe I have selected all default values (but cannot be certain and I cannot test reinstalling since I do not have admin privileges on my computer...  :-( )

That said, my problem is the following: now, when I press tab to get completion, I get the Windows behavior of cycling through the available options instead of the bash behavior of completing to the common root...  which was, for me, the whole point of installing clink (other than completion and history, I don't care much for anything else like colors and such).

Is there something I am doing wrong ?  Is there a setting that I have to change ?

My apologies if this is a dumb question, but I have been trying to fix this with the settings for more than an hour.

**Comment by chrisant996** [comment]
This is one of the first things covered in the Getting Started section of the Clink documentation.

Have you read the docs?  Do you have questions about what's in the docs?

**Comment by ghlecl** [comment]
My apologies.  I have been using clink for a while, but only on my work machine, which I cannot update whenever I want.  The enhanced defaults snuck up on me, but having been a user for quite some time (started with Martin's versions), I did not think to read the complete getting started section.  My bad.

![image](https://user-images.githubusercontent.com/8061814/201159352-667f179b-ee55-4f15-9a8f-858cccc4be60.png)

I stopped reading after the second paragraph which says that tab should work like under bash, not realizing that in the next paragraph, it says if enhanced defaults are active, it'll be the windows behavior.

Not a justification, it really is my bad, but an explanation.

As an aside, is there a way, other than reinstalling completely, to disable the enhanced defaults ?

Sorry for having you waste your time.

**Comment by chrisant996** [comment]
No problem at all.  🙂

The docs do cover how "enhanced defaults" works, but to remove the enhanced defaults basically:
- delete the `default_inputrc` file in the profile directory
- delete the `default_settings` file in the profile directory

The reason I suggested to reinstall is because the installer remembers the checkbox state.

Reinstalling now would make the checkbox stay unchecked moving forward.  Versus if you ever reinstall sometime in the future, the checkbox would still be checked, and so if you forgot to uncheck it in the future then the same problem would get reintroduced.  But since Clink has auto-updates built in now, maybe you'd never need to reinstall again anyway.
