### ISSUE TITLE
Scoop completion broken

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/clink#38]
Hey! 

First of all I'd like to sincerely thank you for reviving this project and adding hundreds of improvements! 

I was using the original repo's Clink until I discovered your fork yesterday. The new documentation is really comprehensive and helpful.

I used this repo called [clink-completions](https://github.com/vladimir-kotikov/clink-completions) along with Clink, but after upgrading to your Clink fork, the completion for Scoop seems to be broken. 

![image](https://user-images.githubusercontent.com/46838874/103133618-75005f80-46d1-11eb-8b76-25f077336a95.png)

Other completions are working fine as they did before upgrading (like git, npm, dotnet, choco etc.). I saw the following in your documentation 

> Script compatibility should be very good, but some scripts may still encounter problems. If you do encounter a compatibility problem you can look for an updated version of the script, update the script yourself, or visit the repo and open an issue describing details about the compatibility problem.

So I decided to open the issue here. 

Once again thanks and cheers!

**Comment by chrisant996** [comment]
Perfect, thank you! Will take a look and fix the issue.

**Comment by chrisant996** [comment]
Oh, interesting.  It's a bug in the scoop.lua script when the %HOME% environment variable isn't set.  That variable is set by Cmder, but is not normally set otherwise.

Clink 0.4.9 _suppresses all lua error reporting_ so error messages from scripts aren't visible.

I think the simplest workaround is to `set HOME=%USERPROFILE%`, or to set HOME in the Environment Variables dialog from the System control panel.

I could make the new Clink also suppress lua errors by default, with a setting to show them.  But that wouldn't really be a solution -- the scoop.lua still wouldn't work, there would just be no indication why it wasn't working.  I think it's better to report errors, but I guess it wouldn't hurt to add a setting that can suppress error messages (but shows them by default).

**Comment by rashil2000** [comment]
Thanks for the update! I'll add it to my environment variables list from the Control Panel.

I think the default 'on' behaviour of error reporting is fine as it is now, it's helpful. Although it's worth noting that scoop completion worked without any problems in Clink 0.4.9; even when the `HOME` variable wasn't set.

**Comment by chrisant996** [comment]
> ... it's worth noting that scoop completion worked without any problems in Clink 0.4.9; even when the `HOME` variable wasn't set ...

Yes, sorry, I updated my reply but you beat me to it. Clink 0.4.9 internally sets HOME if it isn't already set. It did so because Readline needed it internally. That's no longer needed, so Martin removed setting HOME. But that breaks other lua scripts. So I'll add that back.

Thanks again for reporting this!

**Comment by rashil2000** [comment]
You're welcome! I'll temporarily manually set `HOME` before another release fixing this is made.
