### ISSUE TITLE
%CLINK_PROFILE% Environmental Variable

### ISSUE THREAD

**Issue by Zamanry** [chrisant996/clink#385]
**Background**
Hi, I am trying to install permanent history logging for Command Prompt using Clink (via `choco install clink-maintained`). I have configured the following settings and confirmed they are successfully working when used with a non-privileged user through either `clink set` or the `default_settings` file:
- `debug.log_terminal = True`
- `history.dupe_mode = add`
- `history.time_format = "%FT%T %z  "`
- `history.time_stamp = show`
- `history.shared = True`

Additionally, I have successfully set the machine environmental variable of `CLINK_PROFILE` too to change the log destination and read through the README a few times.

**Issue**
On my Windows 10 machine which is used for penetration testing and needs to be purposefully not following security best practices to perform our job, I have configured the registry keys to auto-elevate our CMD shells to administrator sessions. We are only using local accounts, not domain accounts. My related registry key configurations are ([Overview of these registry keys](https://learn.microsoft.com/en-us/windows/security/identity-protection/user-account-control/user-account-control-group-policy-and-registry-key-settings)):

- ConsentPromptBehaviorAdmin = 0 (Only really applicable key I believe; we are not using RID-500)
- EnableSecureUIAPaths = 0
- EnableLUA = 0
- FilterAdministratorToken = 1

From researching the issue and finding [this Stack Overflow article](https://stackoverflow.com/questions/63184282/run-cmd-with-clink-as-administrator-in-windows-to-save-your-command-history-perm) (which didn't work when I attempted to adapt it), it appears Clink does not by default support the auto-elevate method and will run Clink as non-admin in my admin shell, thus making the history feature not work. I am confused on why Clink will run in my auto-elevated CMD shell, but the history feature will not work at all. I tried the following changes in `clink.bat`:
```
start "Clink" cmd.exe /s /k pushd ""%V"" ""%~dpnx0" inject %clink_profile_arg%%clink_quiet_arg%"
start "Clink" cmd.exe /s /k "pushd ""%V"" ""%~dpnx0" inject %clink_profile_arg%%clink_quiet_arg%""
```

I would like to see the feature where Clink will run as admin (understanding the security problems) or if it is preferred to not add this feature, a manual workaround to modify on my end. Clink is in "Program Files x86" which in theory should be locked down assuming quoting is correctly used.

If there are any other questions or a method to try, feel free to reach out. Love the project and the problems it solves; Thanks!

**Comment by chrisant996** [comment]
> From researching the issue and finding [this Stack Overflow article](https://stackoverflow.com/questions/63184282/run-cmd-with-clink-as-administrator-in-windows-to-save-your-command-history-perm) (which didn't work when I attempted to adapt it),

That doesn't seem related to your situation. It's talking about how to make running `clink.bat` with no arguments start a new admin CMD instance, instead of starting a normal CMD instance.

> it appears Clink does not by default support the auto-elevate method and will run Clink as non-admin in my admin shell, thus making the history feature not work. I am confused on why Clink will run in my auto-elevated CMD shell, but the history feature will not work at all.

How are you starting CMD?
How are you injecting Clink?

If you run Clink from inside an elevated CMD (including if CMD runs Clink via AutoRun), then Clink is also elevated.

Clink injects a DLL into the CMD process, so history and everything else happen using whatever account CMD is running as. Clink does not have separate account/permissions from CMD.

> I would like to see the feature where Clink will run as admin (understanding the security problems) 

Simply start CMD elevated.

> Clink is in "Program Files x86" which in theory should be locked down assuming quoting is correctly used.

But where is your profile directory?
Run `clink info` to find out.

I bet what's really going on is that the administrator account doesn't have access to the Clink profile directory.

**Comment by Zamanry** [comment]
Hello, thanks for the quick reply! By the way, I uninstalled the outdated choco clink-maintained version and installed v1.4.3.67deea from the release with all default options except for setting the default output to the install directory.

- Stack Overflow:  Roger, makes sense. Yeah that's different.
- Starting CMD: When I start CMD, it's either through the Start Menu or typing "cmd" within PowerShell
- Injecting Clink: I am not sure. I simply ran the latest v1.4.3.67deea release .exe, nothing custom relating to injection
- Profile directory: See screenshot
- AV is also disabled. Clink history was working without this registry key earlier.

I took some screenshots to help us out below:

First, I ran the PowerShell > CMD example:
![image](https://user-images.githubusercontent.com/28152647/207076867-ab90443a-354d-4f81-8aeb-3b9ed2bf5c64.png)

Next, I ran the CMD example:
![image](https://user-images.githubusercontent.com/28152647/207077077-d12a4d9e-ac32-4ad0-b59a-ebdfae35e64a.png)

**Comment by chrisant996** [comment]
> installed v1.4.3.67deea from the release with all default options except for setting the default output to the install directory.

I don't understand what is meant by "setting the default output to the install directory".

> - Starting CMD: When I start CMD, it's either through the Start Menu or typing "cmd" within PowerShell
> - Injecting Clink: I am not sure. I simply ran the latest v1.4.3.67deea release .exe, nothing custom relating to injection

Ok, you are installing with autorun enabled, meaning every CMD instance will automatically inject Clink. "Inject" refers to the fact that how Clink gets loaded into CMD is by literally injecting the Clink DLL into the CMD process.

> - Profile directory: See screenshot

The screenshots show that CMD is elevated, and Clink is successfully injected into CMD. So, Clink is elevated (because it's not a separate process; it is actually part of the CMD process, which is elevated).

So, the issue is probably that the C:\Logs directory does not grant permission to the administrator account (or maybe only the C:\Logs\clink_history file doesn't grant access to the administrator account; but it's probably the whole directory and thus all the files in the directory).

Triple check the ACLs for the C:\Logs directory.

**Comment by Zamanry** [comment]
I was referring to this unchecked box:
![image](https://user-images.githubusercontent.com/28152647/207103455-0d3bee6f-0581-4d6a-ad31-960573ad6687.png)

`C:\Logs` is not a SMB share. Here are the NTFS permissions which look appropriate (I want `Users` with `Full Control`):
![image](https://user-images.githubusercontent.com/28152647/207103965-78fc074d-5b50-449e-a11c-6dd27bb97c6b.png)

**Comment by Zamanry** [comment]
So I just removed my auto-elevate registry key and sure enough, clink history from a non-admin shell is not working at all despite being enabled. Therefore, something else on my system appears broken. I'll update this issue once I find it UGH

**Comment by chrisant996** [comment]
> I was referring to this unchecked box:
> ![image](https://user-images.githubusercontent.com/28152647/207103455-0d3bee6f-0581-4d6a-ad31-960573ad6687.png)
> 
> `C:\Logs` is not a SMB share. Here are the NTFS permissions which look appropriate (I want `Users` with `Full Control`):
> ![image](https://user-images.githubusercontent.com/28152647/207103965-78fc074d-5b50-449e-a11c-6dd27bb97c6b.png)
> 

No: when you elevate, you run as the local administrator account, instead of the logged in Users account.

Look at the Administrators permissions instead. This is some kind of permissions issue.

**Comment by Zamanry** [comment]
Yep, I realized I needed that checked box. I had misread it's usage. Uninstalled and reinstalled with it.

I reviewed the Administrators permissions and sure enough, it has full control.

-------------
New section, I went ahead and changed the machine's %CLINK_PROFILE% env. variable to `C:\Users\Kali` which we know will 100% have permissions for non-admin Kali and admin Kali to write to. After making the env. changes, I closed CMD/PowerShell and re-opened (to refresh the env. vars). Machine environmental variables:
![image](https://user-images.githubusercontent.com/28152647/207133688-b79317a8-ee8a-429b-a654-d4df460050d2.png)

I modified `default_settings` to have my history settings which took:
```
C:\Users\kali>clink set *
autosuggest.async                 True
autosuggest.enable                True
autosuggest.original_case         True
autosuggest.strategy              match_prev_cmd history completion
clink.autostart
clink.autoupdate                  False
clink.colorize_input              True
clink.default_bindings            windows
clink.logo                        none
clink.max_input_rows              0
clink.paste_crlf                  crlf
clink.path
clink.promptfilter                True
clink.update_interval             5
cmd.admin_title_prefix
cmd.altf4_exits                   True
cmd.auto_answer                   off
cmd.ctrld_exits                   False
cmd.get_errorlevel                True
color.arg                         bold
color.arginfo                     sgr 38;5;172
color.argmatcher                  sgr 1;38;5;40
color.cmd                         sgr 1;38;5;231
color.cmdredir                    sgr 38;5;172
color.cmdsep                      sgr 38;5;214
color.comment_row                 sgr 38;5;87;48;5;18
color.description                 sgr 38;5;39
color.doskey                      sgr 1;38;5;75
color.executable                  sgr 1;38;5;33
color.filtered                    sgr 38;5;231
color.flag                        sgr 38;5;117
color.hidden                      sgr 38;5;160
color.histexpand                  sgr 97;48;5;55
color.horizscroll                 sgr 38;5;16;48;5;30
color.input                       sgr 38;5;222
color.interact                    bold
color.message                     default
color.modmark
color.popup
color.popup_desc
color.prompt
color.readonly                    sgr 38;5;28
color.selected_completion         sgr 38;5;16;48;5;254
color.selection                   sgr 38;5;16;48;5;179
color.suggestion                  sgr 38;5;239
color.unexpected                  default
color.unrecognized                sgr 38;5;203
debug.log_terminal                True
directories.dupe_mode             add
doskey.enhanced                   True
exec.aliases                      True
exec.commands                     True
exec.cwd                          True
exec.dirs                         True
exec.enable                       True
exec.files                        False
exec.path                         True
exec.space_prefix                 True
files.hidden                      True
files.system                      False
history.auto_expand               True
history.dont_add_to_history_cmds  exit history
history.dupe_mode                 add
history.expand_mode               not_quoted
history.ignore_space              True
history.max_lines                 25000
history.save                      True
history.shared                    True
history.sticky_search             False
history.time_format               "%FT%T %z  "
history.time_stamp                show
lua.break_on_error                False
lua.break_on_traceback            False
lua.debug                         False
lua.path
lua.reload_scripts                False
lua.strict                        True
lua.traceback_on_error            False
match.expand_abbrev               True
match.expand_envvars              True
match.fit_columns                 True
match.ignore_accent               True
match.ignore_case                 relaxed
match.max_fitted_matches          0
match.max_rows                    0
match.preview_rows                5
match.sort_dirs                   with
match.substring                   True
match.translate_slashes           system
match.wild                        True
prompt.async                      True
prompt.transient                  off
readline.hide_stderr              False
terminal.adjust_cursor_style      True
terminal.differentiate_keys       False
terminal.east_asian_ambiguous     auto
terminal.emulation                auto
terminal.mouse_input              auto
terminal.mouse_modifier
terminal.raw_esc                  False
terminal.use_altgr_substitute     False
```

Clink info:
```
C:\Users\kali>clink info
version          : 1.4.3.67deea
session          : 1756
binaries         : C:\Program Files (x86)\clink
state            : C:\Users\kali
log              : C:\Users\kali\clink.log
default settings : C:\Program Files (x86)\clink\default_settings
settings         : C:\Users\kali\clink_settings
history          : C:\Users\kali\clink_history
scripts          : C:\Program Files (x86)\clink ; C:\Users\kali
default_inputrc  : C:\Program Files (x86)\clink\default_inputrc
inputrc          : %clink_inputrc%
                     (unset)
                 : state directory
                     C:\Users\kali\.inputrc
                     C:\Users\kali\_inputrc
                 : %userprofile%
                     C:\Users\kali\.inputrc
                     C:\Users\kali\_inputrc
                 : %localappdata%
                     C:\Users\kali\AppData\Local\.inputrc
                     C:\Users\kali\AppData\Local\_inputrc
                 : %appdata%
                     C:\Users\kali\AppData\Roaming\.inputrc
                     C:\Users\kali\AppData\Roaming\_inputrc
                 : %home%
                     C:\Users\kali\.inputrc
                     C:\Users\kali\_inputrc
```

I noticed that `C:/users/kali` has no history/log files and they were located at `C:\users\kali\appdata\local\clink`. I tried deleting `C:\users\kali\appdata\local\clink` folder, opening cmd/clink, running commands, exiting, but the history/log would continue to output in appdata/local. I'm also noticing the clink history file and log are writing correctly, but the `clink history` command is empty admin or non-admin. [clink.log](https://github.com/chrisant996/clink/files/10211350/clink.log)

Am I using the environmental variables incorrectly? And if so, why would `clink history` be empty?

I know this is tedious, but I really appreciate you helping me out!

**Comment by chrisant996** [comment]
This is a config issue and/or a permissions issue.

Also, for reference, I am unable to reproduce any of these problems when using Clink in elevated CMD, regardless where the profile directory is located.

How did you set the CLINK_PROFILE environment variable? In Kali's env vars? Those are not used when running elevated -- elevated means running as localhost\Administrator, not as the logged on user.

Instead, you could try specifying the profile dir directly in the actual autorun config.

Run `clink autorun --help` for details.

Something like `clink autorun install -- --profile c:\users\kali` (the separate `--` is not a typo; see the `--help` text for details).

But the best and simplest approach is actually to not use autorun at all: i.e. turn off autorun for Clink, and instead explicitly run `clink inject --profile {profile_dir_here}`. Then you have complete and unambiguous control over whether to inject Clink into a given CMD instance, and what profile directory to use.

**Comment by Zamanry** [comment]
My last shot here, here is every single thing I did from a fresh Windows 10 Enterprise VM from Microsoft:
1. Booted an updated Windows 10 Enterprise system with Defender disabled with no AV and no custom configurations on the entire OS. Logged in as Kali who is a local admin
2. Downloaded v1.4.3.67deea-setup.exe release and installed Clink with all default options
3. Opened an elevated notepad instance and successfully modified/saved `C:\Program File x86\clink\default_settings` with the following (GitHub doesn't render all the spaces):
	1. `debug.log_terminal                = True`
	2. `history.dupe_mode                 = add`
	3. `history.time_format               = "%FT%T %z  "`
	4. `history.shared                    = True`
4. In an elevated kali PowerShell terminal: 
	1. `[System.Environment]::SetEnvironmentVariable('CLINK_PROFILE',"C:\Users\kali",'Machine')` to set the environmental variable
5. From the start menu, opened non-elevated CMD with clink autostarted:
	1. `clink info` to check the paths which look correct
	2. `whoami` for a history filler command
	3. `clink set *` and found my `default_settings` configurations
	3. `exit`  (closed all clink/CMD instances)
6. Found `C:\Users\Kali` to be empty and `C:\Users\Kali\AppData\Local\clink` to have the log and history
7. In an elevated kali PowerShell terminal:
	1. `Remove-Item -Recurse -Force -Path 'C:\Users\Kali\AppData\Local\clink'`
8. From the start menu, opened non-elevated CMD with clink autostarted:
	1. `echo 123456`
	2. `exit`
9. Now I have log/history files being stored within `C:\Users\Kali` and `C:\Users\Kali\AppData\Local\clink`
	1. `C:/Users/kali` only holds 1 entry of `CTAG_1670893921_338031_5820_0`, etc., but isn't updated again with further history items
	3. `C:\Users\Kali\AppData\Local\clink` has the echo command and will continue to update with further history items and an incorrect timestamp (`time=1670894177`)

If this doesn't help any further, I am not sure what else to do. My Twitter DMs @Zamanry are open.

**Comment by chrisant996** [comment]
When I follow the steps you've listed, using `c:\test385` instead of `c:\users\kali`, then everything works perfectly:
- History is stored in `c:\test385\clink_history`.
- Logging is stored in `c:\test385\clink.log`.
- `clink history` lists the correct history.
- `clink info` lists `c:\test385` as the state (profile) directory.

When I follow the steps you've listed, using `c:\users\chrisant` (my local user account) instead of `c:\users\kali`, then everything works perfectly for the "chrisant" account (both non-elevated and elevated), but doesn't work for other user accounts (of course not, since they don't have permission to the "chrisant" account user tree).

> `debug.log_terminal = True`

Why has detailed input and output logging been enabled?  That's meant for specific diagnostic purposes for debugging keyboard input problems and terminal display problems.  Under normal circumstances it has no benefit and spews a ton of extra output into the log file, and should be off.

> 4. In an elevated kali PowerShell terminal:
>    
>    1. `[System.Environment]::SetEnvironmentVariable('CLINK_PROFILE',"C:\Users\kali",'Machine')` to set the environmental variable

That forces Clink to use the protected user directory for "kali" for all users. The permissions will be incorrect for all users other than "kali", and that will cause problems.

However, I would expect that the "kali" user account would be able to access it, both when running non-elevated and also when running elevated.  That works for me for all local accounts and domain accounts on all of my machines -- so around 10 accounts total, on 4 machines, some of which are domain joined and some of which are not.

>    2. `C:\Users\Kali\AppData\Local\clink` has the echo command and will continue to update with further history items and an incorrect timestamp (`time=1670894177`)

Why do you say that 1670894177 is an incorrect timestamp?
The timestamp is stored in UTC, not local time.
```
1670894177:  2022/12/13  1:16:17  [in UTC]
```

**Comment by chrisant996** [comment]
@Zamanry  I figured it out:

Please run `clink autorun show`.

The installer explicitly sets the profile directory in the autorun.  That of course overrides `CLINK_PROFILE`.

So, as I suggested a few replies ago, you need to use `clink autorun install -- --profile {the directory you want to use}`.

Or better yet, since the intent is to make a config that works for all users, don't set `CLINK_PROFILE` and just use the default profile directory.

What led to trying to override the profile directory?  If there was a problem, then what was the original problem?  And then let's focus on troubleshooting that original problem.  The `CLINK_PROFILE` issues are all just due to not adjusting the `clink autorun` configuration.

**Comment by Zamanry** [comment]
Hey sir! Regarding the timestamp, I misthought the `history.time_format` flag would adjust this too. I realized that's UTC and that's fine. Thanks for the clarification.

I'll go ahead and disable `debug.log_terminal = True`.

I was trying to arrange all logs into one folder regardless of logging application (PowerShell transcripts, clink, etc.). This way when we need to pull custom application logs (not integrated into Event Viewer), we only have to go to one folder.

I just figured I could use the `%CLINK_PROFILE%` to change the global profile as the documentation says "You can override it via set CLINK_PROFILE=path after starting cmd.exe" which appears untrue. ***I finally had success doing the following:***
1. Using the environmental variable (`%CLINK_PROFILE="C:\Logs"`) [Users/Administrators have read/write access]:
    1. `clink autorun uninstall`
    2. `clink autorun install`
```
C:\Windows\system32>clink autorun show
Current AutoRun values
  Current user:
    native : "C:\Program Files (x86)\clink\clink.bat" inject --autorun
     wow64 : "C:\Program Files (x86)\clink\clink.bat" inject --autorun
  All users:
    native : <unset>
     wow64 : <unset>
```
2. Using a custom defined path (`"C:\Logs"`) [Users/Administrators have read/write access]:
    1. `clink autorun install -- --profile "C:\Logs"`
```
C:\Windows\system32>clink autorun show
Current AutoRun values
  Current user:
    native : "C:\Program Files (x86)\clink\clink.bat" inject --autorun --profile C:\Logs
     wow64 : "C:\Program Files (x86)\clink\clink.bat" inject --autorun --profile C:\Logs
  All users:
    native : <unset>
     wow64 : <unset>
```

Regarding the multiple users and one settings file, yeah. I'll work this out on my end. Fair point

So a summary of my final questions are:
1. What is the purpose of `%CLINK_PROFILE%` if it does not change the global profile unless you run two more commands? Shouldn't we add a check to 1. check for the variable and if not found, then use the 2. provided path or 3. default path?
2. How would I go about modifying the `All users:` flags in the `clink autorun show` command? The autorun commands were run in an elevated window.
3. Have you considered if clink is vulnerable to a unquoted service path vulnerability since clink doesn't quote paths? Not my area of expertise, but even if I provide quotes, they were removed.

**Really appreciate the help!**

**Comment by chrisant996** [comment]
> I was trying to arrange all logs into one folder regardless of logging application (PowerShell transcripts, clink, etc.). This way when we need to pull custom application logs (not integrated into Event Viewer), we only have to go to one folder.

The intent makes sense. However, clink intentionally stores all of its files in One profile directory. If you want to put all the profile stuff in a global logs directory, you can do that, but it will also merge together all settings and history for all user accounts. That is probably not desirable.

Clink intentionally does not have a way to store the log file in a separate place, because that would make supporting Clink much more complicated.

> I just figured I could use the `%CLINK_PROFILE%` to change the global profile as the documentation says "You can override it via set CLINK_PROFILE=path after starting cmd.exe" which appears untrue.

It's true ... Unless other steps have been taken that override that. I've already updated the documentation to call out that the setup program Autorun setting overrides that, and how to undo that. See [File Locations](https://chrisant996.github.io/clink/clink.html#filelocations).

> 2. Using a custom defined path (`"C:\Logs"`)
> ...
> Regarding the multiple users and one settings file, yeah. I'll work this out on my end. Fair point

I understand the benefit of storing logs in a global place. It isn't compatible with having more than one user of the machine, and it stores non-log things in the logs directory which may also be problematic.

> So a summary of my final questions are:
> 1. What is the purpose of `%CLINK_PROFILE%` if it does not change the global profile unless you run two more commands? Shouldn't we add a check to 1. check for the variable and if not found, then use the 2. provided path or 3. default path?

This isn't about CLINK_PROFILE at all. It's purely about how the setup program sets up the autorun for best results, combined with wanting to subvert the purpose of the profile directory (I understand why you're doing it, but it's going to continue to cause other problems as well).

Maybe having per-user logs directory could be a compromise that would allow your system to support having more than one user on a machine.

> 2. How would I go about modifying the `All users:` flags in the `clink autorun show` command? The autorun commands were run in an elevated window.

I don't understand the question.

Current user overrides All users.
If current user autorun isn't set, then All users autorun is used.

This is about how CMD works, not really about Clink.

> 3. Have you considered if clink is vulnerable to an unquoted service path vulnerability since clink doesn't quote paths? Not my area of expertise, but even if I provide quotes, they were removed.

Please be specific -- where are you talking about?

**Comment by Zamanry** [comment]
Thanks for all the information! `clink autorun --help` explained my questions about quoting and all users. I'll work out the remaining portions myself. But feel this issue is resolved. Really appreciate the help!

**Comment by Zamanry** [comment]
By the way, I resolved my multiple users and one profile folder by setting `%CLINK_HISTORY_LABEL%` to `%HOMEPATH%`. `%USERNAME%` doesn't work because elevated shells will output as SYSTEM. So now the output history file name is: `clink_history-Userskali`

**Comment by chrisant996** [comment]
> By the way, I resolved my multiple users and one profile folder by setting `%CLINK_HISTORY_LABEL%` to `%HOMEPATH%`. `%USERNAME%` doesn't work because elevated shells will output as SYSTEM. So now the output history file name is: `clink_history-Userskali`

Two more things:
1. The `clink_settings` file will be shared by all users.  Meaning if one user changes a setting, it will affect all other users as well.
2. When I run `set username` in an elevated shell, it reports my username, not SYSTEM.  What was observed that led to the statement that `%USERNAME%` is SYSTEM?

**Comment by chrisant996** [comment]
@Zamanry Aha!  Between issues #385 (this one) and #382, I believe I've figured out what's happening.

In 2016 Martin made a change that accidentally broke CLINK_PROFILE so that it doesn't take effect if a profile directory has been specified through any other means, such as via autorun.

See https://github.com/chrisant996/clink/issues/382#issuecomment-1362032563 for details of the analysis.

A fix will be available soon.

Also:  you'll notice that in your case `clink info` and <kbd>Ctrl</kbd>-<kbd>X</kbd>,<kbd>Ctrl</kbd>-<kbd>Z</kbd> report _different profile directories_ for the same Clink session.  The latter is accurate, and the former is inaccurate due to the bug introduced in 2016.  Since the former was what we "expected" it should report, we assumed it was accurate; but it was not.
