### ISSUE TITLE
Columns does not change when resizing.

### ISSUE THREAD

**Issue by mrkingmidas** [chrisant996/clink#386]
Hello!

Situation:
The number of columns does not change if the cmd.exe or conemu window has been changed. The "C+A+L" command clears the screen, but the number of columns remains the same.
If you open cmd.exe, adjust the size, and already do "inject" there - then the number of columns is correct.

If I understood correctly, then in [issue #340] (https://github.com/chrisant996/clink/issues/340) the reason is described - the console application does not receive messages about changing the terminal size and this is not a quick / easy fix.

Question: is it possible to implement a command (hot key) to reinitialize the number of rows/slobs. Those. the user changes the terminal dimensions (and maybe the font via zoom), executes the command (hot key), clink reads the dimensions again, and if required by the library, clears the screen, already taking into account the new size.
If there is no way to get the information again from inside the running instance of clink, is it possible to somehow "close only click" in order to immediately restart it in the same session?

Sample: ![Resizing](https://i.imgur.com/UWpWH8z.gif)

**Comment by chrisant996** [comment]
Thank you for reporting this.

> Situation: The number of columns does not change if the cmd.exe or conemu window has been changed. The "C+A+L" command clears the screen, but the number of columns remains the same. If you open cmd.exe, adjust the size, and already do "inject" there - then the number of columns is correct.

Sort of...

> If I understood correctly, then in [issue #340] (#340) the reason is described - the console application does not receive messages about changing the terminal size and this is not a quick / easy fix.

340 is about other things. I confirmed in the debugger that Clink receives the resize messages.

It turns out that Clink and Readline accurately know the screen width. But Help and Completion respect a `completion-display-width` config variable in the `.inputrc` file. By default that's `-1`, in which case Readline uses the `%COLUMNS%` environment variable as the screen width.

When I replaced the Readline display code, I made it call `rl_set_screen_size()` to tell Readline the screen size.

But apparently it's necessary to _also_ call `_rl_get_screen_size()`, which has an undocumented side effect of _**setting**_ the screen size environment variables. It's confusing and unexpected that the "set" function only partially sets the size, and the "get" function _**sets**_ the other part of the size. 🤷‍♂️

> Question: is it possible to implement a command (hot key) to reinitialize the number of rows/slobs. Those. the user changes the terminal dimensions (and maybe the font via zoom), executes the command (hot key), clink reads the dimensions again, and if required by the library, clears the screen, already taking into account the new size. If there is no way to get the information again from inside the running instance of clink, is it possible to somehow "close only click" in order to immediately restart it in the same session?

Instead, all that's needed is to call `_rl_get_screen_size()` immediately after calling `rl_set_screen_size()`.
