### ISSUE TITLE
[history-substring-search] set cursor to the end matching substring

### ISSUE THREAD

**Issue by Mark-Joy** [chrisant996/clink#387]
Hello,
Thank you for wonderful app!

Say if I have a command history: `command arg1 arg2 arg3`
and `Up` key is set as `history-substring-search-backward`
If I type `arg2` then press  `Up`, cursor shall be set to the end of `arg2`

Currently, the cursor is set to the beginning of `arg2`

**Comment by chrisant996** [comment]
I think "shall" here means "please make a feature that behaves as follows". Am I understanding that correctly?

Please describe why the behavior change is desired. What is the usage scenario, with context, and why is different behavior requested?

**Comment by Mark-Joy** [comment]
> I think "shall" here means "please make a feature that behaves as follows". Am I understanding that correctly?
Yes, you are right.
Usage scenario is simple. If user want to modify what was typed (add more characters or delete some and then add some), it's best to do it at the ending position of what it was.
[history-search] keeps cursor position unchanged, in this case the end of what was typed. Could you please make [history-substring-search] option that do the same?

**Comment by chrisant996** [comment]
The requested change is not universally beneficial.  Everyone who is used to the existing behavior (which is identical to `bash`) would be negatively impacted by the requested change.

As it stands, I can't implement the feature request.

**Comment by chrisant996** [comment]
> Could you please make [history-substring-search] option that do the same?

I see now that you asked for a new configuration variable.  I'm trying to avoid diverging much from bash's Readline library, but I'll add it as a low priority item in the TODO.md list for future consideration.

> If user want to modify what was typed (add more characters or delete some and then add some), it's best to do it at the ending position of what it was.

Yes.  And also no.  Situations vary and personal preferences vary.  I'm very cautious about tweaking the behaviors of the Readline library very much because it leads to incompatibility with bash (etc), which opens the door for a different set of issues.

**Comment by chrisant996** [comment]
This is tracked in the TODO.md file.  I'm closing the issue since it's tracked in the work list, it's a low priority item, it diverges from the current Clink & Readline roadmap, and it would require support in Readline and the official bash itself.  It might be able to happen at some point, but in the meantime it won't be tracked as an open defect.
