### ISSUE TITLE
Switching between history-search and history-traverse 

### ISSUE THREAD

**Issue by Mark-Joy** [chrisant996/clink#388]
Hello,

Say, I have Up and Down keys setting up for history-substring-search
```
"\e[A": history-substring-search-backward            # arrow up
"\e[B": history-substring-search-forward             # arrow down
```
And command history:
```
command 1
command 2
## my note
command 3
command 4
command 5
```

1. If I type nothing and press `Up` repeatedly, command history shows `command 5` first and then `command 4`, then `command 3` ... I guess because there is nothing before the cursor position, so nothing to search that it show the comands sequentially.

2. If instead I type `note` and then press `Up`, command history is now show `## my note` as expected

3. After <2>, without pressing `Enter` or anything, if I press 'Home', to set the cursor back to position 0 (so that there is nothing to search for), and then press 'Up', I **expect `command 2` will show up**.

Currently, in <3>, `command 5` will show up

This feature is similar to `history.sticky_search = True`, but `sticky_search` requires `Enter` to be pressed between <2> and <3> and hence execute the command which is what I don't want.

**Comment by chrisant996** [comment]
It seems like the current behavior is intentional.

Please describe why the behavior change is desired. What is the usage scenario, with context, and why is different behavior requested?

**Comment by Mark-Joy** [comment]
> It seems like the current behavior is intentional.

Yes, in cases <1> and <2> the current behaviors are perfect. What I want is case <3>. What I want is a quick way to search my history like `history.sticky_search = True` but without excuting the command first (hitting `Enter`)
Since I have a bad memory, say, If I have a group of commands that relating to `xMyWork`, I would note it as below in history:
```
## xMyWork
command 1
command 2
command 3
```
- Suppose the requested feature already works:
To get to command 1, which was totally forgotten after some time, I would type `xMyWork` then hitting `Home`, then `Up` and `Down` to traverse history around my note `xMyWork`

- The current behavior can somewhat work by using option `history.sticky_search = True`:
To get to command 1, which was totally forgotten after some time, I would type `xMyWork` then hitting `Enter`, then `Up` and `Down` to traverse history around my note `xMyWork`

The different is hitting `Enter` executes the command, and error will appears since "## xMyWork" is just a note.

**Comment by chrisant996** [comment]
Thanks for explaining the background, and a little more about what behavior would be expected.

Bash and Readline intentionally reset the current `history-search-substring-backward` search context whenever a command other than `history-search-substring-backward` and `history-search-substring-forward` is invoked.  The <kbd>Home</kbd> key invokes the `beginning-of-line` command, which is neither of those, and so the search context is reset.

This is how all Readline commands work, with respect to resetting context.  `menu-complete` starts a new completion context if the previous command was not `menu-complete` or `menu-complete-backward`, otherwise it cycles through the results from the most recent menu-complete context.  And similar for many other commands.

So, unfortunately, to accommodate the request would require completely redesigning and rewriting how the Readline library deals with command contexts.  That would be very invasive and messy within the Readline library, and would make it very expensive and risky to apply any further updates that the Readline library publishes.

Additionally, it would be necessary to compile a list of which commands for each type of context shouldn't end the context.  That gets very messy, and would create problems and complexity for custom "luafunc:" macro commands as well.

Also, it would greatly impact familiarity and compatibility between Clink and `bash`.

I'm sorry, but this request cannot be accommodated.
