### ISSUE TITLE
how can i show errorlevel code in cmd

### ISSUE THREAD

**Issue by wizken** [chrisant996/clink#389]
> Linux `echo $?` show error code of last program.
> Windows `echo %errorlevel%` show error code of last program.

In Linux, I can see error code in zsh terminal.
I wonder if clink can implement this function.

**Comment by wizken** [comment]
Now I config env PROMPT that make cmd see like zsh.

```batchfile
PROMPT=^[[34m#^[[0m ^[[30;43m%USERNAME%^[[0m ^[[37@^[[0m ^[[32m%COMPUTERNAME%^[[0m^[[31m^(CMD^)^[[0m ^[[37min^[[0m ^[[33m$p^[[0m [$t]$_^[[0m^[[31m$$^[[0m$s
```

**Comment by chrisant996** [comment]
> > Linux `echo $?` show error code of last program.
> > Windows `echo %errorlevel%` show error code of last program.
> 
> In Linux, I can see error code in zsh terminal.
> I wonder if clink can implement this function.

It's already available, and mentioned in the documentation.

**Comment by chrisant996** [comment]
@wizken I had to read the question many times to figure out what was really being asked.

Setting an environment variable, for example `set PROMPT=whatever %VARNAME% whatever`, expands the `%VARNAME%` and sets the result into `%PROMPT%`.

Since you want to show the _current_ value of `%ERRORLEVEL%` each time the prompt is displayed, you can't accomplish that by a `set PROMPT` call.

See [Customizing the Prompt](https://chrisant996.github.io/clink/clink.html#customizing-the-prompt) in the Clink documentation for info on how to use a prompt filter to customize the prompt. Since prompt filters are run each time the prompt is displayed, you can get the current value of `%ERRORLEVEL%`.

**Comment by wizken** [comment]
Think you so much，Page [Customizing the Prompt](https://chrisant996.github.io/clink/clink.html#customizing-the-prompt) solved my problem.
