### ISSUE TITLE
Xterm colors not working in custom prompt

### ISSUE THREAD

**Issue by rashil2000** [chrisant996/clink#39]
Hey! I tried following your documentation https://chrisant996.github.io/clink/clink.html#customisingtheprompt for a custom prompt, but it seems to be behaving weirdly. This is my prompt function 

```lua
local custom_prompt = clink.promptfilter(50)
function custom_prompt:filter(prompt)
    local hello = io.popen("oh-my-posh"):read("*a")
    -- print(hello)
    return hello
end
```

[OhMyPosh](https://ohmyposh.dev/) is a shell-agnostic prompt customizing utility. 

The `print` statement (commented out in above function) works as intended, but when the same string is returned from the function, it messes up the formatting

![image](https://user-images.githubusercontent.com/46838874/103134802-d2001380-46d9-11eb-824a-942a6a5bfd1b.png)

Any idea how to resolve this?

**Comment by chrisant996** [comment]
Thank you for reporting this issue!  Also thanks for sharing; OhMyPosh looks cool.

What console host are you using; is that Windows Terminal?

Some things to try:
- Can you save the string to a file and attach the file to this issue?  I'd like to inspect the string to see if e.g. there is some particular ANSI escape code that's tripping up Clink.
- Can you share the OhMyPosh config so that I can try the exact same config on my machine?  I can try tinkering to see if I can come up with a config that also reproduces the issue, but the most direct approach would be to try with verbatim the same config.
- What happens if you change the `print(hello)` to `clink.print(hello)`?  That will print the string using Clink's output routines, which might behave differently, depending on the console host being used.
- What happens if you try in a standalone CMD console window?
- What happens if you use `clink set terminal.emulation native` to force Clink to let the underlying console host handle ANSI codes?  (It normally uses VT emulation; it's able to automatically detect ConEmu and disable its emulation, but I haven't found a way to detect Windows Terminal yet.)
- If you happen to have ConEmu installed already, what happens if you try in a ConEmu window?

**Comment by chrisant996** [comment]
Try `clink set terminal.emulation native` to force Clink to pass ANSI escape codes directly to the console.  It seems that oh-my-posh is emitting some code that confuses Clink's terminal emulation.  I'll dig into fixing that, but in the meantime setting the emulation mode to `native` appears to work around the issue.

**Comment by chrisant996** [comment]
FWIW, execution time for oh-my-posh is a little slow. Starting from the [cmder-powerline-prompt](https://github.com/AmrEldib/cmder-powerline-prompt) Clink scripts might be another interesting approach (there is less lag when showing a new prompt).

**Comment by chrisant996** [comment]
Oh, I see.  It's using xterm 256 color ANSI escape codes.  That got lost in Martin's rewrite from 0.4.9 to 1.0.0, and was on the list to add back but never happened.  I'll add support back for those.

**Comment by rashil2000** [comment]
> What console host are you using; is that Windows Terminal? 

Yes, it's Windows Terminal, but the problem persists in the default conhost.exe too (I even tried Alacritty, same problem). 

> I haven't found a way to detect Windows Terminal yet.

It's really easy to detect WT. Whenever we use Windows Terminal, the environment variables `WT_PROFILE_ID` and `WT_SESSION` are automatically set, which can be picked up by cmd, powershell or even WSL if required. 

> Try `clink set terminal.emulation native` to force Clink to pass ANSI escape codes directly to the console.

This seems to solve the issue everywhere (conhost, WT, alacritty). But there's some underlying error going on, because every time the prompt is printed, I can hear the error bell.

**Comment by rashil2000** [comment]
> FWIW, execution time for oh-my-posh is a little slow. 

Agreed. Actually, [Starship](https://starship.rs/) is another shell-agnostic utility, that I finally ended up using. Since it's written in Rust, it's faster than OhMyPosh (which is written in Go). And it doesn't cause any weird color issues.

> Starting from the cmder-powerline-prompt Clink scripts might be another interesting approach. 

Thanks for this! I too was looking for a pure Lua prompt config but I couldn't find any. Then I thought of using OhMyPosh and Starship.

**Comment by chrisant996** [comment]
> > I haven't found a way to detect Windows Terminal yet.
> 
> It's really easy to detect WT. Whenever we use Windows Terminal, the environment variables `WT_PROFILE_ID` and `WT_SESSION` are automatically set, which can be picked up by cmd, powershell or even WSL if required.

Yes.  That isn't a reliable indicator, though.  Suppose I'm using Windows Terminal and I run `start cmd.exe`.  The new cmd.exe opens in a separate console window that isn't using Windows Terminal, but `WT_PROFILE_ID` and `WT_SESSION` are still set.

**Comment by chrisant996** [comment]
> This seems to solve the issue everywhere (conhost, WT, alacritty). But there's some underlying error going on, because every time the prompt is printed, I can hear the error bell.

The bell is a problem with oh-my-posh itself:

`oh-my-posh.exe` is emitting the `\x07` bell character in its output.

Looking at the emitted output from oh-my-posh in a hex viewer, I see two interesting things:
1. It writes a bunch of color codes without any text between them to be colored. It produces an almost 2 KB string, most of which is superfluous ANSI escape codes that end up doing nothing. I guess that's just very inefficient, and doesn't cause any functional problem.
2. Near the end of the string, there is `\x1b]0;` _last path component of current directory_ `\x07`. According to [ANSI escape code](https://en.wikipedia.org/wiki/ANSI_escape_code) that is the OSC or Operating System Code, and it's free to be handled however the OS or terminal host chooses. In Xterm this particular sequence ending in the bell character sets the window title. So it's using a special Xterm-specific code that tries to set the window title to the last path component of the current directory. Windows Terminal doesn't handle that particular OSC sequence the same way as Xterm.

So I would say that as-is, the default theme isn't really compatible with Windows.

**Comment by rashil2000** [comment]
> The new cmd.exe opens in a separate console window that isn't using Windows Terminal, but WT_PROFILE_ID and WT_SESSION are still set.

Oh shoot, I hadn't really thought of child processes. Well, detecting WT becomes slightly more difficult then, as I have no other idea 😅

> So I would say that as-is, the default theme isn't really compatible with Windows.

Thanks for such a comprehensive breakdown. I checked, other OhMyPosh themes don't have this issue. 

So should I close this issue then?

**Comment by chrisant996** [comment]
> So should I close this issue then?

Thanks for asking -- let's keep it open. I'm using it to track adding support for VT emulation for 256 color and 24-bit color escape codes.

**Comment by rashil2000** [comment]
Great! I reckon you should change the title to reflect that, then.

**Comment by chrisant996** [comment]
> Great! I feel you should change the title to reflect that, then. 

I felt the title was close enough to satisfy me, but it also seems reasonable to want more detail. I've added the word "Xterm" for clarification.

**Comment by chrisant996** [comment]
@rashil2000 FWIW, I discovered another problem in oh-my-posh, so I opened (and closed) issue #40 so there's a searchable record for anyone else using Clink who runs into problems with oh-my-posh.

The default theme in oh-my-posh appends an escape code to clear to the end of the line. That will break any shell that uses Readline (e.g. Bash and Clink). Readline keeps track of what it's drawn so that it can update the display efficiently and only draw what needs to change. If something else erases Readline's output, Readline won't know and there are situations where the text won't be redrawn. Oh-my-posh shouldn't be emitting an escape code to clear to the end of the line; it's unnecessary, and it leads to input text intermittently disappearing.

**Comment by rashil2000** [comment]
@chrisant996 Hmm, should I alert the OhMyPosh dev by opening an issue pointing to this and #40? Would that be something you'd be comfortable with?

**Comment by chrisant996** [comment]
> @chrisant996 Hmm, should I alert the OhMyPosh dev by opening an issue pointing to this and #40? Or would you like to that yourself, since you're more well-versed with the issue?

Please feel free, and thank you.  The information in #40 should have everything the author needs. Also, I added steps to #40 for how to reproduce one of the kinds of scenarios where the input text will disappear.
