### ISSUE TITLE
could not enter commands correctly after execute xampp_shell.bat

### ISSUE THREAD

**Issue by liudonghua123** [chrisant996/clink#392]
I have installed xmapp, and when I tried to open xmapp shell via executing `xampp_shell.bat`. Autocomplete in cmd is always chaos and not working any more.

No such problems if I execute `xmapp` of `DOSKEY xmapp=set PATH=D:\xampp\;D:\xampp\php;D:\xampp\perl\site\bin;D:\xampp\perl\bin;D:\xampp\apache\bin;D:\xampp\mysql\bin;D:\xampp\FileZillaFTP;D:\xampp\MercuryMail;D:\xampp\sendmail;D:\xampp\webalizer;D:\xampp\tomcat\bin;%PATH%`.

xampp_shell.bat

```bat
@ECHO OFF

GOTO weiter
:setenv
SET "MIBDIRS=%~dp0php\extras\mibs"
SET "MIBDIRS=%MIBDIRS:\=/%"
SET "MYSQL_HOME=%~dp0mysql\bin"
SET "OPENSSL_CONF=%~dp0apache\bin\openssl.cnf"
SET "OPENSSL_CONF=%OPENSSL_CONF:\=/%"
SET "PHP_PEAR_SYSCONF_DIR=%~dp0php"
SET "PHP_PEAR_BIN_DIR=%~dp0php"
SET "PHP_PEAR_TEST_DIR=%~dp0php\tests"
SET "PHP_PEAR_WWW_DIR=%~dp0php\www"
SET "PHP_PEAR_CFG_DIR=%~dp0php\cfg"
SET "PHP_PEAR_DATA_DIR=%~dp0php\data"
SET "PHP_PEAR_DOC_DIR=%~dp0php\docs"
SET "PHP_PEAR_PHP_BIN=%~dp0php\php.exe"
SET "PHP_PEAR_INSTALL_DIR=%~dp0php\pear"
SET "PHPRC=%~dp0php"
SET "TMP=%~dp0tmp"
SET "PERL5LIB="
SET "Path=%~dp0;%~dp0php;%~dp0perl\site\bin;%~dp0perl\bin;%~dp0apache\bin;%~dp0mysql\bin;%~dp0FileZillaFTP;%~dp0MercuryMail;%~dp0sendmail;%~dp0webalizer;%~dp0tomcat\bin;%Path%"
GOTO :EOF
:weiter

IF "%1" EQU "setenv" (
    ECHO.
    ECHO Setting environment for using XAMPP for Windows.
    CALL :setenv
) ELSE (
    SETLOCAL
    TITLE XAMPP for Windows
    PROMPT %username%@%computername%$S$P$_#$S
    START "" /B %COMSPEC% /K "%~f0" setenv
)

```

https://user-images.githubusercontent.com/2276718/209159300-628d6508-ad82-4cfe-8095-2172a5f2d56f.mp4

**Comment by chrisant996** [comment]
The problem is caused by the `start /B` flag.

The help for `start /?` says the `/B` flag "Start application without creating a new window. The application has ^C handling ignored. Unless the application enables ^C processing, ^Break is the only way to interrupt the application."

So now you have two different instances of cmd.exe that are _**both**_ using the same terminal window, and they're fighting with each other for both input and output.  The only possible outcome is chaos (and that's not how to use `/B`).

I think that you're trying to make the `xmapp_shell.bat` script take over the current terminal without starting a new terminal.  If that's what you're trying to do, then `/B` is not how to do that.

Instead, simply delete the `START "" /B ` part.

**Comment by liudonghua123** [comment]
@chrisant996 Thanks for the detailed explanations, delete the `START "" /B ` part works for me! 😄
