### ISSUE TITLE
Unit testing custom completions

### ISSUE THREAD

**Issue by sebthom** [chrisant996/clink#425]
Do you have any ideas/suggestions how to implement/run unit test for custom completions?

**Comment by chrisant996** [comment]
@sebthom can you clarify "custom completions"?  What part of completions, specifically?

There are many unit tests for many aspects of argmatchers and generators and completion commands.
Most of the unit tests that involve custom generators are in these unit test files:
- clink/app/test/env_vars.cpp
- clink/app/test/exec.cpp
- clink/app/test/set.cpp
- clink/lua/test/args.cpp

Also, argmatchers are implemented internally as a custom generator.

**Comment by sebthom** [comment]
I am looking for a way to automatically test my lua scripts at https://github.com/sebthom/more-clink-completions/tree/main/src
e.g. against different clink versions.

**Comment by chrisant996** [comment]
> I am looking for a way to automatically test my lua scripts ... against different clink versions.

@sebthom Ohhh, got it. I thought you meant testing Clink itself.

Yeah, unit testing custom scripts is a hard problem, esp. for backward compatibility against many versions of Clink.

In theory, you could programmatically drive Clink itself. You could inject Clink and point it at a specific profile or script directory that contains test harness scripts. They could use `onbeginedit`, `onendedit`, `onfilterinput`, `onprovideline`, etc to take over control of input. Or use WScript and Send keys to push input. Or probably even redirect stdin for the CMD instance, which would be more universal across versions. Probably you could also capture stdout and analyze it. Some things might be better tested by directly invoking generators by taking advantage of observing implementation details.

Also, you may have noticed the undocumented `clink lua` command which runs a standalone Lua 5.2.4 engine plus Clink's Lua API extensions. That could potentially help. But it's only available in very recent versions, it isn't documented or supported yet, and it may undergo breaking changes before it reaches beta stability. And currently it doesn't even load API extensions that can't be used outside of Clink, such as the argmatcher APIs (I'll consider whether unit testing warrants initializing everything, or if there's a better alternative).

I don't have a good solution for this problem currently, but I'm happy to work together towards something.

**Comment by sebthom** [comment]
`clink lua` sounds nice. I will give it a try :-)

**Comment by sebthom** [comment]
So using the embedded Lua interpreter I can access the objects console, log, os, path, settings, strings, unicode and partially the clink object. Unfortunately as you pointed out on the clink objects all the functions that come from arguments.lua, events.lua, generator.lua are missing currently missing. If they could be made available somehow, that would allow a great way for unit tests.

Btw. the reason why I am so active atm is that I created an integration project (https://github.com/vegardit/haxe-clink-externs) that allows you to write custom clink scripts in [Haxe](https://haxe.org/) instead of Lua which has the big advantage of compile time type safety. Here are some simple tests that interact with the API https://github.com/vegardit/haxe-clink-externs/blob/main/test/clink/TestRunner.hx

**Comment by chrisant996** [comment]
The embedded Lua interpreter won't be very useful for backward compatibility testing, since it's only present in very recent versions.

I would ideally aim for something that works even with Clink v0.4.9.  I think that should be possible by launching cmd.exe with a special command line, with stdin and stdout redirected, and with a custom test harness Lua script.

I'll begin looking into that probably this weekend.

E.g. something along these lines:
```cmd
cmd.exe > "%temp%\output.txt" < "%temp%\input.txt" /k clink inject --profile c:\clink-unit-test-harness\profile
```
With an outer harness that generates appropriate input.txt files and informs the test harness Lua script which test(s) are being run.

**Comment by sebthom** [comment]
I am personally not looking for backward but forward compatibility tests. I.e. I want to define a minimum version against which I develop my scripts (and I don't mind if I start with a recent clink release).

Btw, the exposure of the embedded Lua interpreter is super useful as it allows me to precisely unit test the Haxe-Lua integration on clink API method level.

**Comment by sebthom** [comment]
I just realized that when a Lua runtime error occurs in `clink lua` mode, the clink/lua process exits with exit code 0. Would it be a big thing to change this?

**Comment by chrisant996** [comment]
> I just realized that when a Lua runtime error occurs in `clink lua` mode, the clink/lua process exits with exit code 0. Would it be a big thing to change this?

That's a bug.  It should behave the same as using the official `lua52.exe`, but that returns 1 as the exit code.

**Comment by chrisant996** [comment]
I spoke too soon:  I can't reproduce 0 as the exit code.
For me, the exit code is 1 if the specified script encounters an error.

Can you share more details about how you're using `clink lua` that results in an expected 0 exit code?

Here's what I experience:
```cmd
❯ testexitcode.bat
ERRORLEVEL before is 0
foo.lua:1: attempt to index global 'prgoas' (a nil value)
ERRORLEVEL after is 1
```

_**testexitcode.bat**_
```cmd
@echo off
echo ERRORLEVEL before is %errorlevel%
call c:\wbin\clink\clink.bat lua textexitcode.lua
echo ERRORLEVEL after is %errorlevel%
```

_**testexitcode.lua**_
```lua
prgoas.askdjfhklasdf()
```

**Comment by sebthom** [comment]
The issue is apparently is in Haxe which generates Lua code that catches the error and prints it but does not exit the process. I opened a ticket there. Sorry for the confusion.

**Comment by chrisant996** [comment]
Regarding unit testing, I tried to use redirected stdin to drive Clink, but CMD is smart enough to process all stdin before showing a prompt, so Clink doesn't see any of it.

The only way to do it in a cross-version way will be to send keystrokes, e.g. via WScript SendKeys.

**Comment by chrisant996** [comment]
The plan for `clink lua` is to be a Lua interpreter, but with Clink API extensions.  The argmatcher stuff doesn't really make sense there, as the _only_ thing that could make any use of it would be unit tests, and they'd be unable to actually _use_ the argmatchers since there is no actual input line editor.

For unit testing purposes, it would be much more effective (and work with more versions of Clink) to use the approach I outlined earlier:

> In theory, you could programmatically drive Clink itself. You could inject Clink and point it at a specific profile or script directory that contains test harness scripts. They could use `onbeginedit`, `onendedit`, `onfilterinput`, `onprovideline`, etc to take over control of input. Or use WScript and Send keys to push input. Some things might be better tested by directly invoking generators by taking advantage of observing implementation details.

**Comment by chrisant996** [comment]
@sebthom unit testing for custom match functions can be done with the `clink lua` interpreter.

Unit or integration or system testing for constructed argmatchers and completion commands is much more complicated because Clink's design runs inside CMD and is subject to CMD's rules of operation.  I don't think even sending keys is sufficient, and it would be susceptible to interference from actual keyboard input.

I'll explore possibly adding a "line editor tester" component in the `clink lua` interpreter engine, for the purposes of allowing unit test code to exercise argmatchers and commands independently from user input (similar to how Clink's own unit tests work, though they're written in C++).

**Comment by chrisant996** [comment]
@sebthom do you mean literally "unit testing" your custom completions?  I.e. you're trying to exercise/test only your own code, and not all the outer Clink code?

If so, then the `clink lua` interpreter engine seems sufficient.
The `clink lua` command will stay (I'm using it myself for various things), but I haven't decided how/when to document it.

But if you mean "integration testing" to run the outer Clink code and test the end-to-end execution, then that's not really possible because of the fact that Clink has to inject itself into CMD, and in reality _CMD_ is in overall control.  The standalone interpreter engine can't emulate that thoroughly enough to enable accurate/meaningful integration testing.

I built a prototype "line editor tester" usable from Lua.  I found that it's just not a viable concept.  For simple things it can produce the same results as would happen at the real input prompt.  But since it isn't the real input prompt, many things simply cannot work the same.  And that means the tester's accuracy is unreliable.  Also, it's something very few people would use, and it's inherently complicated to use which further reduces the audience of people who would use it.  I won't invest further in it at this time.
