### ISSUE TITLE
io.truncate return value different than documented

### ISSUE THREAD

**Issue by sebthom** [chrisant996/clink#429]
At https://chrisant996.github.io/clink/clink.html#io.truncate it states:
```
If successful, the return value is the position at which the file was truncated. 
If an error occurs, the return values are nil, an error message, and an error code.
```

However in my tests the return value is not an int but a boolean which is true in case of success or false in case of failure. Also I don't see nil returned in case of failure (e.g. missing permission).

So is the doc wrong? The implementation? Or is this an end-user (me) issue?

**Comment by chrisant996** [comment]
@sebthom Ugh. At this point it has to be considered a doc bug.

Here is what happened:

1. The intended implementation was to return the size.
2. There is no predefined Lua helper function for conditionally returning an integer or a system error, but there is one for Boolean.
3. I hooked it up using the Boolean one, with the intent of updating the implementation to manually return an integer on success, or use the helper function on failure.
4. But I didn't end up doing that.

Also, returning a file position is a little tricky in Lua, because all numbers in Lua are `double` IEEE 754 floating point numbers.  So larger than 52 bits, the number would be inaccurate due to IEEE 754 limitations.  That's dangerous in a file IO API.

So I think that the best thing to do is update the documentation to match the actual behavior, and if actual file size or position is ever needed, then a new API will need to be created that can return the file size or position.

Currently `os.globfiles(pattern, 2)` can return the file size, but it has the same 52 bit limitation.  When listing directories, that's a little more understandable than when getting the file position counter in an active file stream.

P.S. Thank you for all these doc updates!!!
