### ISSUE TITLE
How about adding an automatic update mechanism?

### ISSUE THREAD

**Issue by UweKeim** [chrisant996/clink#441]
Since last year, that `clink update` command is really a joy to use. Thanks again for that feature.

To me, the next logical step would be to do a completely automatic update with zero user interaction.

Could this be something that you might be interested in developing?

I do not have a real idea how this might be implemented, some ideas come to my mind:

- Add a Scheduled Task that does the updating.
- Do it once every _n_ hours/days when the first console window is startet and clink is loaded.

Just some ideas.

**Comment by chrisant996** [comment]
I'm not comfortable with automatic forced updates for Clink, for several reasons. Especially when installed with AutoRun as the potential for conflicts is high.

But if you want to silently update Clink, you can do that with a very tiny script. It doesn't need to be built into Clink.

I'd be more likely to recommend turning _off_ automatic check for updates, and just run `clink update` manually once a month.

To that end, I have been thinking of adding a flag that checks for an update without doing the update, e.g. maybe `clink update --check`.

**Comment by chrisant996** [comment]
You could also run `clink set clink.update_interval 30` to make Clink only check for updates once a month.  (And if you run into some kind of problem, then check the Releases page and/or run `clink update` to check if a newer release fixes the problem.)

Another option is for me to publish releases less frequently.  They've backed of to an average of once per week, but that's still pretty frequent.  I could add an option to choose whether to install pre-release updates or release updates, and make releases infrequent.  I keep thinking it's close to having releases be very infrequent, but there keeps being a slow trickle of things that need changes.

**Comment by chrisant996** [comment]
> BTW: Any donation button or something like that available?

Thank you for asking, but nope -- I don't accept donations at this time. 🙂

**Comment by chrisant996** [comment]
I'm working on a more automatic approach to updates.

I have a prototype in progress, where it can be configured to install updates automatically in the background if it doesn't need to elevate (i.e. if it's installed via .zip file instead of the setup exe).  And if elevation is needed, then it can pop up a prompt window asking whether to install the update or skip the update or prompt again later.

I'm working on a few last kinks before it's ready for release.

**Comment by UweKeim** [comment]
Just some nitpicking:

Calling `clink update` results in:

> No update available; local version v1.5.6 is not older than latest release v1.5.6.

While this is correct and tells me that I'm up to date, it is actually shown in **red** text, and also says "No...".

![image](https://github.com/chrisant996/clink/assets/415439/17edb1c7-b90c-4523-b7f8-2f301c952110)

Red usually means "danger"/"error". "No" usually means an error, too.

How about changing the text to something positive in **green**?

> Everything is up to date! Your local version v1.5.6 is the most recent release 😊

Instantly recognizable:

![image](https://github.com/chrisant996/clink/assets/415439/f939d32b-3137-4493-8584-0dac1dff4e56)

This would help me detecting quicker that there is no error but this is actually a good result.

**Comment by chrisant996** [comment]
I see.  You're using `clink update` to _check_ for an update, instead of to apply an update.  That wasn't how I'd intended/imagined for it to be used.

But it seems reasonable to use it that way.  Presumably you've disabled the automatic checks for updates, and you're just periodically using `clink update` to test for updates on demand?

I understand the intend behind the suggested phrasing and smiley face, but I can't quite go there:  a user can have multiple copies of Clink installed, and each one needs to get updated separately.  So saying "everything is up to date" can be a misleading overstatement.  I won't use emoji, because they only work in certain terminals -- for example the default conhost and ConEmu and ConsoleZ cannot render emoji.

I'll look into changing the design so that it doesn't assume the intent of `clink update` is to apply an update that has already been advertised to the user, and that it may instead be used to test for existence of updates.

**Comment by chrisant996** [comment]
@UweKeim It's not a simple as just changing the text or color or exit code.  Currently the design is that success means apply an update, and failure means don't.  To make a "success but don't apply an update" state, I will have to do a somewhat significant redesign of the updater, and either do some significant refactoring or bubble more detailed directives up and down through the layers in the updater.

I'll put it on the todo list, but it's low priority and may take a while.  Sorry, that kind of usage wasn't on my mind when I designed the updater.  It was designed as a command you run once you've been notified that an update is available.  There are a lot of things that have to change in order to make it behave the way you expected, and it will also be a breaking change if any scripts look at the exit code from `clink update`.  This is unfortunately not a quick or simple task.

Out of curiosity, can you share what is the usage scenario?  Is there a reason not to use `clink set clink.update_interval 1` and `clink set clink.autoupdate auto` (or `clink set clink.autoupdate prompt`)?  That combination would make Clink automatically check for an update once per day _**and also automatically apply an update if available**_.

**Comment by UweKeim** [comment]
Thank you very much, Chris.

Actually, I've enabled `clink set clink.autoupdate auto` and still, my OCD (or how one calls it) just makes me want to do it anyway. Shame on me! (I'm also the guy that regularily presses <kbd>Ctrl</kbd>+<kbd>S</kbd> in Microsoft Office Word and all other application beside the fact that they do auto-save, too.

So there is really no actually meaning in me doing a `clink update`. I've just written my above comment to possible improve the behavior in possibly other scenarios.
