### ISSUE TITLE
Documentation for `globpattern` missing

### ISSUE THREAD

**Issue by sebthom** [chrisant996/clink#443]
I was looking for a documentation what glob pattern features are supported by os.globFiles() but couldn't find anything.

I want something like `os.globFiles("**/*.{yml,yaml}"))` but that does not work.

**Comment by chrisant996** [comment]
Martin called it "glob" but he meant it in the loose sense.
You're thinking of GNU `fnmatch` globbing syntax, or git `wildmatch` globbing syntax.

The `os.globfiles()` function uses Win32 wildcard syntax when performing globbing -- it didn't seem to need special in depth documentation, since it's how Windows works and CMD works and etc.

In the [TODO.md](https://github.com/chrisant996/clink/blob/master/TODO.md) file you'll notice a todo item regarding supporting `fnmatch` and `wildmatch` and recursive globbing.

**Comment by chrisant996** [comment]
@sebthom P.S. today I finished implementing an `os.globmatch()` function, which behaves [the same as git](https://git-scm.com/docs/gitignore#_pattern_format) in the .gitignore file (e.g. "**/*.txt" and so on). Also a `path.fnmatch()` function is coming which behaves like the Linux function `fnmatch(3)`.
