### ISSUE TITLE
Prompt auto_answer display blank lines if prompt have new line for answering

### ISSUE THREAD

**Issue by asen23** [chrisant996/clink#446]
i don't really know how to explain it but it give weird visual glitch like this
![image](https://user-images.githubusercontent.com/31660481/228608109-1abe2a0f-01f9-46e9-8349-acca365b45b1.png)

this happen with pnpm prompt where they give new line after asking the prompt like this.
![image](https://user-images.githubusercontent.com/31660481/228608321-47cb15e5-50d4-4ad6-8854-7ccc06ee547d.png)

is there anyway to fix this?

**Comment by chrisant996** [comment]
There are multiple processes all using the same console window concurrently.  You're using Ctrl-C or Ctrl-Break to interrupt one of them, but some others are still running, and they briefly continue to output text to the console window even after control has returned to the shell.  That's not a problem in Clink, and there's nothing Clink can do about that.

One thing that might be exacerbating it is the value of the `cmd.auto_answer` setting.

Try running `clink set cmd.auto_answer`.  If the value is anything other than `off`, then try running `clink set cmd.auto_answer off`.  That way Clink won't automatically answer "Y" to the "Terminate...?" question, which might give time for the other processes to calm down and stop stomping on the console window output.

**Comment by asen23** [comment]
> There are multiple processes all using the same console window concurrently. You're using Ctrl-C or Ctrl-Break to interrupt one of them, but some others are still running, and they briefly continue to output text to the console window even after control has returned to the shell. That's not a problem in Clink, and there's nothing Clink can do about that.

If that is the case, is there anything that can be done other than turning off auto answer though?

> One thing that might be exacerbating it is the value of the `cmd.auto_answer` setting.

yes, turning it off fixes the problem but now i don't have auto answer from clink.

**Comment by chrisant996** [comment]
You'd have to look at specifically which processes are piping output, and identify which process is printing to stderr in response to the Ctrl-C error state. Or etc.

I guess I could maybe add an optional delay in the auto-answer, but that creates other drawbacks.

The problem is the piping is not set up in a way that fully suppresses visible output. Clink can't do anything about that. Whoever/whatever is constructing and running whatever command you're interrupting would need to fix how the commands and piping is done.
