### ISSUE TITLE
Tab completion messes up ..\ in partial path when no matches found

### ISSUE THREAD

**Issue by kahlkevin** [chrisant996/clink#448]
### Repro

0. Using `Clink v1.4.23.5fc3fc`
1. Have directory structure:
```
.
├── foo
│   └── file1.txt
└── bar
```
2. Navigate to \bar
3. Enter `notepad ..\foo\z` and press Tab to initiate file name completion

### Result
You'll end up with `notepad .\foo\z` (notice missing `.`) with cursor positioned just after the first dot.

### Expect
Cursor flash/bell since no matches found, but also no modification of the in-progress command line and no cursor reposition.

**Comment by chrisant996** [comment]
Confirmed.  What a strange one.  Thanks for reporting it.  I'll investigate and fix.

**Comment by chrisant996** [comment]
It's due to the path disambiguation algorithm, combined with a quirk in how the `FindFirstFile()` API behaves with a search pattern that begins with `.` (which drops into some compatibility logic for DOS).

@kahlkevin You can work around it by running `clink set match.expand_abbrev false` to turn off the path disambiguation feature.

**Comment by chrisant996** [comment]
The fix will appear in the next release (v1.4.24).
