### ISSUE TITLE
Newbie question about window background

### ISSUE THREAD

**Issue by Dan-Essin** [chrisant996/clink#454]
I'm confused and the docs don't seem to address this point.
After installing, if I open the usual cmd.exe, clink is active and the prompt text is bright white in a black background. That's what I prefer.

If I open clink from the program menu, the prompt text is light grey and the background is dark grey.

Both are using  C:\Program Files (x86)\clink\default_settings as far as I can tell.

I've read about the settings and customizing the prompt but there doesn't seem to be a simple way to make clink.exe behave like cmd.exe for the default plain text and background colors.

I must have missed it. Where do I find, adjust these settings?

Thank you

**Comment by garoto** [comment]
Both shortcuts use different `cmd.exe` .lnk set properties, as in default colors for both FG and BG and possibly others. 

It's confusing, I know.

**Comment by chrisant996** [comment]
@Dan-Essin What version of Windows are you using?
When you start Clink from the Programs menu, what kind of window opens up -- is it a Windows Terminal window?

Maybe Windows Terminal is currently configured to force Light theme on all console windows?
It could be that you need to change the Windows Terminal configuration.

The default terminal colors are part of the OS, not part of Clink.  That's why Clink documentation doesn't cover that.  Also, there are many ways for LNK files and terminal programs and user configuration to influence the terminal colors, and trying to have a section in Clink docs about all the external possibilities and troubleshooting would be very long and confusing, and is really outside of what Clink is.

**Comment by ahmed-redda** [comment]
ls , grap , file , touch , --help all this commands are not  recognized as an internal or external command,
operable program or batch file on my windows , why this ?? i am looking for help

**Comment by chrisant996** [comment]
Those are Linux commands.  CMD and Clink are not Linux.  If you want to use Linux commands, then use Windows Subsystem for Linux, or use cygwin or msys2 or another Linux emulation system.
