### ISSUE TITLE
Startup time significantly slower in 1.4.25.e0d48c

### ISSUE THREAD

**Issue by Uxorious** [chrisant996/clink#459]
I just upgraded from 1.4.24, and startup is not significantly slower.
In the previous version (.24), a new interactive console starts up without any significant delay.
With .25, it will stop for 2-3 seconds after printing the Microsoft copyright line. Then the Clink version info will be printed, and the console will be ready.

**Comment by chrisant996** [comment]
@Uxorious which anti-malware suite are you using?

No changes between .24 and .25 can affect startup time.
Startup continues to be instantaneous for me.

Usually delays are caused by anti-malware suites.
- You can try adding an exclusion for cmd.exe, but that of course could risk making anti-malware ignore attacks that involve cmd.exe.
- You can try disabling the anti-malware suite, to confirm whether that's related.  **BUT** be aware that many anti-malware suites have multiple different protections running at the same, and disabling one protection doesn't disable the other protections.  For example, turning off file protection might still be slow, if the slowness is coming from stateful behavior monitoring instead of from file protection.  Until **ALL** protections are disabled, slowness could persist.

Unfortunately neither I nor Clink can do anything about overly aggressive anti-malware suites.

**Comment by Uxorious** [comment]
I'm using ESET Internet Security 16.1.14.0.
And I'm on Windows 11 (all the latest updates available without signing up for Insider).
I tried disabling ESET (no live scanning) and it was still slow...

**Comment by chrisant996** [comment]
See https://github.com/cmderdev/cmder/issues/2816.

Try turning off "Deep Behavioral Inspection".

Adding an exception for cmd.exe will likely work around the ESET performance issue, but could reduce protection against some kinds of malware.

Report the problem to ESET.

**Comment by Uxorious** [comment]
Interesting - thanks for the link.
Before I read this, I had uninstalled ESET - and sure enough, it ran quick.
I just reinstalled it - and it's *still* quick.
Deep Behavioral Inspection is ON by default, so no idea why it's not slow now.
