### ISSUE TITLE
Double click on Clink.bat to flash back

### ISSUE THREAD

**Issue by xyongsec** [chrisant996/clink#460]
双击Clink.bat闪退出

**Comment by chrisant996** [comment]
Google translates that as "Double-click Clink.bat to flash out".

That doesn't give me enough information to understand what happened.

Please share much more information.  The more details, the better.  Screenshots can be especially useful to help clarify when automated translation is unclear.

**Comment by xyongsec** [comment]
https://github.com/chrisant996/clink/assets/48509164/7bb56781-babd-4144-9351-3a196cd3e845

**Comment by chrisant996** [comment]
@xyongsec Thank you for the video, that helped very much!

I've never seen that happen before, and I don't know yet what could cause it.

Here are some questions to help figure it out:
- Is this the first time you have used Clink?  Has this worked in the past, and stopped working?  Or has it never worked?
- Try checking whether your system protection software might have blocked Clink.
- Does the path to Clink have any non-English text?  (Maybe there is a problem in clink.bat with international paths, however if that's the case then I would be surprised none of the other users with international paths have reported this before.)
- Try to find the `clink.log` file.  If you can find it, please share it here -- the file may have information that can help troubleshoot the problem.  The file is normally located at `C:\Users\<your_user_name>\AppData\Local\clink\clink.log`.  Or you can email it to the address in my github profile.
- What happens if you uninstall Clink, and then reinstall but _**uncheck**_ the box for "Autorun when cmd.exe starts"?
![image](https://github.com/chrisant996/clink/assets/17440311/eaebb1ca-3edd-45c2-8ff0-56e1d3ee014a)

**Comment by xyongsec** [comment]
3c6c start_logger              160 ---- 2023/06/02 10:11:52.922 -------------------------------------------------
3c6c start_logger              166 Host process is 'cmd.exe' (pid 15468)
3c6c start_logger              170 DLL path is 'C:\Program Files (x86)\clink'
3c6c start_logger              185 Windows version 10.0.19045 (x64)
3c6c start_logger              187 Clink version 1.4.25.e0d48c (x64)
3c6c hook_setter::hook_setter  159 >>> Started hook transaction.
3c6c hook_setter::attach_iat   316 Attempting to hook SetEnvironmentVariableW in IAT for module 00007FF7C99D0000.
3c6c pe_info::iterate_imports  159 Found import in 'api-ms-win-core-processenvironment-l1-1-0.dll'
3c6c find_iat                  124 Found import at 00007FF7C9A03860 (value is 00007FF803482FC0).
3c6c hook_setter::attach_iat   316 Attempting to hook WriteConsoleW in IAT for module 00007FF7C99D0000.
3c6c pe_info::iterate_imports  159 Found import in 'api-ms-win-core-console-l1-1-0.dll'
3c6c find_iat                  124 Found import at 00007FF7C9A034F8 (value is 000000006B457990).
3c6c hook_setter::attach_iat   316 Attempting to hook GetEnvironmentVariableW in IAT for module 00007FF7C99D0000.
3c6c pe_info::iterate_imports  159 Found import in 'api-ms-win-core-processenvironment-l1-1-0.dll'
3c6c find_iat                  124 Found import at 00007FF7C9A03880 (value is 000000006B454120).
3c6c hook_setter::commit       207 <<< Hook transaction committed.
3c6c hook_setter::hook_setter  159 >>> Started hook transaction.
3c6c hook_setter::detach_iat   359 Attempting to unhook 00007FFFAD21B010 from GetEnvironmentVariableW in IAT for module 00007FF7C99D0000.
3c6c pe_info::iterate_imports  159 Found import in 'api-ms-win-core-processenvironment-l1-1-0.dll'
3c6c find_iat                  124 Found import at 00007FF7C9A03880 (value is 00007FFFAD21B010).
3c6c hook_setter::commit       207 <<< Hook transaction committed.
3c6c hook_setter::hook_setter  159 >>> Started hook transaction.
3c6c hook_setter::attach_iat   316 Attempting to hook ReadConsoleW in IAT for module 00007FF7C99D0000.
3c6c pe_info::iterate_imports  159 Found import in 'api-ms-win-core-console-l1-1-0.dll'
3c6c find_iat                  124 Found import at 00007FF7C9A034E0 (value is 000000006B453960).
3c6c hook_setter::commit       207 <<< Hook transaction committed.
3c6c hook_setter::hook_setter  159 >>> Started hook transaction.
3c6c hook_setter::attach_iat   316 Attempting to hook SetConsoleTitleW in IAT for module 00007FF7C99D0000.
3c6c pe_info::iterate_imports  159 Found import in 'api-ms-win-core-console-l2-2-0.dll'
3c6c find_iat                  124 Found import at 00007FF7C9A03558 (value is 00007FF8034969E0).
3c6c hook_setter::commit       207 <<< Hook transaction committed.
3c6c win_screen_buffer::begin  279 Using native terminal support; found 'ANSI64.dll'.
3c6c init_cached_font          553 console font "新宋体", cell width 9, pitch and family 0x36
3c6c init_cached_font          554 East Asian Ambiguous mode 3
3c6c host_lua::load_scripts    158 Loaded 0 Lua scripts in 0 ms
3c6c ={update.lua}               0 Clink updater: too soon to check for updates (1685433729 vs 1685671912).
3c6c history_db::initialise   1264 master bank ctag: |CTAG_1684292149_67792828_17948_0
3c6c history_db::compact      1526 History:  218 active, 194 deleted
3c6c history_db::compact      1526 History:  218 active, 194 deleted
3c6c history_db::compact      1526 History:  218 active, 194 deleted
3c6c history_db::compact      1526 History:  218 active, 194 deleted

**Comment by xyongsec** [comment]
![image](https://github.com/chrisant996/clink/assets/48509164/f408a6a9-dc1c-447b-9ac2-4e497ad6615b)

**Comment by xyongsec** [comment]
Unchecked and reinstalled with no change

**Comment by chrisant996** [comment]
Interesting!  I see that you have ANSICON loaded (`ANSI64.dll`).

What version of ANSICON are you using?

The last official release v1.89 in 2019 has a crash that looks likely to be related.  See https://github.com/adoxa/ansicon/issues/130.  In 2020 the author tracked down the crash, but there hasn't been a new official release since then.  I wonder if the window may be disappearing because ANSICON crashes immediately.  If you check in the system Event Viewer (`eventvwr.exe`) you might be able to find if any crashes are logged for cmd.exe.

I would recommend to stop using ANSICON, since it is known to have stability issues and performance issues, and also for many years Windows has had significantly better built-in escape code support than what ANSICON provides.

**Comment by chrisant996** [comment]
@xyongsec Since you're using Windows 10, the simplest fix is probably to stop using ANSICON -- it isn't needed on Windows 10, and it can cause various problems (including slow output), so it's probably better to stop using it.

Also, Clink v1.4.27 fixes a crash in Clink caused by some invalid data inside ANSI64.dll or ANSI32.dll while using the `clink.bat` script to open a new Clink window, if ANSICON is configured to automatically install itself into cmd.exe.

Either of those might help to resolve the problem you're encountering.
