### ISSUE TITLE
Dynamic Command-Specific Tab Titles

### ISSUE THREAD

**Issue by koppor** [chrisant996/clink#473]
Currently, the functionality to dynamically change the title of a ConEmu tab to reflect the last command run within it is not available.  This feature is valuable for users who often have multiple tabs open and need to quickly identify each tab's purpose without manually setting the title for each command run.

The desired functionality is akin to what some Unix-like shells offer, where the shell's prompt command (which gets run after every command) or specific shell hooks/tracing features allow dynamic tab title changes.

A suggested implementation would be to introduce a variable similar to the PROMPT_COMMAND in bash, which can be run after every command to capture the command and change the tab title accordingly.

    export PROMPT_COMMAND='ConEmuC -GuiMacro Rename 0 `history 1 | cut -c 8-`'
 
Such an enhancement would significantly improve the usability and efficiency for Clink users, especially those dealing with complex or long-running tasks across multiple tabs. This feature request is in line with Clink's goals of improving the command-line experience on Windows.

The wish is to add configuration for dynamically changing the title:

Mode | Description
-- | --
off | Does not issue a ConEmu command to change the tab title
on | Issue a ConEmu command to change the tab title after each command
auto | Lets Clink check if it runs inside ConEmu and issue the command to change the tab title depending on whether it runs inside ConEmu.

**Comment by chrisant996** [comment]
As described, the suggestion would malfunction when people use escape codes that change the title.

Also, I don't plan to build any ConEmu-only features into Clink.

Instead, make a script that prints the ConEmu escape code for setting the title.  Depending on when you want the title to change, you may want to use `clink.onbeginedit()` and/or `clink.onendedit()`.

**Comment by chrisant996** [comment]
By default, ConEmu now blocks the escape codes for setting the title (and various other escape codes), for security purposes. 
 See https://github.com/Maximus5/ConEmu/commit/122670ffceb6cb4c5934fbe6e84336bdb4f049b1 which implemented the security protection.

**WARNING:**  Be very careful when invoking `conemuc` with another command line as input.  That is easily susceptible to a classic "injection attack" by accident.  Depending on what command line is typed and passed to `conemuc`, the command line could accidentally end up getting executed or partially executed instead of setting the title.

Here is a sample script.

It has two settings, which control whether/how it updates the tab title for ConEmu.

```lua
-- luacheck: no max line length
settings.add('conemu.tab_title', {'auto','off','force'}, 'In ConEmu, runs conemuc.exe to set the title after every command prompt.')
settings.add('conemu.assume_ansi_codes_blocked', true, 'By default, ConEmu blocks setting tab titles via escape codes.  If you\nconfigure ConEmu to allow them, you can set this to false which will\nremove the delay before the input command line gets runs.')

local function set_title(title)
    local mode = settings.get('conemu.tab_title')
    if mode ~= 'force' then
        if mode == 'auto' then
            local host, detected = clink.getansihost()
            if detected ~= 'conemu' and host ~= 'conemu' then
                return
            end
        else
            return
        end
    end

    if settings.get('conemu.assume_ansi_codes_blocked') == false then
        -- Sanitize the input so it doesn't break the escape code sequence.
        title = title:gsub('\x1b', '{ESC}')
        title = title:gsub('\x07', '{BEL}')
        -- 0; sets icon name and window title.
        -- 1; sets only icon name.
        -- 2; sets only window title.
        -- NONL suppresses a line ending, so that only the escape is printed, so
        -- that the cursor doesn't move.
        clink.print('\x1b]2;'..title..'\x07', NONL)
    else
        -- Attempt to sanitize the input so it isn't susceptible to injection
        -- attack, i.e. accidentally running part of the title text as though it
        -- is a command to be executed.
        title = title:gsub('"', '\\"')
        os.execute('2>nul 1>nul conemuc -GuiMacro Rename 0 "'..title..'"')
    end
end

clink.onendedit(set_title)
```

**Comment by chrisant996** [comment]
Also, since `cmd.exe` itself sets the title (which ConEmu suppresses), any attempt to override the title outside of ConEmu gets messy.

E.g. running "dir" would initially set the title to "dir", and then `cmd.exe` appends the command line so the title becomes "dir - dir", and when the command finishes then `cmd.exe` restores the title back to "dir".

**This is definitely an entanglement that I do not want built into Clink.**
