### ISSUE TITLE
Pasting recognizably slower

### ISSUE THREAD

**Issue by jeremitu** [chrisant996/clink#474]
Pasting is recognizably slower with clink, can the delay be fine-tuned?
![animate](https://github.com/chrisant996/clink/assets/3822491/893d4466-b74d-4b30-a42f-d618c28898f4)

**Comment by chrisant996** [comment]
What terminal program are you using?  

That is using a terminal program's paste, not Clink's paste.  Clink's paste command is instantaneous.  The animated screen shot shows that instead, the terminal program's paste command is being used, which pastes one character at a time, as though the pasted text were being typed one letter at a time, which makes it slow.

Try changing the key bindings in the terminal program so that it doesn't handle the paste key anymore, so that Clink can't receive the paste key.

**Comment by jeremitu** [comment]
It seems to be a MS Windows Terminal, `wt.exe` issue. It offers now to run as default windows terminal instead of `cmd.exe`, which works fine with Clink. Paste is quick in wt with clink temporarily disabled or with paste command mapped to another key (settings.json).

**Comment by chrisant996** [comment]
To ensure compatibility with all apps, Windows Terminal has to do "Paste" by sending one letter at a time, as though the user is typing all the content from the clipboard.

Clink does parsing while input is typed, in order to do coloring and completions.  Clink uses the Readline library, which comes from the `bash` shell.  The Readline library has some inefficiencies due to repeatedly trying to display the input text several times per letter typed, and it replies on a bunch of processing to realize it doesn't need to display any changes.  The processing makes it faster than if it redisplayed the full input line multiple times per typed letter, but it could be faster if it were more efficient about keeping track of whether it actually needs to display anything.

I'm considering whether to do my own full rewrite of the Readline library (while still maintaining backward compatibility).  That would slightly improve the paste speed, but that isn't one of the main reasons I'm considering rewriting it.  But I probably won't do a rewrite, because then it would be very hard to pick up any new changes made in the official Readline library.

However, I might be able to do some special trickery to improve pasting speed by deferring display updates -- but that could introduce lag or wrong colors during normal typing.  Anyway, I'll do some experiments to see if I can find up with something.

In the meantime, you could change the Windows Terminal key binding for the paste to something other than Ctrl-V, to let Clink receive the Ctrl-V and do instant efficient paste -- which also has special handling for newlines.  Or you could try turning off the setting for input coloring to see how much that might speed it up (probably not much -- I think the main problem is the redundant display calls inside Readline, which is already on my radar as an efficiency issue).

**Comment by jeremitu** [comment]
Thank you for your thorough consideration and advice provided. Changing the paste key fixes the issue for the time being and the paste speed issue is not a deal breaker anyhow.

**Comment by mcoret** [comment]
Hello,
I am experiencing this issue with the latest builds from the trunk. I believe that this issue started to manifest itself following the Readline update.

Thank you.

**Comment by chrisant996** [comment]
> I am experiencing this issue with the latest builds from the trunk. I believe that this issue started to manifest itself following the Readline update.

@mcoret Uh oh, thanks for reporting this!  I'll track it down.

**Comment by chrisant996** [comment]
Fixed.  Thanks!
