### ISSUE TITLE
How to automatically switch to the directory from the last exit when the program starts again？

### ISSUE THREAD

**Issue by pengyangjin** [chrisant996/clink#481]
When the program starts, the displayed path is the path where the program execution file is located.How to automatically switch to the directory from the last exit when the program starts again？

**Comment by chrisant996** [comment]
> When the program starts, the displayed path is the path where the program execution file is located.

Neither Clink nor CMD choose the startup path.  That's done by however CMD is started:
- When launching a LNK shortcut file, the LNK shortcut file specifies the startup directory.
- When launching CMD directly, the startup directory is inherited from whatever is the current directory at the time.

The LNK shortcut file that Clink installs uses %USERPROFILE% as the startup directory.

So, if the program execution file is the startup directory when you start CMD and/or Clink, then that's not being done by Clink, it's being done by either the user or another program.

> How to automatically switch to the directory from the last exit when the program starts again？

There are a few ways that could be done.  I'll share one way below.

**But, I would discourage doing that, because it can have undesirable outcomes.**  For example, suppose you start one CMD window to do one thing.  And then you double clink a LNK file that starts a second CMD window with the startup directory set to a specific project you want to work on.  The second CMD window would open and override the current directory that the LNK said to use, and would set the same directory as the first CMD window currently has.  I don't think that's going to provide a good experience, but that's for you to decide.  Clink will not provide such behavior "built in", though, even as an option, because generally speaking it's highly likely to cause problems for many (most?) users.

What I do, instead, is I use [clink-gizmos](https://github.com/chrisant996/clink-gizmos) and the [cwdhistory.lua](https://github.com/chrisant996/clink-gizmos/blob/main/cwdhistory.lua) script to remember a list of recently used directories.  If I want to immediately switch to whatever directory I used most recently, I press the key bound to show the cwdhistory popup list, and then immediately press <kbd>Enter</kbd> since the popup list initially selects the most recently used directory.

The default key binding for the cwdhistory popup is <kbd>Shift</kbd>-<kbd>PgUp</kbd> as long as the key isn't already bound.  Personally, I added a key binding in my .inputrc file to bind <kbd>Ctrl</kbd>-<kbd>X</kbd>,<kbd>Ctrl</kbd>-<kbd>D</kbd> to the cwdhistory popup list command.
```inputrc
# This key binding only works if the cwdhistory.lua script is present.
"\C-x\C-d":         "luafunc:cwdhistory_popup"      # ctrl+x, ctrl+d
```

### Sample Lua Script To Automatically Always Override The Startup Directory

Again, I would discourage doing this.  But here's one of the approaches for how it can be accomplished.

This sample script includes logging, so that inspecting the clink.log file can reveal what this script is doing.

```lua
-- This overrides the startup directory whenever Clink is injected, and changes
-- to whatever directory was most recently used.
--
-- DISCLAIMER:  This seems like a dangerous idea and likely to cause problems.

log.info("Loaded lastdir script.")

local function get_history_label()
    -- This is used to associate the last directory with command history.
    -- See https://chrisant996.github.io/clink/clink.html#multiple-master-history-files
    local label = os.getenv("CLINK_HISTORY_LABEL") or ""
    label = label:gsub("%p", "")
    if #label > 0 then
        label = "-" .. label
    end
    return label
end

local function get_lastdir_filename()
    local profile_dir = os.getenv("=clink.profile")
    if profile_dir and profile_dir ~= "" then
        local filename = path.join(profile_dir, "lastdir")
        return filename .. get_history_label()
    end
end

local function write_lastdir()
    -- Overwrite the lastdir file, and deny concurrent writes while it's open.
    local f = io.sopen(get_lastdir_filename(), "w+", "w")
    if f then
        log.info("Write lastdir '" .. os.getcwd() .. "'.")
        f:write(os.getcwd())
        f:close()
    end
end

local function read_lastdir()
    local lastdir
    local f = io.open(get_lastdir_filename())
    if f then
        lastdir = f:read()
        f:close()
    end
    if lastdir and lastdir ~= "" then
        log.info("Got lastdir '" .. lastdir .. "'.")
        return lastdir
    end
end

local skip_onbeginedit = true
local function onbeginedit()
    -- Writes the last directory before each prompt (except the first one, which
    -- would defeat the whole purpose).
    if skip_onbeginedit then
        skip_onbeginedit = false
    else
        write_lastdir()
    end
end

local done
local function oninject()
    local lastdir = read_lastdir()
    if lastdir then
        clink.onprovideline(function ()
            if not done then
                done = true -- CRUCIAL: Prevent infinite loop.
                skip_onbeginedit = true
                log.info("Override startup directory to '" .. lastdir .. "'.")
                return " cd " .. lastdir
            end
        end)
    end
end

clink.oninject(oninject)
clink.onbeginedit(onbeginedit)
```

**Comment by chrisant996** [comment]
> The LNK shortcut file that Clink installs uses %USERPROFILE% as the startup directory.

@pengyangjin I need to clarify that statement:

The LNK shortcut file uses the program's installation directory.  It's been that way since Martin first created the installer in 2012.

But, the LNK shortcut file runs `clink.bat startmenu --profile ~\clink`, and the `startmenu` part causes the `clink.bat` script to `cd /d "%userprofile%"`.  So, double-clicking on the Clink shortcut in the Start menu should use %USERPROFILE% as the startup directory.

In any case, it looks like Martin added the `startmenu` stuff to work around the fact that the installer script neglected to specify a startup directory for the script, and so the NSIS installer compiler defaults to the program's installation directory.  In other words, it appears that Martin was trying to figure out how to fix the bug in the installer script, and there was a simpler and more correct way available, which he didn't notice.

I'll improve that.

But I'm still curious what's happening on your machine, because your machine is behavior differently from how Clink is designed to work, and because I can't reproduce what your machine is experiencing.

So:
- Can you share specific details about how you're starting CMD and/or Clink?
- If you're double-clicking the Clink.lnk file, can you copy/paste the contents of the **Target:** box from the Properties dialog box for the LNK file?

**Comment by chrisant996** [comment]
The `cwdhistory.lua` script in [clink-gizmos](https://github.com/chrisant996/clink-gizmos) now has a new `cwdhistory.restore` setting which on startup restores the last current working directory from the cwdhistory list.  (Unless `%CWDHISTORY_NORESTORE%` is set.)

https://github.com/chrisant996/clink-gizmos/commit/85a1d36b3ae6a8c6a9a3e5f25a1c4f2f6db2fe4d
