### ISSUE TITLE
clink.logo none adds a blank line above prompt

### ISSUE THREAD

**Issue by Qbit42** [chrisant996/clink#488]
To clean up my CMD experience I suppress the copyright notifications with a [common trick](https://superuser.com/a/1786857) by calling the command `cmd.exe /k`. This calls the CMD with an empty command omitting the welcome message. This on it's own works like expected.

![grafik](https://github.com/chrisant996/clink/assets/1956602/292ce4f8-c452-496d-bfb2-3294ad26ec1f)

When I activate clink, I see the full logo as expected.

![grafik](https://github.com/chrisant996/clink/assets/1956602/7f106a90-d5d0-4a0e-981f-13ad8036d25d)

But when I set the `clink.logo` to `none` I'm left with one blank line above the prompt. This is not, what I would expect from `none`.

![grafik](https://github.com/chrisant996/clink/assets/1956602/f880ef11-38a5-481f-999c-e4bb34e10f40)

I also tried to disable `autorun` and injected clink directly with the CMD by calling `cmd.exe /k "%programfiles(x86)%\clink\clink" inject` but the result is the same.

**Comment by chrisant996** [comment]
If you run `cmd.exe /k rem` you get the same blank line.  It's coming from cmd.exe, as a result of having a non-empty command line.

You could write a Lua script to forcibly move the cursor up a line when `clink.logo` is `none`, but that might have unexpected side effects in some cases.

```lua
local function up_if_blank_line()
    if console.getcursorpos and settings.get("clink.logo") == "none" then
        local x, y = console.getcursorpos()
        if y > 1 and console.getlinetext(y - 1) ~= "" then
            clink.print("\x1b[A", NONL)
        end
    end
end

clink.oninject(up_if_blank_line)
```

**Comment by Qbit42** [comment]
Ok I now see where the problem comes from. the `/k` trick was my first guess because it's kind of hacky.

It's still a bit strange that the full logo produces no blank line, but the solution with the script seems to work fine for now. I know that problems may occur by this approach but your code seems reasonable secure and I should be able to move on from this point.

Thanks a lot!

**Comment by chrisant996** [comment]
> It's still a bit strange that the full logo produces no blank line, 

cmd.exe produces a blank line with the full logo, as well:

![image](https://github.com/chrisant996/clink/assets/17440311/97ad2875-073f-41da-804b-6bb4f22af4e1)

Clink prints the logo at the moment it's injected, which is while cmd.exe is running the specified commands, and cmd.exe prints that blank line after it finishes running all the specified commands.  So when there's a logo, cmd.exe emits the blank line after the logo, which looks natural.

One can use a debugger to observe cmd.exe printing the blank line, as well as observing what Clink is responsible for printing.

For example, the following steps can be used with Visual Studio:
1. Run `devenv /debugexe cmd.exe /k echo hello`.
2. Use Debug | New Breakpoint | Function Breakpoint... to enter 3 breakpoints:
    - WriteConsoleW
    - WriteConsoleA
    - WriteFile
3. Press <kbd>F5</kbd> to start running the cmd.exe command line.
4. The first two hits are kernel32.dll!WriteConsoleW and kernelbase.dll!WriteConsoleW for the "hello\r\n" output from the **eEcho** function which implements the "echo hello" command.  (The kernel32 API forwards the call to the kernelbase API, and the name function breakpoint catches both.)
    > - KernelBase.dll!WriteConsoleW
    > - clink_dll_x64.dll!host_cmd::write_console
    >     - _host_cmd::write_console is Clink's hook which can intercept printing the prompt when it's tagged with "C\bL\bI\bN\bK\b", which is how Clink knows when the prompt is being printed.  Since "hello\r\n" is not the tagged prompt, Clink has no idea what is being output or why, and so it passes the output straight through to the OS API._
    > - cmd.exe!CmdPutChars
    > - cmd.exe!cmd_printf
    > - **cmd.exe!eEcho**
    > - cmd.exe!FindFixAndRun
    > - cmd.exe!Dispatch
    > - cmd.exe!main
5. The next WriteConsoleW hits are for printing a blank line inside the **PrintPrompt** function.
    > - KernelBase.dll!WriteConsoleW
    > - clink_dll_x64.dll!host_cmd::write_console
    >     - _host_cmd::write_console is Clink's hook which can intercept printing the prompt when it's tagged with "C\bL\bI\bN\bK\b", which is how Clink knows when the prompt is being printed.  Since "\r\n" is not the tagged prompt, Clink has no idea what is being output or why, and so it passes the output straight through to the OS API._
    > - cmd.exe!CmdPutChars
    > - **cmd.exe!PrintPrompt**
    > - cmd.exe!FillBuf
    > - cmd.exe!Lex
    > - cmd.exe!GeToken
    > - cmd.exe!Parser
    > - cmd.exe!main
6. The next WriteConsoleW hits are for hiding the cursor.  These are inside the **ReadBufFromConsole** function -- yes, Clink prints the prompt inside the function for reading input, not inside the function for printing the prompt.  Clink is able to exercise so much control over how the output and input work because Clink hooks multiple OS API to wait to print the prompt until cmd.exe is waiting for an input line.
    - kernel32.dll!WriteConsoleW
    - **clink_dll_x64.dll!show_cursor(visible=0x00000000)**
    - clink_dll_x64.dll!win_terminal_in::begin
    - clink_dll_x64.dll!line_editor_impl::begin_line
    - clink_dll_x64.dll!line_editor_impl::update
    - clink_dll_x64.dll!line_editor_impl::edit
    - clink_dll_x64.dll!host::edit_line
    - clink_dll_x64.dll!host_cmd::edit_line
    - clink_dll_x64.dll!host_cmd::read_console
    - **cmd.exe!ReadBufFromConsole**
    - cmd.exe!FillBuf
    - cmd.exe!Lex
    - cmd.exe!GeToken
    - cmd.exe!Parser
    - cmd.exe!main
7. The next WriteConsoleW hits are for printing the prompt.
    - kernel32.dll!WriteConsoleW
    - clink_dll_x64.dll!win_screen_buffer::write
    - clink_dll_x64.dll!ecma48_terminal_out::write
    - clink_dll_x64.dll!printer::print
    - clink_dll_x64.dll!terminal_write_thunk
    - [Inline Frame] clink_dll_x64.dll!display_accumulator::flush
    - clink_dll_x64.dll!display_manager::display
    - **[Inline Frame] clink_dll_x64.dll!display_readline**
    - clink_dll_x64.dll!hook_display
    - **clink_dll_x64.dll!readline_internal_setup**
    - [Inline Frame] clink_dll_x64.dll!_rl_callback_newline
    - [Inline Frame] clink_dll_x64.dll!rl_callback_handler_install
    - clink_dll_x64.dll!rl_module::on_begin_line
    - clink_dll_x64.dll!line_editor_impl::begin_line
    - clink_dll_x64.dll!line_editor_impl::update
    - clink_dll_x64.dll!line_editor_impl::edit
    - clink_dll_x64.dll!host::edit_line
    - clink_dll_x64.dll!host_cmd::edit_line
    - clink_dll_x64.dll!host_cmd::read_console
    - **cmd.exe!ReadBufFromConsole**
    - cmd.exe!FillBuf
    - cmd.exe!Lex
    - cmd.exe!GeToken
    - cmd.exe!Parser
    - cmd.exe!main
