### ISSUE TITLE
Can't get readline key binding to work

### ISSUE THREAD

**Issue by iulian3144** [chrisant996/clink#49]
### Description
I'm trying to bind `Ctrl+Alt+u` to `clink-up-directory` but for some reason, it's not working. This is quite annoying as it's probably the shortcut that I've been using most often.
I am currently using clink (1.1.18.f27b9d) with Cmder. I'll also give it a try using plain cmd.

Note: I previously used clink v0.4.9 with ConEmu (not through Cmder) and the autorun option configured. The shortcut was working as expected.

I have added the following line to `%USERPROFILE\.inputrc`:
```
set keymap emacs
"M-C-u":        clink-up-directory
"M-h":          clink-show-help
```
I've also tried `A-C-u`.

`clink-show-help` (`A-h`) prints the following:
```
...snip...
M-C-u       : clink-up-directory                      C-u         : unix-line-discard                       A-1         : digit-argument                          A-~         : tilde-expand
...snip...
C-PgUp      : clink-up-directory                      C-x,C-g     : abort                                   A-7         : digit-argument                          A-C-f       : clink-expand-doskey-alias
..snip...
```
This output looks a little wrong to me... though, I'm not that familiar with readline. I was expecting the shortcut from .inputrc to override the default one.
`C-PgUp` works but it required to remove a shortcut from ConEmu.
It may be that some shortcuts in ConEmu interfere with it but couldn't find anything related to it.

I wish you a happy new year, full of accomplishments.

BTW I think you did a really nice job with clink. I'm glad that someone had the initiative to continue and improve on this awesome project. Any idea what happened with the original author?

**Comment by chrisant996** [comment]
"M-C-u" isn't Alt-Ctrl-u.
It's the literal characters "M" then "-" then "C" then "-" then "u".

Have you tried "\M-\C-u"?

See the Readline docs for more info about how to bind keys.

I will also add more examples in the Clink docs.

**Comment by iulian3144** [comment]
Thanks a lot Chris for the quick reply.

I must say I feel pretty dumb... I did read some of the readline documentation portion regarding init file syntax some time ago but, somehow, this escaped me.
And the reason is that the old .inputrc file that I had (which _seemed_ to work with the older clink version) contained key bindings definitions like the one I mentioned. Can't remember from where I got that file (I'll trace that down).

Actually, I just noticed that my definitions were correct except I had them wrapped in quotes.
So the following should be equivalent:
```
M-C-u
"\M-\C-u"
```
As per the readline documentation, the first one denotes a _keyname_ and the second one, a _keyseq_.
I can confirm now that both are working :D.
Regarding your point, it would be nice if the help command would print the keybindings such that you can differentiate, for example, between character "C" and _Control_ key.
As for the examples, maybe users (like myself) should just read the readline documentation more closely :D.

I'll go ahead and close this one.

Have a nice day.

**Comment by iulian3144** [comment]
Replacing e.g. C with Control, M with Meta etc. might also be a good idea but probably a little too verbose.

**Comment by chrisant996** [comment]
> Replacing e.g. C with Control, M with Meta etc. might also be a good idea but probably a little too verbose.

Yes, exactly -- I tried using "Ctrl" and "Alt" and "Shift" but the key names were very long and made the list harder to read.

**Comment by iulian3144** [comment]
I agree that it's pretty hard to find a better way to do this.

I just looked at the output of `bind -p` (bash builtin) and I think it would be a good idea to follow that.
e.g.:
```
"\M-\C-u": clink-updirectory
```
But keep the column fomatting :).

**Comment by chrisant996** [comment]
> I agree that it's pretty hard to find a better way to do this.
> 
> I just looked at the output of `bind -p` (bash builtin) and I think it would be a good idea to follow that.
> e.g.:
> 
> ```
> "\M-\C-u": clink-updirectory
> ```
> 
> But keep the column fomatting :).

There is already <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>H</kbd> which is bound to `clink-show-help-raw`.  That shows raw key bindings, in one of the canonical Readline formats.  Also, note that Readline 8.1 made a breaking change to the key binding format.  It cleans up some weirdness, but changes the behavior in certain edge cases.

I'm not sure that the `bind -p` format helps a lot -- it still requires the reader to interpret the string the same way that Readline will.
Is that <kbd>Alt</kbd>+<kbd>Ctrl</kbd>+<kbd>u</kbd>?
Or <kbd>\</kbd>,<kbd>M</kbd>,<kbd>-</kbd>,<kbd>\</kbd>,<kbd>C</kbd>,<kbd>-</kbd>,<kbd>u</kbd>?
Or <kbd>Alt</kbd>+<kbd>-</kbd>,<kbd>Ctrl</kbd>+<kbd>-</kbd>,<kbd>-</kbd>,<kbd>u</kbd>?

The trouble here was that the reader thought they were parsing it the same, but weren't.  I've done that myself several times and got frustrated enough to go to the trouble of making `clink-show-help` emit "friendly names" for keys instead of raw key binding strings.

Who among us instantly recognizes what key corresponds to a string like `"\e[27;5;32~"`?  (It's <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Space</kbd> by the way).

It always clear in retrospect how one "should" have interpreted the key sequence.  But I think the software should aim to be friendlier.

**Comment by iulian3144** [comment]
Seems like this is more complicated than I thought. However, I don't think you can figure out this kind of stuff without a convention to follow. So in the end, I think this is just a matter of documenting the syntax.
It's true that even so, there are some edge cases left, but this should probably considered as some kind of limitations and documented accordingly. But then, everyone needs to carefully read the documentation... the usual problem.

**Comment by chrisant996** [comment]
> Seems like this is more complicated than I thought. However, I don't think you can figure out this kind of stuff without a convention to follow. So in the end, I think this is just a matter of documenting the syntax.
> It's true that even so, there are some edge cases left, but this should probably considered as some kind of limitations and documented accordingly. But then, everyone needs to carefully read the documentation... the usual problem.

Agree.  It's all documented in the Readline documentation.

**Comment by chrisant996** [comment]
v1.1.19 has smarts that should detect this kind of typo _only in the emacs key map_ and show a warning about the key binding.

I felt that was a good middle ground between doing nothing vs redesigning how key bindings work in Readline.  Doing nothing isn't feasible for me because it's a reasonable mistake, and adding a warning saves everyone time, including myself (the time it takes to investigate issues and help out -- better for everyone if I imbue the software with smarts to do that work for me ;-).

**Comment by iulian3144** [comment]
Great. I also think that this is a good option.
Thank _you_ again for maintaining this project. I don't think I'll ever be able to work on a windows machine without this awesome tool.
