### ISSUE TITLE
Colors stopped to work in Completion Selection (raw SGR escape code is rendered instead)

### ISSUE THREAD

**Issue by xak2000** [chrisant996/clink#493]
After updating from 1.5.4 to 1.5.5 <kbd>CTRL + SPACE</kbd> autocompletion started to render the SGR escape code of the `selected_completion` color instead of the color itself.

Example from 1.5.4 after pressing <kbd>git</kbd> then <kbd>CTRL + SPACE</kbd>:
<img width="1015" alt="image" src="https://github.com/chrisant996/clink/assets/1576014/39c8a7d4-c7b7-4a2b-8e59-33efc4561d42">

Example from 1.5.5 after pressing <kbd>git</kbd> then <kbd>CTRL + SPACE</kbd>:
<img width="1093" alt="image" src="https://github.com/chrisant996/clink/assets/1576014/2f9d7fcf-cdc9-42df-9e21-cb3eabf37da6">

Pressing the arrow keys moves `0;38;5;16;48;5;254` to the next item. :)

The relevant part of my `clink_settings`:

```
# name: Selected completion color
# type: color
color.selected_completion = sgr 38;5;16;48;5;254
```

**Comment by chrisant996** [comment]
@xak2000 Thank you for reporting this.  I believe you that it's happening for your.

However, I am unable to reproduce that.  I don't think the relevant part is the value of `color.selected_completion` -- I think it's probably related to one or more other settings or .inputrc variables.

So, I need more information to be able to reproduce the problem, so that I can debug it and fix it.
Can you please share your .inputrc file and the full output from `clink set`?

I thought maybe it's because `colored-stats` is `off` in your config (there are no colors in the completion list), but I still can't reproduce it even when I turn off `colored-stats`.

**Comment by chrisant996** [comment]
Found it and fixed it.  Thanks for reporting it!

**Comment by xak2000** [comment]
Thank you very much!

For the reference, my `.inputrc` file was almost empty. This is the full file contents:

```
"\e[B": history-search-forward
"\e[A": history-search-backward
```

Now I added `colored-stats` and `colored-completion-prefix` as well as I think they are good options anyway. Just didn't know they exist.
