### ISSUE TITLE
lua error with clink-completions

### ISSUE THREAD

**Issue by mcoret** [chrisant996/clink#494]
Hello!

While using clink-completions, I encountered the following error:  `attempt to index local 'line' (a nil value)`.
To reproduce this error, one method is to input `robocopy` followed by any argument.

Thank you for your assistance!

**Comment by chrisant996** [comment]
@mcoret Thank you for reporting this!

It only happens if you run Clink after building from the repo.  The change responsible for this hasn't been released yet.  So, extra special thanks for helping catch bugs before they're released publicly!

It's caused by 4c3d4d945ebdf7d518fa0a1edd03eac5622bb583, which accidentally updated a couple of calls that should have been left alone.
