### ISSUE TITLE
Characters @, &, # immediately deleted if written by touch keyboard

### ISSUE THREAD

**Issue by Nabla128k** [chrisant996/clink#501]
Hi, it seems to me, that there is this issue while I use touch keyboard on the screen (not "keyboard on screen" but "touch keyboard"... I hope that's exact english names of these functions). I have Surface Pro X - Win11@arm64. When I use physical keyboard everything is ok. 
When I try write &, @, # on touch keyboard (pop up when physical disconnected, or manually turn on while physical also connected) the character shows up (just for a fraction of second), but it is like immediately deleted by backspace.
With clink uninstalled its ok.

**Comment by chrisant996** [comment]
@Nabla128k What language keyboard is your computer using? I don't experience that with any of the language keyboards I've tried with the on-screen keyboard.  Knowing the language keyboard should enable me to reproduce the issue, and then I can do something about it.

Or, if you're not sure how to find out what language keyboard is used, then here is another option for troublshooting:

- Run `clink echo -v`
- Use the on-screen keyboard to type &, @, # 
- Copy the full output into a reply here.  That might be able to give enough info to identify what's going wrong.

**Comment by Nabla128k** [comment]
@chrisant996 The keyboard is Czech layout and it's true, that when I switch to English it's ok.
These characters are written by RightAlt+letter. Touch keyboard has sticky right alt.
And it seems that all characters written by RightAlt-than-letter are immediately deleted.

Output of clink echo -v for @:
`key event:  _CA __  flags=0x0000002a  char=0x0040  vk=0x0056  scan=0x002f  "V"
"\e\C-V"`
Output of clink echo -v for &:
`key event:  _CA __  flags=0x0000002a  char=0x0026  vk=0x0043  scan=0x002e  "C"
"\e\C-C"`
& is RigtAlt and c and it results in cancel clink echo -v loop like while ctrl+c press, so it seems like RightAlt and Ctrl is somehow evaluated the same way?

**Comment by chrisant996** [comment]
> @chrisant996 The keyboard is Czech layout and it's true, that when I switch to English it's ok. These characters are written by RightAlt+letter. Touch keyboard has sticky right alt. And it seems that all characters written by RightAlt-than-letter are immediately deleted.

I installed "CES" Czech keyboard to try to reproduce the problem.  This is where it gets interesting -- for all other keyboard issues that have ever been reported, I've been able to install the other keyboard and experience the exact same behavior myself.  But not this time.  So we'll need to do a bit more troubleshooting.

> while I use touch keyboard on the screen (not "keyboard on screen" but "touch keyboard"... I hope that's exact english names of these functions)

Is this screen shot what you mean?  In the English language pack, this is called the "On-Screen Keyboard" or "OSC".  Windows 11 has started calling it "Touch Keyboard" in the Settings app, but it's still called "On-Screen Keyboard" in many places.  I can activate it by pressing <kbd>Win</kbd>-<kbd>Ctrl</kbd>-<kbd>O</kbd>.  This is what you mean, right?

![image](https://github.com/chrisant996/clink/assets/17440311/982ca4a9-d0c7-4e2f-9d1f-3406ea2030d4)

> Output of clink echo -v for @:
> ```
> key event:  _CA __  flags=0x0000002a  char=0x0040  vk=0x0056  scan=0x002f  "V"
> "\e\C-V"
> ```
> Output of clink echo -v for &: 
> ```
> key event:  _CA __  flags=0x0000002a  char=0x0026  vk=0x0043  scan=0x002e  "C"
> "\e\C-C"
> ```

Ok, this is very interesting.  The OS claims that the <kbd>AltGr</kbd> (Right Alt) key is _**not pressed**_.  It says only the <kbd>Left Ctrl</kbd> and <kbd>Left Alt</kbd> keys are pressed.

That is also known as the "AltGr substitute" -- pressing <kbd>Left Ctrl</kbd> and <kbd>Left Alt</kbd> together simulate the <kbd>AltGr</kbd> key.  But on your computer, using the OSC <kbd>AltGr</kbd> is _**only**_ reporting that <kbd>Left Ctrl</kbd> and <kbd>Left Alt</kbd> are pressed, not <kbd>AltGr</kbd>.

So, on your computer the OSC is reporting keyboard status inaccurately to the OS.  I don't know why, and I can't get the OS to do that on my computer.

Here is what I get when using the OSC to type <kbd>AltGr</kbd> <kbd>#</kbd>, <kbd>AltGr</kbd> <kbd>&</kbd>, and <kbd>AltGr</kbd> <kbd>@</kbd>.

```
key event:  _CA A_  flags=0x0000002b  char=0x0023  vk=0x0058  scan=0x002d  "X"
"#"
key event:  _CA A_  flags=0x0000002b  char=0x0026  vk=0x0043  scan=0x002e  "C"
"&"
key event:  _CA A_  flags=0x0000002b  char=0x0040  vk=0x0056  scan=0x002f  "V"
"@"
```

> & is RigtAlt and c and it results in cancel clink echo -v loop like while ctrl+c press, so it seems like RightAlt and Ctrl is somehow evaluated the same way?

Yeah, the OSC is behaving very strangely.  Once the <kbd>AltGr</kbd> key is pressed on the OSC (but only in the OSC), then until the physical <kbd>AltGr</kbd> key is pressed and released, the physical keyboard continues to think that <kbd>AltGr</kbd> is held, even though the OSC thinks the <kbd>AltGr</kbd> key has been released.  That's an issue in the Windows OS, and I confirmed it happens regardless whether Clink is being used.

# A Possible Solution

I can't change how the OS reports the keyboard input.

But, Clink has a setting that might help:
`clink set terminal.use_altgr_substitute true`

Normally Clink has that off, because otherwise the AltGr substitute interferes with <kbd>Ctrl</kbd>-<kbd>Alt</kbd> key bindings.  But on your computer it looks like the OS and/or OSC are reporting input differently than normal, and enabling that Clink setting might be the only way to compensate for the inaccurate keyboard input.

Hopefully once the `terminal.use_altgr_substitute` setting is enabled Clink will be able to recognize the inputs from the OSC.

**Comment by Nabla128k** [comment]
Keyboard on your screenshot is not "touch keyboard" but "keyboard on screen" (my translation...). Touch keyboard is this:
![image](https://github.com/chrisant996/clink/assets/5609151/80b7c9f3-a048-4e34-a512-2edf2311b440)

You can switch it to smaller mode:
![image](https://github.com/chrisant996/clink/assets/5609151/63a289c0-ef2f-48ed-aae5-6394c82cfbed)

Now it become even more complicated :-) Because it depends on if physical is connected or not.
If physical connected, its ok except on small touch (small touch always bad).
If physical disconnected it seems bad, but you must restart cmd. If physical disconnected, but previously connected, its ok (except small touch).

So this is with physical connected first scan "small touch" second scan "big touch"/"on-screen"/"physical"
`key event:  _CA __  flags=0x0000002a  char=0x0040  vk=0x0056  scan=0x002f  "V"
"\e\C-V"
key event:  _CA A_  flags=0x0000002b  char=0x0040  vk=0x0056  scan=0x002f  "V"

"@"`

Definitely, `clink set terminal.use_altgr_substitute true` helps and its ok on (i hope) all keyboards.

Thank you very much for help. Can we close the issue?

**Comment by chrisant996** [comment]
@Nabla128k Thank you for helping track this down!  Now it's clear what's happening -- and there are two options for how to solve the issue.

> Keyboard on your screenshot is not "touch keyboard" but "keyboard on screen" (my translation...). Touch keyboard is this:

Ah, thanks, yes I understand now (that was my mistake, not yours).

> Now it become even more complicated :-) Because it depends on if physical is connected or not. If physical connected, its ok except on small touch (small touch always bad). If physical disconnected it seems bad, but you must restart cmd. If physical disconnected, but previously connected, its ok (except small touch).

I'm using a laptop, so it's a bit of a complicated effort to disconnect/disable my physical keyboard.

But I am able to reproduce the issue using the small touch keyboard.  👍

> So this is with physical connected first scan "small touch" second scan "big touch"/"on-screen"/"physical"
> ```
> key event:  _CA __  flags=0x0000002a  char=0x0040  vk=0x0056  scan=0x002f  "V"
> "\e\C-V"
> key event:  _CA A_  flags=0x0000002b  char=0x0040  vk=0x0056  scan=0x002f  "V"
> "@"
> ```

Yes -- on the small touch keyboard, when I press the `&123` button and then the `@` button, it indeed reproduces the problem.  But, for me it dings the bell (depending on the `bell-style` config variable in the .inputrc file).  It doesn't insert the `@` and delete it -- it just never inserts the `@` because Clink doesn't receive any `@` at all, instead Clink receives <kbd>Alt</kbd>-<kbd>Ctrl</kbd>-<kbd>V</kbd>.

The unexpected behavior is happening at the Operating System level.  There's no way for Clink to detect that it's happening, so there's no way for Clink to compensate.

# But...

This reveals that there are two ways to solve the problem.

**Option 1** -- You can indeed run `clink set terminal.use_altgr_substitute true` and that will solve the problem.  But it has a side effect:  now some (all?) of the <kbd>Ctrl</kbd>-<kbd>Alt</kbd> key bindings in Clink will not work anymore.

**Option 2** -- You could make key bindings that translate the <kbd>Ctrl</kbd>-<kbd>Alt</kbd>-<kbd>V</kbd> (etc) keys into their associated <kbd>AltGr</kbd> characters.  Then other <kbd>Ctrl</kbd>-<kbd>Alt</kbd> key bindings will continue to work (after running to `clink set terminal.use_altgr_substitute false` to reset that setting).

### .inputrc file
```
"\e\C-X": "#"
"\e\C-C": "&"
"\e\C-V": "@"
```

You can choose either option, according to your preference.  😎
