### ISSUE TITLE
Scripts whose name begins with .lua are loaded, instead of exact .lua extension

### ISSUE THREAD

**Issue by arisudesu** [chrisant996/clink#502]
It was discovered by accident, Clink does apparently does check only the beginning of extension to match ".lua". This is confusing and isn't documented, so it is most likely an error.

For example, files with name "prompt.lua" and "prompt.lua_" are loaded, whereas "prompt._lua" is not.

**Comment by chrisant996** [comment]
This came up a while ago, but I can't find the associated issue.

Windows actually treats `*.abc` the same as `*.abc*`.

Clink has always (even in v0.4.9) loaded script files via `*.lua`, which has always gotten interpreted by the OS the same as `*.lua*`.

In general, renaming from `.foo` to e.g. `.foo.ignore` is safer than renaming to `.foo_`.

The implications of this DOS compatibility behavior in Windows are far-reaching.  I haven't decided yet whether to start trying to override how the Windows OS works in various places.  I think that will be a mixed bag of benefits and breakages, and will be destabilizing and cause consistency problems.  I'm not sure the benefits would outweigh the drawbacks.  And I'm not sure that the issue is problematic enough to require a remedy.

What are your thoughts on the subject?

**Comment by chrisant996** [comment]
It's easy to make Clink only load Lua scripts whose extension is literally `.lua`.

But that creates a weird problem:  All other things that look for `*.lua` will still catch `foo.lua_` and etc, because that's just how the Windows operating system works (because of legacy DOS and CP/M compatibility reasons).

If Clink behaves specially, then it's even more unexpected when for example a batch script like `for %a in (*.lua) do echo %a` takes action on `foo.lua_`.  Or when a build system like `premake5` handles `for _,m in ipairs(os.matchfiles("*.lua")) do` and includes `foo.lua_`.  Or when Lua scripts in Clink do wildcard searches, and so on.

I don't think the issue causes much of a problem, and I'm concerned about creating inconsistencies that could lead to even more confusing/worse problems (not to mention the extra time spent in troubleshooting to figure out why different apps or usage cases within an app behave differently from each other.

It's a tough call either way, but I'm going to leave it as-is, at least for now.

Thanks for calling out the problem so that it can be properly tracked, and the discussion can be captured for future reference!

**Comment by chrisant996** [comment]
@arisudesu **Some Background Information:** It happens because of how [8.3 short names](https://en.wikipedia.org/wiki/8.3_filename) work.  A name `foo.1234` does not fit the 8.3 naming syntax, so Windows generates an short name such as `foo~1.123` which is 8.3 compliant.  This is a compatibility feature, and it means that in fact `foo.luax` is also `foo~1.lua` which does correctly match `*.lua`.  The `dir /x` flag lists 8.3 short names in addition to long filenames.

It's possible to turn off 8.3 short names entirely, but it takes some effort and it can create compatibility problems in some programs.

Here's another link with some related information and additional links for further reading:  https://superuser.com/questions/238900/winxp-dir-command-3-and-4-char-extensions-are-the-same

(Since it's not a Clink issue per se, and is instead part of how Windows works, it isn't documented as a "Clink issue".  If I were to document all the external things that can affect Clink, then the list would be very long.)

**Comment by arisudesu** [comment]
I completely forgot about the issue being busy with other things!

I never knew about this behavior of Windows systems, that file.ext actually can match file.ext*. This is weird behavior, but since it's documented and this is how Windows OS __should__ behave, I think you are right to leave this behaviour as is, to match other's expectances.

Thank you for detailed explanation!
