### ISSUE TITLE
Odd "CLINK" being printed out during the middle of build process in Visual Studio

### ISSUE THREAD

**Issue by ben-may** [chrisant996/clink#515]
Hi,

I have a strange issue where when we launch Visual Studio from a clink command prompt, we see 
```
CLINK 
```
being printed out before some of our bat files we launch/execute.  I can't find anywhere in the clink code or anything we are doing where we try to print out `C\bL\b\I\bN\K\b \b` since the unknown characters are BS or backspace characters.  

Looking through the clink source I do see some things going on with \b being written out so perhaps it could be the culprit.  since the letters are `CLINK` then I assume it must have something to do with clink.

If we launch Visual Studio not from a clink command prompt the issue does not occur.

We are using CLINK 1.3.0.f070e4

Thanks!
<img width="1639" alt="clink_issue" src="https://github.com/chrisant996/clink/assets/16196367/f3614e39-1e22-49dc-a75d-8b4380ca7215">

**Comment by chrisant996** [comment]
See [this code](https://github.com/chrisant996/clink/blob/303973a65a3380d40d8fcfee1c5a1774e6084c07/clink/lua/src/prompt.cpp#L381-L398), and [this global](https://github.com/chrisant996/clink/blob/303973a65a3380d40d8fcfee1c5a1774e6084c07/clink/lua/src/prompt.cpp#L30).

In order for Clink to detect when CMD is trying to print the prompt, Clink has to override the `%PROMPT%` variable to something both predictable and unique.

Since launching programs inherits environment variables, launching other programs from a Clink window gets the tagged prompt value.  Launching CMD instances from those other programs inherits the tagged prompt value as well.

When CMD prints the tagged prompt value, the "`C\bL\bI\bN\bK\b`{original%PROMPT%value}" looks fine because the `\b` (Backspace) characters backspace over the tag characters, and the prompt looks fine.

But if a program (like Visual Studio) redirects the terminal output and does custom drawing of the terminal output and doesn't handle `\b` characters as doing a backspace, then the custom drawing will end up showing the "hidden" tag.

You could work around the issue by setting %PROMPT% inside the CMD shell launched inside Visual Studio.

There isn't a way for Clink to intercept the prompt without altering the prompt text.

**Comment by ben-may** [comment]
ah excellent thank-you for the explanation!
