### ISSUE TITLE
Please add link to release notes in update dialog

### ISSUE THREAD

**Issue by fstanchina** [chrisant996/clink#520]
Please add a link to the release notes in the update dialog, so one can read them right away and decide if the update is worth installing immediately or can be postponed.

Thanks.

**Comment by chrisant996** [comment]
That's a good idea and I'll work on it.  In the meantime, adding a link in the browser's Favorites list can be a good alternative.

(There are some complications to work through, because it isn't necessarily as simple as showing a link to the "latest" release, due to being able to install pending updates that aren't the latest, and also the possibility of starting to publish pre-release updates.)

**Comment by fstanchina** [comment]
I think the link you show after the update would be good enough. You can always make it better in a future release :)
