### ISSUE TITLE
v1.5.17 display problem in VS Code for wider resolutions

### ISSUE THREAD

**Issue by rokrupnik** [chrisant996/clink#524]
OS: Windows 10
clink: 1.5.17
cmder: 
VS Code: 1.83.1

description:
I use cmder as my local terminal client integration into VS Code, following this [official guide](https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration).

When I start the terminal in an fullwidth mode (monitor resolution 2560 x 1440) the suggestions are jumbled up (multiple lines, some weird text in between), see [screenshot](https://www.dropbox.com/scl/fi/x9j011hhyvga1bnwnwvjm/clink_error..jpg?rlkey=iwyq4w0ixz26i2ad9v9mafhvd&dl=0).
However, when I make the terminal more narrow, everything starts to work ok, see [screenshot](https://www.dropbox.com/scl/fi/h7jjldnou8o7p85ahw02e/clink_ok..jpg?rlkey=tllkpcqb9une382abrqfm9ufv&dl=0).
The breaking point seems to be around the 2100px.
The same happens in PHPStorm (IntelliJ).

[clink.log](https://www.dropbox.com/scl/fi/7d2zmzqck8ktzcejfqt4p/clink_rupnik.log?rlkey=t7vtnu4baqrmtgb2udb8pcbk8&dl=0)
[clink set](https://www.dropbox.com/scl/fi/pgvvcgg1tx2jna94qaf2k/clink_set_rupnik.txt?rlkey=sgtlfjyi2j5hb9onh6w0uwgn3&dl=0)
[clink info](https://www.dropbox.com/scl/fi/3947w5xd6521mojrmy98b/clink_info_rupnik.txt?rlkey=zotv1468fxw7lqldofvnodb5s&dl=0)

**Comment by chrisant996** [comment]
@rokrupnik Thank you for reporting this, and for including the diagnostic info!  And especially thank you for the additional info about a ~2100px breakpoint.  (And for giving it a unique name "clink_rupnik.log" so it's separate in my Downloads folder! 🤩 I appreciate the attention to detail.)

When I replay the log file on my machine, it works fine.  But, since my current monitor is only 1920px wide, I made the terminal width 306 characters to match yours from the log file.  Maybe the actual pixel width is relevant, so I'll try it on a larger monitor later today.

It seems that the hyperlink escape codes are getting mishandled by the terminal when the terminal width is large.  That seems strange, but I recently learned that terminals tend to garble escape codes when outputting long strings.  And Clink outputs the entire prompt and input line as a single string in order to work around problems when resizing the terminal.  It's beginning to look like it's a deadly tradeoff:  either resizing doesn't work, or escape codes in long lines get garbled.

This definitely gives me a promising lead to follow up on later tonight, and I'll report back with my findings.

In the meantime, running `clink set autosuggest.hint false` will probably work around the issue.

**Comment by arogl** [comment]
I have a similar issue in windows terminal preview while using oh-my-posh since upgrading to v1.5.17

Screenshot shows the double prompt and then on windows resize it goes back to a single prompt until the next command is entered

![Terminal display issues](https://github.com/chrisant996/clink/assets/1115472/f0461172-2a9a-46cf-8497-fd5e512a5c1b)

Windows Terminal info 
![image](https://github.com/chrisant996/clink/assets/1115472/c1b4e4be-f762-4d96-8d38-c8e9a205c721)

clink info
```
version          : 1.5.17.288dce
session          : 17376
injected         : clink_dll_x64.dll
binaries         : C:\Program Files (x86)\clink
state            : C:\Users\arogl\AppData\Local\clink
log              : C:\Users\arogl\AppData\Local\clink\clink.log
default settings : C:\Program Files (x86)\clink\default_settings
settings         : C:\Users\arogl\AppData\Local\clink\clink_settings
history          : C:\Users\arogl\AppData\Local\clink\clink_history
scripts          : C:\Program Files (x86)\clink ; C:\Users\arogl\AppData\Local\clink
default_inputrc  : C:\Program Files (x86)\clink\default_inputrc
inputrc          : %clink_inputrc%
                     (unset)
                 : state directory
                     C:\Users\arogl\AppData\Local\clink\.inputrc   (LOAD)
                     C:\Users\arogl\AppData\Local\clink\_inputrc
                 : %userprofile%
                     C:\Users\arogl\.inputrc
                     C:\Users\arogl\_inputrc
                 : %localappdata%
                     C:\Users\arogl\AppData\Local\.inputrc
                     C:\Users\arogl\AppData\Local\_inputrc
                 : %appdata%
                     C:\Users\arogl\AppData\Roaming\.inputrc
                     C:\Users\arogl\AppData\Roaming\_inputrc
                 : %home%
                     C:\Users\arogl\.inputrc
                     C:\Users\arogl\_inputrc
codepage         : 1252
keyboard langid  : 3081
keyboard layout  : 00000409
```


[clink_arogl.log](https://github.com/chrisant996/clink/files/13482210/clink_arogl.log)

[clink_settings_arogl.txt](https://github.com/chrisant996/clink/files/13482221/clink_settings_arogl.txt)

**Comment by chrisant996** [comment]
Thanks, everyone -- I found the issue.  I'll publish a fix this evening.

In 2018 in commit 589b9498 Martin accidentally introduced a buffer-splitting bug at 384 characters.  It can split escape codes or even UTF8 characters.  This has very likely been the source of a few weird intermittent display problems over the years.

The issue was specifically [here](https://github.com/chrisant996/clink/blob/589b949854f63bd56c8a2e7e798a27bba86cb894/clink/terminal/src/win_screen_buffer.cpp#L36-L52).

(This also revealed that indeed some terminal implementations behave strangely when given incomplete escape sequences.  But the primary root cause was in Clink, not in the terminal implementations.)

@rokrupnik @arogl Thank you **VERY MUCH** for the log files.  I was able to gain many clues from them, including the fact that the output string was getting split somewhere between 360 and 396 characters (which is such an unusual number for a buffer size).  Once I found the line of code with the 384 threshold, all the puzzle pieces fell into place.

This has been an issue for a very long time, but until now it was only happening in rare and intermittent cases.

It's very strange that even when I set my terminal width to a size that splits the buffer, the problem doesn't happen for me.  I wonder if it may be due to the fact that I have the latest version of Windows Terminal installed, and maybe it has a fix for split hyperlink escape codes.  I'm going to play a bit more and try to come up with a repro inside Clink, and also outside Clink, so I can be sure that the fix indeed solves the problems.

**Comment by chrisant996** [comment]
> Screenshot shows the double prompt and then on windows resize it goes back to a single prompt until the next command is entered

@arogl Yes.  However, that issue is completely unrelated:

- ce973bff5c306efd8a9ce721621c28ffdf0dec1e fixes the prompt moving up 1 line too far, plus not erasing all the text below the prompt (regression introduced in v1.5.17).
- 396078aff5f46a169fae922d739ad1c54c7268a8 fixes the split escape code issue that was garbling the display (regression introduced in v1.5.15, but really just spotlighted a bug that's existed since Martin's initial v1.0 rewrite of Clink, but previously had only happened in rare cases).

**Comment by chrisant996** [comment]
Now that I know the root cause, I am able to force the issue to happen in the IDEA IntelliJ embedded terminal.

But I am completely unable to make it repro in Windows Terminal or in a legacy conhost terminal window.

At this point, I'm pretty sure the reason I can't reproduce it in WT or conhost is because I have a version of WT installed that has a newer version of the conhost libraries than stock Win10 has, and the newer conhost library has a fix for handling split escape sequences.

This completes the end-to-end analysis, and satisfies me that the root cause has been identified accurately and the fix in Clink v1.5.18 correctly addresses the issue.

**Comment by arogl** [comment]
@chrisant996 I can confirm the update has fixed the double prompt on my version of WT preview.

**Comment by rokrupnik** [comment]
@chrisant996 same here, I confirm the fix resolved the issue.

Thanks for the super quick fix! Also big **THANK YOU** for all the hard work you and the cmder team is doing to keep us sane in corporate Windows environments with super strict policies 😄 The least we can do is to put ourselves in your shoes at least for a minute and help you to help us!
