### ISSUE TITLE
install without admin rights?

### ISSUE THREAD

**Issue by CrazyWolf13** [chrisant996/clink#525]
Hi
Is there any way to install a slim version of this without admin rights?
Injecting in elevated CMD's is not neccessary

**Comment by chrisant996** [comment]
The setup .exe requires administrator rights.

But you can always instead download the .zip file and manually "install" by extracting the files from the .zip file.

**Comment by chrisant996** [comment]
The new [Installation](https://chrisant996.github.io/clink/clink.html#installation) documentation section covers 4 ways to install Clink.  (3 of them do not need administrator rights.)

The [repo page](https://github.com/chrisant996/clink)'s README file also has a new [Installation](https://github.com/chrisant996/clink#installation) section.

**Comment by CrazyWolf13** [comment]
> The setup .exe requires administrator rights.
> 
> But you can always instead download the .zip file and manually "install" by extracting the files from the .zip file.
> 
> Or install via scoop or winget.

Huge thanks!

It worked through the manual zip method, however winget method does require admin as well, was my second attempt before asking here.

❤️

**Comment by chrisant996** [comment]
> however winget method does require admin as well

Oh, ok, I guess winget runs the setup .exe then.  Thanks for the clarification!

**Comment by asu335** [comment]
sorry for bump the closed issue, but any hope to include it in the installer as options to select -- all users (with admin rights) or current user?

**Comment by chrisant996** [comment]
> sorry for bump the closed issue, but any hope to include it in the installer as options to select -- all users (with admin rights) or current user?

@asu335 I assume you're asking because you want to avoid elevation.

Because of AutoRun, _**uninstall**_ requires elevation otherwise the uninstaller can't safely un-register Clink before deleting the program files (if it can't safely un-register Clink during uninstall then that can potentially create errors for all users every time they start cmd.exe).  Since the uninstaller requires elevation, then I'm concerned about making the installer not require elevation.

Either install it manually by downloading the ZIP file and extracting files from it, or use `scoop` to install.  See [Installation](https://chrisant996.github.io/clink/clink.html#installation).
