### ISSUE TITLE
q: win10 't' key is not printed when pressed

### ISSUE THREAD

**Issue by iggu** [chrisant996/clink#541]
Tried every terminal client could reach: vanilla cmd.exe, wezterm, fluent, mobax - can reproduce everywhere
Cmd w/o clink injected accepts 't' key in command line; when clink is injected (or autostarted) - nothing happens, cannot enter 't' key.
I beleive that something wrong in my setup, but can't get a clue what could go wrong.
I downgraded clink up to jul'2022 version - and no difference.
Can please help with advice?

**Comment by chrisant996** [comment]
There's probably something wrong in your .inputrc file.  That's where key bindings are defined.

Can you share your .inputrc file?

**Comment by iggu** [comment]
yes, thanks for the idea
the only line I added to default inputrc is
`terminate_autoanswer = 1`
commenting out this line eliminates the problem
but is that what should be?

**Comment by chrisant996** [comment]
Yes, that's the problem.

How did you decide to put that line in the .inputrc file?

That line looks like it's copied from the very old v0.4.9 Clink settings file, and pasted into the .inputrc file.

The [.inputrc file has a specific format](https://chrisant996.github.io/clink/clink.html#init-file), which is detailed in the Clink documentation.  Putting lines from other file(s) into .inputrc will be interpreted using the format rules for the .inputrc file, and won't behave how you'd expect them to behave in the other file(s) the lines were copied from.

It looks like you're trying to set [Clink settings](https://chrisant996.github.io/clink/clink.html#configclink), so you should use the `clink set` command.  Refer to the documentation.  (In particular, it looks like you're looking for the [`cmd.auto_answer`](https://chrisant996.github.io/clink/clink.html#cmd_auto_answer) setting.)

A good place to start reading to learn more is the [Getting Started](https://chrisant996.github.io/clink/clink.html#getting-started) section.  I know there's a lot of information.  It's because there's so much Clink can do.

**Comment by iggu** [comment]
wow, thanks for the answer
i googled the wrong and/or outdated solution, i beleive
a few people read the official docs, and I am not the one of them :-(

clink is wonderful project, very stange that I haven't heard about it before
thank you for it! 
next time I'll look through the docs first

(but concerning this particular issue - I just forgot that I changed the initrc, and had no chance to solve the problem w/o your help)
