### ISSUE TITLE
[Security] lua used in this project is vulnerable

### ISSUE THREAD

**Issue by the-Chain-Warden-thresh** [chrisant996/clink#555]
CVE-2020-24370 is a security vulnerability in lua. Although the CVE decription in [NVD](https://nvd.nist.gov/vuln/detail/CVE-2020-24370) said that this CVE only affected lua 5.4.0, according to [lua](https://www.lua.org/bugs.html#5.4.0-11) this CVE actually existed since lua 5.2. The root cause of this CVE is the negation overflow that occurs when you try to take the negative of 0x80000000. Thus, this CVE also exists in this project. The file which contains [vulnerable functions](https://github.com/chrisant996/clink/blob/master/lua/src/ldebug.c#L128) is lua/src/ldebug.c.
You can easily fix this vulnerability by referring to this [patch](https://github.com/lua/lua/commit/a585eae6e7ada1ca9271607a4f48dfb17868ab7b).

**Comment by chrisant996** [comment]
Thanks for the notification.

> You can easily fix this vulnerability by referring to this [patch](https://github.com/lua/lua/commit/a585eae6e7ada1ca9271607a4f48dfb17868ab7b).

No, the "easily" part is misleading, and I think it's based on an assumption without having looked at the 5.2 sources or the history between 5.2 and 5.4.

The vararg implementation in Lua was rewritten _twice_ after 5.2.4 and before the commit that fixes the CVE:
- First rewrite:  https://github.com/lua/lua/commit/5c8770f8969a73cf4ca503f54c2217f76de62e04
- Second rewrite:  https://github.com/lua/lua/commit/b1379936cf35787d3ef3aab82d1607a3e1562eef

The cited patch relies on both of the rewrites (which look intertwined with other changes over time, as well).

**Comment by chrisant996** [comment]
The issue is clearly not urgent, and I'll see about coming up with a fix over the next week or so.

**Comment by chrisant996** [comment]
Also, to be clear:  Clink does not perform the vulnerable operation.

Malicious third party scripts might perform the vulnerable operation.  But if you have malicious third party scripts running, then this vulnerability is pretty uninteresting since there are so many much worse things that malicious scripts can do.

In fact, I don't see any reason to even waste time fixing the CVE.  Clink does not perform the vulnerable operation, so Clink by itself is not vulnerable.

The only way to become vulnerable would be to run a malicious script.  And if a malicious script is somehow able to get run, then there's an infinite number of worse and more impactful things it can do simply by using Lua itself without exploiting any bugs.

This isn't even worth addressing as "defense in depth".  Both "Security" and "Moderate" are misleading tags in this case.

**Comment by chrisant996** [comment]
For me the issue is the fix isn't a straight port, so I want to ensure the code is well understood (including by myself) and the fix is verifiable. Both that it solves the issue, and doesn't introduce regressions.

I agree there's no harm in fixing the issue even if it isn't a credible threat. But there would be harm in an incorrect fix, and so I don't want to accept a fix unless it either comes from the Lua org or is well understood by myself (because I'm responsible for the effects).

I partially understand the change, but not fully yet. I can't accept a PR until I sufficiently understand the surrounding code and the change.

**Comment by goodusername123** [comment]
@chrisant996 
I have some good news! The process of bringing this fix into Lua 5.2.4 based on a official source is a lot more straightforward then originally thought as Lua 5.3.6 (the very last release of Lua 5.3 which was also released in the same month as 5.4.1) actually includes a fix for this bug and funnily enough the implementation exactly matches the pull request linked to in [this comment](https://github.com/chrisant996/clink/issues/555#issuecomment-1924067504).

I ended up finding this out while comparing dates and doing diffs on releases of Lua, since minor releases/versions of Lua seem to be quite poorly documented as I'm not sure if changelogs even exist at all.

So in conclusion for a official version of a fix for this bug that's way easier to properly translate into Lua 5.2.4 simply do a diff of `ldebug.c` between [Lua 5.3.5](https://lua.org/ftp/lua-5.3.5.tar.gz) and [Lua 5.3.6](https://lua.org/ftp/lua-5.3.6.tar.gz) or simply look at https://github.com/libretro/RetroArch/pull/16190 since it ends up being identical,
And also the only difference between the area of code in Lua 5.2 and Lua 5.3 where the fix targets is `cast_int` which was introduced in this commit during Lua 5.3's development: https://github.com/lua/lua/commit/e723c75c02a48d0c766f1f30f7a321f7fdb239dc

Oh and also as a final extra note ~~I guess the Lua 5.3 version of this fix doesn't show up in the Lua GitHub mirror since it only tracks the development branch~~ the Lua 5.3 version of this fix appears in the Lua GitHub mirror under the [`v5.3`](https://github.com/lua/lua/tree/v5.3) branch here (I just found this out): https://github.com/lua/lua/commit/b5bc89846721375fe30772eb8c5ab2786f362bf9

**Comment by chrisant996** [comment]
@goodusername123 ah that's great, thanks! I'll take a look tonight and then merge it.
