### ISSUE TITLE
Run lua script at startup, but on demand

### ISSUE THREAD

**Issue by eblis** [chrisant996/clink#558]
I'm trying to configure [Starship](https://starship.rs) with CMD & clink and I'm trying to configure it separate from my standard command prompt.

I would like to tell clink to run a lua script at startup (starship.lua), but only if certain flag are passed on the command line, but I'm having trouble configuring that.

If I create the starship.lua script cmd will always load it, but I want to load it only sometimes, when i start my Starship profile (but not when a normal cmd prompt session is started).

I tried running `cmd /k set clink.path "new\path\with\just\starship.lua"`, but that didn't work.

What's the best way to run cmd and optionally run a lua or batch script ?

**Comment by chrisant996** [comment]
> If I create the starship.lua script cmd will always load it, but I want to load it only sometimes, when i start my Starship profile (but not when a normal cmd prompt session is started).

I think you're asking how to have two different Clink profiles, one with starship and one not with starship, and how to tell Clink which profile to use.  [File Locations](https://chrisant996.github.io/clink/clink.html#filelocations) describes the way to set the profile directory.

> I tried running `cmd /k set clink.path "new\path\with\just\starship.lua"`, but that didn't work.

`set` is a cmd.exe command, and cmd.exe and `set` don't know anything about Clink.

I'm not going to break down the other problems with that attempt, because it's going in a wrong direction and I don't want to create confusion by talking about that direction.

> What's the best way to run cmd and optionally run a lua or batch script ?

There isn't a universally "best way".  There are many ways; too many to try to list and describe.

For example, you could make a Lua script check whether an environment variable is set, and if not then return immediately without running the rest of the script.

**Comment by eblis** [comment]
> I think you're asking how to have two different Clink profiles, one with starship and one not with starship, and how to tell Clink which profile to use. [File Locations](https://chrisant996.github.io/clink/clink.html#filelocations) describes the way to set the profile directory.
> Or you could go with what you started out trying to do, and have two different Clink profiles. Scripts located in a profile directory are only run when using that profile. But history and settings are also in the profile, and if you want to share history and settings between starship and non-starship sessions, then using two profiles will not do what you want.

This sounds exactly like the thing i was looking for, thanks !

I think i want to keep history separate anyway, so that would be another plus.

**Comment by chrisant996** [comment]
I stated the following, but missed explaining the implication:

> Scripts located in a profile directory are only run when using that profile.

So, if you put the starship.lua script directly in the profile directory for the starship profile, then the starship.lua script will only be run when using the starship profile.  That might have already been clear, but I wanted to clarify, just in case.
