### ISSUE TITLE
profile/clink.lua can not be loaded after version clink.1.1.17.ae1847

### ISSUE THREAD

**Issue by fcying** [chrisant996/clink#56]
I put clink.lua in clink's profile dir. but after clink.1.1.17.ae1847.

clink.lua in profile dir can not be loaded, must set clink.path or use clink.1.1.16.c2fd18

**Comment by chrisant996** [comment]
I believe that was fixed the other day in Clink 1.1.20.

**Comment by fcying** [comment]
I current use Clink v1.1.22.808f0d, I test clink.1.1.20.fa19d6, it have same problem.

clink info
```
clink info
version  : 1.1.22.808f0d
session  : 8404
binaries : D:\tool\scoop\apps\clink\1.1.22
state    : d:\tool\scoop\apps\clink\current\profile\
log      : d:\tool\scoop\apps\clink\current\profile\clink.log
settings : d:\tool\scoop\apps\clink\current\profile\clink_settings
history  : d:\tool\scoop\apps\clink\current\profile\clink_history
scripts  : D:\tool\scoop\apps\clink\1.1.22 ; d:\tool\scoop\apps\clink\current\profile\
inputrc  : %clink_inputrc%
             d:\tool\scoop\apps\clink\current\profile\.inputrc
             d:\tool\scoop\apps\clink\current\profile\_inputrc
         : %userprofile%
             C:\Users\fcying\.inputrc
             C:\Users\fcying\_inputrc
         : %localappdata%
             C:\Users\fcying\AppData\Local\.inputrc
             C:\Users\fcying\AppData\Local\_inputrc
         : %appdata%
             C:\Users\fcying\AppData\Roaming\.inputrc
             C:\Users\fcying\AppData\Roaming\_inputrc
         : %home%
             C:\Users\fcying\.inputrc
             C:\Users\fcying\_inputrc
```

the profile/clink.lua which is fork form cmder' vendor/clink.lua, for modify clink.prompt(git,svn), and load clink-completions.

**Comment by chrisant996** [comment]
Ok, thanks. I'll check to make sure the new Clink is really loading clink.lua from the same place as 0.4.9 did.

But cmder uses an undocumented internal debugging mode of Clink in order to take over and replace certain startup behavior of Clink. So copying its clink.lua isn't necessarily going to work as expected, even with Clink 0.4.9.

I'm trying to find a way to clean that up without introducing new problems.

Instead of trying to extract only some of Cmder's functionality, it would be safer and probably simpler to install the vendor scripts directly. From [clink-completions](https://github.com/vladimir-kotikov/clink-completions) and cmder-powerline-prompt (but consider using the [chrisant996/cmder-powerline-prompt](https://github.com/chrisant996/cmder-powerline-prompt) fork since it has new fixes and improvements).

**Comment by chrisant996** [comment]
As far as I can tell, even with Clink 0.4.9 if one copies a clink.lua into the profile directory it won't be loaded, and it's intentionally meant to not be loaded.  Clink 0.4.9 only loads clink.lua from the same directory as the dll file, and Clink 1.1.20 and higher behave the same as Clink 0.4.9 as far as I can tell.

If a difference between 0.4.9 and 1.1.20+ is observed with respect to which directory they load clink.lua from, please reopen this issue with additional details.

Thanks!
