### ISSUE TITLE
Autocompletion for file names fails

### ISSUE THREAD

**Issue by uahim** [chrisant996/clink#568]
~~hello,~~

~~this refers to latest clink on win11.~~

~~in one of the latest versions, file name autocompletion seems to have stopped working for me. CTRL + SPACE provides a list of executables in %path% rather than file name suggestions in %cd%. do I need to change/add a new setting or so?~~
~~and when I try prefixing with a dot like ./ I'm getting a list of the root disk contents rather than again %cd%~~
~~however, autocompletion for subdirectories in %cd% does work~~

~~thank you~~

update: 
apologies, the mistake was of course on my side - sorry for having wasted your time.

**Comment by chrisant996** [comment]
It sounds like you found that it's the [Executable Completion](https://chrisant996.github.io/clink/clink.html#executable-completion) feature (a feature that bash and zsh and fish all have, but which cmd never had until Clink).  The feature can be disabled with the command listed in the docs.

**Comment by chrisant996** [comment]
P.S. regarding this specific part:

> when I try prefixing with a dot like ./ I'm getting a list of the root disk contents rather than again %cd%

That's because in Windows CMD `/` is a switch character, not a path separator.  CMD itself interprets `./xyz` or `abc/xyz` as though `.  /xyz` or `abc  /xyz` was typed.  CMD parses that way, and so Clink has to replicate that same parsing.  Clink can't make CMD treat that differently.  However, adding a leading `"` tells CMD not to treat `/` as a switch character.
