### ISSUE TITLE
Completion problem with two levels or more of ../

### ISSUE THREAD

**Issue by AiZ** [chrisant996/clink#57]
Hello,

First, thank you for keeping this marvellous tool alive!

I have just migrated from 0.4.9 to 1.1.22 and so far so good, everything is Ok, except one thing.

If I complete more than one ../, only the last slash is converted to backslash. It's ok to change directory but not for executing programs ('..' is not recognized as an internal command or etc.).

![clink01](https://user-images.githubusercontent.com/3725758/105061039-52b3f480-5a79-11eb-981d-51c647110241.gif)

Or maybe I missed something in the help file. I've made nearly no tuning to feel at home with your version, keeping previous settings file (almost vanilla from 0.4.9), history and just binding scrolling to Shift-PgUp/PgDn in .inputrc.

Do you experience the same behaviour?

Regards,

    AiZ

**Comment by chrisant996** [comment]
Thank you for reporting this.  I see where the problem is occurring, and it only happens for built in match generators for the first word (and only when `exec.match` is enabled) and for `cd` etc.  It doesn't happen for `echo ../../s`**complete** or for `;echo ../../s`**complete** or `fooexe ../../s`**complete** or etc -- those normalize all the path separators to backslash.

**Comment by chrisant996** [comment]
Or, if you want to type `../whatever` in the first word and use completion, then CMD needs a `"` inserted:  `"../whatever` will allow completion to work as desired.

I know it isn't like bash or Linux.  But this isn't bash or Linux, and it's important to stay compatible with how CMD actually works.
