### ISSUE TITLE
History for multi-line commands

### ISSUE THREAD

**Issue by koppor** [chrisant996/clink#58]
Windows also knows multiline commands (source: https://stackoverflow.com/a/605724/873282)

```terminal
$ echo Hello ^
Mehr? World!
Hello World!
```

If I press <kbd>Cursor</kbd>+<kbd>Up</kbd>, then only the first line is shown:

```terminal
$ echo Hello ^
```

Would it be possible to support multiline command history?

**Comment by chrisant996** [comment]
Maybe. It seems expensive, and it's unclear without research whether it could be possible.

How commonly is it used, and what is an example scenario where it's particularly beneficial?

I confess in 30+ years of using command.com and cmd.exe, I've never actually used the "More?" line continuation.  I never saw a scenario where it seemed useful for my needs.  I'd love to understand if there's a scenario where it's important.

**Comment by koppor** [comment]
For me, it would be OK, if it was stored as single line command, because multi-line caused troubles when pasting it. My usecase was running docker with a complex command line put in a) the documentation and b) copy'n'pasted from that documentation (to try out)

```terminal
docker run^
  --rm^
  -it^
  -e COPYBARA_CONFIG='other.config.sky'^
  -e COPYBARA_SUBCOMMAND='validate'^
  -e COPYBARA_OPTIONS='--init'^
  -v c:/tmp/dir1:/container/dira^
  -v c:/tmp/dir2:/container/dirb^
  copybara copybara
```

(I did not see that I could use docker inside WSL2)

**Comment by chrisant996** [comment]
Sorry, no.

There doesn't appear to be a reliable way to intercept the `More?` prompts.  Clink can't safely handle them, nor can it safely intercept them and append to the previous line.

I can see how to handle or intercept them, but not safely.  Because the `More?` is a localized string and the resource ID is subject to change, but even if that were reliable it's still possible for a subsequent prompt to not actually be a line continuation prompt, because a command script could be printing the text and triggering an input prompt.  There's no way for Clink to tell reliably.

And even if those could be reliable, it would also be complicated and expensive to make the argmatchers and match generators etc work properly (not to mention doing it in a way that lua scripts don't get broken).

This is unfortunately not feasible any time in the foreseeable future, I'm sorry to say.

**Comment by koppor** [comment]
My gut feeling was that when pressing <kbd>Enter</kbd>, the submission can be handled. -- Nevertheless, thank you for looking into this. Now, we have it documented and if someone else discoveres `^`, they now know that this is an edge case very seldomly used and thus unsupported.

**Comment by chrisant996** [comment]
> My gut feeling was that when pressing <kbd>Enter</kbd>, the submission can be handled.

Clink is not currently involved at all.  Clink would have to intercept additional API calls.  And the problem is the API call for the `More?` prompt is too generic and can't be reliably differentiated from other input calls that are not about command line input.
