### ISSUE TITLE
Trojan:Win32/Casdet!rfn

### ISSUE THREAD

**Issue by HeadLightsDc** [chrisant996/clink#581]
I did an installation of tabby, I guess it uses this library too. The antivirus shows me this path clink\updater\v1.6.10.zip and informs me that it's a Trojan:Win32/Casdet!rfn

**Comment by zael99** [comment]
I also get this issue from Cmder

**Comment by chrisant996** [comment]
See pinned issue #369.

The problem is in the anti virus tool, not in Clink. You need to contact the anti virus tool technical support and report the false positive to them so they can fix it. Clink has no control over anti virus tools (if it did then anti virus tools would be worthless because any virus could tell a tool "I'm not a virus" and the took would believe them).
