### ISSUE TITLE
uninject / deactivate clink

### ISSUE THREAD

**Issue by bwagner** [chrisant996/clink#584]
Is there a way to reverse `inject`? `clink uninject` so to speak?
I often cooperate with others who abhor my shell settings, so it would be very useful to move in and out of clink.

**Comment by chrisant996** [comment]
No.  It isn't safe to unhook system APIs after hooking them.

Do you mean you want some environment variable that can be set to tell Clink to stop intercepting the prompt and input?  So that you could run `set CLINK_DISABLE=1` and then cmd.exe would behave as if Clink weren't injected, and then later run `set CLINK_DISABLE=0` and then Clink would start working again?

Two of the reasons I've been reluctant to add something like that are:
1. Inevitably, there will be reports about Clink not working, and after a bunch of time spent on investigation it will turn out that CLINK_DISABLE had been set and forgotten.  I do not want to waste time on that sort of support problem.
2. It isn't clear why that would be an important or necessary feature.

Why not instead create a profile that looks and behaves like plain cmd.exe?  And run `set CLINK_PROFILE=c:\plain_profile` to "disable" Clink?  Etc.

**Comment by bwagner** [comment]
Thank you. In fact, I was thinking of a `clink uninject` command. But I understand it's not often asked for.
Thank you!

**Comment by chrisant996** [comment]
> I was thinking of a `clink uninject` command. But I understand it's not often asked for.

Literally un-injecting Clink isn't safe.  It can leave cmd.exe unstable.

It could potentially be feasible to disable Clink, though, via an environment variable.  Or to switch profiles to one that looks and acts as if Clink weren't injected, even though it is.

**Comment by Cube707** [comment]
just my two cents: 

I successfully use `CLINK_NOAUTORUN` to temporarily disable clink, running this will drop me into a bare cmd session which I can `exit` at any time to get clink back:

```cmd
set CLINK_NOAUTORUN=1 && cmd & set CLINK_NOAUTORUN=

:: do stuff

exit
```

The third command is optional and just ensures `CLINK_NOAUTORUN` is cleaned up when the sub-process exits. Once you run it `clink` remembers it so it's much less of a hassle to reuse than one would think..

--- 

@chrisant996 I cant find `CLINK_DISABLE` in the docs? is this a typo?

**Comment by Welding-Torch** [comment]
I think that a `clink uninject` is **extremely necessary**. Only Windows Terminal on my machine supports nerd fonts. What about plain old `cmd.exe`? That can't show nerd font icons, and so my prompt looks bad. I don't want that if I have to use cmd.exe for something minimal. I want to be able to uninject clink.

![image](https://github.com/chrisant996/clink/assets/46340124/e942c818-1078-4be1-9dfb-3b0bdb789021)

And if clink can't be uninjected, is there a command I can use to see the default prompt (just for the current session) instantly instead of my custom prompt? That could be a solution. It should be a short command, not like the aforementioned `set CLINK_PROFILE=c:\plain_profile`.

Thanks.

**Comment by Welding-Torch** [comment]
Also, `CLINK_DISABLE` doesn't work for me either. Like @Cube707 mentioned.

**Comment by chrisant996** [comment]
> Also, `CLINK_DISABLE` doesn't work for me either. Like @Cube707 mentioned.

@Cube707 @Welding-Torch There is no such thing as `CLINK_DISABLE`.  I think you've misread the comments here.

**Comment by chrisant996** [comment]
> just my two cents:
> 
> I successfully use `CLINK_NOAUTORUN` to temporarily disable clink, running this will drop me into a bare cmd session which I can `exit` at any time to get clink back:

The original poster wants a way to literally un-inject Clink from a CMD instance where Clink has already been injected.  And that isn't safe to do -- it can make CMD crash or malfunction.

If you don't use autorun, then simply running cmd.exe gets you a CMD without Clink.

If you use autorun, then you're right that setting CLINK_NOAUTORUN and then starting a nested cmd.exe gets you a CMD without Clink.

I don't know whether that would meet the original poster's needs, but the original poster specifically wanted a way to evict Clink.  Evicting Clink is not possible (without risking crashes and malfunctions in CMD).

However, it could be possibly to merely _**disable**_ Clink without actually un-injecting Clink.  The original poster said that wasn't good enough for them.

> @chrisant996 I cant find `CLINK_DISABLE` in the docs? is this a typo?

I think you misread the comment.  There is no `CLINK_DISABLE`.  I asked the original poster if adding a `CLINK_DISABLE` would satisfy them, and they said no.

**Comment by Welding-Torch** [comment]
@chrisant996 Shall I open a new issue for this?

> And if clink can't be uninjected, is there a command I can use to see the default prompt (just for the current session) instantly instead of my custom prompt? That could be a solution. It should be a short command, not like the aforementioned set CLINK_PROFILE=c:\plain_profile.

**Comment by chrisant996** [comment]
> I think that a `clink uninject` is **extremely necessary**.

I'm willing to design a way to disable Clink, or to disable parts of Clink.

@Cube707 @Welding-Torch Can you please describe the specific motivations behind wanting a way to "uninject" Clink?  And specifically which parts/features of Clink you want to disable?

If you mean you literally want to evict the Clink DLLs after they've been injected, and unload them from the CMD process, then that specific operation isn't possible to do safely without potentially crashing CMD or causing malfunctions in CMD.

Or if it's acceptable for Clink to technically stay in memory as long as it's disabled, then there are plenty of other approaches that could be built.

You mentioned wanting to disable prompt filtering.  That's only one piece of Clink.  So it sounds like maybe you don't actually want to completely disable Clink.  And the original poster mentioned other users being unfamiliar with Clink and wanting to avoid confusing them.

- Is prompt filtering the only part of Clink you want to disable?
- Do you want to disable the input editing and key bindings and revert to the normal input line editing?
- Do you want to disable input line coloring?
- Do you want to disable completions?
- Do you want to disable/suspend execution of Lua scripts, or do you want those to still work?
- Etc:  the more specifically you can describe which parts of Clink you want disabled, the more it helps me to understand what's desired and be able to design a solution.

I have to take all of these kinds of things into account as part of designing a built-in mechanism for disabling Clink and/or parts of Clink.

> Only Windows Terminal on my machine supports nerd fonts. What about plain old `cmd.exe`? That can't show nerd font icons, and so my prompt looks bad. I don't want that if I have to use cmd.exe for something minimal. I want to be able to uninject clink.

@Welding-Torch Yes it can.  Plain cmd.exe can show nerd font icons, but by default the list of fonts in the Properties dialog only lists certain predefined fonts.  But for example the clink-flex-prompt Readme [has a section](https://github.com/chrisant996/clink-flex-prompt#i-installed-a-font-why-wont-it-show-up-in-the-list-of-available-terminal-fonts) about how to get other fonts (such as Nerd Fonts) to show up in the font list for the old default conhost consoles in Windows.

> And if clink can't be uninjected, is there a command I can use to see the default prompt (just for the current session) instantly instead of my custom prompt? That could be a solution. It should be a short command, not like the aforementioned `set CLINK_PROFILE=c:\plain_profile`.

There currently isn't a built-in mechanism.  I'm willing to build one, but there are a lot of questions that need to be answered first.  (And if fonts are the only motivation then maybe it isn't needed after all?)

In the meantime:

What about the suggestion from @Cube707 ?
You could make a batch script `noclink.cmd` which starts a nested cmd without Clink:
**noclink.cmd**
```cmd
@echo off
setlocal
set CLINK_NOAUTORUN=1
cmd.exe /k
```

You could make a Lua script that disables prompt filtering when an environment variable is set:
**disablepromptfilters.lua**
```lua
-- This disables Clink's prompt filtering when an environment variable
-- CLINK_DISABLE_PROMPT_FILTERS is set.
--
-- For example, running this at the command prompt, or in a batch script:
--      set CLINK_DISABLE_PROMPT_FILTERS=1
--
-- Clear it again later to reenable prompt filtering.
--      set CLINK_DISABLE_PROMPT_FILTERS=

-- You can change the name of the variable by changing envname below.
local envname = "CLINK_DISABLE_PROMPT_FILTERS"

local nono = clink.promptfilter(-999999999)
function nono:filter(prompt)
    if os.getenv(envname) then
        return prompt, false
    end
end
```

And there are some other ways as well.  Different users and different workflows or motivations may prefer different degrees of disablement or different ways of initiating the disablement.

**Comment by bwagner** [comment]
> > just my two cents:
> > I successfully use `CLINK_NOAUTORUN` to temporarily disable clink, running this will drop me into a bare cmd session which I can `exit` at any time to get clink back:
> 
> The original poster wants a way to literally un-inject Clink from a CMD instance where Clink has already been injected. And that isn't safe to do -- it can make CMD crash or malfunction.
> 
> If you don't use autorun, then simply running cmd.exe gets you a CMD without Clink.
> 
> If you use autorun, then you're right that setting CLINK_NOAUTORUN and then starting a nested cmd.exe gets you a CMD without Clink.
> 
> I don't know whether that would meet the original poster's needs, but the original poster specifically wanted a way to evict Clink. Evicting Clink is not possible (without risking crashes and malfunctions in CMD).
> 
> However, it could be possibly to merely _**disable**_ Clink without actually un-injecting Clink. The original poster said that wasn't good enough for them.
> 
> > @chrisant996 I cant find `CLINK_DISABLE` in the docs? is this a typo?
> 
> I think you misread the comment. There is no `CLINK_DISABLE`. I asked the original poster if adding a `CLINK_DISABLE` would satisfy them, and they said no.

In fact, if there were a way to have clink temporarily mimic its absence, that would be fine for my purpose!

**Comment by chrisant996** [comment]
> In fact, if there were a way to have clink temporarily mimic its absence, that would be fine for my purpose!

@bwagner Oh ok can you review [this comment](https://github.com/chrisant996/clink/issues/584#issuecomment-2032443985) and the two solutions it mentions?

Also, can you review the bulleted list of questions in that comment, and share your thoughts?  E.g. is there any interest in also being able to selectively disable parts of Clink, such as keeping completions and input line coloring but disabling prompt filtering.

**Comment by chrisant996** [comment]
> @chrisant996 Shall I open a new issue for this?
> 
> > And if clink can't be uninjected, is there a command I can use to see the default prompt (just for the current session) instantly instead of my custom prompt? That could be a solution. It should be a short command, not like the aforementioned set CLINK_PROFILE=c:\plain_profile.

@Welding-Torch I think this current issue is sufficient for tracking the conversation and collecting answers for the many relevant design questions. Do you feel two issues are needed? What would differentiate the two issues from each other? (I'm open to having two issues, but I don't understand what would be different between them.)

**Comment by chrisant996** [comment]
The [clink-gizmos](https://github.com/chrisant996/clink-gizmos) repo now includes a `noclink` command.

- It has a `noclink.cmd` script which either starts a nested `cmd.exe` without Clink, or disables/reenables Clink prompt filtering.
- It has a `noclink.lua` script which registers an argmatcher for `noclink` and also automatically creates a doskey alias for `noclink` to run the `noclink.cmd` script.

Try it out.  Does it meet the needs?  If not, please describe what's not good, why it's not good, and what you'd like to see instead.

**Comment by Welding-Torch** [comment]
Hi @chrisant996,

Before your 1st reply, I looked at @Cube707 's method for creating a new cmd without clink, and implemented that into an [alias for windows](https://www.bgreco.net/alias/). So now when I type `clinkoff`, this script runs:
```cmd
@echo off
echo Clink is set to off. Type exit when you're done :) && echo: 
set CLINK_NOAUTORUN=1 && cmd & set CLINK_NOAUTORUN=
```

Then after reading [your reply](https://github.com/chrisant996/clink/issues/584#issuecomment-2032443985) in which you wrote `disablepromptfilters.lua`, I added that .lua script to my clink scripts directory, and then created a new alias. So now when I type `promptoff`, this script runs:
```cmd
@echo off
set CLINK_DISABLE_PROMPT_FILTERS=1
```

I'm pretty happy with this setup. I've got exactly what I wanted 👍.

<br>

> Do you feel two issues are needed?

Not at all, I only asked that because you referred to "original poster" multiple times and that gave the impression you wanted a separate issue.

> Plain cmd.exe can show nerd font icons, but by default the list of fonts in the Properties dialog only lists certain predefined fonts. But for example the clink-flex-prompt Readme [has a section](https://github.com/chrisant996/clink-flex-prompt#i-installed-a-font-why-wont-it-show-up-in-the-list-of-available-terminal-fonts) about how to get other fonts (such as Nerd Fonts) to show up in the font list for the old default conhost consoles in Windows.

I had a look and man, I am not doing all that. Looks like an incredibly long and convoluted method to do something simple.

> Try it out. Does it meet the needs? If not, please describe what's not good, why it's not good, and what you'd like to see instead.

This is amazing! Though personally I feel like this is such a useful command it should be included in clink by default. But that's just my two cents. 

Thank you!

**Comment by chrisant996** [comment]
> I had a look and man, I am not doing all that. Looks like an incredibly long and convoluted method to do something simple.

@Welding-Torch it's one quick and simple step, for each font you want to be able to select.

Since you said "not doing all that" and "incredibly long and convoluted" but the step is neither long nor convoluted, it makes me wonder whether there's been some kind of misunderstanding.

**Comment by Welding-Torch** [comment]
It is not "one quick and simple step". That superuser.com answer is long. Sure, installing the font itself is a few commands in PowerShell, but the actual checks you have to go through for the font are frustrating. For example, I use [Hack Nerd Font](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Regular/HackNerdFont-Regular.ttf) found [here](https://www.nerdfonts.com/font-downloads#:~:text=%E2%80%A2-,Version%3A%203.003,-%E2%80%A2%20Info%3A%20Dotted). I followed along with the steps to install it, but it didn't show up when I went to `cmd.exe` -> Properties. I'm not sure if Hack Nerd Font passes all the checks needed, and if it doesn't, then I'm not sure what the nearest Nerd font including glyphs(icons) is accepted.

**Comment by chrisant996** [comment]
Oh.  You cannot use proportional spaced fonts.  I assumed it was easy to tell the difference at a glance between what fonts can be used in the old conhost terminal.  So, for me, it is always just a single step -- add a regkey for the font name -- done.  🤷‍♂️

**Comment by chrisant996** [comment]
Oh, even stranger -- I didn't even need to do anything to make these fonts show up:
- Anonymice Powerline
- Cascadia Code PL
- Consolas NF
- DejaVuSansMono NF
- Fira Code NF (an old NFv2 version of the font)
- FiraCode Nerd Font Mono (current NFv3 version of the font)
- InputMono
- JetBrains Mono
- JetBrainsMono NFM
- MesloLGS NF

They all seem to automatically show up in the list for me.

Sorry that it's being frustrating.

_On a slightly related note, i.e. simplifying the prompt to contain less fanciness and be less disorienting for other users who try to use the computer:_

clink-flex-prompt has a default key binding <kbd>Ctrl</kbd>-<kbd>Alt</kbd>-<kbd>Shift</kbd>-<kbd>Z</kbd> which toggles the prompt info ASCII mode (or back out), where any Nerd Font icons or Unicode line drawing characters or Powerline symbols or etc are stripped.  (It can only affect the current prompt and future prompts -- it cannot retroactively rewrite what's already been printed in the past into the terminal screen buffer.)

I use that before I copy/paste text from my console into an email, so that recipients of the email don't see gibberish where icons or etc would have been visible on my screen.

**Comment by chrisant996** [comment]
Deactivating Clink isn't something that fits as being built into Clink at this time.  There isn't a good way to make a `clink disable` command or other direct `clink` commands for this (because of the necessary cross-process communication), and literally evicting Clink out of the cmd.exe process isn't possible to do safely.

Instead, there is a `noclink` script in the clink-gizmos repo.

And at its core it is simply "start a new nested cmd.exe".  And if you have autorun configured, then it's "set CLINK_NOAUTORUN=1 and then start a new nested cmd.exe".  Those aren't deactivating Clink in the current cmd.exe -- instead they are starting a new cmd.exe without activating Clink in the first place.

I'm reluctant to build something in Clink that "deactivates Clink" when in fact that's not really what it does at all.  I feel that would be misleading, and also promotes confusion.

**Comment by Welding-Torch** [comment]
Update:

I chose Fira Code Regular Nerd Font Complete Mono Windows Compatible. And finally- it works. 
![image](https://github.com/chrisant996/clink/assets/46340124/dd9f7a95-ca85-435c-9ecb-d3eb6ff00bd2)

**Comment by randomseed42** [comment]
> The [clink-gizmos](https://github.com/chrisant996/clink-gizmos) repo now includes a `noclink` command.
> 
> * It has a `noclink.cmd` script which either starts a nested `cmd.exe` without Clink, or disables/reenables Clink prompt filtering.
> * It has a `noclink.lua` script which registers an argmatcher for `noclink` and also automatically creates a doskey alias for `noclink` to run the `noclink.cmd` script.
> 
> Try it out. Does it meet the needs? If not, please describe what's not good, why it's not good, and what you'd like to see instead.

I have an very old engineering exe file written in VB to be run in cmdline, and it fails when using cmd when clink autorun, but I'm tired of type `clink inject` which is almost used in any other scenarios. So I simply wrote below script named `cld.cmd` to minimize the impact

```bat
@echo off
cmd.exe /s /k "path_to_clink\clink_x64.exe inject"
```

after add the `cld.cmd` folder to env var, I can run `cld` to get clink and `cmd` to get the original cmd. Just my two cents...

**Comment by chrisant996** [comment]
@randomseed42 It's very surprising to hear that some other program fails if Clink is injected. 

I would be interested to find out why the VB program fails if Clink is injected.

In what way does it fail?

Is the program something you can share?

**Comment by chrisant996** [comment]
> @randomseed42 It's very surprising to hear that some other program fails if Clink is injected. 
> 
> I would be interested to find out why the VB program fails if Clink is injected.
> 
> In what way does it fail?
> 
> Is the program something you can share?

@randomseed42 can you share more about that?
