### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by ianzone** [chrisant996/clink#590]
# Behavior
when open cmd, it shows
<img width="367" alt="image" src="https://github.com/chrisant996/clink/assets/20043230/2c904c7a-e4f1-4a56-8f82-ee44ea747284">

# What I did.
```
# version is 1.6.10
winget install chrisant996.Clink

touch ~/.config/starship.lua

-- starship.lua

load(io.popen('starship init cmd'):read("*a"))()

clink installscripts  C:\Users\yihen\.config\
```

I've read this https://github.com/chrisant996/clink/issues/243 but still not sure how to fix this issue.

**Comment by ianzone** [comment]
```
  ❯ clink info
version          : 1.6.10.d5dce0
session          : 8120
injected         : clink_dll_x64.dll
binaries         : C:\Program Files (x86)\clink
state            : C:\Users\yihen\AppData\Local\clink
log              : C:\Users\yihen\AppData\Local\clink\clink.log
default settings : C:\Program Files (x86)\clink\default_settings
settings         : C:\Users\yihen\AppData\Local\clink\clink_settings
history          : C:\Users\yihen\AppData\Local\clink\clink_history
scripts          : C:\Program Files (x86)\clink ; C:\Users\yihen\AppData\Local\clink ; C:\Users\yihen\.config\
default_inputrc  : C:\Program Files (x86)\clink\default_inputrc
inputrc          : %clink_inputrc%
                     (unset)
                 : state directory
                     C:\Users\yihen\AppData\Local\clink\.inputrc
                     C:\Users\yihen\AppData\Local\clink\_inputrc
                 : %userprofile%
                     C:\Users\yihen\.inputrc
                     C:\Users\yihen\_inputrc
                 : %localappdata%
                     C:\Users\yihen\AppData\Local\.inputrc
                     C:\Users\yihen\AppData\Local\_inputrc
                 : %appdata%
                     C:\Users\yihen\AppData\Roaming\.inputrc
                     C:\Users\yihen\AppData\Roaming\_inputrc
                 : %home%
                     C:\Users\yihen\.inputrc
                     C:\Users\yihen\_inputrc
system           : 10.0.22631.3374
codepage         : 65001
keyboard langid  : 2052
keyboard layout  : 00000804

The system cannot find the path specified.
The system cannot find the path specified.
```
```
  ❯ clink autorun show
Current AutoRun values

  Current user:

    native : "C:\Users\yihen\Mamba\condabin\mamba_hook.bat"&"C:\Program Files (x86)\clink\clink.bat" inject --autorun
     wow64 : "C:\Program Files (x86)\clink\clink.bat" inject --autorun

  All users:

    native : "C:\Program Files (x86)\clink\clink.bat" inject --autorun
     wow64 : "C:\Program Files (x86)\clink\clink.bat" inject --autorun


The system cannot find the path specified.
The system cannot find the path specified.
```

**Comment by chrisant996** [comment]
What troubleshooting have you done?

This is most likely caused by either the `"C:\Users\yihen\Mamba\condabin\mamba_hook.bat"` part in the AutoRun config, or by something in a Lua script that you have in `C:\Users\yihen\AppData\Local\clink` or in `C:\Users\yihen\.config\`, or by how starship is configured (or by something about the starship.lua script).

You need to do some troubleshooting.
For example:
- You could try `clink uninstallscripts C:\Users\yihen\.config\` to see whether that improves things.
- Or check whether you have the latest version of starship.
- Or try removing the `...\mamba_book.bat` part from the AutoRun config to see whether that improves things.
- Or try `clink autorun --allusers uninstall` -- you didn't mention having explicitly run `clink autorun --allusers install`, but someone or something must have run that because your `clink autorun show` output shows it, but Clink does not do that on its own.
- Or try both `clink autorun --allusers uninstall` and also `clink autorun uninstall` and see whether you still get the problem when launching cmd.  That would mean it's coming from Mamba.
- There are tons of troubleshooting steps you can do to narrow things down further, as well.

**Comment by ianzone** [comment]
Hi, thanks for your reply, I confirm there is no `"C:\Users\yihen\Mamba\condabin\mamba_hook.bat"` on my machine, but why it's in the autorun values, and how to remove it?

**Comment by ianzone** [comment]
Oh, I found it out https://github.com/mamba-org/mamba/issues/1907#issuecomment-1253378027
