### ISSUE TITLE
some key work in linux, but no work in clink

### ISSUE THREAD

**Issue by iamqiz** [chrisant996/clink#593]
this key bind work in WSL (windows subsystem for linux), but no work in clink cmd
```
"\e\x83":beginning-of-line
"\C-xl":"\e\x83axe"
```
if i change \x83 to \x73 as follow
```
"\e\x73":beginning-of-line
"\C-xl":"\e\x73axe"
```
then it work.
is this because \x83 char does not exist?

**Comment by chrisant996** [comment]
What key is "\e\x83" expected to correspond to?

It's an ambiguous key sequence:
- `\x83` is invalid UTF8.
- `\e\x83` can mean Alt + AnAdditionalAlt + Ctrl + C (which is nonsensical).
- `\e\x83` can mean ESC then Alt + Ctrl + C.
- `\e\x83` can mean ESC + ESC + Ctrl + C.

It depends on your terminal emulator and keyboard driver and shell config.

Are you trying to make up fake key sequences so that they can be referenced in macros?
Why not instead use real key sequences?
Or why not use key sequences that are valid UTF8?
Why not use key sequences that are expressed in ASCII but are not producible by keyboard drivers?
`"\e[27;9;` _number_ `~":  "whatever"`

What's happening here is that on Windows, in order for UTF8 input to work reliably, Clink's built-in keyboard driver must force 4 readline config variables on:  [convert-meta](https://chrisant996.github.io/clink/clink.html#configconvertmeta), [enable-meta-key](https://chrisant996.github.io/clink/clink.html#configenablemetakey), [input-meta](https://chrisant996.github.io/clink/clink.html#configinputmeta), and [output-meta](https://chrisant996.github.io/clink/clink.html#configoutputmeta).  Refer to the [Readline docs on convert-meta](https://tiswww.case.edu/php/chet/readline/rluserman.html#index-convert_002dmeta) for some brief info on how Readline handles encoding and decoding the "meta" key (which in Windows is the <kbd>Alt</kbd> key).

I don't think we need to dig deep into the low level specifics of what's happening, but the behavior you've experiencing is expected.  The best recommendation is to not use ambiguous key sequences for fake keys.

**Comment by iamqiz** [comment]
1. \e\x83 does not mean alt+\x83 ? 😲 
i try "ESC then Alt + Ctrl + C", it does not show \e\x83 , in picture below , \c-c is \x3 (see ascii table ) 
![Clip_2024-04-09_21-16-30](https://github.com/chrisant996/clink/assets/48077521/f17b5dc1-6de1-4639-9437-9c878a73cccb)

i see microsoft use \x80 to \xFF in their virsual key (https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes),
i also use these virsul key in my autohotkey ,(see:
https://www.autohotkey.com/docs/v1/lib/Send.htm#vk
https://www.autohotkey.com/docs/v1/lib/_MenuMaskKey.htm#Remarks
)
2: i do not use \x0-\x7f, because i do not want to occupy multiple shortcuts;
in fact, i hope readline allow to combine multiple command ,for example, `"\C-x":beginning-of-line,set-mark,clink-forward-bigword`, because it will only occupy a shortcut instead of 4 shortcuts (3 intermediates+1 final)

**Comment by chrisant996** [comment]
> 1. \e\x83 does not mean alt+\x83 ? 😲 
> i try "ESC then Alt + Ctrl + C", it does not show \e\x83 , in picture below , \c-c is \x3 (see ascii table ) 

It's because of differences in the meta modes in Readline. I recommend reading the Readline documentation I shared links for.

> i see microsoft use \x80 to \xFF in their virsual key (https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes),
> i also use these virsul key in my autohotkey ,(see:
> https://www.autohotkey.com/docs/v1/lib/Send.htm#vk
> https://www.autohotkey.com/docs/v1/lib/_MenuMaskKey.htm#Remarks
> )
> 2: i do not use \x0-\x7f, because i do not want to occupy multiple shortcuts;
> in fact, i hope readline allow to combine multiple command ,for example, `"\C-x":beginning-of-line,set-mark,clink-forward-bigword`, because it will only occupy a shortcut instead of 4 shortcuts (3 intermediates+1 final) 

It sounds like you're manually constructing key sequences, or expecting that Linux and Clink use the same keyboard driver (they don't, and can't).  That isn't recommended (and Linux and different terminals in Linux use different keyboard drivers, and users can configure Readline meta variables differently based on details about their system).

Have you read Clink docs on binding keys? 
Have you found `clink echo` or the table of key sequences in the docs?

**Comment by iamqiz** [comment]
@chrisant996  thanks for your explanation,
> Have you read Clink docs on binding keys?
Have you found clink echo or the table of key sequences in the docs?

i have not, when i am idle, i will
