### ISSUE TITLE
How to stop colors?

### ISSUE THREAD

**Issue by obumnwabude** [chrisant996/clink#612]
Hi and Thanks for the package 

Running `clink set  clink.colorize_input false`  makes everything yellow. How do I stop the entire colors please?

**Comment by chrisant996** [comment]
It sounds like you installed with "Use enhanced defaults" checked.
It sounds like you don't want to use the [enhanced defaults](https://chrisant996.github.io/clink/clink.html#gettingstarted_enhanceddefaults).

You can either:
1. Uninstall and reinstall but uncheck "Use enhanced defaults".
2. Or configure individual settings.  See [Clink Settings](https://chrisant996.github.io/clink/clink.html#clinksettings), and [clink.colorize_input](https://chrisant996.github.io/clink/clink.html#clink_colorize_input) or [color.input](https://chrisant996.github.io/clink/clink.html#color_input).  `clink set color.input clear`

**Comment by obumnwabude** [comment]
Thank you

Will uninstalling and re-installing persist command history ? Wouldn't want to lose them.

Running `clink set color.input clear` didn't change it.

Just noticed that some colors had bold as default and then on setting color.input as bold too, the color reset, finally

But what if there is some other switch to fully turn off colors whether enhanced defaults was set or not?

**Comment by chrisant996** [comment]
There isn't a way to tell Clink "ignore all color configurations, and strip all colors from everything, including custom prompt text".

If you install with "use enhanced defaults", you can use `clink set` to override back to no colors.  For the input line coloring, I thought it was only two settings to change to turn off all coloring off input, i.e. the ones listed in the documentation links I shared.

Or you can uninstall and reinstall without "use enhanced defaults".  That's the real issue here.

When uninstalling, the installer by default preserves profile information such as command history.  You can run the uninstaller and review the on-screen options for more info.

**Comment by chrisant996** [comment]
> Uninstalling and Re-installing without "use enhanced defaults" didn't solve the problem.

Do you mean the input text is still yellow?

Did you manually set color.input to yellow at some point?
If so, then you'd need to run `clink set color.input clear` to reset it back to the default (that can be done before or after uninstall/reinstall).

If that wasn't what happened, then can you please share these so that I can help troubleshoot what's happening?
 
- A list of the files in the directory where you installed Clink.
- The output from `clink set`.
- The output from `clink info`.
- The "clink_settings" file from your profile directory (the file location is listed in the output from `clink info`).

**Comment by obumnwabude** [comment]
Just running `clink set color.input clear` now cleared it and stuff is back to normal. Thank you.

> Did you manually set color.input to yellow at some point?
It is possible, I don't remember. I know I tried a lot of stuff 😂

**Comment by obumnwabude** [comment]
Just running `clink set color.input clear` now cleared it and stuff is back to normal. Thank you.



As for 
> Did you manually set color.input to yellow at some point?

It is possible, I don't remember. I know I tried a lot of stuff 😂
