### ISSUE TITLE
Change color for cmd command?

### ISSUE THREAD

**Issue by vict0rfr** [chrisant996/clink#613]
When I run the cmd /C "commands here" command, the text in the quotes is red, which is very misleading because it is not an error, how can I change the color for whatever is in the quotes?

**Comment by vict0rfr** [comment]
"c:\Users\victo\.vscode\extensions\ms-vscode.cpptools-1.20.5-win32-x64\debugAdapters\bin\WindowsDebugLauncher.exe --stdin=Microsoft-MIEngine-In-cjnjhnqy.ovv --stdout=Microsoft-MIEngine-Out-mxax5mwy.zip --stderr=Microsoft-MIEngine-Error-ka2yim3k.5no --pid=Microsoft-MIEngine-Pid-jfms5ffr.104 --dbgExe=C:\msys64\ucrt64\bin\gdb.exe --interpreter=mi" This. When I run c++ files.

**Comment by chrisant996** [comment]
Ah ok, thanks.

The issue here isn't the color, it's the parser that's running on the text after `cmd /c`.

(Interestingly, in the cited example, the quotes aren't needed.  But the parser needs to better handle when quotes are present.)

The problem in the parser is that CMD can end up treating `cmd /c "..."` two different ways depending on what specific `...` text is inside the quotes.  It can end up getting treated as a quoted program name, or as a quoted command line.

I'll work on a fix.

You can `clink set color.unrecognized clear`, but of course that will also remove coloring from places where the input parser accurately recognized that the input isn't executable.

**Comment by vict0rfr** [comment]
Thank you for your support. `clink set color.unrecognized clear` will do for me. As I only use cmd /C in vscode.

**Comment by chrisant996** [comment]
Yes, but I wanted to warn you that it affects more than just `cmd /c`.

**Comment by chrisant996** [comment]
And here are some quirky cases:
Command Line | Behavior
-|-
`echo hello & world` | Echoes "hello" and executes "world": <br/> `hello` <br/> `'"world"' is not recognized`...
`"echo hello & world"` | Executes "echo hello & world": <br/> `'"echo hello & world"' is not recognized`...
`"echo hello" & world` | Executes "echo hello" and "world": <br/> `'"echo hello"' is not recognized`... <br/> `'"world"' is not recognized`...
`cmd /c "echo hello" & world` | Echoes "hello" and executes "`world.exe`": <br/> `hello` <br/> `'"world"' is not recognized`...
`cmd /c "echo hello & world"` | Echoes "hello" and executes "`world.exe`": <br/> `hello` <br/> `'"world"' is not recognized`...

This is because CMD has a bunch of special case rules for whether to strip a pair of quotes after `/c`, `/k`, and `/r`.  Depending on how many quotes exist and what's between the quotes, CMD may or may not strip the first and last quotes.

That makes it quite difficult to accurately parse an input line that contains `cmd` followed by /c` or `/k` or `/r` (or an alias that expands to that).  I intend to try...

**Comment by chrisant996** [comment]
It's way too convoluted to try to parse all the edge case and nested weirdnesses.

So instead, I've made it simply disable input line coloring by argmatchers for the rest of the line if the next thing after `/C` or `/K` or `/R` is a quote.

(It doesn't disable all input line coloring, it just applies the `color.input` color to the rest of the line, and prevents argmatchers from applying further colors.  But other things can still apply coloring past that point; for example history expansion will still apply coloring past that point.  This is a very nice compromise which achieves exactly what's desired the vast majority of the time.)
