### ISSUE TITLE
How to improve speed or make it faster?

### ISSUE THREAD

**Issue by Max87153** [chrisant996/clink#620]
I've noticed Clink it's quite slow if you type fast, or you move up the history fast. I'm kind of a fast typer so this is a kind of problem to me.
PS: i've tried recording a video where this happens but the video seems normal, no struggling

**Comment by chrisant996** [comment]
That's interesting!  Thanks for reporting this. 

I don't experience that, so I have some questions to help troubleshoot what's happening:

- How old is the computer, and/or what speed is the CPU?
- Does the problem go away if you run `clink set autosuggest.enable false`
- Does the problem go away if you run `clink set clink.colorize_input false`
- What is the output from `set path`
- Do you have additional Lua scripts installed?  Custom scripts or collections of scripts such as from the clink-completions or clink-gizmos repos or other script collections?
- Do you use oh-my-posh, and is the delay mainly after pressing <kbd>Space</kbd>?

**Comment by chrisant996** [comment]
For comparison:
- Your machine is an i9-13900H with 20 effective cores at 3 GHz with 32GB RAM, and yet Clink is laggy while typing.
- My machine is an i7-10870H with 16 effective cores at 2.2 GHz with 32GB RAM, and no lag.

The PATH variable has some large directories listed twice, and that could potentially slow down autosuggest (while it collects completions), but on the other hand autosuggest is designed to run mostly asynchronously and shouldn't be interfering with typing.

It's interesting that turning off colorize cleared up the lag.  That means the lag is primarily coming from running Lua scripts to parse the input line.  But it looks like you said as far as you know the only Lua script you have loaded in Clink is one for oh-my-posh.

Some more troubleshooting questions:

- Have you checked the CPU usage on the computer when the lag is happening?  If the CPUs are over saturated then yes it is normal to experience some lag.
- Also, what terminal program are you using?
- Do you have ANSICON installed?  If so, remove it.  It has a major performance problem because it splits all input in one OS call _per character_, which can degrade performance by 2+ _orders of magnitude_.  And Windows' built-in ANSI support is far more complete and functional that ANSICON's anyway (ANSICON hasn't been needed since Windows 8.1).

**Comment by chrisant996** [comment]
Here's a better question:

The system info you shared says `Shell: bash 5.2.26`.

Do you experience any lag when typing in bash?

I ask because here is what happens when I typed jumbled letters as quickly as my fingers can randomly hit them:
- Typing into Clink, I can observe a small bit of lag.  But no lag when I type at my fullest real speed (which is around 100 wpm).
- Typing into bash running in Ubuntu, I actually observe noticeably more lag than in Clink.

This is interesting, because both Clink and bash are using Readline.

Once I realized I could reproduce a small bit of lag with ultra high speed random input, then I started doing some performance profiling, and I started disabling lots of different features that the profiler showed as using time.  But no matter what I turn off, it only has an infinitesimal affect on reducing lag.  And bash itself seems to have even more lag than Clink.

So I'm curious whether you experience lag in bash.

**Comment by chrisant996** [comment]
And I experience a small lag when typing into plain CMD.exe's command prompt (without Clink).

And when I added detailed logging about delays, there is a small amount of lag even when the APIs claim to be receiving input instantly when it's available.  I can stop typing, and it takes another 100-200 ms for another 6 or so letters to show up one by one, and yet the logging says for each of the letters there isn't input available yet, and it has to wait for 15 to 20 milliseconds before the OS APIs have any input available -- even after I've completely stopped typing, the input APIs still experience waits before the input I already finished typing actually becomes available.  That particular delay is happening in something lower-level than Clink.

The lag that I'm experiencing seems to have nothing to do with Clink.  I experience it in Windows Terminal, in ConEmu, in mintty, and in the old default conhost (standalone legacy default console windows), regardless whether Clink is present or not.

I'm not sure what's going on here, but the lag I'm able to experience seems to be independent from Clink.
I don't know how to tell whether the lag I'm experiencing is the same as the lag you're experiencing.

So I'm also curious what terminal you're using.

**Comment by Amueller36** [comment]
I did not particularly experience any lag, but I just saw this issue and recently I have seen a Video that mentioned the slow windows console layer and a way on "bypassing the windows console layer", maybe this is of interest for you:

https://youtu.be/hxM8QmyZXtg?t=1155

Thanks for your great work btw, I really enjoy the clink experience! :)

**Comment by chrisant996** [comment]
That's an interesting video, thanks for sharing it.  It's about a very different issue than input lag.  I'm not seeing output lag (performance measurements confirm I'm not expecting output lag or slow output).  Instead I'm seeing a tiny amount of input lag when hammering keys at around 200 wpm.  And I think that's the same thing you're hitting.  It's not output that's slow.  The console **_input_** APIs are saying input isn't available for a few milliseconds even when multiple keys are queued already.  That's where the slowness is coming from.

Re: the video, it's worth noting there's a lot of criticism in the video, but also a lot of "I don't know what it's doing and why it's slow" combined with "my code handles everything ... except for the following things which are really the hard parts".  Which feels odd, because yeah if one removes all the code that handles all the hard stuff, then it's going to be faster.  He's got some interesting points.  But he claims it's an apples to apples comparison, and that doesn't seem accurate. 

And the super fast mode seems to disable ANSI escape code handling and colors and all that kind of stuff.  I wonder whether the author hasn't gotten to thinking through all the things that the "terrible and slow" code is actually taking care of.

Anyway, (1) Clink can't make use of that and (2) that stuff doesn't seem to be related to the issue here.

**Comment by chrisant996** [comment]
@Max87153 can you share more information?

> it's quite slow if ... you move up the history fast

Do you mean if you press the <kbd>Up</kbd> arrow repeatedly very quickly at an empty prompt?
I experience no lag at all for that.

If you can narrow it down to some specific history commands that show up slowly, then I could investigate further.  If you can share your `clink_history` file, that might help find what's being slow.

- Do you have any completion scripts from anywhere other that the clink-completions repo?  If so, can you share them?  Completion scripts can potentially affect the speed of showing
- Do you have any keyboard utilities installed?  If so, what are they?  Can you try disabling them to see if the lag you're experiencing goes away?
- Have you checked the CPU usage on the computer when the lag is happening? If the CPUs are over saturated then yes it is normal to experience some lag.
- What terminal program are you using?
- Have you checked if there are display driver updates available?
- **Do you have ANSICON installed? If so, remove it.** It has an implementation problem that degrades performance greatly (by easily around 10x to 100x). And Windows' built-in ANSI support is far more complete and functional than ANSICON's anyway (ANSICON hasn't been needed since Windows 8.1).

**Comment by chrisant996** [comment]
@Max87153 I would like to help troubleshoot what's going on, but I need more information (see questions in previous replies).

In the meantime, I'll close this issue since it has gone stale.
