### ISSUE TITLE
Problem: Copy and paste the command line

### ISSUE THREAD

**Issue by zhefox** [chrisant996/clink#639]
When copying and pasting multiple command lines, line breaks cannot be automatically removed, resulting in only line by line when copying and pasting command lines in the terminal

**Comment by chrisant996** [comment]
I don't understand the description. 

Can you share more information, and a specific example?

**Comment by zhefox** [comment]
okay,here are more information for this question,

such as 
![QQ_1722321135363](https://github.com/user-attachments/assets/17d8fa31-37ef-4ee0-9ec2-59233314aca6)

if i copy  "gflags.exe /p /enable "C:\Users\ben\Desktop\olds\scard.exe" /full" , It wraps because of the window width limit
but if i copy in cmd with clink,  It will be copied as a string with carriage return, as shown below
gflags.exe /p /enable "C:\Users\ben\Desk
top\olds\scard.exe" /full

And it turned out to be a whole line, and it was executed

**Comment by zhefox** [comment]
Itself if you copy-paste in the original cmd then it would be normal, so I think it's a problem with clink

**Comment by chrisant996** [comment]
You're using Windows Terminal, so unless you've deleted its CTRL-V binding, then Windows Terminal is handling the paste, not Clink.

Or have you deleted the default Windows Terminal key binding for CTRL-V to give Clink a chance to paste?  If so, then what is [clink.paste_crlf](https://chrisant996.github.io/clink/clink.html#clink_paste_crlf) set to?  Maybe you want `ampersand`?

I'm still not sure what's being described, though.

What are the specific steps for copying, and what are the specific steps for pasting?  There are several different ways to do each, and the specific ways being used are important in order to be able to troubleshoot.

Is it an issue with how Copy is working?  Exactly how are you copying the text?  There are many different ways to copy text, and in order to troubleshoot, it's important to know exactly which way of copying is used. 

Is it an issue with how Paste is working?  Does pasting into Notepad work how you want?  There are several ways to paste -- Windows Terminal, or conhost, or Clink could be doing the paste.  It depends on specifically how you've configured the terminal and Clink.  But by default, Paste is done by Windows Terminal, not by Clink.

**Comment by zhefox** [comment]
I've removed the ctrl+v of the terminal binding, but it still doesn't seem quite right

![QQ_1722323277193](https://github.com/user-attachments/assets/0946f731-934e-41b7-ad43-75d74054f1b8)
If I just use ctrl+c to copy the command line of the history that was successfully executed above and paste it, you can see that it wraps
![QQ_1722323307090](https://github.com/user-attachments/assets/ff888d62-a17f-4459-9dc9-b26419313e56)
![QQ_1722323554277](https://github.com/user-attachments/assets/a0e0dad3-4bab-4f28-9ad9-6eab2ada8d2b)
![QQ_1722323569628](https://github.com/user-attachments/assets/2c51fece-cd84-4337-84c3-62fc1c4c0262)
![QQ_1722323654623](https://github.com/user-attachments/assets/2fa39e18-6282-4758-ae85-89970fd77051)

**Comment by zhefox** [comment]
I think I seem to have found a solution

**Comment by zhefox** [comment]
You're right, you need to unbind the ctrl-v binding that comes with the terminal, and then turn off some settings
![QQ_1722324034424](https://github.com/user-attachments/assets/5428722c-12c0-46d2-9d61-acc9c7d88cbf)

**Comment by zhefox** [comment]
Oh no, it seems like you just need to turn off the function of the rectangle selected above in the terminal settings, the others are not needed, it doesn't seem to be a problem with clink, I'm sorry

**Comment by zhefox** [comment]
There still seems to be some issues, if I use it on win10's cmd and don't have this option, he still seems to have this
This doesn't seem to be a paste-in-question issue, it's the time ctrl+c is copied to the clipboard, and the line break is already there

**Comment by chrisant996** [comment]
> ![QQ_1722323654623](https://github.com/user-attachments/assets/2fa39e18-6282-4758-ae85-89970fd77051)

Clink settings are set with `clink set`, not with `set`.

**Comment by zhefox** [comment]
![QQ_1722324681071](https://github.com/user-attachments/assets/6d1a972d-833a-49d5-a3e5-0bea372ad8b9)
i exec clink set clink.paste_crlf ampersand

I've now gone to set clink correctly and observed that it seems to wrap the line by adding a &

**Comment by zhefox** [comment]
Ah, it's okay, it's still a problem with the terminal itself

**Comment by chrisant996** [comment]
Right -- the difference was not Clink, the difference was Windows Terminal versus the legacy conhost terminal.
