### ISSUE TITLE
How to move through history?

### ISSUE THREAD

**Issue by Mitezuss** [chrisant996/clink#641]
while write, i get some suggestion, but wanna another (from the history): how? (any key o what ?)

regards

**Comment by chrisant996** [comment]
Are you looking for the info in the "Persistent History" box at [Feature Highlights](https://chrisant996.github.io/clink/clink.html#features) in the documentation?

**Comment by chrisant996** [comment]
Yes, the only reasons I haven't changed the default bindings for <kbd>Up</kbd>, <kbd>Down</kbd>, and <kbd>PgUp</kbd> are these:
1. Many Clink users want bash key bindings and may be annoyed if those behave differently.
2. In both bash and CMD, the default behavior of <kbd>Up</kbd>/<kbd>Down</kbd> is to move through the history without regard for what's been typed so far.  Changing that can be unexpected to and annoying to some users.
3. I could change them when [clink.default_bindings](https://chrisant996.github.io/clink/clink.html#default_bindings) is `windows`, but those are such core to the shell experience that I'm worried about creating confusion if <kbd>Up</kbd>/<kbd>Down</kbd> "mysteriously" behave differently for different users, making it difficult to share steps or communicate about steps for various things.
4. Imposing changed key bindings one everyone ruins muscle memory, and is usually a bad idea.

I have strong personal preferences about how keyboard bindings "Should" work, but I try not to impose my preferences on others if bash/CMD already have strong precedent for something.

Which is why I shared a stripped-down version of my own key bindings (which I've gotten a lot of positive feedback about).

**Comment by chrisant996** [comment]
I've updated the [Saved Command History](https://chrisant996.github.io/clink/clink.html#saved-command-history) documentation to clarify some things and include a table of key bindings for navigating the history.
