### ISSUE TITLE
CTRL-C does not copy text selected using conhost mouse selection

### ISSUE THREAD

**Issue by andry81** [chrisant996/clink#647]
If start selection with the mouse: SHIFT+mouse

and then press CTRL-C, then nothing copied.

In the same time the right mouse button click copies the text as expected.

OS: `Windows 8.1`

> clink info
```
version          : 1.6.18.80e2a3
injected         : clink_dll_x64.dll
system           : 6.3.09600.20778
codepage         : 1251
keyboard langid  : 1033
keyboard layout  : 00000409
```

**Comment by chrisant996** [comment]
Some important questions:

1. What terminal are you using?  The default legacy conhost?  Or Windows Terminal?  Or a different terminal program?
2. What text is being selected?  Text inside the input line, or text outside the input line?
3. Is Clink handling the mouse, or is the terminal handling it?  Have you specially configured Clink to be able to handle the mouse in the input line?
4. Is Clink handling the Ctrl-C, or is the terminal handling it?  What happens if you run `clink echo` and then press Ctrl-C?

Unless both the mouse+selecting and the Ctrl-C are handled by the same thing (both by Clink, or both by the terminal), they won't be able to cooperate.  For them to cooperate, both have to be handled by the same thing.

It sounds like the terminal is handling the mouse and selection, not Clink.  In that case, text anywhere in the screen can be selected, and right click would be interpreted as "Copy".

**Comment by andry81** [comment]
>     1. What terminal are you using?  The default legacy conhost?  Or Windows Terminal?  Or a different terminal program?

conhost

>     2. What text is being selected?  Text inside the input line, or text outside the input line?

both, but the former sometimes works

>     3. Is Clink handling the mouse, or is the terminal handling it?  Have you specially configured Clink to be able to handle the mouse in the input line?

didn't change anything, all by default

>     4. Is Clink handling the Ctrl-C, or is the terminal handling it?  What happens if you run `clink echo` and then press Ctrl-C?

"\C-C"

**Comment by chrisant996** [comment]
You can't mix terminal mouse selection and Clink commands.  They're completely independent.

**Comment by chrisant996** [comment]
Wait a minute.  While in the conhost mouse selection mode, Clink is not active and doesn't even receive any of the input.

I confirmed that with a quick test just now.

Oh, I see what's going on.

Windows 8.1 has some kind of quirk in how it's dealing with console mode changes.

Run `clink set terminal.mouse_input off` to make all mouse input go directly to conhost, and never get intercepted by Clink.

**Comment by chrisant996** [comment]
@andry81 I've been troubleshooting this a bit more on both Win8.1 and Win11.

- Do you have "Quick Edit" mode turned off?
- What does `clink set terminal.mouse*` print?

I'm working on tracking down how the issue correlates with OS version, Quick Edit mode on/off, and the `terminal.mouse*` settings.  If there's a Clink bug, hopefully I'll be able to make a fix.  Or if there's an OS issue, hopefully I'll be able to find a workaround.

**Comment by chrisant996** [comment]
@andry81 This seems to have nothing to do with Clink:

I use Windows 8.1 and run cmd.exe _without Clink_ in a conhost window.

Regardless whether Quick Edit mode is enabled or disabled, pressing <kbd>Ctrl</kbd>-<kbd>C</kbd> after using the mouse to select text, the selection disappears but the text is not copied into the clipboard (it doesn't matter if I click+drag, or right-click and choose Mark and then either click+drag or use <kbd>Arrow</kbd> and <kbd>Shift</kbd>-<kbd>Arrow</kbd> keys).

Pressing <kbd>Enter</kbd> is what copies the selected text into the clipboard.

It's just how conhost works.  Clink isn't involved at all.

Are you saying that without Clink you're somehow able to use <kbd>Ctrl</kbd>-<kbd>C</kbd> instead of <kbd>Enter</kbd> to finish the selection and copy it to the clipboard?  If so, that's surprising, and I don't know how that would be possible.

**Comment by andry81** [comment]
> When I press Ctrl-C, the selection disappears but the text is not copied into the clipboard.

That's right, it has never been working. Not in Win8, nor Win7.

**Comment by chrisant996** [comment]
> > When I press Ctrl-C, the selection disappears but the text is not copied into the clipboard.
> 
> That's right, it has never been working. Not in Win8, nor Win7.

Yes.  This isn't related to Clink.  The same thing happens without Clink.  The feature that you want has to come from Windows, but 7 and 8 don't have that feature.

**Comment by andry81** [comment]
> Yes. This isn't related to Clink. The same thing happens without Clink. The feature that you want has to come from Windows, but 7 and 8 don't have that feature.

Yes, I thought clink has added the feature, because of SHIFT-arrows works.
