### ISSUE TITLE
Replace unix path separator on complete

### ISSUE THREAD

**Issue by zdm** [chrisant996/clink#651]
Hi.

Previously, when I type, for example, "./2" and press "TAB" to complete file name - clink replace "./2" with ".\2" and complete filename with the file started with "2" from the current directory.

But after some clink update (I don't remebmer which version exactly) it require me to use windown path separator "\\" only.

This is not very suitable.

Could you please tell me, what option in config I should set to restore old behaviour. I belive, that you move it to option )).

Thank you!

**Comment by chrisant996** [comment]
All changes are listed at [Changes](https://chrisant996.github.io/clink/clink.html#changes) in the documentation.

You're looking for this one:

- Added an `auto` mode for the `match.translate_slashes` setting. This mode makes completion translate all slashes in the completed word to match whichever kind occurs first in the word, or to the system path separator if there are no slashes yet (e.g. when completing a directory name).

Run `clink set match.translate_slashes` to see more about the setting.

Run `clink set match.translate_slashes system` to select the previous behavior of converting forward slashes to backslashes.

**Comment by zdm** [comment]
Thank you  for answer.

I tried auto, system, backslash.

Nothing works. When I am typing "./1" and press TAB - completion just not performed. Slash not changed.

With "backslash" option - when I am typing ".\1" - it works ( change path to "./1" and make completion), bun this is no what I meed.

**Comment by chrisant996** [comment]
Oh, I understand now.  The original description did not mention that completion is not performed, and I thought you were reporting that completion worked but kept the forward slash.

### What changed and why

The command line parser was changed to respect how CMD syntax works.

- If you run `./something` then CMD interprets that as trying to launch a program `.` and pass it `/something` as an argument.
- If you have a subdirectory `foo` and a script `bar.cmd` (so there's a file `foo\bar.cmd`) and you run `foo/bar.cmd` then CMD interprets that as trying to launch a program `foo` and pass it `/bar.cmd` as an argument.

Parsing the command line in Clink now respects that, so that input line coloring can be accurate and so for example you can type `dir/`<kbd>Tab</kbd> and get completions for `/` flags to `dir`.

### What you want

I understand what you want, and why.

I'll have to think about how that can be accommodated.

**Comment by zdm** [comment]
Ok, thank you very much.
I am wondering, that it worked some time ago.

**Comment by chrisant996** [comment]
@zdm When completing the first word in a command line:
1. Do you only need completing `./` to convert the slash?
2. Or do you also need `somedir/` to convert the slash?

# 1 is easy to allow an exception for.
# 2 is much more problematic to accommodate, so I'd rather not introduce complexity and inconsistencies for that case.

**Comment by zdm** [comment]
I am personally use "./xxx" only. It it fast and easy to type when I need to complete filename from the current directory.
