### ISSUE TITLE
broot integration

### ISSUE THREAD

**Issue by wincmd64** [chrisant996/clink#673]
https://dystroy.org/broot/install-br/

I tried to install **broot --install**
with powershell br alias work OK, but with clink - `br` does not work

**Comment by chrisant996** [comment]
This is a limitation of broot, and it's documented in the link you shared.
It has nothing to do with Clink.

Quoting from https://dystroy.org/broot/install-br/:

"Supported shells today are bash, zsh, fish, nushell, and powershell."

Cmd is not any of those shells.
Broot doesn't support cmd.

**Comment by wincmd64** [comment]
In launcher folder there is a script. Maybe it can be adapted to clink ?

```
function br {
    local cmd cmd_file code
    cmd_file=$(mktemp)
    if broot --outcmd "$cmd_file" "$@"; then
        cmd=$(<"$cmd_file")
        command rm -f "$cmd_file"
        eval "$cmd"
    else
        code=$?
        command rm -f "$cmd_file"
        return "$code"
    fi
}
```

**Comment by chrisant996** [comment]
This is not related to Clink in any way.  Can you please discuss CMD support for broot in the broot forum, instead of in the Clink forum?

**Comment by chrisant996** [comment]
Are you asking me to help?
Or someone from broot to help?
Or someone else to help?

This has nothing at all to do with Clink.

Broot needs CMD support, not Clink support. 
You don't need or want a Lua script, you need a .cmd script or something.

**Comment by chrisant996** [comment]
Once I looked into broot, it does seem like a nifty program.  I probably won't use it myself, as its interface takes a lot of keypresses for the most things like changing to a directory.  In contrast, for things like that the fzf integration in [clink-fzf](https://github.com/chrisant996/clink-fzf) is more lightweight and has much of what broot provides, in a more integrated manner with the shell.  E.g. <kbd>Alt-C</kbd> instead of `br`<kbd>Enter</kbd>, and fuzzy filtering in completions in general, etc.
