### ISSUE TITLE
Readline setting match-hidden-files off never shows completions for hidden

### ISSUE THREAD

**Issue by scrhartley** [chrisant996/clink#680]
### Original problem
I would type the letter `I` and press tab and the completion would be the hidden folder `.IdeaIC14`, while I want the non-hidden folder `IdeaProjects\`

### Attempted solution
I created the file `C:\Users\MyUser\AppData\Local\clink\_inputrc` and put:
```
set match-hidden-files off
```
Now when I complete, I get the non-hidden folder, but if I type `.I` and press tab, it refuses to give a completion suggestion, despite the docs saying:
> If set to "off", the leading . must be supplied by the user in the filename to be completed.

_Note: I tried to find a way to disable Directory Shortcuts in case that was interfering, but that doesn't seem to be possible._

**Comment by chrisant996** [comment]
Yes.  The documentation text is from the Readline library.  But Clink has ever actually behaved that way, because Clink doesn't use Readline's default file globbing code.

I'll implement this detail.

**Comment by chrisant996** [comment]
And the bug is broader:

When a path is included, Clink checks for `.` at the beginning of the path, instead of at the beginning of the filename part.

In other words, when `match-hidden-files` is off then this does not match ".git":
```cmd
c:\somerepo> echo .g
```
And that's correct behavior. ✅

But when `match-hidden-files` is off then this DOES match ".git":
```cmd
c:\foo> echo \somerepo\.g
.git\  .gitignore
```
And that's not right. ❌

And when `match-hidden-files` is off then this DOESN'T match anything:
```cmd
c:\somerepo> echo .git\
```
And that's not right. ❌
