### ISSUE TITLE
Question: Tilde expansion in Cmder

### ISSUE THREAD

**Issue by DRSDavidSoft** [chrisant996/clink#689]
Hi there @chrisant996,

I am doing some cleaning up in the Cmder repo, and noticed an issue which has some user contributed lua scripts for the tilde expansion feature on auto complete (i.e. pressing <kbd>tab</kbd>).

Now doing a quick search for the word ["tilde" on the releases page](https://github.com/chrisant996/clink/releases?q=tilde&expanded=true) I wasn't able to pinpoint the exact release of clink that added support for this to read the docs.

This is the script in question. I just wanted to make sure if I can mark this as "deprecated" so long as clink is supporting this natively.  I might be mistaken, in which case I would appreciate it if you could help me clear the confusion.

https://github.com/cmderdev/cmder/issues/1051#issuecomment-421640011

If this is the case, may I please ask for the equivalent code in clink, just to make a quick comparison?

Thank you!

**Comment by chrisant996** [comment]
v1.1.8 is when tilde expansion was added:

Commit [c42b](https://github.com/chrisant996/clink/commit/c42bf2c74d22e7ad8e798d29d5b085d77b10218d#diff-76cb37375b87907c2f182437af232d23326baa37a91bdb85bebeb5d9e281540eR608), line 608.

It was part of changes for compatibility for scripts from v0.4.9.  Since I had started adding tilde expansion in v1.1.6 (which you pinpointed), the tilde expansion was an implicit part of the new code.  So it didn't manage to make it into the release notes as a description of a specific change.

Also, this question made me discover a typo in the docs for [clink.filematches()](https://chrisant996.github.io/clink/clink.html#clink.filematches) and [clink.dirmatches()](https://chrisant996.github.io/clink/clink.html#clink.dirmatches) -- they were both added in v1.1.8, _not_ in v1.1.<mark>1</unmark>8.  I've updated the docs, and the update will go live with the next Clink update (probably in a couple of weeks).

**Comment by chrisant996** [comment]
Re: "equivalent code in Clink", I cited commit [c42b](https://github.com/chrisant996/clink/commit/c42bf2c74d22e7ad8e798d29d5b085d77b10218d#diff-76cb37375b87907c2f182437af232d23326baa37a91bdb85bebeb5d9e281540eR608) line 608, but in reality it's a little more complicated than just that.  Because there are multiple different spots where tilde expansion can happen, depending on context and how completions are invoke, and depending on certain settings, and it's grown more sophisticated over time.  And IIRC, I think Martin built it into a couple of other spots sometime between v0.4.9 and v1.0.0, but in C++ code, and in a way that wasn't guaranteed to always be invoked.  I believe v1.1.8 is when it was first hooked up in a consistent and mainstream way.

But either way, it's been around for almost 4 years, even if the precise date is a little fuzzy to track down.  😁

**Comment by DRSDavidSoft** [comment]
Thank you for the through investigation and the excellent information which were exactly what I was looking for, Chris! 👍🏻 

I'm going to put a small notice in Cmder that using such scripts is no longer necessary if clink >= 1.1.8 is installed.

As always, thanks for the amazing clink! 😄 ❤️
