### ISSUE TITLE
in cmder, ctrl+c not work

### ISSUE THREAD

**Issue by bigfoxtail** [chrisant996/clink#70]
in cmder, ctrl+c not work
1.1.24 works fine, later versions do not work

**Comment by chrisant996** [comment]
@bigfoxtail thanks for reporting this. Can you please explain further?

When are you pressing Ctrl+C?
What happens when you press Ctrl+C?
What was expected to happen?
Does the problem always happen, or is it intermittent?
Are there steps needed to make the problems start happening, or does it immediately start happening after opening a new tab in Cmder?

I don't seem to see any difference in Ctrl+C at the prompt, when I try pressing Ctrl+C while editing the input line.  Any clarifications would be appreciated.

Thanks!

**Comment by chrisant996** [comment]
Never mind -- I was trying Clink by itself. Inside cmder I'm seeing Ctrl+C not work anymore. Investigating...

**Comment by bigfoxtail** [comment]
Sorry, I meant that when I press ctrl+c, the cursor starts on a new line, but this feature is missing in the new version.
I have cmder version, 1.3.17.
clink 1.1.24 works fine, later versions don't work

**Comment by bigfoxtail** [comment]
thank you

**Comment by chrisant996** [comment]
Cmder is not giving the Ctrl+C input to Clink. It looks like a Cmder bug.

**Comment by bigfoxtail** [comment]
thank you

**Comment by chrisant996** [comment]
Nope, it's a Clink bug.

After building ConEmu and debugging through ConEmu64.exe and ConEmuC64.exe and following the input through multiple processes, layers of code, translations between different data structures, I eventually reached the point in ConEmu where it decides whether the process the Ctrl+C or pass it along to the console process app:

**src/ConEmuCD/Queue.cpp**, in **ProcessInputMessage**:
```
			LogString(L"  ---  CtrlC/CtrlBreak recieved");
			DWORD dwMode = 0;
			GetConsoleMode(GetStdHandle(STD_INPUT_HANDLE), &dwMode);

			// CTRL+C (and Ctrl+Break?) is processed by the system and is not placed in the input buffer
			if ((dwMode & ENABLE_PROCESSED_INPUT) == ENABLE_PROCESSED_INPUT)
				lbIngoreKey = lbProcessEvent = true;
			else
				lbProcessEvent = false;
```

And the `dwMode` has the `ENABLE_PROCESSED_INPUT` bit set!  The whole point of the change in Clink 1.1.25 was to clear that bit.

Also, I'm able to reproduce the problem in Clink without ConEmu/Cmder involved, but only under certain circumstances.

I'll post a writeup of the root cause in Clink soon.

**Comment by chrisant996** [comment]
The problem only occurs when there is a prompt filter registered AND the prompt filter spawns other processes (e.g. spawning `git` or other programs).

Prior to 1.1.25, Clink had been setting the console input mode at the last possible moment before getting input.  That's far too late and causes misinterpreted input.

In 1.1.25, Clink started setting the console input mode at the earlier possible moment before getting input.  That fixed the misinterpreted input.

However, in between those two points in time, Clink gives Lua scripts a chance to run and filter the prompt.  If they spawn other programs, then the console input mode gets reset as a side effect.

So, Clink must also always set the console input mode after giving any Lua scripts a chance to run (for prompt filtering, key bindings, match completion -- any time a Lua script runs).

1.1.28 will include a fix.

Thanks for reporting this!  This was a weird one.  😄
