### ISSUE TITLE
Correct key bindings in ssh session ?

### ISSUE THREAD

**Issue by neradp** [chrisant996/clink#706]
Hi,when im using cmd session with clink injected in ssh, i cannot type characters like |@... When i unload clink, everything is ok.
What i need to setup to get clink working in ssh session ? Im using Putty as ssh client. 

I can get correct key sequence string with the help of: 
`clink echo --debug`
i need setup  environment variable in Putty eg: 
`TERM=Putty`

Then in .inputrc  adding lines eg for "|" can solve my problem.
```
#Putty keybindings
$if term=putty
"\e\C-W": "|"
$endif
```
Is there some easier way to do it ? Or i need to remap all not working keys in this way ?

**Comment by chrisant996** [comment]
I think you're saying you're using Putty/ssh to access a CMD session that has Clink injected. 

In that case, Putty owns all input, and Putty is passing synthesized input to Clink, instead of Clink receiving native input from the OS.

That will fundamentally change both how input shows up to Clink, and also what key combinations Clink is even able to receive at all. 

The inputrc solution you're using is the best way that I know of, for how to help make up for Putty translating input differently than the Windows OS normally does.
