### ISSUE TITLE
Tabby is missing ARM builds of Clink

### ISSUE THREAD

**Issue by h1v9** [chrisant996/clink#711]
Windows on Arm is becoming bigger as Snapdragon X Elite/Plus have come on the market.
As a user I felt the lack of an ARM Build (Tabby terminal was failing to launch clink as no arm build is in the package), however I managed to build it on my own using the instructions on the readme.

It seems to be functional, would it be possible to include an arm build on the next release?

**Comment by chrisant996** [comment]
Clink has included ARM64 for 2 years.
- Introduced by commit 87a4440ebc718963890e369ded450907ea2ecb85 on Dec 27, 2022.
- Release [v1.4.7](https://github.com/chrisant996/clink/releases/tag/v1.4.7) and onward all include ARM64.

You can see [here in the Tabby repo](https://github.com/Eugeny/tabby/tree/master/extras/clink) that Tabby hasn't updated its copy of Clink in over 2 years (since v1.4.3) and lacks ARM64 files (and missed updating the CHANGES file, which is still from v1.2.9).

You need to report the issue in the Tabby repo, not in the Clink repo.

But also, do you have Clink updates turned off?  If you let Clink update itself, then I would expect it would automatically install the missing ARM64 files.

**Comment by h1v9** [comment]
My bad, thought they were missing from here.
I'll report it back to tabby.

I didn't turn off updates, tabby just kept trying (failing) to start the arm64 version of clink

**Comment by chrisant996** [comment]
> My bad, thought they were missing from here.
> I'll report it back to tabby.
> 
> I didn't turn off updates, tabby just kept trying (failing) to start the arm64 version of clink

Run `clink_x64.exe update`.

(If Tabby doesn't put the Clink directory in the system PATH then you'll need to specify the path to the clink_x64.exe file.)

Or maybe even `clink update` will work -- I don't know and can't test that because I don't have an ARM computer or VM.

**Comment by MagicAndre1981** [comment]
One question, in the [winget manifest](https://github.com/microsoft/winget-pkgs/pull/233597/files) the arm64 entry is mising (only x86 and x64). What will happen if you try to install it on Windows on ARM devices?

**Comment by chrisant996** [comment]
Hm, I don't know.  I will have to look into that.

Maybe it's just an oversight, e.g. maybe ARM64 support was added after the winget manifest was created.  And since the winget manifest is not part of the Clink repo, it's not something I would have noticed needed to be updated.

**Comment by chrisant996** [comment]
The installer is an x86 executable.

The installer can be run on x86, x64, and arm64.

The installer installs the appropriate files for the computer.  If the computer is natively arm64, then the installer will install the arm64 files in addition to the x86 and x64 files.

Winget has to be able to install x86 software on arm64 devices, since arm64 can emulate x86.  So, the manifest should be fine.

I assume you were asking a theoretical question out of curiosity.  If you instead have observed some problem, then please share additional details.

**Comment by MagicAndre1981** [comment]
> I assume you were asking a theoretical question out of curiosity. If you instead have observed some problem, then please share additional details.

yes, github startpage now shows activity of people I follow and I saw your PR and found that it missed arm64 entries. I don't own a Snapdragon X device.
