### ISSUE TITLE
`exec.space_prefix` setting doesn't take effect until second input line

### ISSUE THREAD

**Issue by Roze061** [chrisant996/clink#73]
but it seems to be just auto complete for commands that do not work.
I added spaces to ignore history   

clink: 1.1.29

**Comment by chrisant996** [comment]
Can you please give some examples?

**Comment by Roze061** [comment]
Thanks @chrisant996 now I can use Tab completion first word with space prefix after set `exec.space_prefix` to `False`
sorry i didn't figure out `exec.space_prefix` before making it an issue

but when I do this
`run cmd` > `cd "New Folder"` > `clink inject` > `input "   his" or "    cm"` > `press Tab`
Tab completion not suggesting

but when I do this
`run cmd` > `cd "New Folder"` > `clink inject` > `input & enter "   -anything"` > `input "   his" or "    cm"` > `press Tab`
Tab completion work

and when I run `"      history"` after `clink inject`, `'history' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by chrisant996** [comment]
> but when I do this
> `run cmd` > `cd "New Folder"` > `clink inject` > `input " his" or " cm"` > `press Tab`
> Tab completion not suggesting
> 
> but when I do this
> `run cmd` > `cd "New Folder"` > `clink inject` > `input & enter " -anything"` > `input " his" or " cm"` > `press Tab`
> Tab completion work

Oh, the issue is the space in "New Folder".
Thanks, I'll look into it!


> and when I run `" history"` after `clink inject`, `'history' is not recognized as an internal or external command, operable program or batch file.`
> `" exit"` command work

This is expected behavior.  `history` is a doskey alias.  Inserting leading spaces turns off doskey expansion in Clink, just like it turns off doskey expansion in CMD.  If you want to be able to type spaces before `history` and still have it work, then you could make a `history.cmd` batch file that calls `clink history` and passes along the rest of the command line arguments.

**Comment by Roze061** [comment]
> Oh, the issue is the space in "New Folder".
"New Folder" for example where current working directory

**Comment by Roze061** [comment]
> You mean follow the steps after running clink set exec.space_prefix false as a first step, right?

Yes and exit

> What does input & enter " -anything" mean?

type some word and enter

> If you mean simply type Space c m Tab then that seems to be working for me (with exec.space_prefix set to False), so I think maybe I'm not understanding the steps, or there is some configuration or repro step(s) that haven't been captured yet.

You are right simply type

**Comment by chrisant996** [comment]
In the gif I see attempts to complete prefixes of `clink` and `history`.

It's **correct** for those to **not** complete:
- Clink automatically defines `clink` and `history` as doskey aliases.
- Doskey aliases are only expanded at the beginning of a line; leading spaces in both CMD and Clink turn off doskey alias expansion.
- Since doskey aliases won't work when preceded by spaces, they also won't complete when preceded by spaces.

The reason `clink` works anyway when executed is because `clink.cmd` is in the %PATH%, and _that's_ what ends up getting invoked.

Everything appears to be working correctly in the gif.
If it seems like I'm misunderstanding something that's being reported, please do clarify and help me to understand.

Thank you very much for taking the time and effort to report the scenario and make a gif movie of it to help me see what was happening!

**Comment by Roze061** [comment]
in gif after `clink inject` in first line I trying to Tab completion but not work
if `history` prefix with space still completing

**Comment by chrisant996** [comment]
Oh, I see now:

Yes, I'm able to get it to sometimes complete things prefixed with spaces even when it shouldn't.

That's what you're pointing out, right?

Thank you for persisting until I was able to reproduce what you're reporting.  🙃

**Comment by chrisant996** [comment]
> at least I have to manually write the executable name after "clink inject" and the parameters can be auto-completed. but after the first run something will work as usual
> 
> maybe I'm the only one who has this problem

I got it to happen a couple times, but it's intermittent and hard for me to get it to start happening.  Although we are experiencing opposite symptoms, I think the cause is very likely the same for both.  The symptoms are consistent with an uninitialized variable somewhere, or missing a spot where some variable needs to get reset.

I'll work on tracking it down.

**Comment by chrisant996** [comment]
It turned out be a problem in loading settings that are defined in Lua scripts (the exec matching is defined in some built-in Lua scripts).
