### ISSUE TITLE
Cursor shape gets reverted to legacy

### ISSUE THREAD

**Issue by aavramch** [chrisant996/clink#88]
It's a known console API [bug](https://github.com/microsoft/terminal/issues/4124) that resets user cursor shape preference. It has already been fix in the new Windows Terminal, but not the default shell. I'm not smart enough to figure it out, but could you perhaps fix it using this [advise](https://github.com/microsoft/terminal/pull/5251#issuecomment-610075287)?

Thank you!

**Comment by chrisant996** [comment]
There's no description here, so I have to deduce what is being experienced, and what is being requested.

The cited links are not for workarounds in app code. They are source code changes in the implementation of the Windows operating system's console APIs. I can't find anything actionable here for me to do.

Did I miss something?

**Comment by aavramch** [comment]
My bad, Chris. Here's a better description and a cool animation made by another user:
![image](https://user-images.githubusercontent.com/127450/71843286-5e07ce00-3078-11ea-8949-bf8df0c03528.gif)

Essentially, if you open Clink and change the console cursor shape or size, the cursor will change to the desired shape right away, but the moment you start typing, it reverts back to Legacy Small
![image](https://user-images.githubusercontent.com/30131196/111407451-0d82fc00-8691-11eb-924d-a82607a78226.png)

Not a big deal really, just something I noticed.

**Comment by chrisant996** [comment]
I see.  There are four things happening:

1. Clink changes the visibility of the cursor in order to reduce flicker, and to reset the blink timer while typing (otherwise the cursor is intermittently invisible while typing, which tends to be disorienting).
2. Clink changes the shape of the cursor for three reasons:
    - To indicate whether Insert Mode is active.
    - To produce Readline's "visible bell" effect (temporarily flash a different-sized cursor).
    - To support the ANSI escape codes for changing the cursor size. 
3. The OS API has a bug that reverts the cursor shape when changing the visibility of the cursor.
4. The OS API has no way to get/set the five new cursor shapes, so Clink can only use the legacy shapes (small, medium, large).

I can add a setting to prevent Clink from changing the shape, but that breaks points 1 and 2 above.  So it trades one limitation (can't use the new cursor shapes) for **five** other limitations (cursor flicker, disorienting cursor invisibility while typing, can't show Insert Mode, can't produce "visible bell" effect, can't support ANSI escape codes for setting cursor visibility).

I can maybe explore whether the Windows 10 console supports the ANSI escape codes for setting cursor visibility -- if so then maybe Clink could use them to solve the flicker and invisibility limitations, but it may have a side effect of causing the scroll position to reset at undesirable times.

**Comment by chrisant996** [comment]
It's a limitation of the Windows console APIs. The only thing Clink can do is stop adjusting the cursor shape and visibility. But that has several drawbacks. So there's no good solution; one must choose which compromise to make.

Commit 7bc1972f5882a9dc190be1634169cc2cd749f11d adds a setting to cost which choose to make.
