### ISSUE TITLE
[feature request] A hook for filtering the tab completion matches.

### ISSUE THREAD

**Issue by QAston** [chrisant996/clink#89]
Hi,

I'm working on integrating [fzf](https://github.com/junegunn/fzf) for fuzzy matching on clink's tab completion. The intented behaviour is to be able to take the completion list produced by clink's match generators and filter the contents to get a singular match. I've been using clink.ondisplaymatches which *almost* works for this purpose (I get to filter out the completion list successfully), except it doesn't affect completion behaviour (as documented). 

It'd be great if clink provided a hook that allowed filtering completion contents and not just display, so that the code below works.

```lua
function fzf_completion(rl_buffer)
    fzf_complete_intercept=true
    rl.invokecommand("complete")
    fzf_complete_intercept=false
    rl.invokecommand("redraw-current-line")
end

function my_filter(matches, popup)
    
    local pipename = "clinkfzf_"..path.getname(os.tmpname())
    local process_out = io.popen('"C:\\portable\\windows-named-pipe-utils\\build\\createAndReadPipe.exe" '..pipename..' | fzf --height 50%', "r")
    local process_in = nil
    while( not process_in )
    do
        process_in = io.open("\\\\.\\pipe\\"..pipename, "w")
    end

    for _,m in ipairs(matches) do
        process_in:write(m.match.."\n")
    end
    process_in:close()
    local new_matches = {}
    
    while( true )
    do
        local line = process_out:read('*line') 
        if line then 
            for _,m in ipairs(matches) do
                if m.match == line then
                    table.insert(new_matches, m)
                end
            end
        else 
            break
        end
    end
    
    process_out:close()
    
    return new_matches
  end

local interceptor = clink.generator(0)
function interceptor:generate(line_state, match_builder)
    if (not fzf_complete_intercept) then
        return false
    end
    -- Use the line_state object to examine the current line and create matches.
    -- Submit matches to Clink using the match_builder object.
    -- Return true or false
    clink.ondisplaymatches(my_filter)
    return false
end

```

**Comment by chrisant996** [comment]
How would that work?

Fuzzy matching sounds like it would be necessary to also replace how Clink selects and inserts matches.  Not just which matches are collected.

**Comment by QAston** [comment]
As long as the matches are reduced to a single match clink/readline would just the single match filtered by fzf. As for keyboard input and selection, it already works with the code above.

**Comment by chrisant996** [comment]
I see, so the feature proposal is to have a way to tell Clink: "insert this match instead of displaying matches".

Would it be acceptable to restrict it so that the insertion request is rejected if it wasn't already one of the available match candidates?

**Comment by QAston** [comment]
It's fine to restrict the list of matches, I have a hacky version of this working here:
https://github.com/chrisant996/clink/compare/master...QAston:master

**Comment by chrisant996** [comment]
I'm open to exploring this further.  The design is a compelling proof of concept.  It isn't functionally viable yet; it has side effects and regressions in scenarios outside the scenario it's intended to affect.

> It's fine to restrict the list of matches instead of allowing new ones (the intention here is to use the full clink's match list, match generators can be used to add more if needed), 

If there are N inputs:  does fzf always discard exactly either zero or N-1 matches?
If there are 20 inputs, will it always return either 20 or 1 inputs, or can it return 10 of the inputs?

> I have a hacky version of this working here:  [master...QAston:master](https://github.com/chrisant996/clink/compare/master...QAston:master) This kind of approach would work, just needs to have a separate hook with proper lua api.

I think I see the intent, thank you for sharing the sample pull request.

I know it's just an experimental hack, but I can share a couple quick observations:
- It needs to be hooked up a bit differently so that it doesn't break other features and behaviors (especially when not using fzf).  `preprocess_matches()` is used by other commands that fzf does not integrate with at all (such as `menu-complete` and `popup-complete` and `old-menu-complete`).
- The outcomes from the two O(N*N) loops can be achieved in O(N) time with some adjustments.  E.g. the one at line 834 can be converted to O(N) by using separate "read element" and "write element" pointers.  And it can be removed entirely if the other O(N*N) loop is swapped out for using an unordered set.

Here's another behavioral point to consider:

Clink can have multiple matches with the same string, but different match types and other attributes, which can cause the matches to be inserted differently even though the display strings are the same (for example, one may append a slash, space, or other character but the other might append nothing).

That isn't an issue for ondisplaymatches or match display filtering, because they only affect display, not insertion.  As soon as we want to affect insertion, then there are additional issues that need to be dealt with.

For example:  suppose fzf says "insert the `foo` match", but Clink has two different `foo` matches?  Clink could (1) insert the least common denominator of the matches, or (2) list all the `foo` matches instead of inserting one, or (3) arbitrarily insert the first one.  If we assume only fzf would use this capability, then option 1 seems desirable.  However, I don't think I should design Clink around fzf, so I'm not convinced that option 1 is the best choice for Clink.

I'll have to think more about challenges that need to be solved in order to be able to safely affect inserting matches, without breaking other functionality.  Bash doesn't have these issues, because Bash takes a simpler approach to matches -- matches are just strings, and Bash and Readline make file system calls for every string to try to figure out if it should be interpreted as a filename.  That makes match display very slow, and Clink eliminated all those file system calls for a huge noticeable performance improvement, and Clink lets match generators supply a match type and other attributes.  (If a generator only supplies a string, then Clink still falls back to the slow approach in Bash/Readline.)  That simpler but slower approach in Bash/Readline means that two `foo` matches are guaranteed to be treated the same and therefore there's no lossiness when letting fzf manipulate the list of matches.

Makes sense?

**Comment by chrisant996** [comment]
Here's another hiccup -- there's no way to make fzf and existing match display filters integrate seamlessly.

For example, the match display filters in [clink-completions](https://github.com/vladimir-kotikov/clink-completions) tend to generate matches, cache the generated matches, and ignore the matches Clink gives to the match display filter function -- they just use the matches they cached.

It isn't possible to pass the results from match display filters to fzf -- the results can contain ANSI escape codes and display text that will not (must not) be inserted.  And since match display filters can/do ignore the matches passed to them, it isn't necessarily possible to have fzf filter the matches.

**_So:_**

What I can do is make the pipeline look like this:
1. Clink invokes generators to generate matches.
2. **new:** IF doing `complete` or `popup-complete` then Lua callback can filter the list of matches -- this is where fzf could do its thing.
    - However NOT if doing `menu-complete`, because that fundamentally works differently and only collects matches ONCE at the beginning.
3. IF displaying matches (e.g. `menu-complete` does not) then Lua callback can filter the display of matches -- this is the existing match display filter (and ondisplaymatches).
4. IF displaying matches Clink will display them.
5. IF inserting matches Clink will insert the appropriate match (single match if only one, or lcd in `complete` or `menu-complete` with `menu-complete-display-prefix` enabled, or cycling through matches in `menu-complete`, etc).

**Comment by QAston** [comment]
All fair points, the proposed solution looks good to me.

**Comment by chrisant996** [comment]
After sleeping on it, I want to amend it:

Clink will always call Lua callback function, even for `menu-complete` (since that's more correct if we also consider non-fzf scenarios).
So, the fzf integration will need to only take action in the callback when doing `complete` style of completion.

The new callback will include a parameter indicating what completion type is happening.

**Comment by chrisant996** [comment]
fzf doesn't restore the text color before it exits.
fzf clears the entire console screen and all scrollback buffer when it runs; that seems like a bit of a catastrophic drawback.

I'll add Lua support for this, because maybe some other implementation will be less destructive and more usable.

**Comment by chrisant996** [comment]
Implemented in Clink v1.1.41 (published a few minutes ago).
Here is my fzf.luz script.

# fzf.lua
```lua
local fzf_complete_intercept = false

local readpipe_exe = "c:\\wbin\\clink\\createAndReadPipe.exe"
local fzf_exe = "c:\\wbin\\clink\\fzf.exe"

function fzf_complete(rl_buffer)
    fzf_complete_intercept = 1
    rl.invokecommand("complete")
    if fzf_complete_intercept == true then
        rl_buffer:ding()
    end
    fzf_complete_intercept = false
    rl_buffer:refreshline()
end

local function filter_matches(matches, completion_type, filename_completion_desired)
    if completion_type ~= "\t" and completion_type ~= "?" then
        return
    end

    -- Start pipes and fzf.
    local pipename = "clinkfzf_"..os.getpid().."_"..math.floor(math.fmod(os.clock() * 50, 10000))
    local process_out = io.popen(readpipe_exe..' '..pipename..' 2>nul | '..fzf_exe..' --height 50%', "r")
    if not process_out then
        return
    end

    -- Wait up to 5 seconds for the pipe to be available for writing.
    local started = os.time()
    local process_in = nil
    while (not process_in) do
        if os.difftime(os.time(), started) > 5 then
            return
        end
        process_in = io.open("\\\\.\\pipe\\"..pipename, "w")
    end

    -- Write matches to the pipe.
    for _,m in ipairs(matches) do
        process_in:write(m.match.."\n")
    end
    process_in:close()

    -- Read filtered matches from the pipe.
    local ret = {}
    while (true) do
        local line = process_out:read('*line')
        if not line then
            break
        end
        for _,m in ipairs(matches) do
            if m.match == line then
                table.insert(ret, m)
            end
        end
    end
    process_out:close()

    -- Yay, successful; clear it to not ding.
    fzf_complete_intercept = nil
    return ret
end

local interceptor = clink.generator(0)
function interceptor:generate(line_state, match_builder)
    if fzf_complete_intercept then
        clink.onfiltermatches(filter_matches)
    end
    return false
end
```

**Comment by chrisant996** [comment]
Added by 98049e7f5b19d628505f3baa64d533a100576e55.

**Comment by QAston** [comment]
Great, thanks! The pipe is only needed because io.popen doesn't allow reading and writing to the same process. If you could provide a lua api call to allow this the script would be much nicer.

**Comment by chrisant996** [comment]
> Great, thanks! The pipe is only needed because io.popen doesn't allow reading and writing to the same process. If you could provide a lua api call to allow this the script would be much nicer.

I agree.  However, that requires constantly reading and writing (usually accomplished via multiple threads or processes), otherwise Clink can cause the fzf process to hang.  For example, the Lua function currently does all the reading and then all the writing -- that is a classic pattern for causing pipes to hang.  In the case of fzf specifically, it might work out ok as long as fzf never writes until it has completely finished reading.  So while I would like to have a built-in alternative to the createAndReadPipe.exe, that will be complicated and will take some time to get right.

In the meantime, I plan to try making the function use a temporary file instead of a pipe.

**Comment by chrisant996** [comment]
Last night I tried to get delete-on-close temp files working, but CMD doesn't support them in redirection, so that can't work.

I'm going to look into adding some new `io.popen_with_input_pipe()` function to enable using a named pipe for stdin on the spawned process _without_ needing an external tool like createAndUseReadPipe.

If it turns into too big of a project (there's definitely risk of that) then it might not make it into the first public release (we're in the last-minute-ish phase of pre-release builds for the first public release).  I think it might be unidirectional flow in fzf's case (fzf reads until empty, then writes -- and Clink writes until done, then reads until empty), but I need to provide a generalized solution that supports bidirectional flow since the API function can be used with programs other than fzf.

The syntax would be something along the lines of this (error handling omitted for clarity).
```lua
local out, in = io.popen_with_input_pipe("fzf --height 40%")

in.write("blah\n")
in.write("yada\n")
in.write("zzz\n")
in:close()

while (true)
    local line = out:read("*line")
    if not line then
        break
    end
    print(line)
end
out:close()
```

**Comment by QAston** [comment]
Yeah, the possibility of temp files staying was the reason I bothered to use the named pipes in the first place.

**Comment by chrisant996** [comment]
A new `io.popenrw()` function returns both a read pipe and a write pipe.
Of course it can deadlock if the reader and writer don't cooperate properly.
But it will work the same as `createAndReadPipe.exe` does.

```lua
local r,w = io.popenrw("fzf --height 40%")

for _,m in ipairs(matches) do
    w:write(m.match)
    w:write("\n")
end
w:close()

while (true) do
    local line = r:read("*line")
    if not line then
        break
    end
    -- ... do something with line ...
end
r:close()
```

**Comment by chrisant996** [comment]
This version of fzf.lua works with Clink v1.1.42 and has three commands:
- `luafunc:fzf_file`
- `luafunc:fzf_history`
- `luafunc:fzf_complete`

(Seems like this belongs in its own repo maybe. 😄)

# fzf.lua
```lua
if not io.popenrw then
    print("fzf.lua requires a newer version of Clink; please upgrade.")
    return
end

--------------------------------------------------------------------------------
settings.add("fzf.height", "40%", "Height to use for the --height flag")
settings.add("fzf.options", "", "Options to pass to fzf.exe")
settings.add("fzf.exe_location", "", "Location of fzf.exe if not on the PATH")

--------------------------------------------------------------------------------
local function get_fzf()
    local height = settings.get("fzf.height")
    local options = settings.get("fzf.options")
    local command = settings.get("fzf.exe_location")
    if not command or command == "" then
        command = "fzf.exe"
    else
        -- io.popen functions have trouble spawned quoted command names, so try
        -- to use a short name.
        command = os.getshortpathname(command)
    end
    if height and height ~= "" then
        command = command..' --height '..height
    end
    if options then
        command = command..' '..options
    end
    return command
end

local function get_clink()
    local clink_alias = os.getalias("clink")
    if not clink_alias or clink_alias == "" then
        return ""
    end
    return clink_alias:gsub(" $[*]", "")
end

--------------------------------------------------------------------------------
local fzf_complete_intercept = false

--------------------------------------------------------------------------------
function fzf_complete(rl_buffer)
    fzf_complete_intercept = true
    rl.invokecommand("complete")
    if fzf_complete_intercept then
        rl_buffer:ding()
    end
    fzf_complete_intercept = false
    rl_buffer:refreshline()
end

function fzf_history(rl_buffer)
    local clink_command = get_clink()
    if #clink_command == 0 then
        rl_buffer:ding()
        return
    end
    local r = io.popen(clink_command..' history --bare | '..get_fzf()..' --tac')
    if not r then
        rl_buffer:ding()
        return
    end
    local str = r:read('*all')
    r:close()

    str = str:gsub("[\r\n]", "")
    rl_buffer:beginundogroup()
    rl_buffer:remove(0, -1)
    rl_buffer:insert(str)
    rl_buffer:endundogroup()
    rl_buffer:refreshline()
end

function fzf_file(rl_buffer)
    local r = io.popen(get_fzf())
    if not r then
        rl_buffer:ding()
        return
    end
    local str = r:read('*line')
    r:close()
    if str then
        rl_buffer:insert(str)
    end
    rl_buffer:refreshline()
end

--------------------------------------------------------------------------------
local function filter_matches(matches, completion_type, filename_completion_desired)
    if not fzf_complete_intercept then
        return
    end

    -- Start fzf.
    local r,w = io.popenrw(get_fzf()..' --layout=reverse-list')
    if not r or not w then
        return
    end

    -- Write matches to the write pipe.
    for _,m in ipairs(matches) do
        w:write(m.match.."\n")
    end
    w:close()

    -- Read filtered matches.
    local ret = {}
    while (true) do
        local line = r:read('*line')
        if not line then
            break
        end
        for _,m in ipairs(matches) do
            if m.match == line then
                table.insert(ret, m)
            end
        end
    end
    r:close()

    -- Yay, successful; clear it to not ding.
    fzf_complete_intercept = false
    return ret
end

local interceptor = clink.generator(0)
function interceptor:generate(line_state, match_builder)
    if fzf_complete_intercept then
        clink.onfiltermatches(filter_matches)
    end
    return false
end
```
