### ISSUE TITLE
 a lot of history start with | in history file

### ISSUE THREAD

**Issue by fcying** [chrisant996/clink#90]
I want third party tool to read history file and do some operations. 
I saw it have a lot of history start with `|`

![image](https://user-images.githubusercontent.com/106934/111582077-463be600-87f5-11eb-991e-96608c6f3411.png)

start with `|` is duplicate history?  Can't it be deleted directly?

**Comment by chrisant996** [comment]
Those are deleted entries.

The history system uses several files, and is designed for high performance and for sharing between multiple Clink sessions at the same time.

It's not going to work to let another program directly read and modify the history files.

Why can't the `clink history` command be used to access the history info?

**Comment by fcying** [comment]
`clink history` have line number, pass it to fzf  inconvenient, Is there any way to remove the previous line number?

![image](https://user-images.githubusercontent.com/106934/111586742-41c6fb80-87fc-11eb-8561-606d047929be.png)
![image](https://user-images.githubusercontent.com/106934/111586750-45f31900-87fc-11eb-8f64-6d842874ab32.png)

The following code just deletes the final output, there are still line numbers when fzf filter.
```
function fzf_history(rl_buffer)
	str = assert(io.popen('clink history | fzf --reverse --height 40%')):read('*all')
	str = string.sub(str,1,-2)
	str = string.gsub(str, "%s+%d+%s+", "")
	rl_buffer:insert(str)
	rl_buffer:refreshline()
end
```

P.S. 
deleted entries still store in history file, the history file will be too big?
I saw my history file have 7283 line, but valid history only 504

**Comment by chrisant996** [comment]
What does `clink set history.max_lines` say?

The "Saved command history" section in the Clink documentation describes some of how the saved history works.  I'm not sure it's 100% up to date; I'll check when I get a chance.

I like that you're working on a fzf history command. I'm also happy to see that the `luafunc:` key binding mechanism is enabling some cool things.

I'll look into adding a flag to hide the numbers.

The gsub in the quoted code appears to expect a space before the number, but I don't think there is one.

**Comment by fcying** [comment]
> What does `clink set history.max_lines` say?
> The "Saved command history" section in the Clink documentation describes some of how the saved history works. I'm not sure it's 100% up to date; I'll check when I get a chance.
tks, I know the rule: historyfile lines > history.max_lines or > 200, it will be auto compact.
but I run ` history compact`  manual not compact file?

> I'll look into adding a flag to hide the numbers.
thanks~

>The gsub in the quoted code appears to expect a space before the number, but I don't think there is one.
origin output(without gsub), may be space  is add by fzf filter
![image](https://user-images.githubusercontent.com/106934/111606643-6fb73a80-8812-11eb-874d-7cbc178aa937.png)

![image](https://user-images.githubusercontent.com/106934/111606500-3e3e6f00-8812-11eb-9ec4-18a04e276e50.png)

**Comment by chrisant996** [comment]
I copied your code and used it.  It strips the item number for me.  🤷‍♂️

I've added a `clink history --bare` flag, which will be in the next build.

I've also noticed some problems with `onfiltermatches`.  For example, Readline caches matches and doesn't generate/filter matches each time.  So subsequent invocations of various completion commands can either invoke fzf unexpectedly or skip invoking fzf at all.  I'll do something about that -- probably I'll make it so that using `onfiltermatches` discards the matches afterwards, to reset the completion pipeline.

> > What does `clink set history.max_lines` say?
> > The "Saved command history" section in the Clink documentation describes some of how the saved history works. I'm not sure it's 100% up to date; I'll check when I get a chance.
> 
> tks, I get the rule from doc: historyfile lines > history.max_lines or > 200, it will be auto compact.

Yeah the description is not up to date.  I'll update it when I fill in the documentation for `clink.onfiltermatches()`.

> but I run ` history compact` manual not compact file? output message is compacted, but history file also 7000 lines.
> history.max_lines is 10000.

First it deletes old lines until there are <= `history.max_lines` active lines (delete just means mark it as deleted).
Next it checks whether the number of deleted lines >= deletion threshold, and if so then it rewrites the history file, stripping all of the lines that were marked for deletion.
If `history.max_lines` > 0, the deletion threshold is max(`history.max_lines`, 200).
If `history.max_lines` == 0, the deletion threshold is 2500.

So, the maximum total number of lines of text (deleted lines + active lines) the master history file can contain before it gets compacted is roughly `history.max_lines` * 2.

I'll also update `history compact` so that it gives a more relevant message.  Right now it always says "History compacted." no matter what happens.

I'll also add a way to force immediate compaction (use 0 as the deletion threshold).  I had mostly hooked that up already, but I forgot to add a command line flag to actually invoke it.

**Comment by QAston** [comment]
@fcying I've been looking at something similar (fzf filter for history 😛 ) and there's one issue with io.popen('clink history') - it doesn't show the history if the current session, only the history of previous sessions

**Comment by fcying** [comment]
@QAston  I can't reproduce this, it work fine for me.
![image](https://user-images.githubusercontent.com/106934/111636970-f16b9000-8833-11eb-834b-0baf3cc48698.png)

**Comment by QAston** [comment]
@fcying do you have `history.shared` set to enabled? That's the only way it'd work, but I don't want to set this option because I don't want to mix the histories in the current session

**Comment by chrisant996** [comment]
I have `history.shared` false, and `clink history` shows both the master session and the current session history:

![image](https://user-images.githubusercontent.com/17440311/111660983-da915300-87cb-11eb-9432-16965f98e56c.png)

Also, here is my current `fzf.lua` function which has both the `fzf_complete` and `fzf_history`.  It uses `settings.add` to give an easy way to adjust the `--height`, whether to use `--reverse`, and provide a path to `fzf.exe` if it isn't on the PATH.  It also uses `os.getalias("clink")` to get the Clink exe, so that `clink` doesn't have to be on the path.  And it uses a temporary file rather than createAndReadPipe.exe.

Also, the temporary file handling in Lua is weak, so I'll also see about adding a safer tempfile API.

# fzf.lua
```lua
--------------------------------------------------------------------------------
settings.add("fzf.height", "40%", "Height to use for the --height flag")
settings.add("fzf.reverse", true, "Reverses the fzf list")
settings.add("fzf.exe_location", "", "Location of fzf.exe if not on the PATH")

--------------------------------------------------------------------------------
local function get_fzf()
    local height = settings.get("fzf.height")
    local reverse = settings.get("fzf.reverse")
    local command = settings.get("fzf.exe_location")
    if not command or command == "" then
        command = "fzf.exe"
    else
        --command = os.getshortname(command)
    end
    if height and height ~= "" then
        command = command..' --height '..height
    end
    if reverse then
        command = command..' --reverse'
    end
    return command
end

local function get_clink()
    local clink_alias = os.getalias("clink")
    if not clink_alias or clink_alias == "" then
        return ""
    end
    return clink_alias:gsub(" $[*]", "")
end

--------------------------------------------------------------------------------
local fzf_complete_intercept = false

--------------------------------------------------------------------------------
function fzf_complete(rl_buffer)
    fzf_complete_intercept = true
    rl.invokecommand("complete")
    if fzf_complete_intercept then
        rl_buffer:ding()
    end
    fzf_complete_intercept = false
    rl_buffer:refreshline()
end

function fzf_history(rl_buffer)
    local clink_command = get_clink()
    if #clink_command == 0 then
        rl_buffer:ding()
        return
    end

    local str = assert(io.popen(clink_command..' history --bare | '..get_fzf())):read('*all')
    str = str:gsub("[\r\n]", "")
    rl_buffer:insert(str)
    rl_buffer:refreshline()
end

local function filter_matches(matches, completion_type, filename_completion_desired)
    if not fzf_complete_intercept then
        return
    end

    -- Write matches to temp file.
    local tempname = os.tmpname()
    if not tempname or tempname == "" then
        return
    end
    local tempfile = io.open(tempname, "w")
    if not tempfile then
        os.unlink(tempname)
        return
    end
    for _,m in ipairs(matches) do
        tempfile:write(m.match.."\n")
    end
    tempfile:close()

    -- Start fzf.
    local foo = get_fzf()..' < "'..tempname..'"'
    local process_out = io.popen(get_fzf()..' < "'..tempname..'"', "r")
    if not process_out then
        os.unlink(tempname)
        return
    end

    -- Read filtered matches.
    local ret = {}
    while (true) do
        local line = process_out:read('*line')
        if not line then
            break
        end
        for _,m in ipairs(matches) do
            if m.match == line then
                table.insert(ret, m)
            end
        end
    end

    process_out:close()
    os.unlink(tempname)

    -- Yay, successful; clear it to not ding.
    fzf_complete_intercept = false
    return ret
end

local interceptor = clink.generator(0)
function interceptor:generate(line_state, match_builder)
    if fzf_complete_intercept then
        clink.onfiltermatches(filter_matches)
    end
    return false
end
```

**Comment by chrisant996** [comment]
> @chrisant996 yes, clink history shows the current session's history when run from the command line.
> 
> However, when run from io.popen it doesn't (I assume because popen spawns a separate process). I've tested this with the above script and latest version of clink

How strange. It finds the history session ID from a hidden environment variable that is inherited by child processes (`clink history` always spawns a separate process).

Will take a look when I get a chance.

**Comment by QAston** [comment]
I guess if io.popen spawns a cmd itself and clink autoinject is enabled the clink history spawned by io.popen() has a different id.

**Comment by QAston** [comment]
You can fix this by changing the env variable name from =clink.id to clink.id and then prefix`clink.id=<value for invoking process>`  . Variables starting with = are not legal and so can't be set in cmdline because validation rejects them

**Comment by chrisant996** [comment]
> You can fix this by changing the env variable name from =clink.id to clink.id and then prefix`clink.id=<value for invoking process>` . Variables starting with = are not legal and so can't be set in cmdline because validation rejects them

No, that's not the problem.  There are good reasons for the `=` prefix, and in fact it's not an uncommon practice.  The prefix means it can't be set via `cmd set`, but that's intentional.

Also, I actually _do_ see the current session history show up even when spawned via `os.popen()`.  So my guess about `_wputenv_s()` vs `SetEnvironmentVariableW()` doesn't seem to be able to explain the behavior.

Looks like there's more going on, and I'll have to dig into it when I get a chance.

**Comment by fcying** [comment]
> @fcying do you have `history.shared` set to enabled? That's the only way it'd work, but I don't want to set this option because I don't want to mix the histories in the current session

![image](https://user-images.githubusercontent.com/106934/111718985-ea756980-8895-11eb-99ef-4769406473c4.png)

`history.shared` is False, my fzf script:
`_inputrc`
```
C-t:	"luafunc:fzf_file"
C-r:	"luafunc:fzf_history"
```
`init.lua`
```
function fzf_file(rl_buffer)
	str = assert(io.popen('fzf --reverse --height 40%')):read('*all')
	str = string.sub(str,1,-2)
	rl_buffer:insert(str)
	rl_buffer:refreshline()
end

function fzf_history(rl_buffer)
	str = assert(io.popen('clink history | fzf --reverse --height 40%')):read('*all')
	str = string.sub(str,1,-2)
	str = string.gsub(str, "%s+%d+%s+", "")
	rl_buffer:insert(str)
	rl_buffer:refreshline()
end
```

**Comment by QAston** [comment]
This is strange I don't see why you wouldn't have the issue I'm experiencing. Still, I managed to work around it on my system using env variables method above, so I personally don't mind.

**Comment by chrisant996** [comment]
I don't know what's going on yet - I focused on the pipe thing first (which is pushed to the repo, but no build published yet).

I mostly can't reproduce the history problem, but I did manage to reproduce it once, temporarily. It's still on my list to get to soon.

**Comment by fcying** [comment]
I test the last version: v1.1.42.485f69. Works well with fzf.


`history compact` can't force compacted also.
```
set `history.max_lines = 1000`
history file add `|ir` to 1300.
run history compact
```

**Comment by fcying** [comment]
` v1.1.43.9a8a44` Work well, thanks~~

**Comment by chrisant996** [comment]
@fcying Yeah, sorry, today I added `history --diag` to report diagnostics about the history file operations, and I realized `history compact` was still not hooked up right.  Clink v1.1.43 should have it working now.

Can you try changing your `fzf_history` function so it invokes `history --diag` instead of just `history`?  That will cause it to print some diagnostic information to stderr (so it shouldn't affect the behavior of fzf).

It will be very interesting to see what the diagnostics reveal about what is going on when invoking the `history` command from inside `io.popen()`.

**Comment by QAston** [comment]
Here's the diagnostics:

1. running fzf_history with no new stuff in this session
```
Microsoft Windows [Version 10.0.19041.867]
(c) 2020 Microsoft Corporation. All rights reserved.
Clink v1.1.43.9a8a44
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2021 Christopher Antos
http://github.com/chrisant996/clink

~
@❯ ... master file 'C:\Users\qasto\AppData\Local\clink\clink_history'
... session file 'C:\Users\qasto\AppData\Local\clink\clink_history_4304'
... removals file 'C:\Users\qasto\AppData\Local\clink\clink_history_4304.removals'
... printed 1028 lines from master bank
... printed 0 lines from session bank
... loading history
... ... master bank:  lines active 1028 / deleted 1209
... ... session bank:  lines active 0 / deleted 0
... total lines active 1028
... reap session file 'C:\Users\qasto\AppData\Local\clink\clink_history_4304'
```
2. adding a new history entry to this session:
```
@❯ 220320201 
'220320201' is not recognized as an internal or external command,
operable program or batch file.
```
3. running the fzf_history with this session
```
~
@❯ ... master file 'C:\Users\qasto\AppData\Local\clink\clink_history'
... session file 'C:\Users\qasto\AppData\Local\clink\clink_history_20984'
... removals file 'C:\Users\qasto\AppData\Local\clink\clink_history_20984.removals'
... printed 1028 lines from master bank
... printed 0 lines from session bank
... loading history
... ... master bank:  lines active 1028 / deleted 1209
... ... session bank:  lines active 0 / deleted 0
... total lines active 1028
... reap session file 'C:\Users\qasto\AppData\Local\clink\clink_history_20984'
```
4. running history diag for this session
```
@❯ history --diag
... master file 'C:\Users\qasto\AppData\Local\clink\clink_history'
... session file 'C:\Users\qasto\AppData\Local\clink\clink_history_6956'
... removals file 'C:\Users\qasto\AppData\Local\clink\clink_history_6956.removals'
<history here>
... printed 1028 lines from master bank
... printed 1 lines from session bank
... loading history
... ... master bank:  lines active 1028 / deleted 1209
... ... session bank:  lines active 1 / deleted 0
... total lines active 1029
```

**Comment by chrisant996** [comment]
Thank you, that's very interesting.

And I might have figured out what's going on...

@QAston do you have Clink set up for autorun, so it automatically injects into every new CMD?

I'm pretty sure that you do, and that @fcying and I do not.

**Comment by QAston** [comment]
Yup, do I have autoinject on.

**Comment by chrisant996** [comment]
> Yup, do I have autoinject on.

Thanks for confirming.

The issue is that `io.popen("foo")` actually spawns `"cmd.exe /c foo"` (which is why pipes and redirection and etc work).  So if autorun is installed, then the spawned cmd.exe gets a new Clink instance injected, and then the `history` command uses that new session.

This is a hole in Clink's session tracking system.  I don't see any fully auto-magical solution.

The best mitigation I see is this:
- Add an undocumented `clink --session` flag for internal use.
- Make the auto-defined `clink` and `history` doskey aliases explicitly specify the session.
- If Lua code uses `os.getalias("clink")` or `os.getalias("history")` to get the clink exe to invoke, then `io.popen()` and `io.popenrw()` and etc will use the right session.
- But any Lua code that uses the literal `clink` string with `io.popen()` and `io.popenrw()` and etc will end up using the wrong (new) session.

**I'm torn: is this worth mitigating?**  There's no way to fully mitigate all cases for this.  The mitigation described above will work, but _only_ if Lua scripts use `os.getalias()` instead of using the literal string `clink`.  And `io.popen("script.cmd")` could invoke `clink history` inside script.cmd and there's nothing that can mitigate that usage scenario.

**Comment by QAston** [comment]
I think it's way simpler to just open up the session variable so that it can be set explicitly from cmd like I did in my solution, but I'm biased I guess 😛

**Comment by chrisant996** [comment]
> There's also cmd /d that disables the autorun feature of cmd.exe

There's no way to use `/d` because `io.popen` internally uses `/c`.

> I think it's way simpler to just open up the session variable so that it can be set explicitly from cmd like I did in my solution, but I'm biased I guess 😛

The session variable gets inherited, and it's a private implementation detail.  It doesn't belong in public view (reported by `set`, etc), and it shouldn't be easily modifiable by anything that wants to.  In particular, what should happen if something changes the session id variable in the current CMD instance?  If Clink were to use the new session id that would cause problems.  And if Clink doesn't use the new session id then why is there a variable that can be changed?  Also, the proposal functionally fails in that case (something sets `clink.id`, but the current Clink instance isn't using that id, so passing that id to the spawned clink history command will malfunction).

> Alternatively you could add an env variable that disables autoinject when present in the environment (this could be useful in a more general case when you don't want to have autoinject for some other reason).

That's a great suggestion, thanks, I'll add that.

I've also added a `clink --session` flag and `clink.getsession()` function.  Even if they're misused, they can't cause any real problems.  So it's a safe solution, though still as awkward as any of the proposals.
