### ISSUE TITLE
clink-popup-history not work with cmder

### ISSUE THREAD

**Issue by trungking** [chrisant996/clink#92]
I setup clink-popup-history in .inputrc.
When i use popup history with command prompt, it show the popup but when i use it with cmder it only change title and revert back.
I remember it used to work with cmder in previous version.
You can check the video

https://user-images.githubusercontent.com/18730477/111940930-84d9e500-8b02-11eb-9301-687168da29bc.mp4

**Comment by chrisant996** [comment]
Thanks for reporting this.  It got broken when I got it to work in Windows Terminal.

Apparently something -- presumably ConEmu -- is actively lying to the console application about its window.  In order to work in Windows Terminal it was necessary to hunt around a bit to find the right HWND.  But in order to work in ConEmu apparently it's necessary to blindly use the HWND from GetConsoleWindow() -- because querying whether the console window is visible actively lies to the application.  APIs called on the HWND from inside the process get one set of answers, but APIs called on the HWND from outside the process get very different answers that are the expected correct answers.

I'll make it not trust the APIs when it's running inside ConEmu.  😕

**Comment by chrisant996** [comment]
It should work in the next build.
